#+title: a constructivist manifesto / 一個構造主義者的宣言
#+author: Errett Bishop

* 題解

  - 原文來源
    書名 foundations of constructive analysis
    爲 Bishop 的最主要著作
    成書與 1967 年
    系統地介紹 構造主義 處理分析學的方式
    在 構造主義 的框架內 重新證明了許多古典定理
    因而受人尊敬與重視
  - 譯文取其第一章

* 排版

  - 排版用 雙文
    譯文在先 原文在後
    原文 譯文 段段交叉 以便讀者對比 並指正譯文中不當之處
  - 譯文中
    方形括號內的段落爲我的筆記

* 說數 / the descriptive basis of mathematics

*** 譯文

    - 數學之爲人之智力活動
      超越生理與環境

      - 我們所觀察到的生命系統的原理
        可能亦適用於其他世界的生物
        但是 其他世界的生物 也很可能遵循其他的原理

      - 物理世界的原理 更爲普世
        然而 還是可能想像 另外一個世界 爲不同的物理規則所主導

      數學之爲心智所創造
      不像 生命系統的原理 或 物理世界的原理
      這些自然之造物一般任意

      我們想像中的異形生物
      居住在另一個世界
      具有另一套生理結構
      這種異形生物所發展出的數學 本質上也將與我的相同

      如若相信如上所述 我們就入了陷阱

      - 數學之爲我們心智所創造
        我們的心智 當然很難想像 它能如何與我們現在對它的想像不同
        除非我們真的看見了不同的可能

      或許
      對於 不同類型智慧生物的數學活動
      我們該少做些預言

      再說
      我們相信數學具有超越性
      其務實之處 並非有關異形生物
      其實
      所信者 指導着數學的研究方向
      這種研究方向源於 對數學內蘊性的執着
      執着數學內蘊自身而於外無求

    - 數學主要關乎數
      即 正整數
      [下面 數 不加限定詞時 就指正整數]
      我們體會數
      正如 康德體會空間
      [當然 康德體會空間 而的幾何
       康德還體會時間 而得算數]

      我們心智之特性
      讓我們預先假設數和算數運算
      我們還傾向於相信
      這正是心智本身之特性

      數的理論
      源起於單位
      還有單位相繼
      還有數學歸納法
      對於如此發展而來的理論 我們深信不疑

      用克倫內克[Kronecker]的話說
        上帝創造正整數
      克倫內克若說
        上帝 爲人和其他有限生物的利益
        而創造正整數
      那他說的就更好了

      [西方宗教認爲 上帝無限 而人與其他生物有限
       下面的翻譯中 有時我會忽略 有限 這個限定詞]

      數學屬於人 而不屬於上帝
      我們並不關心正整數那些難以言說於人的性質
      當人要證明某個正整數存在時
      他必須說明如何找到這個正整數
      如果上帝自己也要做些數學
      讓他自己做自己的去吧

    - 幾乎與數同樣重要的
      是我們藉以由數攀升
      而構造更高級數學實體的方法

      這些構造方法
      關乎觀察已經構造出來的數學實體之間的關係
      在觀察的過程中
      我們自然構造出新的數學實體來

      起步階段我們能觀察到的關係是
      數的 序 和 算數運算

      從這些觀察 我們得到各種構造方法
        組某些數成對成組
        分某些數出整體
        聯某數於另一個

      這些構造方法給出了 集合 和 函數 的感念

    - 一個集合 不是只有空想存在之物
      只有當定義了之後 一個集合才存在
      爲定義一個集合
      我們要說明
      1. 如何構造其元素
      2. 如何判斷兩個元素相等

    - 函數也如此
      爲定義一個從 集合 A 到 集合 B 的函數
      我們需要說明
      1. 一個在有限時間內結束的算法
         把 A 的元素 轉化成 B 的元素
      2. 並且證明
         相等的 A 的兩個元素
         被轉化成
         相等的 B 的兩個元素

    - 以數爲基礎
      我們編織出 集合 與 函數 組成網絡
      這樣就得到了基本的數學結構
        有理數
        實數
        歐幾里得空間
        複數
        代數數
        希爾伯特空間
        典型群

      很多數學就實現在這些結構的框架內
      一切都與數相聯
      一切數學論斷
      終可歸結爲
        給以數
        我們可以做某些運算
        而得到某些結果

    - 數學來了一次飛躍
      從那些 可以具體構造出來的實體
      轉向了那些 假設可以構造出來的實體

      某種程度上 假設可構造的實體 一開始就有
        每當我們說
        所有正整數具有某個性質
        其實我們是在考錄某個正整數
        並假設可以構造出這個數

      然而如今我們更大膽了
      我們考錄 假設可構造的集合
      賦之以 假設可施行的操作
      限之以 某些公理
      如此我們引入了
        拓撲空間
        羣
        流形

      其動機來自於 學習具體構造的例子
      其理由在於
      由 假設的構造 所構建的理論
      可能適用於更多的具體構造的例子

      最近流行再做一次飛躍
      去研究 假設的假設構造
      [指範疇論]

      同樣動機和理由來自具體的例子
      而具體的例子又終歸爲數
      因此
      即便是最抽象的數學也有計算基礎

    - 數學的超越性要求
      數學研究不能被限制於 我能施行的計算
        或你能施行的計算
        或一百個人在一百年內用一百台計算機所能施行的計算
      任何在有限步驟內可以結束的計算
      都可以研究

      這不意謂着計算的效率沒有價值
      一個應用數學家 會把計算的效率視爲重中之重
      而形式主義數學家 注重優雅勝於效率

      數學
      應該 也必將 注重效率
        也許有損優雅時也將如此
      但是
      以效率爲重
      恐怕只有當 現實主義 盛行之時了
      在那之前
      我們首先要儘可能
      把數學置於一個現實主義基礎之上
      但並不關注效率問題

*** 原文

    - Mathematics is that portion of our intellectual activity
      which transcends our biology and our environment.

      - The principles of biology as we know them
        may apply to life forms on other worlds,
        yet there is no necessity for this to be so.

      - The principles of physics should be more universal,
        yet it is easy to imagine another universe
        governed by different physical laws.

      Mathematics, a creation of mind,
      is less arbitrary than biology or physics,
      creations of nature;

      the creatures we imagine inhabiting another world
      in another universe,
      with another biology
      and another physics,
      will develop a mathematics
      which in essence is the same as ours.

      In believing this we may be falling into a trap:

      - Mathematics being a creation of our mind,
        it is, of course, difficult to imagine
        how mathematics could be otherwise
        without actually making it so,

      but perhaps we should not presume to predict
      the course of the mathematical activities
      of all possible types of intelligence.

      On the otherhand,
      the pragmatic content of our belief
      in the transcendence of mathematics
      has nothing to do with alien forms of life.
      Rather it serves to give a direction to mathematical investigation,
      resulting from the insistence that
      mathematics be born of an inner necessity.

    - The primary concern of mathematics is number,
      and this means the positive integers.
      We feel about number the way Kant felt about space.

      The positive integers and their arithmetic are presupposed
      by the very nature of our intelligence and,
      we are tempted to believe,
      by the very nature of intelligence in general.

      The development of the theory of the positive integers
      from the primitive concept of the unit,
      the concept of adjoining a unit,
      and the process of mathematical induction
      carries complete conviction.

      In the words of Kronecker,
        the positive integers were created by God.
      Kronecker would have expressed it even better
      if he had said that
        the positive integers were created by God
        for the benefit of man
        (and other finite beings).

      Mathematics belongs to man, not to God.
      We are not interested in properties of the positive integers
      that have no descriptive meaning for finite man.
      When a man proves a positive integer to exist,
      he should show how to find it.
      If God has mathematics of his own that needs to be done,
      let him do it himself.

    - Almost equal in importance to number
      are the constructions by which we ascend from number
      to the higher levels of mathematical existence.

      These constructions involve the discovery
      of relationships among mathematical entities already constructed,
      in the process of which new mathematical entities are created.

      The relations which form the point of departure are
      the order and arithmetical relations of the positive integers.

      From these we construct various rules
        for pairing integers with one another,
        for separating out certain integers from the rest,
        and for associating one integer to another.

      Rules of this sort
      give rise to the notions of sets and functions.

    - A set is not an entity which has an ideal existence.
      A set exists only when it has been defined.
      To define a set we prescribe, at least implicitly,
      1. what we (the constructing intelligence) must do
         in order to construct an element of the set,
      2. and what we must do to show that
         two elements of the set are equal.

    - A similar remark applies to the definition of a function:
      in order to define a function from a set A to a set B,
      1. we prescribe a finite routine
         which leads from an element of A to an elementof B,
      2. and show that
         equal elements of A
         give rise to
         equal elements of B.

    - Building on the positive integers,
      weaving a web of ever more sets and more functions,
      we get the basic structures of mathematics:
        the rational number system,
        the real number system,
        the euclidean spaces,
        the complex number system,
        the algebraic number fields,
        Hilbert space,
        the classical groups,
        and so forth.

      Within the framework of these structures
      most mathematics is done.
      Everything attaches itself to number,
      and every mathematical statement
      ultimately expresses the fact that
        if we perform certain computations
        within the set of positive integers,
        we shall get certain results.

    - mathematics takes another leap,
      from the entity which is constructed in fact
      to the entity whose construction is hypothetical.

      To some extent
      hypothetical entities are present from the start:
        whenever we assert that
        every positive integer has a certain property,
        in essence we are considering a positive integer
        whose construction is hypothetical.

      But now we become bolder and consider a hypothetical set,
      endowed with hypothetical operations
      subject to certain axioms.
      In this way we introduce such structures as
        topological spaces,
        groups,
        and manifolds.

      The motivation for doing this
      comes from the study of concretely constructed examples,
      and the justification
      comes from the possibility of
      applying the theory of the hypothetical structure
      to the study of more than one specific example.

      Recently it has become fashionable
      to take another leap
      and study, as it were,
      a hypothetical hypothetical structure
        a hypothetical structure qua hypothetical structure.

      Again the motivations and justifications
      attach themselves to particular examples,
      and the examples
      attach themselves to numbers in the ultimate analysis.
      Thus even the most abstract mathematical statement
      has a computational basis.

    - The transcendence of mathematics demands that
      it should not be confined to computations that I can perform,
      or you can perform,
      or 100 men working 100 years
        with 100 digital computers can perform.
      Any computation that can be performed by a finite intelligence
        any computation that has a finite number of steps
      is permissible.

      This does not mean that
      no value is to be placed on the efficiency of a computation.
      An applied mathematician will prize a computation
      for its efficiency above all else,
      whereas in formal mathematics
      much attentionis paid to elegance
      and little to efficiency.

      Mathematics should and must concern itself with efficiency,
        perhaps to the detriment of elegance,
      but these matters will come to the fore
      only when realism has begun to prevail.
      Until then
      our first concern will be
      to put as much mathematics as possible
      on a realistic basis
      without close attention to questions of efficiency.

*** 記 數學的超越性

    - 在翻譯之前
      初讀文章時
      我覺得 所謂 數學的超越性
      是 Bishop
      先入一論點 而非 Bishop 所持
      順着這個論點說下去
      實際的用意是要反駁

    - 畢竟
      這個詞 經常被用來爲 非構造主義數學 做辯護

    - 但是
      Bishop 並沒有直接否定 數學的超越性
      而是在文末
      重新定義了這個詞
      以合乎自己對數學研究的分類
      之後這個詞轉而可以用來辯護 構造主義數學 了

* 理想 / the idealistic component of mathematics

*** 譯文

    - 幾何學是高度理想化的
        從 歐幾里得 還有古代
        到 笛卡爾的時代
      從公理展開理論
      而公理
      要麼是顯然的
      要麼反映真實世界的性質

      笛卡爾把幾何學劃歸到實數的理論
      十九世紀
      戴德金[Dedekind] 維爾斯特拉斯[Weierstrass] 和其他人
      通過把實數系統算數化
      而把空間化爲了具體對象 由純粹思想所創造

    - 不幸
      空間算數化 對數學許下的諾言
      並沒實現
      主要歸咎於 世紀之交 形式主義計劃的介入

      數學的形式化之成功
      引數學在錯誤的道路上走了下去

      既然 空間 數 還有所有東西
      都被放置在理想主義基質內
      就連正整數都有模棱兩可的計算存在
      那麼
      空間已經被算數化 這件事 就沒了效益

      數學成了集合的遊戲
      這個遊戲玩着還不錯
      具有極精確的規則
      然而
      這遊戲成了它自己存在的理由 [自由乎]
      但 其實它只代表了一類非常理想化的數學實體
      人們通通忽略了這一點

    - 當然
      理想主義傾向 在古希臘就已經出現在數學中了
      甚至可以說是主導了數學
      但是
      只是經由 形式主義 的繁盛發展
      才扼殺了
      算數化 本可以給我們的
      洞察數學本質的機會

    - 我們來看一看
      最基本的古典分析理論的結果
      是多麼缺乏計算意義
      觀察下面的斷言
      - 任意 有界非空實數集 A
        都有最小上界
        - 實數 b 是 A 的最小上界
          若 任意 a 屬於 A
          有 a 小於等於 b
          並且 存在 A 中的元素
          任意地靠近 b

      爲避免不必要的複雜
      我們來考慮它的推論
      - 任意 有界有理數列 {x(k)}
        都有最小上界 b (在實數集中)

      如果這個論斷是 構造性有效的
      那麼我們計算 b 這個實數的方式
      就是去計算它的 任意精度的 有理數逼近
      我們可以編程以讓計算機幫我們計算
      例如
      計算機可以被編程而一個一個地生成
      序列 {b(k), m(k)} 的元素
      其中 b(k) 是有理數
      而 m(k) 是正整數 滿足
      1. x(j) <= b(k) + 1/k
         對於所有 j 和 k
      2. x(m(k)) >= b(k) - 1/k
         對於所有 k

      除非 有一個一般方法 M
      能用以 給每個有界有理序列
      生成這種計算機程序
      那麼 按照 構造主義 的標準
      我們就不能說
      - 任意 有界有理數列 {x(k)}
        都有最小上界 b (在實數集中)

      來看看這個 一般方法 M 的威力吧
      考慮
      項僅爲 0 或 1 的序列 {n(k)}
      用 一般方法 M
      我們生成了一個程序來計算 {b(k), m(k)}
      來看一看取 n = 3 時的情況
      設 N = m(3)
      1. n(j) <= b(3) + 1/3
         for all positive integers j
      2. n(N) >= b(3) - 1/3

      而 n(N) = 0 或 1
      若 n(N) = 0
      則 (1) 和 (2) 蘊含
        n(j) <= b(3) + 1/3 <= n(N) + 2/3 = 2/3
        對與所有 j
      因爲 n(j) = 0 或 1
      所以結論是
        n(j) = 0
        對與所有 j
      這樣
      對於每個
      項僅爲 0 或 1 的序列 {n(k)}
      一般方法 M 能夠
      1. 生成一個 n(k) 都爲零的證明
      2. 生成一個 正整數 N 使得 n(N) = 1
      當然
      這個 一般方法 M 並不存在
      沒人有望能夠找到這個方法
      因爲這個方法
      能夠解決很多有名的數學未解之難題
      費瑪大定理 [現在已經證明]
      四色定理 [現在已經在計算機的幫助下證明]
      黎曼假設 等等爲例
      因爲這些問題都可以被化爲
      項僅爲 0 或 1 的序列 {n(k)}
      而需要證明的就是
      或者 n(k) = 0 對所有 k
      或者 n(k) = 1 對某些 k

    - 做爲另一個例子
      考慮直覺上非常顯然的中值定理
      - 每個 閉區 [0,1] 間上的連續函數 f
        滿足 f(0) < 0 且 f(1) > 0
        都在某一點 x0 爲零

      這個定理可以從 最小上界定理推出
      只要取 x0 爲
      滿足 f(x) < 0 的 x 的集合
      的最小上界

      用 最小上界定理來 證明中值定理
      這還並不代表 中值定理 不具有構造意義
      只能說是這個證明 不具有構造意義

      只要仔細觀察一下
      就能發現 中值定理 不具有構造意義
      我們展示如下

      [這裏的證明是我重新敘述的]

      先做一些輔助構造
      設 {n(k)} 爲項爲 -1 或 0 或 1 的數列
      定義實數 a 爲
        a = 求和 3^-k * n(k)
            其中 k 從 1 到 正無窮

      這個構造的特點是
        {n(k)} 如果存在非零項
        那麼其首個非零項 決定 a 的正負
        若 首個非零項 爲 1 則 a >= 0
        若 首個非零項 爲 -1 則 a <= 0
        判定 任意一個 {n(k)} 的首個非零項
          爲 1
          爲 -1
          不存在首個非零項 即 全部都是 0
        的一般方法是不存在的
        這樣
        判定 a >= 0
        或 a <= 0
        的一般方法也是不存在的

      取 區間 [0,1] 上的連續函數 f 滿足
        f(0) = -1
        f(1) = 1
        f(1/3) = f(2/3) = a
      讓 f 在下面每個區間都是線性函數即可
        [0,1/3]
        [1/3,2/3]
        [2/3,1]

      如果 中值定理 在構造主義意義下 有效
      那麼 就有 x0 使得 f(x0) = 0
        x0 做爲實數
        是由 計算任意精度有理近似 的函數 定義的

      當計算得 x0 之後
      如果發現 x0 < 2/3 那麼就有 a >= 0
      如果發現 x0 > 1/3 那麼就有 a <= 0
      所以說
      如果算得了 x0
      就得完成了上面輔助構造中的 不可能完成的判定

      所以 中值定理 不具有構造意義

    - 布勞維爾[Brouwer] 對抗 形式主義的進展
      並試圖 把數學從邏輯中解脫出來
      通過
        給每個數學定理和數學證明
        以實用的詮釋
      他想要加強數學

      他的計劃沒有獲得支持

      他是個無親和力的展示者
      是個不圓滑的倡導人
      爭先挑戰希爾伯特的偉大威望
      挑戰理想主義數學以最少的代價獲得最多的成果這一事實

      更有甚者
      布勞維爾 自己的思想體系裏
      就有 理想唯心的蹤跡 加以形而上學的空斷
      由此
      具體數學活動
      受構造主義的哲學偏見所累

      一種關於否定的演算被發展出來
      依靠它就能避免獲得具體的構造果
      難怪
      布勞維爾的某些告誡 之後被形式化
      由此發展出 所謂 直覺主義數論
      如此得來的形式系統 其實沒有一點構造性價值

      公道地說 布勞維爾 並沒有參與這種形式化現實的活動
      要怪就怪邏輯學家
      他們導致
      很多自認爲 瞭解構造主義觀點的 數學家
      腦子裏想的其實是一個不足掛齒的形式體系
      或者 把構造主義與遞歸函數理論 混爲一談

    - 布勞維爾 深陷 形而上學的空斷
      只爲改進關於 連續統[continuum] 的理論
      強行揣測 連續統的性質
      成了布勞維爾和邏輯學家的魔怔

      這引邏輯學家走向扭曲
      發展各種形式體系
      種種都脫離實際
      你解釋我 我解釋你
      寄希望於 連續統的性質 終有一天將自行顯現

      這引起布勞維爾揮之不去的懷疑
      他感覺 除非他親自出馬加以阻止
      否則 連續統 將變爲 離散的
      他爲此引入了 自由選擇序列[free-choice sequences]
      用以構造連續統
      這樣 連續統 就不能是離散的了
      只因定義上的差異
      這使得數學變得非常怪異
      變得不合數學家的胃口
      這註定毀了布勞維爾的計劃
      這很可惜
      因爲對於古典數學的缺陷
      布勞維爾有卓越的洞見
      且他英雄壯舉 預要改正數學

*** 原文

    - Geometry was highly idealistic
        from the time of Euclid and the ancients
        until the time of Descartes,
      unfolding from axioms
      taken either to be self-evident
      or to reflect properties of the real world.

      Descartes reduced geometry to the theory of the real numbers,
      and in the nineteenth century
      Dedekind, Weierstrass, and others,
      by the arithmetization of the real number system,
      brought space into the concrete realm of objects
      constructed by pure thought.

    - Unfortunately
      the promise held out to mathematics
      by the arithmetization of space
      was not fulfilled,
      largely due to the intervention,
      around the turn of the century,
      of the formalist program.

      The successful formalization of mathematics
      helped keep mathematics on a wrong course.

      The fact that space has been arithmetized
      loses much of its significance
      if space, number, and everything else
      are fitted into a matrix of idealism
      where even the positive integers
      have an ambiguous computational existence.

      Mathematics becomes the game of sets,
      which is a fine game as far as it goes,
      with rules that are admirably precise.
      The game becomes its own justification,
      and the fact that it represents
      a highly idealized version of mathematical existence
      is universally ignored.

    - Of course, idealistic tendencies have been present
      if not dominantin mathematics
      since the Greeks,
      but it took the full flowering of formalism
      to kill the insight into the nature of mathematics
      which its arithmetization could have given.

    - To see how some of the most basic results of classical analysis
      lack computational meaning,
      take the assertion that
      - every bounded non-void set A of real numbers
        has a least upper bound.
        - The real number b is the least upper bound of A
          if a <= b
          for all a in A
          and if there exist elements of A
          that are arbitrarily close to b.

      To avoid unnecessary complications,
      we actually consider the somewhat less general assertion that
      - every bounded sequence {x(k)} of rational numbers
        has a least upper bound b
        (in the set of real numbers).

      If this assertion were constructively valid,
      we could compute b,
      in the sense of computing a rational number approximating b
      to within any desired accuracy;
      infact we could program a digital computer
      to compute the approximations for us.
      For instance,
      the computer could be programmed to produce, one by one,
      a sequence {(b(k), m(k))} of ordered pairs,
      where each b(k) is a rational number
      and each m(k) is a positive integer, such that
      1. x(j) <= b(k) + 1/k
         for all positive integers j and k,
      2. x(m(k)) >= b(k) - 1/k
         for all positive integers k.

      Unless there exists a general method M that
      produces such a computer program
      corresponding to each bounded
      constructively given sequence {x(k)} of rational numbers,
      we are not justified, by constructive standards,
      in asserting that each of the sequences {x(k)}
      has a least upper bound.

      To see the scope such a method M would have,
      consider a constructively given sequence {n(k)} of integers,
      each of which is either 0 or 1.
      Using the method M,
      we compute a rational number b(3)
      and a positive integer N = m(3) such that
      1. n(j) <= b(3) + 1/3
         for all positive integers j
      2. n(N) >= b(3) - 1/3

      Either n(N) = 0 or n(N) = 1
      If n(N) = 0
      then (1) and (2) imply that
        n(j) <= b(3) + 1/3 <= n(N) + 2/3 = 2/3
        for all j
      Since each n(j) is either 0 or 1,
      it follows that n(j) = 0, for all j.
      Thus,
      for each of the sequences {n(k)} being considered,
      the method M either
      1. produces a proof that
         the n(k) are all equal to 0,
      2. or produces a positive integer N
         such that n(N) = 1.
      Of course, such a method M does not exist,
      and nobody expects that one will ever be found.
      Such a method
      would solve most of the famous unsolved problems of mathematics
      Fermat's last theorem,
      the four-color problem,
      and the Riemann hypothesis, in particular,
      since each of these problems can be reduced to finding,
      for a certain sequence {n(k)} of the type being considered,
      either a proof that
        n(k) = 0 for all k
      or a proof that
        n(k) = 1 for some k.

    - As another instance,
      consider the intuitively appealing theorem that
      - every continuous function f on the closed interval [0,1],
        for which f(0) < 0 and f(1) > 0,
        vanishes at some point x0.

      This theorem can be derived from the least-upper-bound principle:
      take x0 to be the least upper bound
      of the set of all x for which f(x) < 0.

      The fact that we make use of the least-upper-bound principle
      does not mean our theorem is unconstructive;
      it only means the given proof is unconstructive.

      A closer examination demonstrates that
      our theorem itself is unconstructive.
      This demonstration, which we now give,
      uses facts from the constructive theory of continuous functions,
      with which the reader is probably not familiar.
      Nevertheless, it should provide some insight.
      Let {n(k)} be any constructively given sequence of integers,
      each of which is either -1, 0, or 1.
      Define the real number a by
        a = SUM 3^-k * n(k)
            where k from 1 to positive-infinity
      There exists a unique constructively given continuous
      function f on [0,1] such that
        f(0) = -1
        f(1) = 1
        f(1/3) = f(2/3) = a
      and f is linear on each of the intervals
        [0,1/3]
        [1/3,2/3]
        [2/3,1]
      If our theorem is valid,
      there exists a point x0 with f(x0) = 0.
        By computing a sufficiently close
        rational approximation to x0,
      we show that either
      1. x0 < 2/3
      2. x0 > 1/3
      In the first case, a >= 0,
      and therefore
      the first nonzero term of the sequence {n(k)},
      if one exists, equals 1.
      Similarly, in the second case,
      the first nonzero term,
      if one exists, equals -1.
      Thus our theorem gives a method,
      for each of the sequences {n(k)} being considered,
      of either
      1. proving that any term that equals 1
         is preceded by a term that equals -1,
      2. proving that any term that equals -1
         is preceded by a term that equals 1.
      Nobody believes that such a method will ever be found.

    - Brouwer fought the advance of formalism
      and undertook the disengagement of mathematics from logic.
      He wanted to strengthen mathematics by
        associating to every theorem and every proof
        a pragmatically meaningful interpretation.

      His program failed to gain support.

      He was an indifferent expositor and an inflexible advocate,
      contending against the great prestige of Hilbert
      and the undeniable fact that
      idealistic mathematics produced the most general results
      with the least effort.

      More important,
      Brouwer's system itself had traces of idealism
      and, worse, of metaphysical speculation.
      There was a preoccupation
      with the philosophical aspects of constructivism
      at the expense of concrete mathematical activity.

      A calculus of negation was developed
      which became a crutch
      to avoid the necessity of getting precise constructive results.
      It is not surprising that
      some of Brouwer's precepts were then formalized,
      giving rise to so-called intuitionistic number theory,
      and that the formal system so obtained
      turned out not to be of any constructive value.

      In fairness to Brouwer
      it should be said that
      he did not associate himself with these efforts
      to formalize reality;
      it is the fault of the logicians that
      many mathematicians who think they know something of the constructive point of view
      have in mind a dinky formal system
      or, just as bad,
      confuse constructivism with recursive function theory.

    - Brouwer became involved in metaphysical speculation
      by his desire to improve the theory of the continuum.
      A bugaboo of both Brouwer and the logicians
      has been compulsive speculation
      about the nature of the continuum.

      In the case of the logicians this leads to contortions
      in which various formal systems,
      all detached from reality,
      are interpreted within one another
      in the hope that
      the nature of the continuum will somehow emerge.

      In Brouwer's case
      there seems to have been a nagging suspicion that
      unless he personally intervened to prevent it
      the continuum would turn out to be discrete.
      He therefore introduced the method of free-choice sequences
      for constructing the continuum,
      as a consequence of which the continuum cannot be discrete
      because it is not well enough defined.
      This makes mathematics so bizarre
      it becomes unpalatable to mathematicians,
      and foredooms the whole of Brouwer's program.
      This is a pity,
      because Brouwer had a remarkable insight
      into the defects of classical mathematics,
      and he made a heroic attempt to set things right.

* 構造 / the constructivization of mathematics

*** 譯文

    - 一個集合定義於
      描述如何構造其元素
      描述如何判斷二元素相等

      並沒有保證說這種描述一定能被理解
      可能 作者認爲已經把集合描述清楚了
      而 讀者卻沒有頭緒

      比如
      考慮整數序列 {n(k)}
      爲了構造這樣一個序列
      我們需要
      1. 給出一個計算規則
         使得對於 任意 正整數 k
         都能算得 一個 整數 n(k)
      2. 並且每次的計算
         都能在有限步驟內結束

      那好 整數序列 {n(k)} 也可以解釋爲
      1. 搜索 並 辨認以接受
      2. 並證明在有限步驟內
         搜索可以找到一個可以接受的 n(k)

      [我不確定 搜索 一詞 對 Bishop 意謂着什麼
       我想 搜索 代表了 隨機性
       我可以嘗試給一個例子 來補充 Bishop 這裏的論點
       設想
       一個小小納米機器人在某個分子世界中隨機行走
       每當它走累了就停下裏歇息
       並記錄身邊的一個分子中原子的個數 做爲 n(k)
       我瞭解這個小機器人 知道它走一會就得歇息一會
       有限步驟內一定能找到 n(k)
       這裏蘊含的隨機性
       已經使得 所生成的數列 不是傳統的函數了
       總之 能體會到上下兩種最整數序列的定義
       其性質是完全不同的 就好]

      當然 我們想的並不是這樣的定義
      但是 我們不可能考慮到
      對我們所下的定義的 所有可能的解釋
      並說出 各種解釋符不合符合我們的心意

      定義總會有歧義
      但是 隨着讀者閱讀
      歧義會減少
      作者的意圖會被一點一點發現
      隨着 閱讀深入 思維展開
      讀者需要修改自己解釋
      來迎合作者的意圖

      在交流的過程中
      只要對與作者目前所說的 有個合理的解釋
      讀者就應該滿足了

      而作者本身
      不可能全然知曉 他下的定義 所能衍生出來的所有解釋
      且 他也有必要修改自己的解釋
      有時 連定義本身也要修改
      順應經驗使然

    - 構造主義 對 數學連詞 與 數學量詞 的
      [Bishop 故意不說 邏輯連詞 與 邏輯量詞]
      由布勞維爾建立

    - 爲證 (P 且 Q)
      需 證 P
      且 證 Q
      這與古典數學相同

    - 爲證 (P 或 Q)
      需 證 P
      或 證 Q
      而在古典數學中 爲證 (P 或 Q) 可以根被不必證明 P Q 之一

    - 爲證 (P 則 Q)
      需證 P 可證 則 Q 可證
      [我們也記之爲
       (P -> Q)
       (若 P 則 Q)
       (P 推出 Q)
       (P 蘊含 Q)]

      [這類式子 我稱之爲 則式
       則 字 譯自 imply
       通常譯之爲 蘊含
       Bishop 對 則式 的理解曖昧不明
       故不良之句 去而不譯
       我同時也
       譯 瑾欽[Gentzen]的 sequent calculus 爲 則式演算
       並譯 sequent 爲 則式
       對與 則式 的討論
       詳見 程序語言蟬語的文檔]

    - 爲證 (否 P)
      需正 (P 則 0 = 1)
      或者 (P 則 其他顯然的矛盾)
      [也就是說 否定被細化爲了各種各樣的矛盾]
      古典數學不區分 P 與 (not (not P))
      而對於構造主義來說
      二者顯然有別 後者弱 而前者強

    - 布勞維爾的體系中
      否定在定義中得以重用
      例如 不等 和 補集
      根據布勞維爾
      集合 A 的兩個元素不等
      若 這元素之相等 能讓我們算出 0 = 1

      自然想換 消極的定義 成 積極的定義
      在定義中 儘量多說一些 計算有關的信息
      詳細地
      用 什麼樣的計算 產生 什麼樣的結果
      來做定義

      布勞維爾本人 對於實數系統就是這麼做的
      對於不等關係 給以了更強的積極定義
      以補之前充消極的定義
      經驗表明
      根本沒必要用否定來定義不等關係
      需要不等關係的地方 最好以積極的方式引入它們
      對於 補集 也是如此

    - Van Dantzig 和 其他人 更認爲
      可以完全 去除構造主義數學中的 否定
      經驗證實了這一點
      在很多地方 我們看似在用否定
      比如
        一個整數 要麼爲偶數 要麼不爲偶數
      我們實際是說 有限的兩種選擇中的一個

      爲了不那麼教條
      我們在這類情形下還是使用根 否定 有關的說法
      但僅僅把這種說法限制在這種有限的情況下
      直到經驗讓我們改了主意
      直到反例給我們了新的動機

      這樣的好處是把數學變得更直接
      並且
      在某些情況下
      鼓勵我們琢磨我們的結論

    - 反證法 [歸謬法]
      [這裏我完全拋棄 Bishop 的句子
       自己重新敘述]

      [反證法 在於
       爲否定某個命題
       先假設其正確
       再推出矛盾
       此方法在構造主義數學中的合法性是顯然的
       因爲
       我們定義 (否 P) 的方式
       就是 (P 則 某個矛盾)
       比如上面我們對 任意有界實數集有最小上界 這個命題的否定
       就在於 證明
       (若 任意有界實數集有最小上界
        則 我們能找到萬能程序生成器 M
           這個 M 可以用來生成各種數學難題的證明)]

    - 任意量詞
      即 任意 A 之元素 有性質 P
      [記爲 (x : A 則 P(x))
       或 (x : A -> P(x))]
      在構造主義數學中的意思與古典數學一樣
      爲了證明這種命題
      需證
      若 x 爲 A 的元素
      則 x 有性質 P

    - 存在量詞
      構造主義數學中 存在量詞
      要比 古典數學中 侷限得多

      證明一個東西存在的唯一方式
      就是找出它
      或構造它
      或寫一個在有限步驟內結束的程序算出它
      然而
      在古典數學中
      有別的手段可以用來證明 存在性

      如下原則在古典數學中有效
        要麼 任意 A 的元素 有性質 P
        要麼 存在 A 的某個元素 有性質 (否 P)
      這個原則
      我們稱之爲 無所不知原則[the principle of omniscience]
      是古典數學中 大多數不具有構造性的結果 的根源
      看 無所不知原則的簡化版本 就知道了
        若 {n(k)} 是整數數列
        則 要麼 n(k) = 0 對某些 k 成立
           要麼 n(k) =/= 0 對所有 k 成立
      我們稱之爲 受限無所不知原則[the limited principle of omniscience]
      古典數學中的 一個接一個的定理
      都本質上依賴 受限無所不知原則
      因此 他們的證明 是不具有構造性的

      例如
      - 閉區間上 連續實值函數 達到其最大值
      - 封閉單元上 連續變換 具有不動點 [即 不動點定理]
      - 遍歷定理[ergodictheorem]
      - 哈恩-巴拿赫定理[Hahn-Banach theorem]

      然而
      構造主義數學 並不是把這些定理拋棄了
      這裏列出的每個定理 P
      都有一個構造主義代替 Q
      Q 是具有構造意義的
      在古典數學中 Q 蘊含 P
      [即 Q 強與 P]
      例如
        封閉單元上 連續變換 具有不動點
      其構造主義代替爲
        封閉單元上 連續變換
        可找一點
        其像與其任意接近

    - 古典數學中的定理
      在多大程度上 有良好的構造主義代替
      展示了
      古典數學具有堅實的構造主義基礎

    - 當一個古典數學家聲明自己是個構造主義者時
      他可能指 他不使用 選擇公理
      這個公理是少有的 能折磨古典數學家良心的了
      但是 實際上這個公理 並不是古典數學非構造性的根源
      選擇函數 在構造主義數學中是存在的
      因爲
      選擇 蘊於 存在之本
      [a choice is implied by the very meaning of existence]

      古典數學中 使用選擇公理時
      要麼 是無關緊要的
      要麼 就混用了 無所不知原則
      選擇公理被用以從等價類中選取元素
      然而 等價類一開始就不應該出現
      例如
      實數 不應該被定義爲
      柯西列[Cauchy sequences] 的等價類
      等價類 之引入 實屬無益
      又例如
      實數集是良序的[the real numbers can be well ordered]
      其證明 就混用了 選擇公理 和 無所不知原則
      這種證明獲得構造意義的希望渺茫
        實數集是良序的
      這個定理想要獲得
      與古典解釋的直覺意義 相互協調的 構造主義版本
      看來是不可能了

    - 幾乎所有能想到的抵抗都試過了
      想要抵抗這種 現實主義的 簡單處理數學 的方式

      布勞維爾 所做的構造主義數學比任何人都多
      但是 他卻認爲
      需要爲 連續統 引入一種 革命性的 半神祕的理論

      外爾[Weyl] 偉大的數學家
      在實踐中壓制着自己對構造主義的信仰
      但是 他卻說過
      理想主義數學應用於物理學
      在這種應用中 找的到理想主義數學的合理性

      希爾伯特 在其所提出的 元數學[meta-mathematics] 中
      堅持使用 構造主義方法
      但是 他卻相信
      構造主義數學的代價太大
      只要在元數學內證明形式體系的一致性[consistency]
      他就滿足了
      [即 著名的 希爾伯特計劃]

      另外還有些人 想要在遞歸函數理論中 尋找構造主義的真諦
      [指 蘇俄的學派]

      人們仍然尋求着通向現實的捷徑
      好想找到去桃花源的路
      豁然開朗 讓人洞觀所有古典數學的構造意義
      人們忙於找捷徑 但都以失敗告終
      毫不誇張地說
      坦途大路還沒人走過呢
      現實主義的 簡單處理數學 的方式
      還有待嘗試呢
      現在 是時候做這樣的嘗試了

*** 原文

    - A set is defined
      by describing exactly what must be done
      in order to construct an element of the set
      and what must be done in order to show that
      two elements are equal.

      There is no guarantee that
      the description will be understood;
      it may be that
      an author thinks he has described a set with sufficient clarity
      but a reader does not understand.

      As an illustration
      consider the set of all sequences {n(k)} of integers.
      To construct such a sequence
      we must give a rule
      which associates an integer n(k)
      to each positive integer k in such a way that
      for each value of k
      the associated integer n(k) can be determined
        in a finite number of steps
        by an entirely routine process.

      Now this definition could perhaps be interpreted
      to admit sequences {n(k)}
      in which n(k) is constructed by a search,
      the proof that the search actually produces a value of n(k)
      after a finite number of steps
      being given in some formal system.

      Of course, we do not have this interpretation in mind,
      but it is impossible
      to consider every possible interpretation of our definition
      and say whether that is what we have in mind.

      There is always ambiguity,
      but it becomes less and less as the reader continues to read
      and discovers more and more of the author's intent,
      modifying his interpretations if necessary
      to fit the intentions of the author
      as they continue to unfold.

      At any stage of the exposition
      the reader should be content
      if he can give a reasonable interpretation
      to account for everything the author has said.

      The expositor himself
      can never fully know all the possible ramifications of his definitions,
      and he is subject to the same necessity of modifying his interpretations,
      and sometimes his definitions as well,
      to conform to the dictates of experience.

    - The constructive interpretations
      of the mathematical connectives and quantifiers
      have been established by Brouwer.

    - To prove the statement (P and Q)
      we must prove the statement P and prove the statement Q,
      just as in classical mathematics.

    - To provethe statement (P or Q)
      we must either prove the statement P or prove the statement Q,
      whereas in classical mathematics
      it is possible to prove (P or Q) without proving either the statement P or the statement Q.

    - The connective 'implies' is more complicated.
      To prove (P implies Q)
      we must show that P necessarily entails Q,
      or that Q is true whenever P is true.
      The validity of the computational facts implicit in the statement P
      must insure the validity of the computational facts implicitin the statement Q,
      but the way this actually happens can only be seen
      by looking at the proof of the statement (P implies Q).
      Statements formed with this connective,
      for example, statements of the type ((P implies Q) implies R),
      have a less immediate meaning than the statements from which they are formed,
      although in actual practice
      this does not seem to lead to difficulties in interpretation.

    - The negation (not P) of a statement P
      is the statement (P implies 0 = 1).
      Classical mathematics makes no distinction
      between the content of the statements P and not (not P),
      whereas constructively
      the latter is a weaker statement.

    - Brouwer's system makes essential use of negation in defining,
      for instance, inequality and set complementation.
      Thus two elements of a set A are unequal
        according to Brouwer
      if the assumption of their equality
      somehow allows us to compute that 0 = 1.

      It is natural to want to replace this negativistic definition
      by something more affirmative,
      phrased as much as possible
      in terms of specific computations
      leading to specific results.

      Brouwer himself does just this for the real number system,
      introducing an affirmative and stronger relation of inequality
      in addition to the negativistic relation already defined.
      Experience shows that it is not necessary to define inequality in terms of negation.
      For those cases in which an inequality relation is needed,
      it is better to introduce it affirmatively.
      The same remarks apply to set complementation.

    - Van Dantzig and others have gone as far as to propose that
      negation could be entirely avoided in constructive mathematics.
      Experience bears this out.
      In many cases where we seem to be using negation
      for instance, in the assertion that
        either a given integer is even or it is no
      we are really asserting that
      one of two finitely distinguishable alternatives actually obtains.

      Without intending to establish a dogma,
      we may continue to employ the language of negation
      but reserve it for situations of this sort,
      at least until experience changes our minds,
      and for counterexamples and purposes of motivation.

      This will have the advantage of making mathematics more immediate
      and in certain situations forcing us to sharpen our results.

    - Proofs by contradiction
      are constructively justified in finite situations.

      When we have proved that
      one of finitely many alternatives holds at a certain stage in the proof of a theorem,
      to finish the proof of the theorem it is enough to show that
      the theorem is a consequence of each of the alternatives.
      Should one of the alternatives lead to a contradiction,
      that is, imply 0 = 1,
      we may either say that the alternative in question is ruled out
      and pass on to the consideration of the other alternatives,
      or we may be more meticulous
      and prove that the theorem is a consequence of the equality 0 = 1.

    - A universal statement,
      to the effect that
      every element of a certain set A has a certain property P,
      has the same meaning in constructive as in classical mathematics.
      To prove such a statement
      we must show by some general argument that
      if x is any element of A,
      then x has property P.

    - Constructive existence
      is much more restrictive
      than the ideal existence of classical mathematics.

      The only way to show that an object exists
      is to give a finite routine for finding it,
      whereas in classical mathematics
      other methods can be used.
      In fact the following principle is valid in classical mathematics:
        Either all elements of A have property P
        or there exists an element of A with property (not P).
      This principle,
      which we shall call the principle of omniscience,
      lies at the root of most of the unconstructivities of classical mathematics.
      This is already true of the principle of omniscience in its simplest form:
        if {n(k)} is a sequence of integers,
        then either n(k) = 0 for some k
        or n(k) =/= 0 for all k.
      We shall call this the limited principle of omniscience.
      Theorem after theorem of classical mathematics
      depends in an essential way on the limited principle of omniscience,
      and is therefore not constructively valid.

      Some instances of this are the theorem that
      - a continuous real valued function
        on a closed bounded interval
        attains its maximum,
      - the fixed-point theorem
        for a continuous map of a closed cell into itself,
      - the ergodictheorem,
      - and the Hahn-Banach theorem.

      Nevertheless these theorems are not lost to constructive mathematics.
      Each of these theorems P has a constructive substitute Q,
      which is a constructively valid theorem
      Q implying P in the classical system
      by a more or less simple argument
      based on the limited principle of omniscience.
      For instance,
      the statement that
        every continuous function from a closed cell in euclidean space
        into itself admits a fixed point
      finds a constructive substitute in the statement that
        such a function admits a point
        which is arbitrarily near to its image.

    - The extent
      to which good constructive substitutes exist for the theorems of classical mathematics
      can be regarded as a demonstration that
      classical mathematics has a substantial underpinning of constructive truth.

    - When a classical mathematician claims he is a constructivist,
      he probably means he avoids the axiom of choice.
      This axiom is unique in its ability to trouble the conscience of the classical mathematician,
      but in fact it is not a real source of the unconstructivities of classical mathematics.
      A choice function exists in constructive mathematics,
      because a choice is implied by the very meaning of existence.

      Applications of the axiom of choice in classical mathematics
      either are irrelevant
      or are combined with a sweeping appeal to the principle of omniscience.
      The axiom of choice is used to extract elements from equivalence classes
      where they should never have been put in the first place.
      For instance,
      a real number should not be defined
      as an equivalence class of Cauchy sequences of rational numbers;
      there is no need to drag in the equivalence classes.
      The proof that the real numbers can be well ordered
      is an instance of a proof in which a sweeping use of the principle of omniscience
      is combined with an appeal to the axiom of choice.
      Such proofs offer little hope of constructivization.
      It is not likely that the theorem
        the real numbers can be well ordered
      will be given a constructive version
      consonant with the intuitive interpretation of the classical result.

    - Almost every conceivable type of resistance has been offered
      to a straightforward realistic treatment of mathematics,
      even by constructivists.

      Brouwer, who has done more for constructive mathematics than anyone else,
      thought it necessary to introduce a revolutionary, semimystical theory of the continuum.

      Weyl, a great mathematician who in practice suppressed his constructivist convictions,
      expressed the opinion that idealistic mathematics finds its justification in its applications to physics.

      Hilbert, who insisted on constructivity in meta-mathematics
      but believed the price of a constructive mathematics was too great,
      was willing to settle for consistency.

      Brouwer's disciples
      joined forces with the logicians
      in attempts to formalize constructive mathematics.

      Others seek constructive truth in the framework of recursive function theory.

      Still others look for a short cut to reality,
      a point of vantage
      which will suddenly reveal classical mathematics in a constructive light.
      None of these substitutes for a straightforward realistic approach has worked.
      It is no exaggeration to say that
      a straightforward realistic approach to mathematics has yet to be tried.
      It is time to make the attempt.

*** 記 任何使人心悅誠服的論證都是證明

    - 文章開頭的論述 詮釋着 Bishop 之後的名言
      A proof is any completely convincing argument
      即 任何使人心悅誠服的論證都是證明

    - 同時也詮釋着 布勞維爾意義上數學的主觀性
