#+html_head: <link rel="stylesheet" href="../css/org-page.css"/>
#+title: are you an anarchist / 你是無政府主義者嗎
#+author: David Graeber

* 題解

  - 本譯文算是我的自我解釋
    爲了向 我愛的 關心我的朋友 解釋我最近的想法和行爲

  - 原文的作者 David Graeber 是美國人類學家
    其著作頗豐 對現代城市中的人類行爲有有趣的見解

* 譯文

  - 你可能以已經聽說過 無政府主義 一詞
    也聽說過 無政府主義者 所具有的信條
    但是 很可能你所聽說的相關的一切都是胡說

  - 很多人 誤認爲 無政府主義者 是 暴力 混亂 破壞 的倡導者
    誤認爲 他們反對所有形式的秩序和組織
    誤認爲 他們是狂熱的 想要炸毀一切的 虛無主義者
    這些都與事實相去甚遠
    其實 無政府主義 就是
    相信人們不必被強迫也能合理行事
    這只是很簡單的想法
    但是正是這個簡單的想法
    讓有錢有權的人覺得極端危險

  - 簡單地說 無政府主義者的信條 可以歸結爲兩條基本假設
    第一是
    在正常情況下人們都會儘量 通情達理 並且 遵守禮節 [reasonable and decent]
    並且不用告訴他們 他們就能組織好他們自己還有他們的社區
    第二是
    權利會腐敗

  - 無政府主義 主要就是
    有勇氣去追隨 我們賴以爲生的 常禮[common decency] 和其邏輯結論

  - 也許聽起來很奇怪
    在很多重要的方面 你可能已經是無政府主義者了 -- 只是你自己沒有意識到

  - 我們以日常生活中的一些例子爲例

    - 如果人們正在排隊等着進入一輛擁擠的公交車
      你是會耐心地排隊
      還是會擠過人羣 ?

  - 如果你的回答是 "耐心排隊"
    那麼你就已經習慣了像無政府主義者一樣行事!
    因爲最基本的無政府主義原則就是 *自治* [self-organization]
    即 相信人們不需要以起訴相威脅
    就能理解他人並且相互尊重

  - 每個人都相信 自己能合理行事
    如果他們認爲法律和警察是必要的
    只是因爲他們不相信他人也能合理行事
    但是 他人不是也如此看待你嗎 ?
    無政府主義者認爲
    是反社會行爲使得 軍隊 警察 監獄 以及 政府 對我們的控制 成爲必要
    但是幾乎所有這些反社會行爲 都是由系統的不平等和不公正引起的
    而正是因爲 軍隊 警察 監獄 和 政府
    使得這些系統的不平和不公成爲了可能
    這是一個惡性循環
    如果人們習慣了自己的意見和看法總是被當作無足輕重
    那麼他們就容易變得憤世嫉俗甚至暴力
    這樣當然就又給了當權者理由 去說他們的意見和看法並不重要
    一旦人們明白了自己的的意見 是和其他人的意見同等重要的
    他們就會表現的非常能理解他人
    簡而言之
    無政府主義者相信 通常是權利自身 以及權利的影響
    導致了人們的愚蠢和不負責任

    - 你是某個 聚落布 或者 運動隊
      或者任何一個依志願而形成的組織 的成員嗎 ?
      在其中 決策不是由某個領導者強加給你的
      而是依所有成員的共識達成的

  - 如果你的回答是 "是"
    那麼你就屬於某個依照無政府主義原則而運作的組織
    因爲 另一個無政府主義原則就是 *志願合作* [voluntary association]
    這其實就是簡單地把民主原則適用到日常生活當中
    區別只在於 無政府主義者相信
    構建這樣的一個社會也是有可能的
    其中的方方面面都可以依此原則來運作
    所有的小組都依其成員的自由志願[free consent]而決策
    因此 所有自上而下的軍事化的組織
    比如 軍隊 官僚 和 大的公司
    這些依照命令的鏈條而運作的組織
    都不再必要了
    也許你認爲這是不可能的
    也許你認爲這是可能的
    但是 每當你因一致同意而達成協議 從而避免了恐嚇與脅迫
    每當你和另外某人達成共識而作出志願的計劃
    或者當你考慮到他人的特殊困境而作出妥協
    你都在踐行無政府主義原則 -- 即使你沒有意識到

  - ><

* 原文

  - Chances are you have already heard something
    about who anarchists are and what they are supposed to believe.
    Chances are almost everything you have heard is nonsense.
    Many people seem to think that
    anarchists are proponents of violence, chaos, and destruction,
    that they are against all forms of order and organization,
    or that they are crazed nihilists
    who just want to blow everything up.
    In reality, nothing could be further from the truth.
    Anarchists are simply people who believe
    human beings are capable of behaving in a reasonable fashion
    without having to be forced to.
    It is really a very simple notion.
    But it's one that the rich and powerful
    have always found extremely dangerous.

  - At their very simplest,
    anarchist beliefs turn on to two elementary assumptions.
    The first is that human beings are, under ordinary circumstances,
    about as reasonable and decent as they are allowed to be,
    and can organize themselves and their communities
    without needing to be told how.
    The second is that power corrupts.
    Most of all, anarchism is just a matter of
    having the courage to take the simple principles
    of common decency that we all live by,
    and to follow them through to their logical conclusions.
    Odd though this may seem,
    in most important ways you are probably already an anarchist
    -- you just don't realize it.

  - Let's start by taking a few examples from everyday life.

    - If there's a line to get on a crowded bus,
      do you wait your turn and refrain from
      elbowing your way past others even in the absence of police?

  - If you answered "yes",
    then you are used to acting like an anarchist!
    The most basic anarchist principle is self-organization:
    the assumption that human beings
    do not need to be threatened with prosecution
    in order to be able to
    come to reasonable understandings with each other,
    or to treat each other with dignity and respect.

  - Everyone believes they are capable of
    behaving reasonably themselves.
    If they think laws and police are necessary,
    it is only because they don't believe that other people are.
    But if you think about it,
    don't those people all feel exactly the same way about you?
    Anarchists argue that almost all the anti-social behavior
    which makes us think it's necessary to have
    armies, police, prisons, and governments to control our lives,
    is actually caused by the systematic inequalities and injustice
    those armies, police, prisons and governments make possible.
    It's all a vicious circle.
    If people are used to being treated like
    their opinions do not matter,
    they are likely to become angry and cynical,
    even violent -- which of course makes it easy for those in power
    to say that their opinions do not matter.
    Once they understand that their opinions really do matter
    just as much as anyone else's,
    they tend to become remarkably understanding.
    To cut a long story short:
    anarchists believe that for the most part
    it is power itself,
    and the effects of power,
    that make people stupid and irresponsible.

    - Are you a member of a club or sports team
      or any other voluntary organization
      where decisions are not imposed by one leader
      but made on the basis of general consent?

  - If you answered "yes",
    then you belong to an organization
    which works on anarchist principles!
    Another basic anarchist principle is voluntary association.
    This is simply a matter of applying democratic principles
    to ordinary life. The only difference is that
    anarchists believe it should be possible to have a society
    in which everything could be organized along these lines,
    all groups based on the free consent of their members,
    and therefore, that all top-down, military styles of organization
    like armies or bureaucracies or large corporations,
    based on chains of command, would no longer be necessary.
    Perhaps you don't believe that would be possible.
    Perhaps you do. But every time you reach an agreement by consensus,
    rather than threats, every time you make a voluntary arrangement
    with another person, come to an understanding,
    or reach a compromise by taking due consideration
    of the other person's particular situation or needs,
    you are being an anarchist -- even if you don't realize it.

  - ><

  - Anarchism is just the way people act
    when they are free to do as they choose,
    and when they deal with others who are equally free
    -- and therefore aware of the responsibility to others that entails.
    This leads to another crucial point:
    that while people can be reasonable and considerate
    when they are dealing with equals,
    human nature is such that they cannot be trusted
    to do so when given power over others.
    Give someone such power,
    they will almost invariably abuse it in some way or another.

    - Do you believe that most politicians are selfish,
      egotistical swine who don't really care about the public interest?
      Do you think we live in an economic system
      which is stupid and unfair?

  - If you answered "yes",
    then you subscribe to the anarchist critique of today's society
    -- at least, in its broadest outlines.
    Anarchists believe that power corrupts
    and those who spend their entire lives seeking power
    are the very last people who should have it.
    Anarchists believe that our present economic system
    is more likely to reward people for selfish
    and unscrupulous behavior
    than for being decent, caring human beings.
    Most people feel that way.
    The only difference is that most people don't think
    there's anything that can be done about it, or anyway
    -- and this is what the faithful servants of the powerful
    are always most likely to insist
    -- anything that won't end up making things even worse.

  - But what if that weren't true?

  - And is there really any reason to believe this?
    When you can actually test them,
    most of the usual predictions about
    what would happen without states or capitalism
    turn out to be entirely untrue.
    For thousands of years people lived without governments.
    In many parts of the world people live outside of the control
    of governments today. They do not all kill each other.
    Mostly they just get on about their lives
    the same as anyone else would.
    Of course, in a complex, urban, technological society
    all this would be more complicated:
    but technology can also make all these problems
    a lot easier to solve. In fact, we have not even begun
    to think about what our lives could be like
    if technology were really marshaled to fit human needs.
    How many hours would we really need to work
    in order to maintain a functional society -- that is,
    if we got rid of all the useless or destructive occupations
    like telemarketers, lawyers, prison guards,
    financial analysts, public relations experts,
    bureaucrats and politicians,
    and turn our best scientific minds away from working on
    space weaponry or stock market systems
    to mechanizing away dangerous or annoying tasks
    like coal mining or cleaning the bathroom,
    and distribute the remaining work among everyone equally?
    Five hours a day? Four? Three? Two?
    Nobody knows because no one is even asking this kind of question.
    Anarchists think these are the very questions we should be asking.

    - Do you really believe those things you tell your children
      (or that your parents told you)?

  - "It doesn't matter who started it."
    "Two wrongs don't make a right."
    "Clean up your own mess."
    "Do unto others..."
    "Don't be mean to people just because they're different."
    Perhaps we should decide whether we're lying to our children
    when we tell them about right and wrong,
    or whether we're willing to take our own injunctions seriously.
    Because if you take these moral principles
    to their logical conclusions, you arrive at anarchism.

  - Take the principle that
    two wrongs don't make a right.
    If you really took it seriously,
    that alone would knock away almost the entire basis
    for war and the criminal justice system.
    The same goes for sharing:
    we're always telling children that
    they have to learn to share,
    to be considerate of each other's needs,
    to help each other;
    then we go off into the real world
    where we assume that everyone is naturally selfish
    and competitive. But an anarchist would point out:
    in fact, what we say to our children is right.
    Pretty much every great worthwhile achievement in human history,
    every discovery or accomplishment
    that's improved our lives, has been based on
    cooperation and mutual aid;
    even now, most of us spend more of our money
    on our friends and families than on ourselves;
    while likely as not there will always be
    competitive people in the world,
    there's no reason why society has to be based on
    encouraging such behavior, let alone making people
    compete over the basic necessities of life.
    That only serves the interests of people in power,
    who want us to live in fear of one another.
    That's why anarchists call for a society based
    not only on free association but mutual aid.
    The fact is that most children grow up
    believing in anarchist morality,
    and then gradually have to realize that
    the adult world doesn't really work that way.
    That's why so many become rebellious, or alienated,
    even suicidal as adolescents,
    and finally, resigned and bitter as adults;
    their only solace, often, being the ability
    to raise children of their own and pretend to them that
    the world is fair.
    But what if we really could start to build a world
    which really was at least founded on principles of justice?
    Wouldn't that be the greatest gift
    to one's children one could possibly give?

    - Do you believe that
      human beings are fundamentally corrupt and evil,
      or that certain sorts of people
      (women, people of color,
       ordinary folk who are not rich or highly educated)
      are inferior specimens, destined to be ruled by their betters?

  - If you answered "yes", then, well,
    it looks like you aren't an anarchist after all.
    But if you answered "no",
    then chances are you already subscribe to
    90% of anarchist principles, and, likely as not,
    are living your life largely in accord with them.
    Every time you treat another human with consideration and respect,
    you are being an anarchist.
    Every time you work out your differences with others
    by coming to reasonable compromise,
    listening to what everyone has to say
    rather than letting one person decide for everyone else,
    you are being an anarchist.
    Every time you have the opportunity
    to force someone to do something,
    but decide to appeal to their sense of reason
    or justice instead, you are being an anarchist.
    The same goes for every time you share something with a friend,
    or decide who is going to do the dishes,
    or do anything at all with an eye to fairness.

  - Now, you might object that
    all this is well and good as a way for small groups of people
    to get on with each other,
    but managing a city, or a country,
    is an entirely different matter.
    And of course there is something to this.
    Even if you decentralize society
    and put as much power as possible
    in the hands of small communities,
    there will still be plenty of things that need to be coordinated,
    from running railroads
    to deciding on directions for medical research.
    But just because something is complicated
    does not mean there is no way to do it democratically.
    It would just be complicated.
    In fact, anarchists have all sorts of different ideas and visions
    about how a complex society might manage itself.
    To explain them though would go far beyond the scope
    of a little introductory text like this.
    Suffice it to say, first of all, that
    a lot of people have spent a lot of time coming up with models
    for how a really democratic, healthy society might work;
    but second, and just as importantly,
    no anarchist claims to have a perfect blueprint.
    The last thing we want is to
    impose prefab models on society anyway.
    The truth is we probably can't even imagine
    half the problems that will come up
    when we try to create a democratic society;
    still, we're confident that,
    human ingenuity being what it is,
    such problems can always be solved,
    so long as it is in the spirit of our basic principles
    -- which are, in the final analysis,
    simply the principles of fundamental human decency.
