#+title: algebraic-topology-1

* intro

  1. I will show how to design and implement a language
     to formalize and machinalize
     a little part of algebraic topology.

  2. I call this prototype 'at1',
     which is an abbreviation of 'algebraic-topology-1'.

  3. [advice for reader]
     If you know how to implement an interpreter,
     try to imagine how you would implement this language
     by directed graph processing.

* summary of principles

  1. construct by attaching boundary

  2. gluing by named common boundary

* simple-space

  1. In a language, we always have primitive elements,
     and many ways to compose elements to new compound element,
     also many ways to derive new element from old one.

  2. Here, I describe a simple way to construct spaces,
     so constructed spaces will be called simple-spaces,
     which constitute the first kind of primitive spaces in my language.

     Before having other ways to construct spaces,
     I will simply call them 'space' instead of 'simple-space'.

     - In algebraic topology,
       our simple-space is called
       CW-complex, cell-complex or cellular polytopes.

  3. A space is constructed part by part.

  4. A part is of certain dimension,
     part of 0 dimension is point,
     part of 1 dimension is an interval,
     part of 2 dimension is a disk,
     part of 3 dimension is a ball,
     part of 4 dimension is a 4-cell,
     part of n dimension is a n-cell.

  5. The way to construct a space from parts,
     goes from low dimension to high dimension,
     by attaching the boundary of a n-cell,
     to a (n-1)-sphere in the space.

     Our principle here is 'construct by attaching boundary'.

  6. As an example, let us construct a tetrahedron.

     - [advice for reader]
       Draw a picture by yourself, when trying to follow
       my formal description.

       And imagining how such picture can be dynamicly
       and automaticly drawn by a drawer that
       accompanies the main interpreter of the language.

     - In 0 dimension,

       we name all the points of the space.

       #+begin_src scheme
       (type space
         a1 a2 a3 a4 (-1 <>))
       #+end_src

     - In 1 dimension,

       we name all the intervals of the space,

       and for each interval,
       we attach its two end points to two points of the space
       [the two points of the space might be the same point],

       so that the boundary of the interval
       can be viewed as two points of the space.

       #+begin_src scheme
       (type space
         a1 a2 a3 a4 (-1 <>)
         b12 (0 a1 a2)
         b13 (0 a1 a3)
         b14 (0 a1 a4)
         b23 (0 a2 a3)
         b24 (0 a2 a4)
         b34 (0 a3 a4))
       #+end_src

       For example, the boundary of 'b12' are 'a1' and 'a2',
       the boundary of 'b13' are 'a1' and 'a3'.

       One can view 'b12' as a directed path pointing from 'a1' to 'a2',
       and 'b13' as a directed path pointing form 'a1' to 'a3'.

       We write two points in the keyword '(0 ...)',
       and the order matters.

       Since, 'b12' and 'b13' have a common boundary -- 'a1',
       we view 'b12' and 'b13' as glued together by the common boundary.

       Our principle here is 'gluing by named common boundary'.

     - In 2 dimension,

       we name all the disk of the space,

       and for each disk,
       we attach its boundary circle to a circle in the space.

       #+begin_src scheme
       (type space
         a1 a2 a3 a4 (-1 <>)
         b12 (0 a1 a2)
         b13 (0 a1 a3)
         b14 (0 a1 a4)
         b23 (0 a2 a3)
         b24 (0 a2 a4)
         b34 (0 a3 a4)
         c123 (1 b12 b23 b13 rev)
         c124 (1 b12 b24 b14 rev)
         c134 (1 b13 b34 b14 rev)
         c234 (1 b23 b34 b24 rev))
       #+end_src

       I use the keyword '(1 ...)' to specify path in the space.

       For example, '(1 b12 b23)' denotes
       the path which goes through 'b12' forwardly and 'b23' forwardly.

       In the keyword '(1 ...)',
       the right end point of one interval must matches
       the left end point of the next interval.

       And '(1 b12 b23 b13 rev)' denotes the path which
       goes through 'b12' forwardly, 'b23' forwardly, and 'b13' backwardly.

       The boundary of 'c123' is attached to the circle '(1 b12 b23 b13 rev)'.

       We check whether a path is a circle,
       by checking whether the left end point of the first interval,
       is equal to the right end point of the last interval,
       i.e. whether the path is closed.

     - In 3 dimension,

       we name all the ball of the space,

       and for each ball,
       we attach its boundary sphere to a sphere in the space.

       #+begin_src scheme
       (type space
         a1 a2 a3 a4 (-1 <>)
         b12 (0 a1 a2)
         b13 (0 a1 a3)
         b14 (0 a1 a4)
         b23 (0 a2 a3)
         b24 (0 a2 a4)
         b34 (0 a3 a4)
         c123 (1 b12 b23 b13 rev)
         c124 (1 b12 b24 b14 rev)
         c134 (1 b13 b34 b14 rev)
         c234 (1 b23 b34 b24 rev)
         d1234 (2 c123
                  c124 (1 b14 b24 rev b23 b13 rev) as-remained-boundary
                  c134 (1 b34 b24 rev b23) as-remained-boundary
                  c234 (1) as-remained-boundary))
       #+end_src

       I use the keyword '(2 ...)' to specify glued polygon in the space.

       For example :
       #+begin_src scheme
       (2 c123)
       ;; a polygon in a stack

       (2 c123
          c124)
       ;; two polygons in the stack

       (2 c123
          c124 (1 b14 b24 rev b23 b13 rev))
       ;; two polygons and a circle in the stack

       (2 c123
          c124 (1 b14 b24 rev b23 b13 rev) as-remained-boundary)
       ;; 'as-remained-boundary' is a function,
       ;;   which takes two polygons and a circle out from the stack,
       ;;   try cancel out part of the common boundary of 'c123' and 'c124',
       ;;   so that the remained boundary can be '(1 b14 b24 rev b23 b13 rev)'.
       ;; if there are no way or more then one way to do this,
       ;;   it reports to the user.
       ;; if there is only one way to do this,
       ;;   it puts a glued polygon back to the stack,
       ;;   whose boundary is '(1 b14 b24 rev b23 b13 rev)'.
       #+end_src

       The boundary of 'd1234' is attached to the sphere :
       #+begin_src scheme
       (2 c123
          c124 (1 b14 b24 rev b23 b13 rev) as-remained-boundary
          c134 (1 b34 b24 rev b23) as-remained-boundary
          c234 (1) as-remained-boundary)
       #+end_src

       We check whether a glued polygon is sphere,
       by checking whether the glued polygon is
       2-dimensional, closed, connected and orientable.

       Note that, we can implement more functions like 'as-remained-boundary',
       to help us get 2-dimensional glued polygons.

  7. Note that, syntax in (0 ...) (1 ...) (2 ...) are different,
     but syntax in (2 ...) (3 ...) (4 ...) ... are similar.

     - (0 ...) is special, in the sense that,
       only two 0-dimensional points can occur in it.

     - (1 ...) is special, in the sense that,
       there is not explict functions, like 'as-remained-boundary' in it.

     - [hesitation]
       Should these three distinctions be unified ?
       If these distinctions are really meaningful,
       and ought not to be unified,
       Should we design distinct syntaxes for them,
       to maintain the distinctions,
       instead of using the seemingly unified syntax ?

  8. Note that, 'as-remained-boundary' involves searching,
     which makes the specification of part of the space implict,
     such implicitness is need, for when the dimension gets higher,
     the detail of high dimension information might be too complex
     to use an explict method.

  9. [hesitation about cobordism]
     Note that, not all closed spaces
     can be boundary of a 1-dim higher space.
     if two disjoint closed spaces, B1 and B2, are boundary of
     1-dim higher space C, then C is the cobordism of B1 and B2,
     classically expressed as (C; B1, B2),
     where B1 and B2 are called cobordant.

     Under what conditions, a closed space can be
     the boundary of a 1-dim higher space ?
     This question should be thoroughly understood,
     before developing the formal semantics of the language.

* >< map and continuity-check

  1. We must distinguish following different types of maps
     1. level-same
     2. level-diff
        1. level-up
        2. level-down

  2. For level-same maps, the rule for continuity-check is simple.
