* the dawning of the day

  - https://en.wikipedia.org/wiki/The_Dawning_of_the_Day

  - This morning early I walked on
    While my darling was in a dream
    The last sweet days of summer bloomed
    And dressed the trees in green
    Then soaring high in the gleaming sky
    From far across the bay
    Came a fearsome roar from a distant shore
    At the dawning of the day

    Then I called my men to follow me
    Knowing well that the view was dim
    Though tired and worn, how they fought all morn'
    As time was closing in
    And my heart was sad though sore with pride
    For brave lads all were they
    As the angels fly, how they climbed so high
    On the dawning of the day

    But the edge is moving nearer now
    Inside the fading sun
    And calling, calling out to them
    My brothers, one by one
    But only dust silence sounds
    The ashes float away
    As the twilight ends and the night descends
    'til the dawning of the day

    Forgive me love, I'm going now
    So very far away
    When darkness falls, only think me near
    And do not be afraid
    And please don't grieve when I am gone
    Abide in what remains
    'til the shadows end and we meet again
    On the dawning of the day

    For when shadows end,
    We shall meet again
    On the dawning of the day

  - [on raglan road]
    https://en.wikipedia.org/wiki/On_Raglan_Road
    On Raglan Road on an autumn day I met her first and knew
    That her dark hair would weave a snare that I might one day rue;
    I saw the danger, yet I walked along the enchanted way,
    And I said, let grief be a fallen leaf at the dawning of the day.

    On Grafton Street in November we tripped lightly along the ledge
    Of the deep ravine where can be seen the worth of passion's pledge,
    The Queen of Hearts still making tarts and I not making hay -
    O I loved too much and by such and such is happiness thrown away.

    I gave her gifts of the mind I gave her the secret sign that's known
    To the artists who have known the true gods of sound and stone
    And word and tint. I did not stint for I gave her poems to say.
    With her own name there and her own dark hair like clouds over fields of May

    On a quiet street where old ghosts meet I see her walking now
    Away from me so hurriedly my reason must allow
    That I had wooed not as I should a creature made of clay -
    When the angel woos the clay he'd lose his wings at the dawn of day.

* pag ryan's polka [egan's polka]
