#+title: adventures in writing

* link

  - https://lagunita.stanford.edu/courses/VPUE/PWR/AdventuresinWriting/about

* 1. Academic Language

  - This module invites you to explore the way in which
    successful writers consciously change how they use language
    to work best in different contexts – from tone,
    to word choice, to style – focusing specifically on
    how to develop a strong, persuasive academic voice.

* 2. Purpose, Audience, and Context: Language as Communication

  - This module asks you to develop a nuanced understanding of how language works,
    suggesting that powerful communication is about more than just what you want to say;
    you also need to take into account your goals, your audience, and context.

* 3. Identifying Passive and Active Voice

  - This module focuses on one of the most common stylistic choices in writing:
    the use of passive and active voice.

* 4. Punctuation: Signposts to Guide Readers

  - This module explains that punctuation is more than just a set of rules;
    it’s a series of communication tools that you can use
    to increase the clarity and precision of your language.

* 5. Argument: Making and Supporting Claims

  - This module leads you through the steps for constructing an effective argument,
    from developing a central claim, to supporting it with evidence,
    considering diverse opinions, and even thinking about why your argument matters.
