#+html_head: <link rel="stylesheet" href="css/org-page.css"/>
#+title: CV

- NAME -- Xie Yuheng
  - FAMILY NAME -- Xie
  - GIVEN NAME -- Yuheng

- BORN -- January 15, 1992 in YinChuan, China

- CITIZENSHIP -- China

- EDUCATION
  - B.S. (Mathematics) Sun Yat-sen University, 2015

- HONORS AND SOCIETIES -- None

- EMAIL -- xyheme@gmail.com

- GITHUB -- https://github.com/xieyuheng

* PROFESSIONAL EXPERIENCE

*** 2015 -- 2017

    - Learning programming languages and language design.

*** 2017-11 -- 2018-02

    - Three months as a python programmer,
      at a company which builds online quantitative trading system.

*** 2018-03 -- 2018-05

    - One month writing elixir and learning cryptography,
      at a company which builds crypto currency exchange network.

* REMARK

  - Ideally one would put all the information
    that one considers public about oneself on a page like this.
    When asked to fill out a form,
    one would simply put down the URL
    in place of any information that is on the page
    and tell the recipient of the form to just look it up.

  - More precisely, here's a proposed new civil right.
    No Government agency, educational institution or business
    should ever be able to require anyone to supply anew information
    that the institution already has or is publicly available.
