#!/usr/bin/env bash

function up {
    hexo clean && hexo generate && \
        surge public inner-universe.surge.sh
        # now switch xieyuheng && now -n inner deploy public --prod
}

function main {
    for TASK in $@
    do
        $TASK
    done
}

main $@
