#!/usr/bin/env bash

function up {
    npx hexo clean && \
        npx hexo generate && \
        npx vercel switch xieyuheng && \
        npx vercel -n inner deploy public --prod
}

function main {
    for TASK in "$@"
    do
        "$TASK"
    done
    exit
}

main "$@"
