#!/usr/bin/env bash

function install {
    npm install
}

function build {
    echo "[build]"
}

function publish {
    echo "[publish]" &&
        npx plaintext toc src -o src/toc &&
        cat README src/toc > src/index &&
        cp AUTHORS LICENSE src &&
        npx plaintext dir src -o out &&
        true
}

function upload {
    echo "[upload]" &&
        publish && vercel out
    # surge out inner-universe.surge.sh &&
}

function t {
    echo "[test]"
}

function serve {
    publish &&
        echo "[serve]" &&
        npx http-server out &&
        true
}

function h {
    echo "commands:"
    for subcommand in $(declare -F | sed 's/declare -f//g')
    do
        echo "  $subcommand"
    done
}

if [ $# == 0 ]
then
    h
else
    for TASK in $@
    do
        $TASK
    done
fi
