#+html_head: <link rel="stylesheet" href="css/org-page.css"/>
#+title: Paper reading Microblog

* Intro

  - Notes and reviews on papers, books and learning materials.

  - "Paper reading Microblog", I learned this term
    from Mark J. Nelson and his http://www.kmjn.org/paperlog

* John McCarthy

  - From John McCarthy's works, my enlightenment begun.
    After I read his "Recursive Functions of Symbolic Expressions
    and Their Computation by Machine, Part I",
    My programming story begun.

  - His home page is still hosted by Stanford,
    with great honor, at http://www-formal.stanford.edu/jmc

*** (1980) Circumscription -- A Form of Nonmonotonic Reasoning

    - http://www-formal.stanford.edu/jmc/circumscription/circumscription.html

    #+begin_quote
    Humans and intelligent computer programs
    must often jump to the conclusion that
    the objects they can determine to have certain properties or relations
    are the only objects that do.
    Circumscription formalizes such conjectural reasoning.
    #+end_quote

    - [todo]

*** (1986) Applications of Circumscription to Formalizing Common Sense Knowledge

    - http://www-formal.stanford.edu/jmc/applications/applications.html

    #+begin_quote
    We present a new and more symmetric version
    of the circumscription method of nonmonotonic reasoning
    first described in (McCarthy 1980)
    and some applications to formalizing common sense knowledge.
    The applications in this paper are mostly based on
    minimizing the abnormality of different aspects of various entities.
    Included are nonmonotonic treatments of is-a hierarchies,
    the unique names hypothesis, and the frame problem.
    The new circumscription may be called formula circumscription
    to distinguish it from the previously defined domain circumscription and predicate circumscription.
    A still more general formalism called prioritized circumscription is briefly explored.
    #+end_quote

*** (1988) Mathematical logic in artificial intelligence

*** (1989) Artificial Intelligence, Logic and Formalizing Common Sense

    - http://www-formal.stanford.edu/jmc/ailogic/ailogic.html

    #+begin_quote
    This is a position paper about the relations among
    artificial intelligence (AI), mathematical logic
    and the formalization of common-sense knowledge and reasoning.
    It also treats other problems of concern to both AI and philosophy.
    I thank the editor for inviting it.
    The position advocated is that philosophy can contribute to AI
    if it treats some of its traditional subject matter in more detail
    and that this will advance the philosophical goals also.
    Actual formalisms (mostly first order languages)
    for expressing common-sense facts are described in the references.
    #+end_quote

*** (2003) Elaboration Tolerance

    - http://www-formal.stanford.edu/jmc/elaboration

    #+begin_quote
    A formalism is elaboration tolerant to the extent that
    it is convenient to modify a set of facts expressed in the formalism
    to take into account new phenomena or changed circumstances.
    Representations of information in natural language have good elaboration tolerance
    when used with human background knowledge.
    Human-level AI will require representations with much more elaboration tolerance
    than those used by present AI programs, because human-level AI
    needs to be able to take new phenomena into account.

    The simplest kind of elaboration is the addition of new formulas.
    We'll call these additive elaborations.
    Next comes changing the values of parameters.
    Adding new arguments to functions and predicates represents more of a change.
    However, elaborations not expressible as additions to the object language representation
    may be treatable as additions at a meta-level expression of the facts.

    Elaboration tolerance requires nonmonotonic reasoning.
    The elaborations that are tolerated depend on
    what aspects of the phenomenon are treated nonmonotonically.
    Representing contexts as objects in a logical formalism
    that can express relations among contexts should also help.

    We use the missionaries and cannibals problem
    and about 20 variants as our Drosophila
    in studying elaboration tolerance in logical AI.

    The present version has only some parts of a situation calculus formalization.
    However, the English language elaborations listed
    are enough to serve as a challenge to logical AI formalisms claiming elaboration tolerance.
    #+end_quote

* Errett Bishop

*** (1967) A Constructivist Manifesto

*** (1973) Schizophrenia in Contemporary Mathematics

* Max Dehn

* Joseph Goguen

  - https://en.wikipedia.org/wiki/Joseph_Goguen

*** ‎(1989) What is Unification ?

    - A Categorical View of Substitution, Equation and Solution

*** (1991) A Categorical Manifesto

* MIT AI Lab

*** (1988) How to do Research At the MIT AI Lab

    - by a whole bunch of current, former, and honorary MIT AI Lab graduate students

    #+begin_quote
    This document presumptuously purports to explain how to do research.
    We give heuristics that may be useful in picking up the
    specific skills needed for research (reading, writing, programming)
    and for understanding and enjoying the process itself
    (methodology, topic and advisor selection, and emotional factors).
    #+end_quote
