#+html_head: <link rel="stylesheet" href="css/org-page.css"/>
#+title: Quote

* Mathematics

  - The code pretty much writes itself.
    -- Bartosz Milewski
    -- In "category theory for programmers".

  - Mathematics is a beautiful dream world where progress can begin.
    -- Eugenia Cheng
    -- In her 2015 TEDx talk.

* Game

  - There is always a chance to start asking "Why?" again.
    -- James Portnow
    In "The Martian Chronicles - The New Martians - Extra Sci Fi - #13"

  - You will level up as a player, even if you do not feel any progress in the game.
    -- James Portnow
    -- In "Dark Souls - #7 - Dan Masters the Crossbow - Side Quest"

* Life

  - (The miniature plan)
    If he maps out important work for himself on great lines,
    a glance at this miniature plan
    of his life will, more than anything else
    stimulate, rouse and ennoble him,
    urge him on to action and keep him from false paths.
    -- Arthur Schopenhauer

  - (A day)
    We are apt to forget that every day is an integral,
    and therefore irreplaceable portion of life,
    and to look upon life as though it were a collective idea or name
    which does not suffer if one of the individuals it covers is destroyed.
    -- Arthur Schopenhauer
