* the dawning of the day

  - https://en.wikipedia.org/wiki/The_Dawning_of_the_Day

  - This morning early I walked on
    While my darling was in a dream
    The last sweet days of summer bloomed
    And dressed the trees in green
    Then soaring high in the gleaming sky
    From far across the bay
    Came a fearsome roar from a distant shore
    At the dawning of the day

    Then I called my men to follow me
    Knowing well that the view was dim
    Though tired and worn, how they fought all morn'
    As time was closing in
    And my heart was sad though sore with pride
    For brave lads all were they
    As the angels fly, how they climbed so high
    On the dawning of the day

    But the edge is moving nearer now
    Inside the fading sun
    And calling, calling out to them
    My brothers, one by one
    But only dust silence sounds
    The ashes float away
    As the twilight ends and the night descends
    'til the dawning of the day

    Forgive me love, I'm going now
    So very far away
    When darkness falls, only think me near
    And do not be afraid
    And please don't grieve when I am gone
    Abide in what remains
    'til the shadows end and we meet again
    On the dawning of the day

    For when shadows end,
    We shall meet again
    On the dawning of the day

  - [on raglan road]
    https://en.wikipedia.org/wiki/On_Raglan_Road
    On Raglan Road on an autumn day I met her first and knew
    That her dark hair would weave a snare that I might one day rue;
    I saw the danger, yet I walked along the enchanted way,
    And I said, let grief be a fallen leaf at the dawning of the day.

    On Grafton Street in November we tripped lightly along the ledge
    Of the deep ravine where can be seen the worth of passion's pledge,
    The Queen of Hearts still making tarts and I not making hay -
    O I loved too much and by such and such is happiness thrown away.

    I gave her gifts of the mind I gave her the secret sign that's known
    To the artists who have known the true gods of sound and stone
    And word and tint. I did not stint for I gave her poems to say.
    With her own name there and her own dark hair like clouds over fields of May

    On a quiet street where old ghosts meet I see her walking now
    Away from me so hurriedly my reason must allow
    That I had wooed not as I should a creature made of clay -
    When the angel woos the clay he'd lose his wings at the dawn of day.

* pag ryan's polka [egan's polka]
* star-of-the-county-down
  
  Near Banbridge town, in the County Down
  One morning last July
  Down a bóithrín green came a sweet cailín
  And she smiled as she passed me by.

  From Bantry Bay up to Derry Quay
  And from Galway to Dublin town
  No maid I've seen like the brown cailín
  That I met in the County Down.

  She looked so sweet from her two bare feet
  To the sheen of her nut brown hair
  Such a coaxing elf, sure I shook myself
  To be sure I was really there.

  From Bantry Bay up to Derry Quay
  And from Galway to Dublin town
  No maid I've seen like the brown cailín
  That I met in the County Down.

  As she onward sped I scratched my head
  And I looked with a feeling rare
  And I said, says I, to a passerby
  "Who's the maid with the nut-brown hair?"
  He smiled at me, and, he says, says he,
  "That's the gem of Ireland's crown.
  Young Rosie McCann from the banks of the Bann
  She's the star of the County Down."

  At the Harvest Fair she'll be surely there
  And I'll dress in my Sunday clothes,
  With my shoes shone bright and my hat cocked right 
  For a smile from my nut brown rose.
  No pipe I'll smoke, no horse I'll yoke
  Till my plough turns rust coloured brown.
  Till a smiling bride by my own fireside
  Sits the star of the County Down.

  From Bantry Bay up to Derry Quay
  And from Galway to Dublin town
  No maid I've seen like the brown cailín
  That I met in the County Down.
  From Bantry Bay up to Derry Quay
  And from Galway to Dublin town
  No maid I've seen like the brown cailín
  That I met in the County Down.
  
