#+TITLE:  bishop

* foundations-of-constructivean-analysis

* constructive-analysis

*** note
    - foundations-of-constructivean-alysis 的修訂版
      由 bishop 和 bridges 共同完成

*** a constructivist manifesto

***** the descriptive basis of mathematics
      - 這裏作者設問說
        人對 數學結構 的創造
        比大自然對 物理世界 還有 生命體存在形式 的創造
        具有更少的任意性
        但是
        這是詭辯
        只爲廣告其理論而已
        因爲
        即便是 kronecker 的自然數
        其超越 物理世界的 普世性 也是虛的
        並且
        作者本身對分析學的構造主義處理就是對設問的否定
      - 集合是
        1. 對元素的構造
        2. 外加對等詞的定義
        以等詞爲集合的一部分
        數據結構變豐富 而簡化了對結構化集合的討論
        [映射必須保持等詞]
      - 在作者的構造主義中
        邏輯似乎都不需要了
        也許
        邏輯推演規則 其實是說 如何用已有的函數構造新的函數
      - bourbaki 意義上的
        用公理定義的 抽象數學結構
        與
        通過構造來定義的 具體數學結構
        依照作者的觀點來看
        前者是假設有其構造的集合
        而後者是有具體構造的集合
      - 使用抽象數學結構的動機
        在 bourbaki 的工作中已經有很好的表達了
        即 證明一次就證明了多次
        並且 各種抽象結構對具體結構所形成的分類
        是我們組織自己數學知識的很好方式
      - 在作者看來[在構造主義意義上]
        數學之方法論之新穎之處[之超越性]
        就在於想要去討論所有的可計算之物
        而不顧具體的計算方式之效率
        而應用數學則以高效的計算爲其研究目標
        也許當某種 現實主義數學 大行其道之時
        效率問題就將像當前構造的構造問題一般爲人們爭議

***** the idealistic component of mathematics
      - 作者說 不經意地人們認同數學背後的理想主義哲學
        這一點纔是值得批判的
        而構造主義反而是沒有形而上學色彩的
        [數學中哲學觀點的衝突 在作者的表述下被凸顯出來了]

***** the constructivization of mathematics
      - 這一節提到了
        對 命題演算中的連詞
        和 謂詞演算中的量詞 的構造主義解釋
        但是其實
        以 (-> A) 來 證明 (-> (A | B)) 這種對命題的弱化是從來都不應該進行的
        這裏的推演規則本身被 pattern match 的規則來捕捉就行了
        但是 drop 這種證明 運算是常用的
      - 那麼什麼樣的命題纔是需要證明的呢
        當對命題的描述都被形式化了之後
        爲什麼不能直接得到命題的判定算法呢
      - 作者在這裏所表達的一個觀點非常有趣
        即 下面的行爲是類似的
        | 先得到不嚴格論證                   | 再找嚴格論證       |
        | 先去得到一個古典證明               | 再找構造性證明     |
        | 先找到一個通過窮舉來完成計算的算法 | 再找效率更高的算法 |
      - 構造主義使用形式體系時
        不需要證明其一致性證明
        hilbert 之所以需要證明形式體系的一致性
        是因爲 他要用具有構造性的 元數學
        來打造公理化的古典數學
        此時 對於所設計的 古典數學的形式體系
        需要證明其 一致性

*** calculus and the real numbers

***** sets and functions

***** the real number system

***** sequences and series of real numbers

***** differentiation

***** integration

***** certain important functions

*** set theory

*** metric spaces

*** complex analysis

*** integration

*** normed linear spaces

*** locally compact abelian groups

*** commutative banach algebras

* selected-papers-errett-bishop

* errett-bishop--reflections-on-him-and-his-research

*** publications of errett bishop

*** schizophrenia in contemporary mathematics
    - the debasement of meaning
      應該是意義在先
      而 技術處理 與 形式描述 在後
      所以 蟬語的具體實現 與 類型系統理論方面的研究 不應該如此分離
    - 強調 抽象數學結構 的表示
      即 具體數學結構
      但是卻完全否定了 抽象數學結構 本身
      整數被定義爲了它的一種特殊表示
      即 進位製[十進制]的數字
    - 我的處理方式是對於某個具體的數學結構
      去形成一般的方法
      以發現可以被公理化而成 抽象數學結構 的性質
      [主要是 運算律]
      但是
      我憑什麼說
      以我的擴展方法
      從後繼關係開始發展出來的具體結構
      比 直接用十進制表示定義的整數 優越呢
    - 兩個具體結構之間的關係可以利用一個明顯的雙射建立
      但是
      實際上我的處理方式並沒有優越性
      同一個抽象數學結構的不同具體結構
      就像是同樣的信息的不同編碼方式一樣
      適用於不同的目的
    - 但是只有有了對抽象的結構的認識
      我才能說 兩者是等價的 這就是範疇論
    - 我的處理方式其實是爲了理解算數的級而設計的
      ><><>< 但是
      這種處理方式目前只對自然數有用
      也許 推演規則 是下一個可以嘗試這種方法的對象
    - 按照我的想法
      所有的可以發現運算律的 具體數學結構
      都可以按照我的方式處理
      但是這是就之前對 代數結構 的觀察而言的
      現在 我又知道了 推演結構[證明論][偏序結構]
    - 又回到了 bourbaki 的三大關係
      但是
      此時三種關係並不是做爲相對獨立的
      可以用以組成其他複合抽象結構的組成部分
      而是由 變化 這個概念 聯繫起來
      變化產生序
      變化之間的等價產生代數
      變化所形成的軌跡產生幾何
    - 否定被定義爲了
      與[具體數學結構中的]基本等詞的衝突
    - 定義函數的時候
      人們常說
      [一個具體數學結構中]相同的元素
      要被映射爲[另一個具體數學結構中]相同的元素
      這是函數必須滿足的條件
      很難想像這個條件如何能夠不被滿足
      同一個東西在同樣的變化下所得到的東西也一定是同樣的
      但是其實 這裏所說的 相同
      考慮的是 具體數學結構 中的等詞
      比如相同的整數 在某個模型中可能有不同的表示
      而函數的定義 一般都是就這些具體的表示方式而言的
      所以需要檢驗所定義的函數是否滿足這個基本性質

* techniques-of-constructive-analysis [Douglas S. Bridges and Luminiţa Simona Vîţă]

* note Bishop's four principles of constructivism

  (A) Mathematics is common sense.

  (B) Do not ask whether a statement is true until you know what it means.

  - after knowing the meaning of the statement,
    one still needs an argument to be convinced.

  (C) A proof is any completely convincing argument.

  - a proof is to prove a statement is true,
    thus there is no objective truth.

  - 這裏強調了數學證明的主觀性
    但是 用程序語言來實現數學推演
    就是說推演規則與數學定理的真理性是絕對客觀的
    如何調和這裏的主觀與客觀
    - 我承認主觀性
      可能是因爲
      不認同目前的客觀化策略
      想要給出新的客觀化策略
      就要強調主觀性 以說明新的策略的可能
    - 但是上面的 '說服'
      顯然可以用更好的方式完成
      只要說明有多樣的策略就行了
    如若如此
    我其實想要強調的是客觀性
    畢竟我是在用機器來形式化數學

  - (B) seems saying the meaning of a statement can be more objective.

  - machinallized proof system seems giving truth objectivity, but it is not.
    actually, the truth of a statement proved by a proof system,
    is based on the fact that, he, who uses the proof system,
    is convinced by the design and implementation
    of the proof system [in some programming language].

  (D) Meaningful distinctions deserve to be maintained.

  - to maintain meaningful distinctions between ><><><, we use type
    to maintain meaningful distinctions between ><><><, we use different syntax
