#+title: brentano (1838 –- 1917)

* on what is continuous (1914)

  - The formation of concepts requires
    1. things should affect the senses,
       since "no one can learn or understand anything
       in the absence of sense."
    2. images are formed,
       since "the soul never thinks without an image."
    3. whatever acts upon the mind,
       the active principle that conveys forms to the mind,
       cannot be of a lower order than the recipient,
       since "always, the active is superior to the passive factor,
       the originating force to the matter which it forms."
    "to think is to be affected."
    until a form enters,
    the receptive mind is mere potentiality.

  - We never think a general thought
    that is not accompanied by a sensory image.
    Just as the mathematician who wants to prove a general proposition
    draws in the sand a particular triangle
    and discovers the general truth by observing this triangle,
    so also if someone intellectually contemplates some other thing,
    he always has an appropriate representation in his sensitive faculty.

  - The question concerning the concept of continuity
    cannot be framed in such a way that
    one would call into doubt whether we do in fact possess such a concept.
    For otherwise we would not be able to understand ourselves
    when arguing about other aspects of this concept.

  - All our concepts are either taken immediately from an intuition
    or combined out of marks that are taken from intuition.

  - The concept of what is continuous, firstly, must be viewed as primitive instead of compound.
    (1) 'primitive' as been taken immediately from an intuition.
    (2) 'compound' as been combination of individual marks distilled from intuition.

  - 當試圖描述連續體爲複合概念時
    我們形成的理論如此玄虛
    以至於 我們在觀察中所直覺到的連續體的簡單性質
    比如 邊界 等等
    必須要以迂迴複雜的方式才能被表述出來

  - 想要分解連續體 把這個概念劃歸到更簡單的概念
    我可以理解這種意圖
    但是我認爲這個計劃失敗了

  - 我重申
    The concept of the continuous is acquired
    not through combinations of marks taken from different intuitions
    and experiences, but through abstraction from unitary intuitions.

  - 我要提出理解連續體的直覺方式
    尤其我要能很好地描述 連續體之邊界 和 邊界之重合

  - 我斷言 有關我們的 外部感知 內部感知 和 記憶
    的任何一個直覺 都揭示着連續體這個抽象概念

  - Thus in seeing we have as object something
    that is extended in length and breadth which
    at the same time shows itself clearly
    as allowing us to distinguish a front and rear side
    and thus as characterised as the two-dimensional boundary
    of something extended in three dimensions.

  - 當觀看一個呈現於我們面前的連續體的時候
    我們同時也能夠想象自己的觀看行爲本身
    當繞着被觀看物運動時 它呈現於我們的表面也連續變化着
    當我們靜止時 我們還能想象被觀察的連續體自身隨時間而形變
    如此說來
    運動於靜止 恆定與漸變 都是我們想象的基本性質[或基本元素]
    [sense of sensation]
    - 正如 thurston 所說
      爲了想象三維流形
      我們可以想象我們在幾何性質迥異的空間中運動
    - 也就是說
      在觀察中考慮觀察者
      並且觀察觀察行爲本身 是重要的
      否則觀察就是不完整的
      或者說 觀察觀察行爲本身
      可以使得形成概念時有更豐富的材料

  - 這樣就算解決了連續體這個概念的起源問題了嗎 ?

  - 我們可以在需要的時候細分一個連續體
    細分是潛在無窮的 但是總是有限的
    我們不應想象在無窮的細分一條線之後 能獲得點
    我們不應該聲稱這些點構成了這條線

  - [染色的棋盤]
    一個無法感知但是可以想象的例子
    爲討論連續體的邊界做準備
    因爲我們是沒法感知構成一個連續的邊界的所有點的
    但是我們能夠想象其邊界
    正如
    我們沒法感知到[觀看到 觸碰到 等等]沒有寬度的線
    但是我們能想象沒有寬度的線
    - 也就是說
      在考慮觀察行爲本身的時候
      要明白觀察本身的侷限性
      還要知道對於觀察到的材料
      我們可以形成抽象的想象

  - 相比於用合成的方式來構造連續體之概念
    我們用直覺來抽象出連續體之概念
    其好處是
    我們可以附加別的直覺概念到它上面 使這個概念更豐富
    我們還可以通過區分別的直覺概念 來分類連續體
    1. 一維連續體 定義爲只有不連續的邊界的連續體
       比如時間作爲一個一維連續體 其邊界是此刻
       而此刻本身沒有時間延展[temporal extension]
       我們把它們稱爲瞬間
    2. 最多以一維連續體爲邊界的連續體 就稱爲二維連續體
       依此類推
    3. 有些二維曲面沒有邊界
       但是一個一維曲線可以將其分離爲兩部分
       因此 在這種特殊情況下
       我們也有有效的判別維數的方式

  - x -
    Boundaries can be distinguished as inner and outer.
    #+begin_src scheme
    (def cylinder
      (type space
        (: [a0, a1] (-1 <>))
        (: b0 (0 a0 a0))
        (: b1 (0 a1 a1))
        (: h  (0 a0 a1))
        (: c0 (1 h b1 h rev b0 rev))))
    #+end_src
    這裏 h 就是 inner-boundary
    而 b0 與 b1 是 outer-boundary
    只因爲在 c0 的邊界 (1 h b1 h rev b0 rev) 中 h 重複出現了
    - 如果重複出現是判斷 inner-boundary 的標準的話
      那麼 一個 disk 的邊界繞着 circle 盤繞兩圈所形成的連續體
      將只有 inner-boundary 而沒有 outer-boundary
      因爲每個邊界都重複出現了一次

  - x -
    brentano 用 plerosis 這個詞來描述邊界的重複出現次數
    重複出現的地方不一定是同一個 cell
    一部分邊界也可能重複出現在很多不同的 cell 的邊界中

  - plerosis
    - noun
      Originally Theology. The action or process of being made full or complete, fulfilment.
    - Origin
      Early 19th century (in an earlier sense).
      From ancient Greek πλήρωσις filling up, filling, becoming full,
      repletion from πληροῦν to fill + -σις.

  - x -
    我想 brentano 這個詞的用意是
    要描述 連續體的邊界的各個部分
    都沾染了這個連續體的性質[比如 顏色]
    因此 一段邊界 重複出現在多個連續體的邊界中
    就沾染上了豐富的性質

  - x -
    Boundaries require belongingness.
    就是說 一個連續體的邊界被看作是連續體的部分
    即 '屬於' 連續體
    但是有趣的是
    在關於連續體的形式語言的類型論中
    邊界是連續體的類型
    連續體 反過來 '屬於' 其邊界

  - x -
    我想
    如果回到之前對感知與想象的討論
    只有連續體最高維數的部分纔是可感知的
    而其邊界只能是想象出來的

  - x -
    之後的一節
    討論時間這個概念的難點
    homotopy 的概念以時間爲直覺基礎
    但是在形式化的處理中
    時間這個維度的特殊性被消除了
    證明同倫等價的時候
    只要解決有關 I 的 extension-problem
    #+begin_src scheme
    (let ([f0 (lambda (-> A B) ...)]
          [f1 (lambda (-> A B) ...)])
      (lambda (-> (* A I) B)
        (extend-from
          (lambda (-> (* A (0 I)) B)
            (-> (* :a i0) [:a f0])
            (-> (* :a i1) [:a f1])))
        ...))
    #+end_src

  - x -
    有趣的是如此的形式語言
    使得我們獲得了兩種想象同倫的方式
    一種是想象出在時間中的運動與形變
    一種是想象高維連續體被揉入低維連續體

  - x -
    有一個論點用以區分
    時間連續[spatially continuous] 和 空間連續[temporally continuous]
    即 "spatially continuous, if it exists, exists as a whole."
    這其實是錯誤的
    我們能完全直觀一個連續體爲一個整體與否
    不在於時空之分 而在於維數
    當維數高於三時 完全的直觀就失效了
    時間之所以被當作不能被完全直觀的連續體
    是因爲時間總是被加入到已有的三維空間中來考慮
    此時被觀察的連續體就有四維了
    我們通常把這個四維空間投影到現在這個時間點
    然後方能觀察它
    我說
    當維數低於三時 完全的直觀是可能的
    當維數高於三時 完全的直觀就失效
    例如
    三維球面的嵌入四維歐氏空間 時是無法被直觀的
    而利用球極映射把它投影到 三維歐氏空間 就能夠直觀

  - x -
    之後考慮給空間連續體着色
    着色的方式可以多種多樣
    可能是一致的 可能是漸變的
    這樣在空間連續體上
    我們就附加了新的連續信息
    整個連續體就多了些維度
    正是通過將 時間 和 空間 這兩個連續體 複合在一起
    我們得以描述運動

  - x -
    運動必須用函數來描述
    當把一個線段嵌入個空間三維連續體時
    我們可以把這個嵌入理解爲運動的軌跡
    並且可以計算速度
    爲了計算速度
    線段作爲一維連續體必須被幾何化
    它必須有方向和度量[單位]
    注意 在這裏我們不能計算在某一點運動的速度
    而只能計算在一段線段上運動的速度
    我們可以嘗試以這種方式來建立運動與力之間的關係
    還是考慮上面這個對線段的嵌入
    母空間是三維連續體
    子空間是一維線段
    母空間中的力會限制子空間嵌入其中的方式
    這樣我們就能得到動力學

  - x -
    母空間中的力就是向量場

* the theory of categories (1907 -- 1917)

* psychology from an empirical standpoint (1874)
