#+title: charles sanders peirce

* (1868) Some Consequences of Four Incapacities

* (1868) Questions Concerning Certain Faculties Claimed for Man

* (1868) On a New List of Categories

* (1869) Grounds of Validity of the Laws of Logic

  - Further Consequences of Four Incapacities

* [todo] (1870) Description of a Notation for the Logic of Relatives

  - Resulting from an Amplification
    of the Conceptions of Boole's Calculus of Logic

*** General Definitions of the Algebraic Signs

    - *Inclusion in* or *being as small as* is a *transitive* relation.
      The consequence holds that

      If    x -< y
      and   y -< z
      then  x -< z

    - *Equality* is the conjunction of being as small as and its converse.
      To say x = y is to say that x -< y and y -< x.

    - *Being less than* is being as small as with the exclusion of its converse.
      To say that x < y is to say that x -< y, and that it is not true that y -< x.

    - *Being greater than* is the converse of being less than.
      To say that x > y is say that y < x.

    - *Addition* is an associative operation.
      That is to say,

      (x +, y) +, z == x +, (y +, z)

      - I write a comma below the sign of addition,
        except when (as is the case in ordinary algebra)
        inverse operation (subtraction) is determinative.

    - Addition is a commutative operation.
      That is,

      x +, y == y +, x

    - *Invertible addition* is addition the corresponding inverse of which is determinative,
      The last two formulae hold good for it, and also the consequence that

      If    x + y == z
      and   x + y' == z
      then  y == y'

    - *Multiplication* is an operation which is *doubly distributive with reference to addition*.
      That is,

      x * (y +, z) == x * y +, x * z
      (x +, y) * z == x * z +, x * z

    - Multiplication is almost invariably an associative operation.

      (x * y) * z = x * (y * z)

      - x -
        I use `x * y` instead of `x y`

    - Multiplication is not generally commutative.
      If we write commutative multiplication with a comma, we have

      x *, y == y *, x

    - *Invertible multiplication* is multiplication whose corresponding inverse operation
      (division) is determinative.
      We may indicate this by a dot;
      and then the consequence holds that

      If    x . y == z
      and   x . y' == z
      then  y == y'

    - *Functional multiplication* is the application of an operation to a function.

      sin (a * b * c) * d * e * f
      log (a * b * c, d * e * f) * g * h * i

      - x -
        I use `f (x, y)` for function application

    - The operation of *Involution* obeys the formula

      (x ^ y) ^ z == x ^ (y * z)

      - x -
        I use `x [y]` instead of `x ^ y`

    - Involution, also, follows the *indexical principle*.

      x ^ (y +, z) == (x ^ y) *, (x ^ z)

    - Involution, also, satisfies the *binomial theorem*.

      (x +, y) ^ z ==
      (x ^ z) +,
      sigma (p) ((p -< z), (x ^ (z - p)) *, (y ^ p)) +,
      (y ^ z)

      - x -
        `sigma (<var>) (<pred>, <exp>)` introduces a bound variable

    - *Subtraction* is the operation inverse to addition.
      We may write indeterminative subtraction
      with a comma below the usual sign.
      Then we shall have that

      (x -, y) +, y == x
      (x - y) + y == x
      (x + y) - y == x

    - [todo]

    - x -
      The categorical understanding of the art of abstraction
      is not achieved at the author's time.

      This kinds of pre category theory striving for abstraction
      can be used as a motivation to introduce category theory.

*** Use of the Letters

    - x -
      can all relations be reduced to
      composition of relations with arity less or equal than 3 ?

*** Numbers corresponding to Letters

*** The Signs of Inclusion, Equality, etc.

*** [todo]

* (1877) the fixation of belief

* (1878) how to make our ideas clear

* [todo] (1880) On the algebra of logic

* (2000) (geraldine brady) from peirce to skolem

*** 1 The Early Work of Charles S. Peirce

*** 2 Peirce's Calculus of Relatives: 1870

    - (1870) Description of a Notation for the Logic of Relatives

    - Peirce's belief that
      this was the most important advance since Boole
      was certainly based on the fact that
      the algebra ofrelations is far more expressive
      than the algebra of propositions,
      and reflects a great deal more of everyday logical inference
      than does Boole'stheory of sets,
      since relations, not just sets,
      are the bread and butter ofreasoning.

    - In this early work on the calculus of relatives,
      Peirce shows more concern with
      maintaining the analogies between
      the notation he is setting forth
      and ordinary algebraic notation
      than with giving a direct account of the problem at hand.

*** 3 Peirce on the Algebra of Logic: 1880

    - (1880) On the algebra of logic

*** 4 Mitchell on a New Algebra of Logic: 1883

*** 5 Peirce on the Algebra or Relatives: 1883

*** 6 Peirce's Logic of Quantifiers: 1885

*** 7 Schroder's Calculus of Relatives

*** 8 Lowenheim's Contribution

*** 9 Skolem's Recasting
