#+title: charles sanders peirce

* links

  - https://en.wikipedia.org/wiki/Charles_Sanders_Peirce
  - https://en.wikipedia.org/wiki/Charles_Sanders_Peirce_bibliography

  - https://plato.stanford.edu/entries/peirce/
  - https://plato.stanford.edu/entries/peirce-logic/

  - http://www.iupui.edu/~arisbe/
    A philosophical website,
    providing access to resources for
    the life, work, and continuing interest in
    the American philosopher, scientist, and humanist
    Charles Sanders Peirce

  - http://www.peirce.org/

  - http://www.pragmaticism.net/

  - http://peirce.iupui.edu/index.html

  - https://academic.oup.com/monist

* [note] deduction induction abduction

  - https://plato.stanford.edu/entries/peirce/#dia

  - Peirce's trichotomy of inferences [arguments]
    can be obtained by asking what would happen
    if one were to interchange propositions in the syllogism AAA-1

    and providing syllogism as drawing conclusions on the basis of taking samples
    - i.e. statistical interpretation

  - deduction -- syllogism AAA-1 (Barbara)

    - necessary inference
      if major premise and minor premise are both "true"
      the result conclusion is also "true"

      where "true" can be defined as constructable

    | M | membership of some population |
    | P | property of members           |
    | S | sample taken from population  |

    | M -> P | rule   | X% population have property         |
    | S -> M | case   | sample is taken from the population |
    |--------+--------+-------------------------------------|
    | S -> P | result | X% sample have property             |

    - while the syllogism can be viewed as function composition
      it also can be viewed as subtype relation

    | M <: P |
    | S <: M |
    |--------|
    | S <: P |

  - induction -- syllogism AAA-3

    - exchange result with rule

    | S -> P | result | X% sample have property             |
    | S -> M | case   | sample is taken from the population |
    |--------+--------+-------------------------------------|
    | M -> P | rule   | X% population have property         |

    - the core meaning of induction is to argue from sample to population

      the proportion of a trait found in the sample
      is attributed also to the population

    - x -
      like constant conjunction of hume

  - abduction -- syllogism AAA-2

    - a.k.a. hypotheses, retroduction and "educated guess"

    - exchange result with case

    | M -> P | rule   | X% population have property         |
    | S -> P | result | X% sample have property             |
    |--------+--------+-------------------------------------|
    | S -> M | case   | sample is taken from the population |

    - arguing a plausible explanation

    - x -
      we see similarity between A and B,
      then we conjecture relations behind the similarity.

  - practice the trichotomy by classifying argument that occurs in everyday life

    - analogy should be construed as inductions
      -- arguments from a sample of the properties of things
      to a population of the properties of things

      or abductions -- conjectures made on the basis of sufficient similarity
      which notion might not easily be analyzed in terms of sets of properties

      - mathematical structure is one example of "sufficient similarity"

  - x -
    we can also write down the function application version of the trichotomy

    - deduction

    | A -> B |
    | A      |
    |--------|
    | B      |

    - induction

    | B      |
    | A      |
    |--------|
    | A -> B |

    - induction in application form mirrors
      abduction in composition form

    | M -> P |
    | S -> P |
    |--------|
    | S -> M |

    - abduction

    | A -> B |
    | B      |
    |--------|
    | A      |

  - x -
    the function composition view of syllogism
    also give us a non-commutative algebra

    - https://en.wikipedia.org/wiki/Noncommutative_ring

    | argument type | equation to solve |
    |---------------+-------------------|
    | deduction     | a b == x          |
    | induction     | x b == c          |
    | abduction     | a x == c          |

  - Peirce extend the trichotomy of arguments
    to three phases of the methodology of science
    -- a systematic procedure for seeking truth
    that he called the "scientific method"

    Scientific method begins with abduction or hypothesis:
    because of some perhaps surprising or puzzling phenomenon,
    a conjecture or hypothesis is made about what actually is going on.

    This hypothesis should be such as to explain the surprising phenomenon,
    such as to render the phenomenon more or less a matter of course
    if the hypothesis should be true.

    Scientific method then proceeds to the stage of deduction:
    by means of necessary inferences, conclusions are drawn
    from the provisionally adopted hypothesis
    about the obtaining of phenomena other than the surprising one
    that originally gave rise to the hypothesis.

    Conclusions are reached, that is to say,
    - beliefs are fixed
    about other phenomena that must obtain if the hypothesis should actually be true.
    These other phenomena must be such that experimental tests
    can be performed whose results tell us
    whether the further phenomena do obtain or do not obtain.

    the "feedback loop" of scientific method goes on and on

    If the deduced consequences do obtain,
    then we loop back to the deduction stage,
    deducing still further consequences of our hypothesis
    and experimentally testing for them again.

    But, if the deduced consequences do not obtain,
    then we loop back to the abduction stage
    and come up with some new hypothesis
    that explains both our original surprising phenomenon
    and any new phenomena we have uncovered
    in the course of testing our first, and now failed, hypothesis.

  - hypothesis-testing, but not merely that part of it
    that consists of arguing from sample to population

  - "the economy of research"
    The idea is that, because research is difficult,
    research labor-time is valuable and should not be wasted.
    Both in the creation of hypotheses to be tested
    and in the experiments chosen to test these hypotheses.

    The object is to proceed at every stage
    so as to maximize the reduction in indeterminacy of our beliefs.

    - mathematical theory of the economy of research can be developed

  - x -
    it is as if intelligence are this kind of creature
    who are always seeking for beliefs
    if its beliefs are broken, it trys its best to form new beliefs.

* [note] pragmaticism and scientific method

  - For Peirce, the entire universe and everything in it
    is an evolutionary product. Indeed, he conceived that
    even the most firmly entrenched of nature's habits
    - for example, even those habits
      that are typically called "natural laws"
    have themselves evolved, and accordingly can and should be
    subjects of philosophical and scientific inquiry.

    One can sensibly seek evolutionary explanations
    of the existence of particular natural laws.

  - both Hegel and Peirce make the whole evolutionary interpretation
    of the evolving phaneron to be a process that is said to be logical,
    the "action" of logic itself.

  - Hegel's logic is vague

    but Peirce's logic is clear and is the whole logical apparatus
    of the physical and social sciences.

  - scientific method is
    - essentially public
    - reproducible in its activities
    - self-correcting in the following sense:
      No matter where different researchers may begin,
      as long as they follow the scientific method,
      their results will eventually converge toward the same outcome.

      - the equivalence between theories
        are defined by pragmatic principle

      - x -
        how about diverging theories in mathematics ?

  - optimistic
    Peirce tends to hold that every genuine question
    - that is, every question whose possible answers
      have empirical content (or pragmatic content)
    can be answered in principle, or at least
    should not be assumed to be unanswerable.

    For this reason, one his most important dicta,
    which he called his first principle of reason,
    is "Do not block the way of inquiry!"

  - the scientific method involves three phases or stages:
    - abduction -- making conjectures or creating hypotheses
    - deduction -- inferring what should be the case
      if the hypotheses are the case
    - induction -- the testing of hypotheses

    The process of going through the stages
    should also be carried out with concern for the economy of research.

  - economy of research
    science is essentially a human and social enterprise
    and that it always operates in some given historical,
    social, and economic context.

* [note] continuum

  - if a line is cut into two portions,
    the point at which the cut takes place actually becomes two points.

  - x -
    to develop a good theory of continuum
    we need a theory of boundary

* [note] probability

  - statistical information is often the best information
    that we can have about phenomena

  - there are three distinct and
    mutually incommensurable measures of uncertainty
    (of imperfection of certitude)

    only one was probability

    | probability                 | deduction |
    | verisimilitude (likelihood) | induction |
    | plausibility                | abduction |

    - for plausibility :
      seeking hypothesis for some actual fact that is surprising,
      the hypothesis must be plausible in order to taken seriously.

      - for example, using god or UFO
        to explain some surprising phenomena
        is not plausibility (is not to taken seriously)

      - x -
        plausibility is said to be hard to be formalized,
        how about using markov logic networks ?

  - two interpretations of probability

    - subjectivists -- conceptualists
      these believed that probability was
      a measure of the strength of belief
      actually accorded to a proposition
      or a measure of the degree of rational belief
      that ought to be accorded to a proposition

    - objectivists -- materialists
      these believed that probability was
      a measure of the relative frequency
      with which an event of some specific sort repeatedly happened

  - peirce adopted an objectivist notion of probability

    - probability is a notion with clear empirical content
      and that there are clear empirical procedures
      for ascertaining that content

    - probability is not just a measure of events
      rather, is an argument,
      an argument having premisses and a conclusion

      - just like the view of Kolmogoroff that
        all probabilities are conditional probabilities

  - peirce rejects Bayesianism and the method of inverse probabilities

    in fact no probability at all can be assigned to inductive arguments.
    Instead of probability,
    a different measure of imperfection of certitude
    must be assigned to inductive arguments:
    verisimilitude or likelihood.

    - about hypothesis-testing

* (1868) some consequences of four incapacities

* (1868) questions concerning certain faculties claimed for man

  - x -
    about semiotics

* (1868) on a new list of categories

  - http://www.iupui.edu/~arisbe/menu/library/bycsp/newlist/nl-frame.htm

  - https://en.wikipedia.org/wiki/Categories_(Peirce)
    In Aristotle's logic, categories are adjuncts to reasoning
    that are designed to resolve equivocations, ambiguities
    that make expressions or signs recalcitrant to being ruled by logic.
    Categories help the reasoner to render signs
    ready for the application of logical laws.
    An equivocation is a variation in meaning
    -- a manifold of sign senses -- such that,
    as Aristotle put it about names in the opening of Categories
    "Things are said to be named 'equivocally' when,
    though they have a common name,
    the definition corresponding with the name differs for each".
    So Peirce's claim that three categories are sufficient amounts
    to an assertion that all manifolds of meaning
    can be unified in just three steps.

  - the act of lifting as argument of relation and increasing arity

  - classification of relations

  - analysis of dependence between relations
    prescind <-> depend

  - analysis relations of arity 0 1 2 3

* (1869) grounds of validity of the laws of logic

  - Further Consequences of Four Incapacities

* [todo] (1870) description of a notation for the logic of relatives

  - Resulting from an Amplification
    of the Conceptions of Boole's Calculus of Logic

*** General Definitions of the Algebraic Signs

    - *Inclusion in* or *being as small as* is a *transitive* relation.
      The consequence holds that

      If    x -< y
      and   y -< z
      then  x -< z

    - *Equality* is the conjunction of being as small as and its converse.
      To say x = y is to say that x -< y and y -< x.

    - *Being less than* is being as small as with the exclusion of its converse.
      To say that x < y is to say that x -< y, and that it is not true that y -< x.

    - *Being greater than* is the converse of being less than.
      To say that x > y is say that y < x.

    - *Addition* is an associative operation.
      That is to say,

      (x +, y) +, z == x +, (y +, z)

      - I write a comma below the sign of addition,
        except when (as is the case in ordinary algebra)
        inverse operation (subtraction) is determinative.

    - Addition is a commutative operation.
      That is,

      x +, y == y +, x

    - *Invertible addition* is addition the corresponding inverse of which is determinative,
      The last two formulae hold good for it, and also the consequence that

      If    x + y == z
      and   x + y' == z
      then  y == y'

    - *Multiplication* is an operation which is *doubly distributive with reference to addition*.
      That is,

      x * (y +, z) == x * y +, x * z
      (x +, y) * z == x * z +, x * z

    - Multiplication is almost invariably an associative operation.

      (x * y) * z = x * (y * z)

      - x -
        I use `x * y` instead of `x y`

    - Multiplication is not generally commutative.
      If we write commutative multiplication with a comma, we have

      x *, y == y *, x

    - *Invertible multiplication* is multiplication whose corresponding inverse operation
      (division) is determinative.
      We may indicate this by a dot;
      and then the consequence holds that

      If    x . y == z
      and   x . y' == z
      then  y == y'

    - *Functional multiplication* is the application of an operation to a function.

      sin (a * b * c) * d * e * f
      log (a * b * c, d * e * f) * g * h * i

      - x -
        I use `f (x, y)` for function application

    - The operation of *Involution* obeys the formula

      (x ^ y) ^ z == x ^ (y * z)

      - x -
        I use `x [y]` instead of `x ^ y`

    - Involution, also, follows the *indexical principle*.

      x ^ (y +, z) == (x ^ y) *, (x ^ z)

    - Involution, also, satisfies the *binomial theorem*.

      (x +, y) ^ z ==
      (x ^ z) +,
      sigma (p) ((p -< z), (x ^ (z - p)) *, (y ^ p)) +,
      (y ^ z)

      - x -
        `sigma (<var>) (<pred>, <exp>)` introduces a bound variable

    - *Subtraction* is the operation inverse to addition.
      We may write indeterminative subtraction
      with a comma below the usual sign.
      Then we shall have that

      (x -, y) +, y == x
      (x - y) + y == x
      (x + y) - y == x

    - [todo]

*** [note] motive for category theory

    - The categorical understanding of the art of abstraction
      is not achieved at the author's time.

      This kinds of pre category theory striving for abstraction
      can be used as a motivation to introduce category theory.

    - in the following sections,
      Peirce provides interpretation of the abstract algebraic system,
      starting from Letters.

*** Use of the Letters

    - x -
      can all relations be reduced to
      composition of relations with arity less or equal than 3 ?

    - x -
      the author uses single letter variable name
      and uses different fonts
      to distinguish different classes of terms,
      I can not afford to do the same,
      I will give variable longer names.

    - absolute terms :
      a. animal
      b. black
      f. Frenchman
      h. horse
      m. man
      p. President of the United States Senate
      r. rich person
      u. violinist
      v. Vice-President of the United States
      w. woman

    - simple relative terms :
      a. enemy
      b. benefactor
      c. conqueror
      e. emperor
      h. husband
      I. lover
      m. mother
      n. not
      o. owner
      s. servant
      w. wife

    - conjugative terms :
      g. giver to -- of --
      b. betrayer to -- of --
      w. winner over of -- to -- from --
      t. transferrer from -- to --

*** Numbers corresponding to Letters

*** The Signs of Inclusion, Equality, etc.

*** The Signs for Addition

*** The Signs for Multiplication

* (1877) the fixation of belief

  - x -
    practicing physical science
    the whole meaning of a physical concept
    is determined by an exact method of measuring it

* (1878) how to make our ideas clear

*** [I] (CP5.388, W3.257)

    Whoever has looked into a modern treatise on logic of the common sort,
    will doubtless remember the two distinctions
    between clear and obscure conceptions,
    and between distinct and confused conceptions.

    They have lain in the books now for nigh two centuries,
    unimproved and unmodified,
    and are generally reckoned by logicians as among the gems of their doctrine.

    - x -
      Like aristotle, Peirce summaries historical approaches to the same inquiry.

      By "a modern treatise on logic of the common sort",
      Peirce might mean Descartes' treatise, or Descartes influenced treatise.
      (See the following sections about Descartes)

*** (CP5.389)

    A clear idea is defined as one which is so apprehended that
    it will be recognized wherever it is met with,
    and so that no other will be mistaken for it.
    If it fails of this clearness, it is said to be obscure.

    This is rather a neat bit of philosophical terminology;
    yet, since it is clearness that they were defining,
    I wish the logicians had made their definition a little more plain.

    Never to fail to recognize an idea,
    and under no circumstances to mistake another for it,
    let it come in how recondite a form it may,
    would indeed imply such prodigious force and clearness of intellect
    as is seldom met with in this world.

    On the other hand, merely to have such an acquaintance with the idea
    as to have become familiar with it,
    and to have lost all hesitancy in recognizing it in ordinary cases,
    hardly seems to deserve the name of clearness of apprehension,
    since after all it only amounts to a subjective feeling of mastery
    which may be entirely mistaken.

    I take it, however, that when the logicians speak of "clearness,"
    they mean nothing more than such a familiarity with an idea,
    since they regard the quality as but a small merit,
    which needs to be supplemented by another,
    which they call distinctness.

*** (CP5.390)

    A distinct idea is defined as one which contains nothing which is not clear.
    This is technical language; by the contents of an idea
    logicians understand whatever is contained in its definition.

    So that an idea is distinctly apprehended, according to them,
    when we can give a precise definition of it, in abstract terms.

    Here the professional logicians leave the subject;
    and I would not have troubled the reader with what they have to say,
    if it were not such a striking example of how they have been
    slumbering through ages of intellectual activity,
    listlessly disregarding the enginery of modern thought,
    and never dreaming of applying its lessons to the improvement of logic.

    It is easy to show that the doctrine that
    *familiar use* and *abstract distinctness* make the perfection of apprehension
    has its only true place in philosophies which have long been extinct;
    and it is now time *to formulate the method of attaining to a more perfect clearness of thought*,
    such as we see and admire in the thinkers of our own time.

    - x -
      Peirce changes the question from "what" to "how".

*** (CP5.391)

    When Descartes set about the reconstruction of philosophy,
    his first step was to (theoretically) permit scepticism
    and to discard the practice of the schoolmen
    of looking to authority as the ultimate source of truth.

    That done, he sought a more natural fountain of true principles,
    and thought he found it in the human mind;
    thus passing, in the directest way,
    from the method of authority to that of apriority,
    as described in my first paper.

    Self-consciousness was to furnish us with our fundamental truths,
    and to decide what was agreeable to reason.
    But since, evidently, not all ideas are true, he was led to note,
    as the first condition of infallibility, that they must be clear.
    The distinction between an idea seeming clear and really being so,
    never occurred to him.

    Trusting to introspection, as he did, even for a knowledge of external things,
    why should he question its testimony in respect to the contents of our own minds?

    But then, I suppose, seeing men, who seemed to be quite clear and positive,
    holding opposite opinions upon fundamental principles,
    he was further led to say that clearness of ideas is not sufficient,
    but that they need also to be distinct,
    i.e., to have nothing unclear about them.

    What he probably meant by this (for he did not explain himself with precision) was,
    that they must sustain the test of dialectical examination;
    that they must not only seem clear at the outset,
    but that discussion must never be able to bring to light
    points of obscurity connected with them.

    - x -
      Peirce understand Descartes by reconstructing Descartes' thread of thoughts.

*** (CP5.392)

    Such was the distinction of Descartes,
    and one sees that it was precisely on the level of his philosophy.
    It was somewhat developed by Leibnitz.
    This great and singular genius was as remarkable
    for what he failed to see as for what he saw.
    That a piece of mechanism could not do work perpetually
    without being fed with power in some form,
    was a thing perfectly apparent to him;
    yet he did not understand that
    the machinery of the mind can only transform knowledge,
    but never originate it,
    unless it be fed with facts of observation.

    He thus missed the most essential point of the Cartesian philosophy,
    which is, that to accept propositions which seem perfectly evident to us
    is a thing which, whether it be logical or illogical, we cannot help doing.

    Instead of regarding the matter in this way,
    he sought to reduce the first principles of science to two classes,
    those which cannot be denied without self-contradiction,
    and those which result from the principle of sufficient reason (of which more anon),
    and was apparently unaware of the great difference
    between his position and that of Descartes.
    So he reverted to the old trivialities of logic;
    and, above all, abstract definitions played a great part in his philosophy.

    It was quite natural, therefore, that
    on observing that the method of Descartes
    labored under the difficulty that we may seem to ourselves
    to have clear apprehensions of ideas
    which in truth are very hazy,
    no better remedy occurred to him
    than to require an abstract definition of every important term.

    Accordingly, in adopting the distinction of clear and distinct notions,
    he described the latter quality as
    the clear apprehension of everything contained in the definition;
    and the books have ever since copied his words.

    There is no danger that his chimerical scheme
    will ever again be over-valued.
    Nothing new can ever be learned by analyzing definitions.
    Nevertheless, our existing beliefs can be set in order by this process,
    and order is an essential element of intellectual economy, as of every other.

    It may be acknowledged, therefore, that
    the books are right in making familiarity with a notion the first step
    toward clearness of apprehension, and the defining of it the second.

    But in omitting all mention of any higher perspicuity of thought,
    they simply mirror a philosophy which was exploded a hundred years ago.
    That much-admired "ornament of logic"
    -- the doctrine of clearness and distinctness
    -- may be pretty enough,
    but it is high time to relegate to our cabinet of curiosities the antique bijou,
    and to wear about us something better adapted to modern uses.

*** (CP5.393)

    The very first lesson that we have a right to demand that logic shall teach us is,
    how to make our ideas clear; and a most important one it is,
    depreciated only by minds who stand in need of it.

    To know what we think, to be masters of our own meaning,
    will make a solid foundation for great and weighty thought.

    It is most easily learned by those whose ideas are meagre and restricted;
    and far happier they than such as wallow helplessly in a rich mud of conceptions.

    A nation, it is true, may, in the course of generations,
    overcome the disadvantage of an excessive wealth of language
    and its natural concomitant, a vast, unfathomable deep of ideas.

    We may see it in history, slowly perfecting its literary forms,
    sloughing at length its metaphysics,
    and, by virtue of the untirable patience
    which is often a compensation, attaining great excellence
    in every branch of mental acquirement.

    The page of history is not yet unrolled that is to tell us
    whether such a people will or will not in the long run prevail over
    one whose ideas (like the words of their language) are few,
    but which possesses a wonderful mastery over those which it has.

    For an individual, however, there can be no question that
    a few clear ideas are worth more than many confused ones.

    A young man would hardly be persuaded
    to sacrifice the greater part of his thoughts to save the rest;
    and the muddled head is the least apt to see the necessity of such a sacrifice.
    Him we can usually only commiserate, as a person with a congenital defect.
    Time will help him, but intellectual maturity with regard to clearness comes rather late,
    an unfortunate arrangement of Nature,
    inasmuch as clearness is of less use to a man settled in life,
    whose errors have in great measure had their effect,
    than it would be to one whose path lay before him.

    It is terrible to see how a single unclear idea,
    a single formula without meaning, lurking in a young man's head,
    will sometimes act like an obstruction of inert matter in an artery,
    hindering the nutrition of the brain,
    and condemning its victim to pine away
    in the fullness of his intellectual vigor
    and in the midst of intellectual plenty.

    Many a man has cherished for years as his hobby
    some vague shadow of an idea,
    too meaningless to be positively false;
    he has, nevertheless, passionately loved it,
    has made it his companion by day and by night,
    and has given to it his strength and his life,
    leaving all other occupations for its sake,
    and in short has lived with it and for it,
    until it has become, as it were,
    flesh of his flesh and bone of his bone;
    and then he has waked up some bright morning to find it gone,
    clean vanished away like the beautiful Melusina of the fable,
    and the essence of his life gone with it.

    I have myself known such a man;
    and who can tell how many histories of
    circle-squarers,
    metaphysicians,
    astrologers,
    and what not, may not be told
    in the old German story?

*** [II] (CP5.394)

    The principles set forth in the first part of these papers
    lead, at once, to a method of reaching a clearness of thought
    of a far higher grade than the "distinctness" of the logicians.

    We have there found. that the action of thought
    is excited by the irritation of doubt,
    and ceases when belief is attained;
    so that the production of belief is the sole function of thought.

    - x -
      When trying to define thought,
      Peirce observes its effect on us.

    - x -
      Thus when asking "can machine think?",
      we should firstly ask "can machine doubt?".

      We doubt, firstly, by finding logic contradiction within our current believes,
      or, secondly, in between our current believes and observations.

      Machine can doubt in the same manner.

      If I program a theorem prover, so that
      when I give it a group of inconsistent theorems (a group of believes),
      It will adjust the theorems to a group of consistent theorems,
      Then it can think in the first manner.

      If it can also adjust contradiction in believes its current believes and observations,
      it also can think in the second manner.

      The problem is to formalize logics, believes and observations,
      so that we can write thinking programs.

      And to adjust contradiction,
      the program must search for new believes without contradiction.

      Before designing a program which can search for believes,
      we must also ask how to use those believes ?

    All these words, however, are too strong for my purpose.
    It is as if I had described the phenomena
    as they appear under a mental microscope.

    Doubt and Belief, as the words are commonly employed,
    relate to religious or other grave discussions.

    But here I use them to designate the starting of any question,
    no matter how small or how great, and the resolution of it.

    If, for instance, in a horse-car,
    I pull out my purse and find a five-cent nickel and five coppers,
    I decide, while my hand is going to the purse,
    in which way I will pay my fare.

    To call such a question Doubt, and my decision Belief,
    is certainly to use words very disproportionate to the occasion.

    To speak of such a doubt as causing an irritation which needs to be appeased,
    suggests a temper which is uncomfortable to the verge of insanity.

    Yet, looking at the matter minutely, it must be admitted that,
    if there is the least hesitation as to whether
    I shall pay the five coppers or the nickel
    (as there will be sure to be, unless I act
    from some previously contracted habit in the matter),
    though irritation is too strong a word,
    yet I am excited to such small mental activity
    as may be necessary to deciding how I shall act.

    Most frequently doubts arise from some indecision,
    however momentary, in our action.
    Sometimes it is not so.
    I have, for example, to wait in a railway-station,
    and to pass the time I read the advertisements on the walls.
    I compare the advantages of different trains and different routes
    which I never expect to take,
    merely fancying myself to be in a state of hesitancy,
    because I am bored with having nothing to trouble me.

    Feigned hesitancy,
    whether feigned for mere amusement
    or with a lofty purpose,
    plays a great part in the production of scientific inquiry.

    However the doubt may originate,
    it stimulates the mind to an activity
    which may be slight or energetic,
    calm or turbulent.

    Images pass rapidly through consciousness,
    one incessantly melting into another,
    until at last, when all is over
    -- it may be in a fraction of a second,
    in an hour, or after long years --
    we find ourselves decided
    as to how we should act under such circumstances
    as those which occasioned our hesitation.

    In other words, we have attained belief.

*** (CP5.395)

    In this process we observe two sorts of elements of consciousness,
    the distinction between which may best be made clear by means of an illustration.

    In a piece of music there are the separate notes, and there is the air.

    A single tone may be prolonged for an hour or a day,
    and it exists as perfectly in each second of that time as in the whole taken together;
    so that, as long as it is sounding,
    it might be present to a sense from which
    everything in the past was as completely absent as the future itself.

    But it is different with the air,
    the performance of which occupies a certain time,
    during the portions of which only portions of it are played.
    It consists in an orderliness in the succession of sounds
    which strike the ear at different times;
    and to perceive it there must be some continuity of consciousness
    which makes the events of a lapse of time present to us.

    We certainly only perceive the air by hearing the separate notes;
    yet we cannot be said to directly hear it,
    for we hear only what is present at the instant,
    and an orderliness of succession cannot exist in an instant.

    These two sorts of objects,
    what we are immediately conscious of
    and what we are mediately conscious of,
    are found in all consciousness.

    Some elements (the sensations) are completely present at every instant so long as they last,
    while others (like thought) are actions having beginning, middle, and end,
    and consist in a congruence in the succession of sensations which flow through the mind.

    They cannot be immediately present to us,
    but must cover some portion of the past or future.

    Thought is a thread of melody running through the succession of our sensations.

*** (CP5.396)

    We may add that just as a piece of music may be written in parts,
    each part having its own air,
    so various systems of relationship of succession
    subsist together between the same sensations.

    These different systems are distinguished
    by having different motives, ideas, or functions.

    Thought is only one such system,
    for its sole motive, idea, and function is to produce belief,
    and whatever does not concern that purpose
    belongs to some other system of relations.

    The action of thinking may incidentally have other results;
    it may serve to amuse us,
    for example, and among dilettanti it is not rare to find those
    who have so perverted thought to the purposes of pleasure
    that it seems to vex them to think that
    the questions upon which they delight to exercise it
    may ever get finally settled;
    and a positive discovery which takes a favorite subject out of the arena of literary debate
    is met with ill-concealed dislike.
    This disposition is the very debauchery of thought.

    But the soul and meaning of thought,
    abstracted from the other elements which accompany it,
    though it may be voluntarily thwarted,
    can never be made to direct itself toward anything but the production of belief.

    Thought in action has for its only possible motive the attainment of thought at rest;
    and whatever does not refer to belief is no part of the thought itself.

*** (CP5.397)

    And what, then, is belief?

    It is the demi-cadence
    which closes a musical phrase
    in the symphony of our intellectual life.

    We have seen that it has just three properties:
    First, it is something that we are aware of;
    second, it appeases the irritation of doubt;
    and, third, it involves the establishment in our nature
    of a rule of action, or, say for short, a habit.

    As it appeases the irritation of doubt,
    which is the motive for thinking,
    thought relaxes, and comes to rest for a moment when belief is reached.

    But, since belief is a rule for action,
    the application of which involves further doubt and further thought,
    at the same time that it is a stopping-place,
    it is also a new starting-place for thought.

    That is why I have permitted myself to call it thought at rest,
    although thought is essentially an action.

    The final upshot of thinking is the exercise of volition,
    and of this thought no longer forms a part;
    but belief is only a stadium of mental action,
    an effect upon our nature due to thought,
    which will influence future thinking.

*** (CP5.398)

*** [todo] OLD NOTES

  - Some elements (the sensations) are completely present
    at every instant so long as they last,
    while others (like thought) are actions
    having beginning, middle, and end,
    and consist in a congruence in the succession of sensations
    which flow through the mind.

    They cannot be immediately present to us,
    but must cover some portion of the past or future.

    Thought is a thread of melody
    running through the succession of our sensations.

  - Thought in action has for its only possible motive
    the attainment of thought at rest;
    and whatever does not refer to belief
    is no part of the thought itself.

  - And what, then, is belief?
    It is the demi-cadence which closes a musical phrase
    in the symphony of our intellectual life.

    We have seen that it has just three properties:
    First, it is something that we are aware of;
    second, it appeases the irritation of doubt;
    and, third, it involves the establishment
    in our nature of a rule of action, or, say for short, a habit.

  - But, since belief is a rule for action,
    the application of which involves further doubt and further thought,
    at the same time that it is a stopping-place,
    it is also a new starting-place for thought.

  - It appears, then, that the rule for attaining
    the third grade of clearness of apprehension is as follows:
    Consider what effects,
    which might conceivably have practical bearings,
    we conceive the object of our conception to have.
    Then, our conception of these effects
    is the whole of our conception of the object.

* (1880) on the algebra of logic

* (2000) (geraldine brady) from peirce to skolem

*** 1 The Early Work of Charles S. Peirce

*** 2 Peirce's Calculus of Relatives: 1870

    - (1870) Description of a Notation for the Logic of Relatives

    - Peirce's belief that
      this was the most important advance since Boole
      was certainly based on the fact that
      the algebra ofrelations is far more expressive
      than the algebra of propositions,
      and reflects a great deal more of everyday logical inference
      than does Boole'stheory of sets,
      since relations, not just sets,
      are the bread and butter ofreasoning.

    - In this early work on the calculus of relatives,
      Peirce shows more concern with
      maintaining the analogies between
      the notation he is setting forth
      and ordinary algebraic notation
      than with giving a direct account of the problem at hand.

*** 3 Peirce on the Algebra of Logic: 1880

    - (1880) On the algebra of logic

*** 4 Mitchell on a New Algebra of Logic: 1883

*** 5 Peirce on the Algebra or Relatives: 1883

*** 6 Peirce's Logic of Quantifiers: 1885

*** 7 Schroder's Calculus of Relatives

*** 8 Lowenheim's Contribution

*** 9 Skolem's Recasting

* [note] semiotics (semeiotics)

*** etymology

    - semiotics
      Coined by John Locke
      from σημειωτικός (sēmeiōtikós, "fitted for marking, portending")
      from σημειοῦν (sēmeioûn, "to mark, interpret as a portend")
      from σημεῖον (sēmeîon, "a mark, sign, token")
      from σῆμα (sêma, "mark, sign")

    - portend
      Borrowed from Latin portendere ("to foretell")
      from por- ("forward") + tendere ("to stretch"),
      present active infinitive of tendo

*** triadic definition

    - [[https://en.wikipedia.org/wiki/Semiotic_theory_of_Charles_Sanders_Peirce][Semiotic_theory_of_Charles_Sanders_Peirce]]

    - Peirce adopted the term semiosis (or semeiosis)
      and defined it to mean an "action, or influence,
      which is, or involves, a cooperation of three subjects,
      such as a sign, its object, and its interpretant,
      this trirelative influence
      *not being in any way resolvable*
      into actions between pairs".

      - x -
        in my view, the three means,
        1. formal syntax and abstract syntax
        2. objects
        3. interpretation -- operations on objects
           note that,
           interpretation might happens in context (or in environment)

      - one might say my view is wrong,
        because many formal syntax can denote the same system of objects,
        so objects are independent from syntax,
        but it is also true that there must at least one syntax,
        and different syntax might make us think differently.
        thus the three are intertwined.

    - his semiotics is not contained
      in a mathematical or deductive system
      and does not proceed chiefly by drawing necessary conclusions
      about purely hypothetical objects or cases.

    - [[https://en.wikipedia.org/wiki/Interpretant][Interpretant]]
      For example, one way to approach the concept of an interpretant
      is to think of a psycholinguistic process.
      In this context, an interpretant can be understood as
      a sign's effect on the mind, or on anything that acts like a mind,
      what Peirce calls a quasi-mind.
      An interpretant is what results from a process of interpretation,
      one of the types of activity
      that falls under the heading of semiosis.

    - Peirce argued that logic is the formal study of signs
      in the broadest sense, not only signs that are
      artificial, linguistic, or symbolic,
      but also signs that are semblances or are indexical
      such as reactions.

    - [[https://en.wikipedia.org/wiki/Indexicality][Indexicality]]

* [todo] (1902) the simplest mathematics

  - [[https://en.wikipedia.org/wiki/Hypostatic_abstraction][Hypostatic_abstraction]]
    to convert an adjective or predicate into an extra subject,
    thus increasing by one the number of "subject" slots,
    called the arity or adicity, of the main predicate.
    - for example "Honey is sweet"
      is transformed into "Honey has sweetness"
