#+title: charles sanders peirce

* links

  - https://en.wikipedia.org/wiki/Charles_Sanders_Peirce
  - https://en.wikipedia.org/wiki/Charles_Sanders_Peirce_bibliography

  - https://plato.stanford.edu/entries/peirce/
  - https://plato.stanford.edu/entries/peirce-logic/

  - http://www.iupui.edu/~arisbe/
    A philosophical website,
    providing access to resources for
    the life, work, and continuing interest in
    the American philosopher, scientist, and humanist
    Charles Sanders Peirce

  - http://www.peirce.org/

  - http://www.pragmaticism.net/

  - http://peirce.iupui.edu/index.html

  - https://academic.oup.com/monist

* (1868) some consequences of four incapacities

* (1868) questions concerning certain faculties claimed for man

  - x -
    about semiotics

* (1868) on a new list of categories

  - http://www.iupui.edu/~arisbe/menu/library/bycsp/newlist/nl-frame.htm

  - https://en.wikipedia.org/wiki/Categories_(Peirce)
    In Aristotle's logic, categories are adjuncts to reasoning
    that are designed to resolve equivocations, ambiguities
    that make expressions or signs recalcitrant to being ruled by logic.
    Categories help the reasoner to render signs
    ready for the application of logical laws.
    An equivocation is a variation in meaning
    -- a manifold of sign senses -- such that,
    as Aristotle put it about names in the opening of Categories
    "Things are said to be named 'equivocally' when,
    though they have a common name,
    the definition corresponding with the name differs for each".
    So Peirce's claim that three categories are sufficient amounts
    to an assertion that all manifolds of meaning
    can be unified in just three steps.

  - the act of lifting as argument of relation and increasing arity

  - classification of relations

  - analysis of dependence between relations
    prescind <-> depend

  - analysis relations of arity 0 1 2 3

* (1869) grounds of validity of the laws of logic

  - Further Consequences of Four Incapacities

* [todo] (1870) description of a notation for the logic of relatives

  - Resulting from an Amplification
    of the Conceptions of Boole's Calculus of Logic

*** General Definitions of the Algebraic Signs

    - *Inclusion in* or *being as small as* is a *transitive* relation.
      The consequence holds that

      If    x -< y
      and   y -< z
      then  x -< z

    - *Equality* is the conjunction of being as small as and its converse.
      To say x = y is to say that x -< y and y -< x.

    - *Being less than* is being as small as with the exclusion of its converse.
      To say that x < y is to say that x -< y, and that it is not true that y -< x.

    - *Being greater than* is the converse of being less than.
      To say that x > y is say that y < x.

    - *Addition* is an associative operation.
      That is to say,

      (x +, y) +, z == x +, (y +, z)

      - I write a comma below the sign of addition,
        except when (as is the case in ordinary algebra)
        inverse operation (subtraction) is determinative.

    - Addition is a commutative operation.
      That is,

      x +, y == y +, x

    - *Invertible addition* is addition the corresponding inverse of which is determinative,
      The last two formulae hold good for it, and also the consequence that

      If    x + y == z
      and   x + y' == z
      then  y == y'

    - *Multiplication* is an operation which is *doubly distributive with reference to addition*.
      That is,

      x * (y +, z) == x * y +, x * z
      (x +, y) * z == x * z +, x * z

    - Multiplication is almost invariably an associative operation.

      (x * y) * z = x * (y * z)

      - x -
        I use `x * y` instead of `x y`

    - Multiplication is not generally commutative.
      If we write commutative multiplication with a comma, we have

      x *, y == y *, x

    - *Invertible multiplication* is multiplication whose corresponding inverse operation
      (division) is determinative.
      We may indicate this by a dot;
      and then the consequence holds that

      If    x . y == z
      and   x . y' == z
      then  y == y'

    - *Functional multiplication* is the application of an operation to a function.

      sin (a * b * c) * d * e * f
      log (a * b * c, d * e * f) * g * h * i

      - x -
        I use `f (x, y)` for function application

    - The operation of *Involution* obeys the formula

      (x ^ y) ^ z == x ^ (y * z)

      - x -
        I use `x [y]` instead of `x ^ y`

    - Involution, also, follows the *indexical principle*.

      x ^ (y +, z) == (x ^ y) *, (x ^ z)

    - Involution, also, satisfies the *binomial theorem*.

      (x +, y) ^ z ==
      (x ^ z) +,
      sigma (p) ((p -< z), (x ^ (z - p)) *, (y ^ p)) +,
      (y ^ z)

      - x -
        `sigma (<var>) (<pred>, <exp>)` introduces a bound variable

    - *Subtraction* is the operation inverse to addition.
      We may write indeterminative subtraction
      with a comma below the usual sign.
      Then we shall have that

      (x -, y) +, y == x
      (x - y) + y == x
      (x + y) - y == x

    - [todo]

*** [note] motive for category theory

    - The categorical understanding of the art of abstraction
      is not achieved at the author's time.

      This kinds of pre category theory striving for abstraction
      can be used as a motivation to introduce category theory.

    - in the following sections,
      Peirce provides interpretation of the abstract algebraic system,
      starting from Letters.

*** Use of the Letters

    - x -
      can all relations be reduced to
      composition of relations with arity less or equal than 3 ?

    - x -
      the author uses single letter variable name
      and uses different fonts
      to distinguish different classes of terms,
      I can not afford to do the same,
      I will give variable longer names.

    - absolute terms :
      a. animal
      b. black
      f. Frenchman
      h. horse
      m. man
      p. President of the United States Senate
      r. rich person
      u. violinist
      v. Vice-President of the United States
      w. woman

    - simple relative terms :
      a. enemy
      b. benefactor
      c. conqueror
      e. emperor
      h. husband
      I. lover
      m. mother
      n. not
      o. owner
      s. servant
      w. wife

    - conjugative terms :
      g. giver to -- of --
      b. betrayer to -- of --
      w. winner over of -- to -- from --
      t. transferrer from -- to --

*** Numbers corresponding to Letters

*** The Signs of Inclusion, Equality, etc.

*** The Signs for Addition

*** The Signs for Multiplication

* (1877) the fixation of belief

* (1878) how to make our ideas clear

  - x -
    like aristotle, Peirce summaries
    historical approaches to the same inquiry.

  - We have there found. that the action of thought
    is excited by the irritation of doubt,
    and ceases when belief is attained;
    so that the production of belief is the sole function of thought.

  - x -
    when trying to define thought,
    Peirce observe its effect on us.

  - Some elements (the sensations) are completely present
    at every instant so long as they last,
    while others (like thought) are actions
    having beginning, middle, and end,
    and consist in a congruence in the succession of sensations
    which flow through the mind.

    They cannot be immediately present to us,
    but must cover some portion of the past or future.

    Thought is a thread of melody
    running through the succession of our sensations.

  - Thought in action has for its only possible motive
    the attainment of thought at rest;
    and whatever does not refer to belief
    is no part of the thought itself.

  - And what, then, is belief?
    It is the demi-cadence which closes a musical phrase
    in the symphony of our intellectual life.

    We have seen that it has just three properties:
    First, it is something that we are aware of;
    second, it appeases the irritation of doubt;
    and, third, it involves the establishment
    in our nature of a rule of action, or, say for short, a habit.

  - But, since belief is a rule for action,
    the application of which involves further doubt and further thought,
    at the same time that it is a stopping-place,
    it is also a new starting-place for thought.

  - It appears, then, that the rule for attaining
    the third grade of clearness of apprehension is as follows:
    Consider what effects,
    which might conceivably have practical bearings,
    we conceive the object of our conception to have.
    Then, our conception of these effects
    is the whole of our conception of the object.

* [todo] (1880) on the algebra of logic

* (2000) (geraldine brady) from peirce to skolem

*** 1 The Early Work of Charles S. Peirce

*** 2 Peirce's Calculus of Relatives: 1870

    - (1870) Description of a Notation for the Logic of Relatives

    - Peirce's belief that
      this was the most important advance since Boole
      was certainly based on the fact that
      the algebra ofrelations is far more expressive
      than the algebra of propositions,
      and reflects a great deal more of everyday logical inference
      than does Boole'stheory of sets,
      since relations, not just sets,
      are the bread and butter ofreasoning.

    - In this early work on the calculus of relatives,
      Peirce shows more concern with
      maintaining the analogies between
      the notation he is setting forth
      and ordinary algebraic notation
      than with giving a direct account of the problem at hand.

*** 3 Peirce on the Algebra of Logic: 1880

    - (1880) On the algebra of logic

*** 4 Mitchell on a New Algebra of Logic: 1883

*** 5 Peirce on the Algebra or Relatives: 1883

*** 6 Peirce's Logic of Quantifiers: 1885

*** 7 Schroder's Calculus of Relatives

*** 8 Lowenheim's Contribution

*** 9 Skolem's Recasting

* [note] semiotics (semeiotics)

*** etymology

    - semiotics
      Coined by John Locke
      from σημειωτικός (sēmeiōtikós, "fitted for marking, portending")
      from σημειοῦν (sēmeioûn, "to mark, interpret as a portend")
      from σημεῖον (sēmeîon, "a mark, sign, token")
      from σῆμα (sêma, "mark, sign")

    - portend
      Borrowed from Latin portendere ("to foretell")
      from por- ("forward") + tendere ("to stretch"),
      present active infinitive of tendo

*** triadic definition

    - [[https://en.wikipedia.org/wiki/Semiotic_theory_of_Charles_Sanders_Peirce][Semiotic_theory_of_Charles_Sanders_Peirce]]

    - Peirce adopted the term semiosis (or semeiosis)
      and defined it to mean an "action, or influence,
      which is, or involves, a cooperation of three subjects,
      such as a sign, its object, and its interpretant,
      this trirelative influence
      *not being in any way resolvable*
      into actions between pairs".

      - x -
        in my view, the three means,
        1. formal syntax and abstract syntax
        2. objects
        3. interpretation -- operations on objects
           note that,
           interpretation might happens in context (or in environment)

      - one might say my view is wrong,
        because many formal syntax can denote the same system of objects,
        so objects are independent from syntax,
        but it is also true that there must at least one syntax,
        and different syntax might make us think differently.
        thus the three are intertwined.

    - his semiotics is not contained
      in a mathematical or deductive system
      and does not proceed chiefly by drawing necessary conclusions
      about purely hypothetical objects or cases.

    - [[https://en.wikipedia.org/wiki/Interpretant][Interpretant]]
      For example, one way to approach the concept of an interpretant
      is to think of a psycholinguistic process.
      In this context, an interpretant can be understood as
      a sign's effect on the mind, or on anything that acts like a mind,
      what Peirce calls a quasi-mind.
      An interpretant is what results from a process of interpretation,
      one of the types of activity
      that falls under the heading of semiosis.

    - Peirce argued that logic is the formal study of signs
      in the broadest sense, not only signs that are
      artificial, linguistic, or symbolic,
      but also signs that are semblances or are indexical
      such as reactions.

    - [[https://en.wikipedia.org/wiki/Indexicality][Indexicality]]

* [todo] (1902) the simplest mathematics

  - [[https://en.wikipedia.org/wiki/Hypostatic_abstraction][Hypostatic_abstraction]]
    to convert an adjective or predicate into an extra subject,
    thus increasing by one the number of "subject" slots,
    called the arity or adicity, of the main predicate.
    - for example "Honey is sweet"
      is transformed into "Honey has sweetness"
