#+title: charles sanders peirce

* (1868) Some Consequences of Four Incapacities

* (1868) Questions Concerning Certain Faculties Claimed for Man

* (1868) On a New List of Categories

* (1869) Grounds of Validity of the Laws of Logic

  - Further Consequences of Four Incapacities

* [todo] (1870) Description of a Notation for the Logic of Relatives

  - Resulting from an Amplification
    of the Conceptions of Boole's Calculus of Logic

*** General Definitions of the Algebraic Signs

    - *Inclusion in* or *being as small as* is a *transitive* relation.
      The consequence holds that

      If    x -< y
      and   y -< z
      then  x -< z

    - *Equality* is the conjunction of being as small as and its converse.
      To say x = y is to say that x -< y and y -< x.

    - *Being less than* is being as small as with the exclusion of its converse.
      To say that x < y is to say that x -< y, and that it is not true that y -< x.

    - *Being greater than* is the converse of being less than.
      To say that x > y is say that y < x.

    - *Addition* is an associative operation.
      That is to say,

      (x +, y) +, z == x +, (y +, z)

      - I write a comma below the sign of addition,
        except when (as is the case in ordinary algebra)
        inverse operation (subtraction) is determinative.

    - Addition is a commutative operation.
      That is,

      x +, y == y +, x

    - *Invertible addition* is addition the corresponding inverse of which is determinative,
      The last two formulae hold good for it, and also the consequence that

      If    x + y == z
      and   x + y' == z
      then  y == y'

* (1877) the fixation of belief

* (1878) how to make our ideas clear

* [todo] (1880) On the algebra of logic

* (2000) (geraldine brady) from peirce to skolem

*** 1 The Early Work of Charles S. Peirce

*** 2 Peirce's Calculus of Relatives: 1870

    - (1870) Description of a Notation for the Logic of Relatives

    - Peirce's belief that
      this was the most important advance since Boole
      was certainly based on the fact that
      the algebra ofrelations is far more expressive
      than the algebra of propositions,
      and reflects a great deal more of everyday logical inference
      than does Boole'stheory of sets,
      since relations, not just sets,
      are the bread and butter ofreasoning.

    - In this early work on the calculus of relatives,
      Peirce shows more concern with
      maintaining the analogies between
      the notation he is setting forth
      and ordinary algebraic notation
      than with giving a direct account of the problem at hand.

*** 3 Peirce on the Algebra of Logic: 1880

    - (1880) On the algebra of logic

*** 4 Mitchell on a New Algebra of Logic: 1883

*** 5 Peirce on the Algebra or Relatives: 1883

*** 6 Peirce's Logic of Quantifiers: 1885

*** 7 Schroder's Calculus of Relatives

*** 8 Lowenheim's Contribution

*** 9 Skolem's Recasting
