#+title: lefschetz

* (1941) algebraic topology

* (1942) topics in topology

* (1949) introduction to topology

*** introduction, a survey of some topological concepts

***** 1. theory of sets. topological spaces

      - [the origin of topology]
        Topology begins where sets are implemented with some cohesive properties
        enabling one to define continuity.
        The sets are then called topological spaces.
        Thus topology is a branch of general set theory.

      - [homotopy equivalent between mappings]
        The guiding purpose is to obtain properties
        associated with the disappearance,
        or the reduction in dimension, of certain parts,
        as a consequence of continuous deformations.

      - [This is the origin of homology theory]
        (K : complex)
        (C : p-chain of K)
        From an intuitive standpoint the boundary of a cell
        is "deformable" over the cell into a point.
        Recalling our earlier intuitive remarks,
        on geometric grounds the boundary of a cell,
        and therefore owing to linearity, the boundary of the p-chain,
        should be more or less neglected.
        We introduce then with Poincare a homology (r ~ 0)
        to signify that 'r' bounds.

      - x -
        (r ~ 0) denotes that
        'r' is the boundary of a higher chain,
        or, 'r' is the image of the boundary operator.

        only circle (closed continuum) can be boundary of a higher  chain,
        but not all circles are boundary of a higher chain.

      - x -
        note that,
        in homology theory,
        continuum is generalized to chain,
        in AT1 such generalization is implemented by keywords such as
        (1 ...) (2 ...)

*** Chapter I. Basic Information about Sets, Spaces, Vectors, Groups

*** Chapter II. Two-dimensional Polyhedral Topology

*** Chapter III. Theory of Complexes

***** 1. intuitive approach.

      - [homology theory with application to simplify integration]
        a good guide in the type of questions that concern us
        is always provided by integration.

        There still remain a large number of paths to be considered
        and some method for reducing their number is most desirable.

***** 2. simplexes and simplicial complexes.

      - ><

*** Chapter IV. Transformations of Complexes. Simplicial Approximations and Related Questions

*** Chapter V. Further Properties of Homotopy. Fixed Points. Fundamental Group. Homotopy Groups

*** Chapter VI. Introduction to Manifolds. Duality Theorems

* differential equations: geometric theory
