#+title: lukasiewicz

* aristotle's syllogistic

*** chapter 1 elements of the system

***** 1. The true form of the Aristotelian syllogism

      - Aristotle always puts the predicate in the first place
        and the subject in the second.
        He never says 'All B is A',
        but uses instead the expression
        'A is predicated of all B'
        or more often 'A belongs to all B'.

      - Barbara :

        - If all B is A,
          and all C is B,
          then all C is A.

          - x -
            this can be understand as subtype relation :
            - if B < A
              and C < B
              then C < A
            note that, if B < A,
            the identity function on B,
            can be viewed as a function of type (-> B -- A)
            thus we have :
            - if f : (-> B -- A)
              and g : (-> C -- B)
              then [g f] : (-> C -- A)

        - If A is predicated of all B
          and B is predicated of all C,
          then A is predicated of all C.

        - If A belongs to all B
          and B belongs to all C,
          then A belongs to all C.

***** 2. Premisses and terms

      - Every Aristotelian *syllogism*
        consists of three propositions called *premisses*.

      - A premiss is a sentence
        affirming or denying something of something.

        - In this sense the conclusion is also a premiss,
          because it states something about something.

      - The two elements involved in a premiss
        are its *subject* and *predicate*.
        Aristotle calls them 'terms'.

      - Every premiss is either universal, particular, or indefinite.
        - 'All' and 'no' added to the subject -- universality
        - 'some' and 'some not' (or 'not all')
          added to the subject -- particularity.
        - A premiss without such quantity -- indefinite

***** [note] premiss

      - x -
        how should we understand premiss ?

      - k -
        natural language is so vague,
        the meaning of 'is' is heavily overloaded.
        for example, in :
        - If all B is A,
          and all C is B,
          then all C is A.
        we can view the first line as :
        1. (-> B -- A) -- function type
        2. B < A -- subtype [subset]
        3. B : A -- belonging
        4. quotient type

      - x -
        ><><><

***** 3. Why singular terms were omitted by Aristotle

      - Aristotle divides all things into three classes.

        1. Some, he says, are such that
           they cannot be predicated truly of anything at all,
           like Cleon and Callias and the individual and sensible,
           but other things may be predicated of them,
           e.g. man or animal.

        2. Some other things,
           and these are the second class,
           are themselves predicated of others
           but nothing prior is predicated of them.
           For this class of things no example is given,
           but it is clear that Aristotle means
           what is most universal, like being.

        3. To the third class belong those things that
           may be predicated of others and others of them,
           e.g. man of Callias and animal of man,
           and as a -- rule, concludes Aristotle,
           arguments and inquiries are concerned
           with this class of things.

***** 4. Variables

      - if all S is R,
        and some S is P,
        then some R is P.

        - x -
          this example makes most sense
          when viewed in set theory.
          where S R P are sets,
          and 'is' is the 'belong' in set theory.

        - k -
          but syllogism in natural language seems
          is able to capture more meaning then set theory.
          - because 'is' is overloaded.

***** 5. Syllogistic necessity

***** 6. What is formal logic ?

***** 7. What is formalism ?

*** chapter 2 theses of the system

***** 8. Theses and rules of inference

      - THE Aristotelian theory of the syllogism
        is a system of true propositions
        concerning the constants A, E, I, and O.

        - 'true propositions' means
          true for all values of the variables.

      - True propositions of a deductive system I call *theses*.

      - types of theses :

        - implications :
          begin with 'if :a then :b'

          1. laws ofconversion
             - and laws of the square of opposition
               not mentionedin the Prior Analytics
             for example :
             'If all B is A, then some A is B.'

          2. syllogisms
             of form 'if :a and :b, then :c'
             for example :
             'If all B is A,
             and all C is B,
             then all C is A.'

        - laws of identity :

          1. 'A belongsto all A' or 'All A is A'

          2. 'A belongs to some A' or 'Some A is A'

        - It must be said emphatically that
          no syllogism is formulated by Aristotle
          as an inference with the word 'therefore' (apa),
          as is done in the traditional logic.
          Syllogisms of the form :
          'All B is A; all C is B;
          therefore all C is A'
          are not Aristotelian.

***** 9. The syllogistic figures

***** 10. The major, middle, and minor terms

***** 11. The history of an error

***** 12. The order of the premisses

***** 13. Errors of some modern commentators

***** 14. The four Galenian figures

*** chapter 3 the system

***** 15. Perfect and imperfect syllogisms

***** 16. The logic of terms and the logic of propositions

***** 17. The proofs by conversion

***** 18. The proofs by reductio ad impossibile

***** 19. The proofs by ecthesis

***** 20. The rejected forms

***** 21. Some unsolved problems

*** chapter 4 aristotle's system in symbolic form

***** ><

* studies-in-logic-and-the-foundations-of-mathematics
