#+title: marvin minsky

* [note]

  - 對 conscious 一詞的使用需要分類
    正如 aristotle 在 category 中分類 be 一詞的使用一樣
    類型系統可以幫助我們避免犯錯

* the society of mind

*** 1 prologue

***** intro

***** 1.1 the agents of the mind

***** 1.4 the world of blocks

      - 看似是常識的事情其實是我們在幼年習得的
        只是我們如今已經忘記了學習的過程

      - 如此看來
        在 reid 和 hume 之間
        我們更應該學習 hume 的觀點

      - 利用 hume 的觀點
        我們也許可以建立理論和模型來模擬人腦工作
        就這種目的而言 reid 的觀點可能完全沒有用

***** 1.5 common sense

      - common sense is not a simple thing.
        Insteod, it is an immense society
        of hard-earned practical ideas
        of multitudes of life-learned rules and exceptions,
        dispositions and tendencies, balances and checks.

***** 1.6 agents and agencies

*** 2 wholes and parts

***** 2.1 components and connections

      - you couldn't predict what would happen in a human community
        from knowing only what each separate individual can do;
        you must also know how they are organized
        -- that is, who talks to whom.

      - And it's the same for understanding
        any large and complex thing.
        First, we must know how each separate part works.
        Second, we must know how each part interacts
        with those to which it is connected.
        And third, we have to understand
        how all these local interactions combine
        to accomplish what that system does
        -- as seen from the outside.

      - x -
        當提到社會的權力結構時
        只強調一個樹狀結構是消極的
        因爲這樣的視角 使人不再能意識到新的組織方式之可能

      - x -
        所謂積極 即能促進行動
        所謂消極 即能阻礙行動

      - k -
        一個社會中的人
        完善自己個人的能力是不夠的
        他必須積極地與人交流
        他需要有一個羣體 能讓他立足其中 與人分享 並相互鼓勵
        這樣他才能融入到社會的生機中去

        羣體的各種組織方式 都有不少不足之處
        但是他要積極地面對這些問題
        因爲幸福與快樂只有在分享中才有生機

***** 2.2 novelists and reductionist

***** 2.3 parts and wholes

      - ><

* THE EMOTION MACHINE

*** INTRODUCTION

    - x -
      在寫程序解決問題的時候
      [比如 proof search 這類問題]
      如果程序有多種解決同一個問題的方法
      並且能在一個方法遇到困難時切換另一個方法
      並且還能根據結果和效率批判各種解法的有效性
      那麼就像是智能了

    - Ch1. We are born with many mental resources.
      Ch2. We learn more from interacting with others.
      Ch3. Emotions are different Ways to Think.
      Ch4. We learn to think about our recent thoughts.
      Ch5. We learn to think on multiple levels.
      Ch6. We accumulate huge stores of commonsense knowledge.
      Ch7. We switch among different Ways to Think.
      Ch8. We find multiple ways to represent things.
      Ch9. We build multiple models ofourselves.

*** FALLING IN LOVE

*** ATTACHMENTS AND GOALS

*** FROM PAIN TO SUFFERING

*** CONSCIOUSNESS

*** LEVELS OF MENTAL ACTIVITIES

*** COMMON SENSE

*** THINKING

*** RESOURCEFULNESS

*** THE SELF

* (2011 fall) mit-6-868j-the-society-of-mind

*** 1. Introduction

***** k-line

      - minsky -
        how higher knowledge is represented in brain ?
        maybe k-line ?

        biologists do not think in this way, but :

        - you can not look for something,
          until you have the idea of it.

        - x -
          maybe the idea of k-line can be used in proof search

      - why programming is a good medium
        for expressing poorly understood
        and sloppily-formulated ideas ?

      - There is a popular, widespread belief
        that computers can do only what they are programmed to do.
        This false belief is based on
        a confusion between form and content.

        A rigid grammar need not make
        for precision in describing processes.
        The programmer must be very precise
        in following the computer grammar,
        but the content he wants to be expressed remains free.

        The grammar is rigid
        because of the programmer who uses it,
        not because of the computer.
        The programmer does not even have to
        be exact in his own ideas
        - he may have a range of
          acceptable computer answers in mind
          and may be content if the computer's answers
          do not step out of this range.

        The programmer does not have to fixate the computer
        with particular processes.
        In a range of uncertainty
        he may ask the computer to generate new procedures,
        or he may recommend rules of selection
        and give the computer advice
        about which choices to make.
        - x -
          this is specially true
          when thinking about proof search

        Thus, computers do not have to be
        programmed with extremely clear and precise formulations
        of what is to be executed, or how to do it.

*** 2. Falling In Love-6AS48fTXBBs.mkv
*** 3. Cognitive Architectures-2KbvJ3iapbc.mkv
*** 4. Question and Answer Session 1-LuJFPVY1Nzo.mp4
*** 5. From Panic to Suffering-AO7F0n2Dclc.mp4
*** 6. Layers of Mental Activities.mp4
*** 7. Layered Knowledge Representations.mp4
*** 8. Question and Answer Session 2.mp4
*** 9. Common Sense.mp4
*** 10. Question and Answer Session 3.mp4
*** 11. Mind vs. Brain: Confessions of a Defector.mp4
*** 12. Question and Answer Session 4.mp4
*** 13. Closing Thoughts.mp4
