#+title: marvin minsky

* [note]

  - 對 conscious 一詞的使用需要分類
    正如 aristotle 在 category 中分類 be 一詞的使用一樣
    類型系統可以幫助我們避免犯錯

* the society of mind

*** 1 prologue

***** intro

***** 1.1 the agents of the mind

***** 1.4 the world of blocks

      - 看似是常識的事情其實是我們在幼年習得的
        只是我們如今已經忘記了學習的過程

      - 如此看來
        在 reid 和 hume 之間
        我們更應該學習 hume 的觀點

      - 利用 hume 的觀點
        我們也許可以建立理論和模型來模擬人腦工作
        就這種目的而言 reid 的觀點可能完全沒有用

***** 1.5 common sense

      - common sense is not a simple thing.
        Insteod, it is an immense society
        of hard-earned practical ideas
        of multitudes of life-learned rules and exceptions,
        dispositions and tendencies, balances and checks.

***** 1.6 agents and agencies

*** 2 wholes and parts

***** 2.1 components and connections

      - you couldn't predict what would happen in a human community
        from knowing only what each separate individual can do;
        you must also know how they are organized
        -- that is, who talks to whom.

      - And it's the same for understanding
        any large and complex thing.
        First, we must know how each separate part works.
        Second, we must know how each part interacts
        with those to which it is connected.
        And third, we have to understand
        how all these local interactions combine
        to accomplish what that system does
        -- as seen from the outside.

      - x -
        當提到社會的權力結構時
        只強調一個樹狀結構是消極的
        因爲這樣的視角 使人不再能意識到新的組織方式之可能

      - x -
        所謂積極 即能促進行動
        所謂消極 即能阻礙行動

      - k -
        一個社會中的人
        完善自己個人的能力是不夠的
        他必須積極地與人交流
        他需要有一個羣體 能讓他立足其中 與人分享 並相互鼓勵
        這樣他才能融入到社會的生機中去

        羣體的各種組織方式 都有不少不足之處
        但是他要積極地面對這些問題
        因爲幸福與快樂只有在分享中才有生機

***** 2.2 novelists and reductionist

***** 2.3 parts and wholes

      - ><

* THE EMOTION MACHINE

*** INTRODUCTION

    - x -
      在寫程序解決問題的時候
      [比如 proof search 這類問題]
      如果程序有多種解決同一個問題的方法
      並且能在一個方法遇到困難時切換另一個方法
      並且還能根據結果和效率批判各種解法的有效性
      那麼就像是智能了

    - Ch1. We are born with many mental resources.
      Ch2. We learn more from interacting with others.
      Ch3. Emotions are different Ways to Think.
      Ch4. We learn to think about our recent thoughts.
      Ch5. We learn to think on multiple levels.
      Ch6. We accumulate huge stores of commonsense knowledge.
      Ch7. We switch among different Ways to Think.
      Ch8. We find multiple ways to represent things.
      Ch9. We build multiple models ofourselves.

*** FALLING IN LOVE

*** ATTACHMENTS AND GOALS

*** FROM PAIN TO SUFFERING

*** CONSCIOUSNESS

*** LEVELS OF MENTAL ACTIVITIES

*** COMMON SENSE

*** THINKING

*** RESOURCEFULNESS

*** THE SELF
