#+title: p-j-higgins

* presentations-of-groupoids-with-applications (1964)

* categories and groupoids (1971)

*** preface to the reprint

    - the theory of presentations of groups
      generalised easily to presentations of groupoids,
      using generating graphs instead of generating sets.
      [is using a type system]

    - the general philosophy of algebra,
      is the importance of universal properties and word problems.

*** 1 some basic categories

    - [two view points]

      (1) [large]
      morphism as structure-preserving map of concrete category.

      providing general theorems with applications in concrete categories,
      which describe in abstract terms some of the standard constructions
      occurring in many different branches of mathematics.

      theorems of this kind concern :
      - product
      - direct limit
      - adjoint functors
      - monad and algebra of monad
      - universal properties
        functional equations to be solved in concrete models.
      - how to build new groupoids from old ones

      (2) [small]
      category as algebraic structure itself,
      functor as structure-preserving map.

      leading to the consideration of algebraic notions as :
      - congruences [why ?]
      - generators and relations
      - free generated categories or groupoids
      - word problems

      - x -
        如果不是把 n-groupoid 當成拓撲空間
        那麼高維的等價幾乎總是沒有必要的
        很少有地方需要 證明 證明一個等式的兩種不同方式 是等價的
        尤其是對於情形 (1) 來說

    - [concrete category]
      a concrete category is a category
      that is equipped with a faithful functor to the category of sets.
      This functor makes it possible to think of the objects of the category
      as sets with additional structure,
      and of its morphisms as structure-preserving functions.

      faithful functor means that
      it maps different morphisms between the same objects to different functions.
      However, it may map different objects to the same set,
      if this occurs, it will also map different morphisms to the same function.

      a category C may admit several faithful functors into (category set)
      Hence there may be several concrete category structures of the same category C.
      [not a property but a structure]

      - concrete
        (category topology) (category group) (category category)

      - not concrete
        (category homotopy-topology)
        for the morphisms are not actual functions between them,
        but rather classes of functions

    - [some forgetful functors]

      (category groupoid)
      forget we can do inverse -> (category category)
      forget we can do compose -> (category directed-graph)

      (category directed-graph)
      forget about edges -> (category set)

      (category directed-graph)
      forget about vertexes -> (category set)

    - as the theory developing,
      syntax is simplified.

    - directed-graph is intro-ed.
      [for free generated groupoid ?]

    - a sub-structure generated by the image of a morphism
      is emphasised, ><><><

    - x -
      is it fine to define a map by means of its generators ?
      [and checking relations]

*** note 遺忘函子

    - x -
      在討論某個範疇的時候
      先看看通過遺忘函子能夠獲得哪些簡單的範疇
      然後用這些簡單的範疇中的定理和概念來提問

      比如在這裏
      (category set)
      (category directed-graph)
      (category category)
      (category groupoid)

    - k -
      對於高維的代數也可以有類似的敘述方式嗎 ?

    - x -
      ><><><

*** 2 natural equivalence and adjoint functors

    - adjoint functor typically arise from the constructions of universal property.

    - x -
      since every groupoid is equivalent to a family of groups,
      what is not preserved by the equivalence between the two categories ?

*** 3 paths and components

*** 4 free groupoids

*** 5 tree and simplicial groupoids

*** 6 fundamental groupoids of topological spaces

*** 7 limit in categories
