#+title: ronald brown

* note

*** group vs groupoid

    - ronald brown -
      all of the basic theory of the fundamental group obtained a better expression,
      with more powerful theorems and more elegant proofs,
      if expressed in terms of the fundamental groupoid
      of a space X on a set A of base points,
      rather than restricting to the fundamental group on a single base point.
      The immediate problem was to calculate the fundamental group of a space
      which was the union of two subsets with a non connected intersection W.
      Since W had more than one component,
      it was not clear in which component to put the base point.
      A reasonable solution turned out to be to use one point in each component,
      i.e. to use a set of base points.

    - x -
      loop 是可以分解成很多 path 的
      因此 groupoid 描述了更多的細節信息
      這些信息對於發展理論來說可能是必要的

*** n-groupoid theory

    - x -
      when developing n-groupoid theory,
      we can mimic the development of group theory.
      then what is the development of group theory ?

    - k -
      先看表面的現象
      羣論有一個乘法
      而其公理中有
      (1) 封閉性
      (2) 單位元與可逆性
      (3) 結合性

    - x -
      (1) 封閉性
      我們考慮的是 生成子 加 關係 所定義的羣
      同樣 生成子 加 關係 也可以定義高維的代數結構
      此時封閉性是自然的
      (2) 單位元與可逆性
      單位元也是自然的
      可逆性需要考慮相乘的位置
      首先可以用 '相乘的位置'
      來解釋一般的羣論中的乘法與逆元
      爲不同位置的相乘
      然後再推廣到高維
      (3) 結合性
      相乘的結果最終
      與各種可能的相乘的方式無關

    - k -
      羣論本身可以用來描述空間的對稱性
      高維的代數可以用來描述什麼呢 ?

    - x -
      group 描述對稱性
      groupoid 可以看成是描述對稱性 但是加上了類型信息 和 類型檢查

    - [關於正規性]
      從一般的高維乘法看來
      羣論之所以可以被如此簡化
      是因爲線段是規則的圖形
      正如 cube 和 simplex 是 規則的圖形一樣

    - higher dim elements can be used
      to record the proofs of equality
      between elements of one dim lower.

    - x -
      the computation of product of higher algebra,
      is enabled by two kinds of rules,
      (1) same-position-self-gluing
      (2) one-dim higher elements as relations

*** higher homotopy groups are always commutative

    - x -
      by the definition of homotopy group I showed in AT1,
      can I prove higher homotopy groups are always commutative ?

*** 高維代數結構中的乘法

    - 對於高維的乘法 (n ...)
      既然乘法是 '可交換的'
      爲什麼我們還需要相乘的序
      因爲 序 給出指明乘合體中位置的方式

*** interchange law

    - 2 homotopy group (Cech 1932) -> two group structure ->
      interchange law -> one group structure

    - 2 homotopy groupoid -> two groupoid structure ->
      interchange law -> more then one groupoid structure (more non abelian)

*** algebraic inverse to subdivision

    - ronald brown -
      That is, we know how to cut things up,
      but do we have available an algebraic control
      over the way we put them together again ?

* note combinatorial infi-groupoid theory

*** 類比 combinatorial group theory

***** generators and relations

      - x -
        adding types to the generators,
        we get a combinatorial 1-groupoid theory.

***** object group [subgroup structure] of 1-groupoid

      - x -
        about tree
        ><><><

***** 正規子羣與羣同態

      - x -
        在 combinatorial group theory 中
        通過增加 relation 可以得到已有的 g.r.group 的正規子羣
        正規子羣 與 羣同態 之間 有一一對應關係
        對於 combinatorial infi-groupoid theory
        我們可以形成類似的理論嗎 ?

      - k -
        這種現象稱爲 第一同態定理
        groupoid theory 並沒有這種現象
        把 groupoid theory 劃歸爲 group theory
        就能觀察到這個定理的缺失

*** 高階代數的表示論之語言的特點

    1. 需要設計新的語法來描述階元的乘法
       '乘號' 本身應該被高階生成元的邊界結構化

       - 可以用語言學來論述 '不存在良好的高維幾何[代數]語言'
         比如 在 CL 中消去 lambda
         所謂 '消去' 只是轉變了編碼方式
         而不能從本質上簡化語言

       - 幾何體的分類問題可以簡化描述的複雜度

    2. 相乘的條件是有公共邊界
       相乘後公共邊界被消除

    3. 高一階元素是低一階元素之間的關係[等式]

    4. 必須能描述一個元素的邊界的所有位置
       同一個元素就相同的位置自乘則相消

       - 描述粘合方式的語言必定是線性的
         線性的描述方式自然給出指明粘合體中所有位置的方法

*** a critique of eckmann-hilton argument

    - about interchange law.

    - x -
      所謂 eckmann-hilton argument
      與高階乘法的 '交換性'
      應該被視爲一個語言學現象

      首先
      古典理論中對高階乘法的交換性的證明
      用到了連續的 homotopy
      而只是在形式化的處理方式中才需要用到 eckmann-hilton argument

      eckmann-hilton argument 說
      利用如下的條件
      (A x B) o (C x D) = (A o C) * (B o D)
      [即 多種粘合次序能粘合出同一個幾何體]
      就能證明高階乘法的交換性

      但是 這個條件本質上是交換性的另一種表述方式
      考慮一階元素的兩種相乘方式 [>< 此處需要圖示]
      (p * q) 與 ((p rev) * (q rev))
      此時 eckmann-hilton 的條件就變成了
      ((a * b) rev) * ((c * d) rev) =
      ((a rev) * (c rev)) * ((b rev) * (d rev))
      即
      (b rev) * (a rev) * (d rev) * (c rev) =
      (a rev) * (c rev) * (b rev) * (d rev)
      另 c = d = 1 得
      b * a = a * b

      其實 正確的理解方式是
      兩種相乘方式之所以相等 (A x B) = (A o B)
      是因爲它只是就 a 與 b 的兩個不同的公共邊界來相乘
      所得到的將是對同一個幾何體的兩種邊界不同的表述
      這種不同的表示本質上代表相同的幾何體
      因爲兩種相乘方式是 '同位的'
      [比如 (p * p) 不等於 (p * (p rev)) 是因爲 用於相乘的公共邊界不是同位的]
      以這一階幾何體爲邊界的更高階幾何體 將表示這這一階幾何體之間的關係
      這些關係可以重載於這兩種不同的邊界表示方式之上

    - k -
      可以看出
      數學語言之缺陷在於
      它總是被侷限在語法上
      而沒有考慮語法與語義之間的關係

*** a critique of fibration in hott

    - x -
      hott 對乘法的處理方式與 AT 的直覺相左
      並且與對 fiber-space 的對稱處理相衝突

      對稱的處理方式在於
      同一個幾何體的不同邊界表示 本質上還要被認爲是同一個幾何體
      比如 (m : ((p1 * p2) = q)) 與 (m : (p2 = ((p1 rev) * q)))
      而 hott 中處理它們的方式 講給幾何體加上多餘的信息
      [考慮 一個邊在面中漸進到另一個邊]
      這種多餘的信息 將使兩者不能視爲本質等同

      所得到的 tp 將使得
      一個 m 在同一個 fiber 中有兩種不同的像
      同一個 m 沿着不同的推進方式 將被映爲同一個 fiber 中的兩個面
      [在只考慮 globe 的情形下 是體現不出來的]

    - x -
      [bridges 與 logic programming]
      在已有的形式處理中 不好的一點是 totel-space 是 fiber 的不交並
      因爲其不交 所以當要把一個 path lift 到 totel-space 中時
      f : ((x : A) -> x P)
      ~ : ((p : (x = y)) -> (x f = y f))
      而後面的這個 (x f = y f) 是不可能的
      即 兩個不同空間中的點沒有路

      已有的形式處理方式
      可以在 '不交並' 的前提下
      巧妙地給出這種 path 的定義

      而我想用 bridge 把 fiber 連起來
      這樣就不能說是 '不交並' 了

      可逆性可以用 logic language 來處理
      一個 path 引出兩個 fiber 之間的 等價
      可以試着使用一個 relation 來處理這個等價
      比如
      p(x, y) 用來 unify x, y 的同時 還能返回一個邊
      m(p1, p2, p3) 做 unify 的同時 也能返回一個面

* from groups to groupoids: a brief survey (1987)

*** 1 intro

    - Brandt's definition of groupoid arose out of his work on
      generalising to quaternary quadratic
      forms a composition of binary quadratic forms due to Gauss.

*** 2 examples

    - In the theory of groups,
      two motivating examples are symmetry groups, that is, groups of automorphisms,
      and groups derived from paths in a space, that is, the Poincaré or fundamental groups.
      We find that these examples generalise
      to give ‘symmetry groupoids’ and fundamental groupoids.

    - example 1
      a disjoint union of groups.

    - example 2
      an equivalence relation R on X,
      with (x, y) (y, z) = (x, z) as groupoid product.

      for examples, coarse groupoid and fine groupoid.

      This consideration of an equivalence relation as a groupoid
      also suggests the utility of groupoids for studying quotienting constructions,
      particularly in cases where the quotient set X/R
      cannot carry the appropriate structure.

    - example 3
      group G act on the set X,
      (x, g) : (X, G) as element in the groupoid.

    - example 4
      study a geometry [a structure] by means of its group of automorphisms.
      [Klein’s Erlangen Programme]
      generalised to
      study a family of structures by means of its actions typed by the structures.
      for example, in fiber-space with projection (p : (E -> B)),
      where transports [iso between fibers] are typed by points in B.
      [so called symmetry groupoid of fiber-space]

    - example 5
      fundamental group of space
      - i.e. loop space
      generalised to
      fundamental groupoid of space
      - i.e. loop space with a set A of base points
        or just the whole path space when the set A is the space itself

*** 3 applications of the fundamental groupoid

    - to use groupoid to express van kampen theory in a better way.

    - orbit space

*** 4 the category of groupoids

    - the notation of object group or vertex group of groupoid.

    - The classification of groupoids up to isomorphism
      was early on found to be reducible to the classification of groups.

    - One of the features of groupoids
      is the variety of types of homomorphisms.
      For groups, we have basically monomorphisms, epimorphisms, isomorphisms.

      For groupoid homomorphisms
      we have similar terminology to that for functors,
      namely faithful, full, representative,
      and also a variety of other types
      such as quotient, universal, covering, fibration, and discrete kernel.

      It may disturb people to learn that
      the first isomorphism theorem fails for groupoids.
      But in fact these apparent difficulties and complications
      lead to a theory richer than that of groups, and with wider uses.

    - the coarse groupoid (X * X), where X = {0, 1}, denoted as J.

      - give element 'a' of groupoid G,
        we have unique homomorphism (f : J -> G) of groupoids
        such that f(i) = a.
        thus, J plays for groupoids the role
        that the infinite cyclic group Z plays for groups.

      - J with the two inclusions {0} -> J {1} -> J,
        it has properties analogous to the unit interval
        in the homotopy theory of spaces.
        So it is easy to write down a homotopy theory for groupoids,
        with notions of homotopy equivalence,
        covering morphism, fibration,
        exact sequence, and so on.
        [homotopy theory is enabled by unit interval]

    - Indeed the construction of covering spaces
      is nicely expressed in terms of the problem of
      topologising the object set of a covering groupoid G
      of the fundamental groupoid.

    - Fibrations of groupoids occur naturally
      in a number of ways in group or group action theory;
      the resulting exact sequences give results
      on the original group theoretic situation.

*** 5 some applications

*** 6 the classifying space of a topological groupoid

    - about the nerve of a small category [groupoid].

*** 7 structured groupoids

    - groupoid object G internal to a category C.
      [just as simplicial object]

*** 8 conclusion

    - it seems that the transition from group to groupoid
      often leads to a more thoroughly non-abelian theory.

      This is seen in the von Neumann algebra of a measured groupoid,
      which has also been thought to be appropriate for quantisation in physics

      - [90]
        D. KASTLER, ‘On A. Connes’ non-commutative integration theory’,
        Commun. Math. Phys. 85 (1982) 99-120.

    - groupoid methods replace principal bundles

      - [99]
        K. MACKENZIE, Lie groupoids and Lie algebroids in differential geometry
        (Cambridge University Press, 1987).

    - higher dimensional groupoids have led in homotopy theory
      to new results and calculations
      which seem unobtainable by other means.

      the ideas of ‘higher order symmetry’,
      or ‘symmetry of symmetries’ and methods of calculation for these.

      - [19]
        R. BROWN,
        ‘Coproducts of crossed P-modules:
        applications to second homotopy groups and to the homology of groups’,
        Topology 23 (1984) 337-345.

      - [33]
        R. BROWN and J.-L. LoDAY,
        ‘Van Kampen theorems for diagrams of spaces’,
        Topology, 26 (1987) 311-334.

      - [34]
        R. BROWN and J.-L. LODAy,
        ‘Homotopica1 excision and Hurewicz theorems for n-cubes of spaces’,
        Proc. London Math. Soc.,(3) 54 (1987) 176-192.

      - [57]
        G. J. ELLIS and R. STElNER,
        ‘Higher dimensional crossed modules and the homotopy groups of (n + 1)-ads’,
        J. Pure Appl. Algebra, 46 (2-3) (1987) 117–136.

    - the relationship of covering spaces to Galois theory
      and problems of descent in algebraic geometry.

      - [103]
        A. R. MAGID,
        ‘Covering spaces of algebraic curves’,
        Amer. Math. Monthly 83 (1976) 614-621.

* topology and groupoids (1968 1988 2006)

*** preface 2

    - W. S. Massey -
      this method of characterising various mathematical structures
      as solutions to universal mapping problems
      seems to be one of the truly unifying mathematical principles.

    - brown -
      is it possible to rewrite homotopy theory,
      substituting the word groupoid for the word group,
      and making other consequential changes ?
      If this is done, is the result more pleasing ?

*** preface 3

    - geometry -> underlying processes ->
      algebra -> algorithms -> computation

    - [about universal property]
      analogies are not between objects themselves,
      but between the relations between objects.

*** chapter 1 some topology on the real line

***** note 拓撲公理

      - x -
        分析的算數化 -> 拓撲公理

***** 1.1 Neighbourhoods in R

      - given (a : R), we say P holds near a, or is valid near a,
        if P holds for all points in some neighbourhood of a.

        There is no notion of absolute nearness,
        that is, of a point x being ‘near a’.

      - a set A determines the set of points of which A is a neighbourhood;
        this set is called the interior of A, and is written Int A.

***** 1.2 continuity

      - The function f is continuous at a
        if for every neighbourhood N of f(a),
        f^{−1}(N) is a neighbourhood of a.

***** note 關於實數理論

      - x -
        我們幾乎沒法按照這種連續性的定義
        來證明一個被計算機實現的函數的連續性

      - k -
        我想在下這個論斷之前
        首先我們要知道 '實數上的函數' 是如何被實現的

      - x -
        實現實數函數的方式是
        (1) 潛在無窮精確的有理數域上的函數
        (2) 有限精度的實值函數 這就涉及到了誤差與數值分析
        我想
        當用集合論的語言來定義
        函數的連續性和可微性等等性質時
        就根本沒法用定義來驗證如此實現的函數的這些性質了

      - k -
        這就可以說成是 '不具構造性' 嗎 ?
        '構造性' 就被定義爲 '可用計算機實現' ?

      - x -
        我想這些關於實數的理論
        其應用都將體現在數值分析中
        而數值分析中的概念與方法又需要用一個程序語言來實現
        考慮實現這些概念與方法時所使用的類型系統
        可能就能讓我們獲得一個 '具有現實意義的' 實數理論

*** chapter 2 topological spaces

*** ><><>< chapter 3 connected spaces, compact spaces

***** 3.1 the sum of topological spaces

***** 3.2 connected spaces

***** 3.3 components and locally connected spaces

***** 3.4 path-connectedness

***** 3.5 compactness

***** 3.6 further properties of compactness

*** chapter 4 identification spaces and cell complexes

    - a generalision of equivalence class,
      defined by universal property.

    - local consideration -- what happens in a given space.
      global consideration -- the relation of this space to other spaces.

    - [cell complexes]
      there are two useful ways of thinking about cell complexes
      (a) constructive [cell complex]
      (b) descriptive [complex structure]

*** chapter 5 projective and other spaces

***** 5.1 quaternions

***** 5.2 normed vector spaces again

***** 5.3 projective spaces

***** 5.4 isometries of inner product spaces

***** 5.5 simplicial complexes

***** 5.6 bases and sub-bases for open sets; initial topologies

***** 5.7 joins

***** 5.8 the smash product

***** 5.9 spaces of functions, and the compact-open topology

*** chapter 6 the fundamental groupoid

***** note

      - the modelling of the geometry of pushouts of spaces
        by pushouts of groupoids.

      - analogies between topology and algebra
        are described by the language of category theory.

      - analogies between relations instead of objects.

***** 6.1 categories

      - from equations
        (f g = 1) and (g f = 1)
        we cannot deduce (f g = g f)
        since 1 may denote different identities in each equation

      - Here we already see the double use of the idea of category.

        (a) General statements about topological spaces and continuous functions
        can in many cases be regarded as statements of an algebraic character
        about the category Top, and this is often convenient,
        particularly when it brings out analogies between constructions
        for topological spaces and constructions for other mathematical objects.

        (b) The category PX of paths on X
        is regarded as an algebraic object in its own right,
        as much worthy of study as an example of a category
        as are examples of groups, rings or fields.

      - if f has a left and a right inverse,
        then f has an unique two-sided inverse.
        Such a morphism f is called invertible, or an isomorphism.

***** 6.2 construction of the fundamental groupoid

      - a functor from (category path-space) to (category groupoid)
        where equivalence class is defined by homotopy rel end points.

        | (path-space X)       | (groupoid X)       |
        | ((path-space X) x y) | ((groupoid X) x y) |

      - tree groupoid := ((number ((groupoid X) x y)) = 1) (for-all x y : G)
        space X is 1-connected := (groupoid X) is tree groupoid
        for example, a convex subset of a normed vector space is 1-connected.

        X and (groupoid X) are simple-connected :=
        path-component of X is 1-connected
        thus, any two paths in X with the same end points are equivalent.

        A groupoid G is called simply-connected
        if (for-all x y : G) (G x y) has not more than one element

      - proof of non-equivalent between two paths
        involves techniques for computing the fundamental groupoid.
        [or should we say this reversely ?]

***** 6.3 properties of groupoids

      - the object groups of a connected groupoid are all isomorphic.

***** 6.4 functors and morphisms of groupoids

      - groupoid functor from (category topology) to (category groupoid)
        respect product and sum [or say, coproduct or union].

***** 6.5 homotopies

      - this section defines
        homotopy between two functions,
        and homotopy equivalence between two spaces.

      - A map is inessential if it is homotopic to a constant map,
        otherwise it is essential.
        [essential is a property of maps]

        A space is contractible if its identity map is essential.
        [contractible is a property of spaces]

      - to proof two maps of type (S1 -> (S1 * S1)) are not homotopic,
        we need to know that S1 is not simply-connected.

***** 6.6 coproducts and pushouts

      - a pushout is a square generated by a angle.

***** 6.7 the fundamental groupoid of a union of spaces

      - x -
        I can generalise van kampen theory to n-dim by the language of AT1.

*** chapter 7 cofibrations

***** 7.1 the track groupoid

      - the so called track groupoid
        is the groupoid of mapping-space (X -> Y)
        where objects are (f : (X -> Y))
        and arrows [morphisms] are (h : ((X * I) -> Y))

        to get groupoid from path-space,
        we use maps of type ((X * I * I) -> Y) as equivalent relation.

***** 7.2 fibrations of groupoids

***** 7.3 examples

***** 7.4 the gluing theorem for homotopy equivalences of closed unions

***** 7.5 the homotopy type of adjunction spaces

***** 7.6 the cellular approximation theorem

*** chapter 8 some combinatorial groupoid theory

*** chapter 9 computation of the fundamental groupoid

*** chapter 10 covering spaces, covering groupoids

*** chapter 11 orbit spaces, orbit groupoids

*** chapter 12 conclusion

*** appendix a functions, cardinality, universal properties

***** a.4 universal properties

      - product

      - sum

      - equivalent class
        topological identification

      - pushout
        adjunction space [for topological spaces]
        van kampen theory [for groupoid]

* nonabelian algebraic topology (2011)

*** info

    - filtered spaces, crossed complexes, cubical homotopy groupoids

*** prerequisites and reading plan

    - the use in algebraic topology of algebraic colimit arguments
      rather than exact sequences that is a key feature of this book.

*** historical context diagram

    - The theory of groupoids and categories
      gets more complicated in higher dimensions
      basically because of the complexity of the basic geometric objects.
      Thus in dimension 2 we might take as basic objects
      the 2-disk, 2-globe, 2-simplex, or 2-cube.

      | 2-disks | crossed modules     |
      | 2-cubes | double groupoids    |
      | n-disks | crossed complexes   |
      | n-cubes | cubical w-groupoids |

      the cubical model leads to conjectures and then theorems,
      partly through the ease of expressing multiple compositions.

      the disk model leads to calculations,
      and clear relations to classical work.

*** part i 1- and 2-dimensional results
