#+title: schopenhauer

* essays of schopenhauer

*** counsels and maxims

***** chapter i: general rules

******* 1

        - aristotle -
          not pleasure, but freedom from pain,
          is what the wise man will aim at.

        - happiness is negative.

          pleasure is only the negation of pain,
          and pain is the positive element in life.

        - when the will meets resistance, it is in pain.
          the will is satisfied, when it meets no resistance.

        - what arrests the will is positive,
          the will is pleasure when freeing from such arresting,
          thus pleasure is negative,
          thus when happiness defined by pleasure and satisfaction,
          it is also negative.

        - to live happily only means to live less unhappily.

        - life is given us, not to be enjoyed,
          but to be overcome, to be got over.

        - aristotle bids us direct our aim,
          not toward securing what is pleasurable and agreeable in life,
          but toward avoiding, as far as possible, its innumerable evils.

        - there is some wisdom in taking a gloomy view,
          in looking upon the world as a kind of Hell,
          and in confining one’s efforts to securing a little room
          that shall not be exposed to the fire.

        - to purchase pleasure at the cost of pain,
          or even at the risk of incurring it;
          to do so is to pay what is positive and real,
          for what is negative and illusory.

        - the lost state of painlessness, the paradise,
          once lost can only be looked with regret.

******* 2

        - To estimate a man’s condition in regard to happiness,
          it is necessary to ask, not what things please him,
          but what things trouble him;
          and the more trivial these things are in themselves,
          the happier the man will be.
          To be irritated by trifles,
          a man must be well off;
          for in misfortunes trifles are unfelt.

******* 3

        - In their search for gold,
          the alchemists discovered other things,
          gunpowder, china, medicines, the laws of nature.
          there is a sense in which we are all alchemists.

***** chapter ii: our relation to ourselves

******* 4

        - THE MASON EMPLOYED on the building of a house
          may be quite ignorant of its general design;
          or at any rate, he may not keep it constantly in mind.
          So it is with man: in working through the days and hours of his life,
          he takes little thought of its character as a whole.

***** chapter iii: our relation to others

******* 21

***** chapter iv: worldly fortune.—section

******* 47

***** chapter v: the ages of life

*** on authorship and style

*** on noise

    - the observation of each thing preceding the
      idea one forms of it.

      that narrow ideas precede broader.

      when this order is not followed,
      imperfect and subsequently wrong ideas spring up.

    - because those been observed by one are so complicated,
      abstract ideas from observations and experience is necessary.

      but, one can not only learn abstract ideas from others,
      one must form abstract ideas after his own observations.

      no idea should be formed
      but what has come through the medium of observations.

      following this rule,
      mind will be thorough and clear.

    - classifing ones ideas by observations,
      is helpful to remove bad ideas.

    - people hace tendency of being satisfied with words
      instead of wishing to understand things.

    - The most necessary thing for the practical man is the attain-
      ment of an exact and thorough knowledge of what is really
      going on in the world; 
      
      but it is also the most irksome.


*** on reading and books

*** metaphysics of love
