#+title: 赫伯特 塞弗特 / Herbert Seifert

* (1934) (seifert and threlfall) lehrbuchder topologie [a textbook of topology] [拓撲學教程]

*** 1 例子 / illustrative material

***** 1 拓撲學的基本問題 / the principal problem of topology

      - 拓撲學的研究對象是幾何圖形
        所研究的幾何圖形的性質 是其在拓撲映射下不變的性質

        所謂 拓撲映射
        就是 連續的一一映射 並且要求其逆映射也是連續的

        所謂 幾何圖形
        是三維或者更高維空間之中的點集

        - x -
          在描述點集時
          我們可以侷限於如下的方法
          幾何圖形 被分爲一片一片的
          對其中的每一片
          我們給以其參數表示
          片與片之間的關係需要被加以限定
          限定方式可能多種多樣
          因此具體如何限定
          先暫且不談

      - 連續函數只需要定義於幾何圖形之中的點
        而不需要定義於幾何圖形所在的整個空間中的所有點

      - 在拓撲映射下不變的性質
        稱爲拓撲性質

      - 兩個圖形
        如果可以被某個拓撲映射變換爲另一個
        就稱這兩個圖形同胚

      - 如果在直覺上
        一個圖形經過扭曲和形變可以變爲另一個
        那麼二者就是同胚的

      - 想要發現很多很多同胚的圖形很容易
        然是想要證明兩個圖形不同胚則很難

      - 正如全等的圖形在歐氏幾何中被認爲是沒有本質上的區別的
        同胚的圖形在拓撲學中也被認爲是沒有本質上的區別的

        兩個全等的圖形總是可以通過一個整個空間的疊合變換而被重疊
        但是 可能沒有整個空間的同胚變換來重疊兩個同胚的圖形

        比如
        在三維空間中
        結 與 圈 同胚
        不經扭曲的閉合的帶 與 莫比烏斯帶 同胚
        但是這些同胚都不能擴展到整個空間到自身的拓撲映射

        然而
        當把這些圖形嵌入在四維空間中時
        這些同胚卻又可以擴展到整個空間到自身的拓撲映射了

        如此更可以看出 同胚 這個等價關係
        是就圖形的點而言的
        而不是就圖形所在的空間而言的

      - 因此我們必須區分兩種拓撲性質
        一種是內蘊於圖形本身的拓撲性質
        另一種拓撲性質 是關於圖形如何被放置於外在的空間之中的
        後一種拓撲性質 在外在空間的拓撲映射下不變

        在觀察圖形與外在空間的關係時
        所得到的一些差異
        在考慮內蘊的拓撲時
        可能就不復存在了

      - 這裏所區分的 內蘊性質與外在性質
        在微分幾何中同樣也會出現
        三維空間中曲面的內蘊度量性質由其第一基本形式決定 [first fundamental form]
        而外在的度量性質由其第二基本形式決定 [second fundamental form]

      - 拓撲學的基本問題是
        判斷兩個圖形是否同胚
        並且分類列舉所有不同胚的圖形

        儘管人們發展出了很多理論來處理歐氏空間的任意子空間
        但是我們將限制我們討論的對象
        以避免集合論所帶來的困難

        我們首先限制我們的研究對象於
        布勞威爾[Brouwer] 所引入的 復形[complex]
        然後進一步侷限於 流形[manifold]

      - 復形之有別於任意點集所構成的圖形
        在於它們可以被 三角化 [或者說單形化]

        與其說對一個已有的空間進行三角化
        也可以說是利用單形來構造復形
        這後一種構造是不依賴於外在空間而內蘊的

        - x -
          因此 作者在這裏考慮的是 單純復形[simplicial complex]

      - 可三角化 這個性質
        將爲我們排除點集拓撲中的很多病態情形

        儘管復形的拓撲學被戲稱爲 '橡皮糖拓撲學'
        但是其實經過這樣的限制之後
        我們恰恰可以把精力集中於具有更強幾何意義的研究對象

      - 在嘗試研究拓撲學的基本問題的過程中
        人們找到了很多關於復形的拓撲不變量
        利用這些不變量 我們可以區分不同胚的復形

        其中最重要的兩個不變量
        是復形的同調羣與基本羣
        這將是我們研究的核心

      - 然而我們現在卻要試試
        在不利用這兩個不變量的情形下
        來研究研究拓撲學的基本問題

        - x -
          因此我們目前的主要工具就是直覺與想象

        首先我們問
        不同胚的閉曲面都由哪些 ?

***** 2 閉曲面 / closed surfaces

      - 我們可以通過將多邊形的邊粘合在一起來構造曲面
        這個多邊形稱爲 基本多邊形[fundamental polygon]
        由此而構造的曲面的所有內蘊拓撲性質
        爲多變形的粘合方式所完全確定

        然而此時
        空間的度量是不確定的
        因此曲面的面積是不確定的
        曲面嵌入外部空間的方式也是不確定的
        曲面的拓撲學並不關心這些性質

      - ><

      - 我們還不確定如上列出的閉曲面代表了所有的閉曲面
        之後我們將利用正規化算法來證明
        所有的閉曲面[二維閉流形] 都可以被化爲如上所列出的一種 [38 小節]

        其次
        我們還需要證明如上生成的閉曲面相互不同胚
        這需要先明白同調羣和同倫羣之類的代數不變量才行
        [39 小節]

***** 3 同痕 同倫 同調 / isotopy, homotopy, homology

      - 證明流形之不同胚 就是分類流形
        我們的方式是形成不變量
        而形成不變量的方式是
        去分類低維圖形到這些流形之中的映射

      - 首先我們處理的是閉曲面
        首先考慮的映射是 曲線到曲面的映射

      - ><

***** 4 高維流形 / higher dimensional manifolds

      - ><

*** 2 simplicial complexes

***** 5 鄰域空間 / neighborhood spaces

***** 6 映射 / mappings

***** 7 歐氏空間中的點集 / point sets in euclidean spaces

***** 8 等價空間 / identification spaces

***** 9 n-單形 / n-simplexes

***** 10 單純複形 / simplicial complexes

***** 11 單純複形的型式 / the schema of a simplicial complex

      - [strict combinatorial topology]
        element of set as vertex,
        distinguished subset as simplex.

***** 12 finite, pure, homogeneous complexes

***** 13 normal subdivision

***** 14 examples of complexes

*** 3 homology groups

***** intro

      - The considerations in this chapter are purely combinatorial.
        No use is made of the concepts of neighborhood or continuity.

***** 15 鏈 / chains

***** 16 邊界 閉鏈 / boundary, closed chains

***** 17 同調鏈 / homologous chains

***** 18 同調羣 / homology groups

***** 19 computation of the homology groups in simple cases

***** 20 homologies with division

***** 21 computation of homology groups from the incidence matrices

***** 22 block chains

***** 23 chains mod 2, connectivity numbers, euler's formula

***** 24 pseudomanifolds and orientability

*** 4 simplicial approximations

***** 25 singular simplexes

***** 26 singular chains

***** 27 singular homology groups

***** 28 the approximation theorem, invariance of simplicial homology groups

***** 29 prisms in euclidean spaces

***** 30 proof of the approximation theorem

***** 31 deformation and simplicial approximation of mappings

*** 5 local properties

***** 32 homology groups of a complex at a point

***** 33 invariance of dimension

***** 34 invariance of the purity of a complex

***** 35 invariance of boundary

***** 36 invariance of pseudomanifolds and of orientability

*** 6 surface topology

***** intro

      - The principal problem of topology,
        the homeomorphism problem,
        can be solved in dimension 2,
        using methods which cannot be generalized to higher dimensions.

        For this reason we shall develop surface topology
        independently of our previous results,
        which were valid for arbitrary dimension.

        We shall start with polygons,
        instead of with a simplicial complex,
        and we shall construct closed polyhedral surfaces
        by identifying sides of polygons.

***** 37 closed surfaces

      - [manifold-checker]
        We first devote our attention only to systems of polygons
        for which the total number of sides is even
        and each side is paired with exactly one otherside
        by the topological mapping.

      - [topological feeling [neighborhood space]]
        In the system of polygons,
        points which map into one another
        are to be considered equivalent
        in the sense that
        points in a neighborhood space are equivalent.

      - [combinatorial natural of a system of polygons]
        We can then recognize the following classes of equivalent points
        in a system of polygons :
        - an inner point of a polygon is equivalent only to itself;
        - an inner point of a polygonal side
          is equivalent to exactly one other point;
        - a vertex may be equivalent to one, several, or even no other points.

      - [connectedness condition]

      - system of polygons -> closed surfaces

      - In the treatment which follows,
        our interest shall be not in the particular system of polygons
        but, rather, in the surface which it determines.

        We now set ourselves the task of discovering
        when two systems of polygons determine the same surface,
        that is, finding when the polyhedral surfaces
        produced by the identification of equivalent points
        are different polygonal decompositions of the same surface.

        [we solve this by normalization]

      - [orientation]
        We now orient the polygonal sides.
        That is, we choose one of the two boundary points of each side
        as initial point
        and the other as endpoint of the side.

        - x -
          such orientation is nothing but maintain the information
          of different positions in the boundary of a n-disk.

        - k -
          but a polygon only has two orientations.

          while so much information are maintained,
          are they really the information about orientation ?

      - The orientation of the polygon
        will determine a sense of traversal of the boundary,
        that is, a cyclic ordering of the sides.

        [is this the same for polyhedron ?]

***** 38 transformation to normal form

******* step 1: one fundamental polygon

******* step 2: side cancellation

******* step 3: transformation to a polyhedral surface having a single vertex

******* step 4: cross-cap normalization

******* step 5: handle normalization

******* step 6: transformation of the handles into cross-caps

***** 39 types of normal form: the principal theorem

***** 40 surfaces with boundary

***** 41 homology groups of surfaces

*** 7 the fundamental group

***** 42 the fundamental group

***** 43 examples

***** 44 the edge path group of a simplicial complex

***** 45 the edge path group of a surface complex

***** 46 generators and relations

***** 47 edge complexes and closed surfaces

***** 48 the fundamental and homology groups

***** 49 free deformation of closed paths

***** 50 fundamental group and deformation of mappings

***** 51 the fundamental group at a point

***** 52 the fundamental group of a composite complex

*** 8 covering complexes

***** intro

      - ><

***** 53 unbranched covering complexes

***** 54 base path and covering path

***** 55 coverings and subgroups of the fundamental group

***** 56 universal coverings

***** 57 regular coverings

***** 58 the monodromy group

*** 9 3-dimensional manifolds

***** 59 general principles

***** 60 representation by a polyhedron

      - [full polyhedron]
        full (solid) polyhedron is defined as the following,
        a closed 3-ball (or a topological image of a closed 3-ball)
        whose boundary been divided into polygons
        so that the following conditions are satisfied :
        1. each polygon is at least a 2-gon.
        2. each point of boundary belongs to at least one polygon.
        3. two polygons are either disjoint
           or have certain common edges or vertices.

        for example :
        - solid dodecahedron.
        - a closed 3-ball
          whose boundary sphere has been decomposed into two hemispheres
          by a great circle also becomes a full polyhedron
          when one subdivides the great circle by two or more vertices.

      - x -
        使用三角形
        也許可以大大簡化描述二階代數時 所需語言的語法之複雜度

        當考慮 polyhedron 所構造的三維流形時
        manifold-checker 很簡單
        就是 euler number 爲 0

        現在要問的是
        這個 manifold-checker 對 manifold 的 2-skeleton
        有什麼限制
        [我們已經知道找個 2-skeleton 不能是任意的有限生成羣了]

        知道這些限制之後
        我們就可以試着模仿二階的情形來設計 normalization 算法

        同時也可以試着模仿 Dehn 的算法
        來設計相似的算法
        以判斷二階代數中任意兩個元素是否相等

***** 61 homology groups

***** 62 the fundamental group

***** 63 the heegaard diagram

***** 64 3-dimensional manifolds with boundary

***** 65 construction of 3-dimensional manifolds out of knots

*** 10 n-dimensional manifolds

***** 66 star complexes

***** 67 cell complexes

***** 68 manifolds

***** 69 the poincare duality theorem

***** 70 intersection numbers of cell chains

***** 71 dual bases

***** 72 cellular approximations

***** 73 intersection numbers of singular chains

***** 74 invariance of intersection numbers

***** 75 examples

***** 76 orientability and two-sidedness

***** 77 linking numbers

*** 11 continuous mappings

***** 78 the degree of a mappings

***** 79 a trace formula

***** 80 a fixed point formula

***** 81 applications

*** 12 auxiliary theorems from the theory of groups

***** 82 generators and relations

***** 83 homomorphic mappings and factor groups

***** 84 abelianization of groups

***** 85 free and direct products

***** 86 abelian groups

***** 87 the normal form of integer matrices

* [topology of 3-dimensional fibered spaces]

*** fibered spaces

*** orbit surface

*** fiberings of s3

*** triangulations of fibered spaces

*** drilling and filling (surgery)

*** classes of fibered spaces

*** the orientable fibered spaces

*** the nonorientable fibered spaces

*** covering spaces

*** fundamental groups of fibered spaces

*** fiberings of the 3-sphere (complete list)

*** the fibered poincare spaces

*** constructing poincare spaces from torus knots

*** translation groups of fibered spaces

*** spaces which cannot be fibered

*** appendix: branched coverings
