#+title: combinatorial group theory

* (1966 1976) (wilhelm magnus) combinatorial group theory

*** info

    - presentations of groups in terms of generators and relations

* (1977) (roger lyndon and paul schupp) combinatorial group theory

* (1980 1992) (john stillwell) classical topology and combinatorial group theory

*** info

    - topology is ostensibly the study of arbitrary continuous functions.
      in reality, however, we can comprehend and manipulate
      only functions which relate finite "chunks" of space
      in a simple combinatorial manner,
      and topology originally developed on this basis.

    - x -
      雖然作者在開頭這麼說了
      但是作者在之後的敘述中 還是遵循了拓撲空間那種 算數化的語言
      如下的用詞就是一些徵兆 :
      - neighbourhood
      - local compactness

*** 0 introduction and foundations

***** 0.1 The Fundamental Concepts and Problems ofTopology

******* 0.1.1 The Homeomorphism Problem

        - One may consider a geometric figure to be an arbitrary point set,
          and in fact the homeomorphism problem
          was first stated in this form, by Hurwitz 1897.
          However, this degree of generality
          makes the problem completely intractable,
          for reasons which belong more to set theory than geometry,
          namely the impossibility of describing or enumerating all point sets.

        - x -
          也就是說這種處理問題的方式不具有構造性
          沒法在計算機上用數據結構來實現這個模型
          更沒法用算法來實現就這個模型而敘述的函數

        - For the moment
          we wish to claim that all "natural" geometric figures
          are either simplicial complexes or homeomorphic to them,
          which is just as good for topological purposes.

        - knot complement in R3 is not finitely describable in terms of simplexes.

******* 0.1.2 Continuous Functions, Open and Closed Sets

******* 0.1.3 Examples of Continuous Maps

******* 0.1.4 Identification Spaces

        - x -
          again, glue is handled by quotient-space by the author.
          while in AT1, I handled it by common boundary.

******* 0.1.5 The H-ball and the ^-sphere

******* 0.1.6 Manifolds

        - x -
          這里給出了一個例子來說明
          #+begin_src scheme
          (type space
            (: base (-1 <>))
            (: p (0 base base))
            (: c (1 p p p)))
          #+end_src
          並非是 manifold
          也就是說 group 的 generators 與 relations
          所給出的 underlying-space 並非是 manifold

******* 0.1.7 Bounded Manifolds

        - x -
          既然可以把 manifold 推廣到 bounded manifold
          那麼也沒有什麼理由不把一般的 group 的 underlying-space
          包含到考慮範圍之內
          而所得到的 underlying-space 的差異
          都可以通過 group 的性質來描述

          之前問
          what are the underlying-space and covering-space
          of low order finite groups ?
          現在知道這些就是不是 manifold 的空間了

          之前關於有限生成羣的分類的問題
          二維曲面的分類很簡單 因爲這些曲面是 很特殊的羣的 underlying-space
          而一般的羣的分類很難 對應的 underlying-space 的分類也將很難

          而且之所以我們的討論要限制於
          那些 underlying-space 是 manifold 的羣
          可能就是因爲這種羣的 underlying-space 可以有簡單的嵌入
          從而讓人能夠直觀

          而對一般的羣的 underlying-space 的研究
          其實都是用代數方法來完成的

        - In dimension 2
          we can distinguish manifolds from bounded manifolds
          by the fundamental group (4.2.1 and 5.3.3).

******* 0.1.8 Embedding Problems

        - next to the homeomorphism problem,
          the most important type of topological problem is that of
          distinguishing different embeddings of one figure in another.

        - x -
          這裏的 homeomorphism problem 代數化之後就是空間之間的同倫等價
          即 (~~ A B)
          而後面的的 embedding 問題就是特殊的函數之間的等價
          即 (~ f g)
          其特殊性在於
          證明等價時所用的 (-> (* A I) B) 不能有自交

******* 0.1.9 Homotopy and Isotopy

        - The group properties depend crucially on the fact that
          the curve is not required to be simple at any stage,
          and in fact the deformation may create more singularities
          than were present at the beginning.

          Only then can one introduce a product of closed curves,
          and cancel a closed curve by its inverse.

        - x -
          同倫羣的定義依賴於各階球面的自交的映射

        - isotopy seems to be a more natural notion of deformation,
          but it is not algebraically tractable.
          In the case of simple curves on a 2-manifold
          the situation is saved by a theorem of Baer 1928 (6.2.5)
          which says that simple curves are isotopic
          if and only if they are homotopic.

        - note the difference between

          - isotopy
            the "knotted part" can be shrunk to nothing
            without acquiring asingularity at any stage.

          - ambient-isotopy
            knot theory

        - x -
          在 AT1 中
          應該如何定義上面兩個概念
          如果要求 證明等價時所用的 (-> (* A I) B) 不能有自交
          是否就有了 ambient-isotopy ?

          有可能不行
          因爲 ambient-isotopy 是用 (-> (* B I) B) 定義的

***** 0.2 Simplicial Complexes

******* 0.2.1 Definition and Basic Properties

        - simplicial complex as schema.
          It is a consequence of the triangulation and Hauptvermutung that
          all homeomorphism questions for 2- and 3-manifolds
          reduce to combinatorial questions about schemata.

******* 0.2.2 Orientation

        - in general,
          we interpret the ordered (n + 1)-tuple (P0, ..., Pn+1)
          as an orientation of the n-simplex.

          orientations are equivalent
          if they differ by an even permutation of the vertices,
          so there are in fact two possible orientations,
          - (+ (P0, ..., Pn+1)) which is just (P0, ..., Pn+1)
          - (— (P0, ..., Pn+1)) obtained by
            an odd number of exchanges of vertices.

        - an orientation of an n-complex
          is an assignment of orientations to its simplexes.
          The orientation is coherent
          if n-simplexes which share an (n-1)-dimensional face
          induce opposite orientations in that face.

******* 0.2.3 Realization in Euclidean Space

        - any n-complex can be embedded in R^(2n+1)

******* 0.2.4 Cell Complexes

        - in the last resort,
          one can always view cells and the dividing cells inside them
          as unions of simplexes in a simplicial decomposition.
          The point of considering cell complexes at all
          is to minimize the number of cells,
          which usually helps to shorten computations.

        - x -
          作者有使用 simplicial complex 的傾向

******* 0.2.5 Triangulation and Hauptvermutung

        - The Hauptvermutung (main conjecture) of Steinitz 1908
          states that homeomorphic manifolds are combinatorially homeomorphic.

***** 0.3 The Jordan Curve Theorem

******* 0.3.1 Connectedness and Separation

        - The statement, as a theorem,
          that every simple closed curve in R2
          separates it into two regions (Jordan 1887)
          was important in the history of topology
          as the first moment when an "obvious" fact
          was seen to require proof.

******* 0.3.2 The Polygonal Jordan Curve Theorem

******* 0.3.3 0-graphs

******* 0.3.4 Arcs Across a Polygon

******* 0.3.5 The Jordan Separation Theorem

******* 0.3.6 Arcs in a Polygon

******* 0.3.7 No Simple Arc Separates R2

******* 0.3.8 The Jordan Curve Theorem

******* 0.3.9 The Jordan-Schoenflies Theorem

        - there are topologically distinct embeddings of S2 in R3.

***** 0.4 Algorithms

******* 0.4.1 Algorithmic Problems

******* 0.4.2 Recursively Enumerable Sets

******* 0.4.3 The Diagonal Argument

***** 0.5 Combinatorial Group Theory

******* 0.5.1 The Fundamental Group

******* 0.5.2 Generators, Words, and Relations

******* 0.5.3 Group Presentations

******* 0.5.4 Coset Decomposition, Normal Subgroups

        - a set of elements v < G
          generates a normal subgroup N of G
          #+begin_src scheme
          (-> [(: :g G) (: :v V)]
              [(: [:g :v :g rev] N)
               (: [:g :v rev :g rev] N)])
          #+end_src

        - generating a subgroup by inverse and product,
          generating a normal subgroup also by conjugation.

        - x -
          how about the fact that
          the fundamental group of a covering space of (underlying-space G)
          is a subgroup of G ?

******* 0.5.5 Quotient Groups and Homomorphisms

        - we can get quotient group of a group representation
          by adding new relations.
          [where new relations generates a normal subgroup.]

        - isomorphism = (kernel = id)

******* 0.5.6 Dyck's Theorem (Dyck 1882)
******* 0.5.7 The Word Problem and Cayley Diagrams

        - solution of the word problem for G
          is equivalent to the construction of Cayley diagram of G.

        - x -
          如何等同呢 ?
          用有向圖實現這個 [有可能是無限的] cayley diagram 嗎 ?
          path 到 vertex 的 hash function 嗎 ?

******* 0.5.8 Tietze Transformations

        - Tietze's Theorem.
          Any two finite presentations of a group G
          are convertible into each other
          by a finite sequence of Tietze transformations.

******* 0.5.9 Coset Enumeration

        - x -
          這裏作者給出了不計算法複雜性的傻瓜算法

*** 1 complex analysis and surface topology

***** 1.1 Riemann Surfaces

******* 1.1.1 Introduction

        - A complex function is a map from sphere onto sphere.
          [a covering map.]

        - The general purpose of Riemann surfaces in function theory
          is to provide domains on which
          all algebraic functions become single-valued.

******* 1.1.2 Branched Coverings of the 2-sphere

        - torus can cover sphere.

******* 1.1.3 Connectivity and Genus

        - In general
          the connectivity of a surface
          can be measured
          by the maximu mnumber of disjoint closed curves
          which can be drawn on the surface without separating it.
          [This number is called the genus of the surface.]

        - mobius
          clifford
          klein

******* 1.1.4 Branched Coverings of Higher Dimension

        - for 3-dim covering-space

        - james w. alexander

***** 1.2 Nonorientable Surfaces

******* 1.2.1 The Mobius Band

        - Klein imagines a small oriented circle (the indicatrix)
          placed on the surface,
          then transported round an arbitrary closed curve.

******* 1.2.2 The Projective Plane

******* 1.2.3 The Klein Bottle

******* 1.2.4 Dyck's Classification of Nonorientable Surfaces

        - crosscap + handle = 3 crosscaps.

        - special underlying-space
          | group                   | underlying-space |
          |-------------------------+------------------|
          | general                 | cell-complex     |
          | orientable manifold     | ...              |
          | non-orientable manifold | ...              |
          | manifold with boundary  | ...              |

***** 1.3 The Classification Theorem for Surfaces

******* 1.3.1 Combinatorial Definition of a Surface

        - Dehn and Heegaard (1907)
          define a closed surface to be
          a finite 2-dimensional simplicial complex.

******* 1.3.2 Schemata

        - build surfaces from polygons instead of only using triangles.

******* 1.3.3 Reduction to a Single Polygon with a Single Vertex

        - amalgamate polygons to one polygon.
          reduce the number of vertices of the polygon.

******* 1.3.9 Bounded Surfaces

        - x -
          Dehn's paper about 1-holed sphere, 2-holed sphere, and so on,
          is based on the normalization of surface.

***** 1.4 Covering Surfaces

******* 1.4.1 The Universal Covering Surface

        - covering without branch points
          covering with branch points

******* 1.4.2 The Universal Cover of an Orientable Surface of Genus > 1

******* 1.4.3 Fuchsian Groups

******* 1.4.4 The 2-sheeted Cover of a Nonorientable Surface

*** 2 graphs and free groups

***** 2.1 Realization of Free Groups by Graphs

******* 2.1.1 intro

        - to vividly illustrate the dual view of
          a group as fundamental group of a space
          and automorphism group of a covering-space.

******* 2.1.2 Graphs, Paths, and Trees
******* 2.1.3 The Cay ley Diagram of a Free Group
******* 2.1.4 Solution of the Word Problem for Free Groups
******* 2.1.5 Spanning Trees
******* 2.1.7 Generators for the Fundamental Group
******* 2.1.8 Freeness of the Generators
******* 2.1.9 The Tree as the Universal Covering Graph of the Bouquet of Circles

***** 2.2 Realization of Subgroups

******* 2.2.1 Covering Graphs

        - covering-map can be adequately represented
          by labelling and orienting the edges in covering-space.

******* 2.2.2 The Subgroup Property

        - x -
          帶有類型的代數結構之間的同態
          誘導出去掉類型的代數結構之間的單同態

******* 2.2.3 Realization of an Arbitrary Subgroup of a Free Group

******* 2.2.4 The Nielsen-Schreier Theorem

        - Every subgroup of a free group is free.

******* 2.2.6 Schreier Transversals

******* 2.2.7 Normal Subgroups and Cayley Diagrams

        - (: covering (-> X (underlying-space G)))
          if (fundamental-group X) is normal subgroup of G,
          then (= X (cayley-graph (/ G (fundamental-group X))))

*** 3 foundations for the fundamental group

***** 3.1 The Fundamental Group

******* 3.1.1 IntroductionThe fundamental group

        - Such a definition
          makes the computation of generators and relations routine,
          but it is open to the objection that
          the group is not obviously a topological invariant.

          Since the topologists of the time
          pinned their hopes on the Hauptvermutung,
          they could be satisfied with a proof that
          the fundamental group was invariant under combinatorial homeomorphisms,
          which was supplied by Tietze 1908.

        - The only group which has to be derived from first principles
          is that of the circle;
          all the other fundamental groups we need
          are then obtained by combining the simple technique of
          deformation retraction
          with the Seifert-Van Kampen theorem.

***** 3.2 The Fundamental Group of the Circle

***** 3.3 Deformation Retracts

***** 3.4 The Seifert-Van Kampen Theorem

***** 3.5 Direct Products

*** 4 fundamental groups of complexes

***** 4.1 Poincare's Method for Computing Presentations

***** 4.2 Examples

***** 4.3 Surface Complexes and Subgroup Theorems

*** 5 homology theory and abelianization

***** 5.1 Homology Theory

***** 5.2 The Structure Theorem for Finitely Generated Abelian Groups

***** 5.3 Abelianization

*** 6 curves on surfaces

***** 6.1 Dehn's Algorithm

***** 6.2 Simple Curves on Surfaces

***** 6.3 Simplification of Simple Curves by Homeomorphisms

***** 6.4 The Mapping Class Group of the Torus

*** 7 knots and braids

***** 7.1 Dehn and Schreier's Analysis of the Torus Knot Groups

***** 7.2 Cyclic Coverings

***** 7.3 Braids

*** 8 three-dimensional manifolds

***** 8.1 Open Problems in Three-Dimensional Topology

***** 8.2 Polyhedral Schemata

***** 8.3 Heegaard Splittings

***** 8.4 Surgery

***** 8.5 Branched Coverings

*** 9 unsolvable problems

***** 9.1 Computation

***** 9.2 HNN Extensions

***** 9.3 Unsolvable Problems in Group Theory

***** 9.4 The Homeomorphism Problem

* (1982) (bruce chandler and wilhelm magnus) the history of combinatorial group theory: a case study in the history of ideas

*** info

    - Nearly the entire body of research in the field
      is due to mathematicians who either are still alive
      or who were the teachers or senior colleagues of living mathematicians.
      This makes it possible to supplement the written tradition
      with oral information which is particularly valuable
      when dealing with questions of motivation
      for a particular investigation or of the transfer of ideas.

    - x -
      it seems the tradition of writing hides motivations,
      while the dialog reveals motivations.

      it might also be the authors who fail to convey their motivations
      are not good at their art.

*** Part I The Beginning of Combinatorial Group Theory

***** 1 Introduction to Part I

      - Part I of our book covers the period from 1882 to 1918,
        the end of the first World War.

***** 2 The Foundation: Dyck's Group-Theoretical Studies

      - in Dyck's paper :
        For the further development of the present group theoretical problems
        the analytic (combinatorial) formulation has to replace every geometric description.
        However, the primary geometric interpretation has produced certain viewpoints
        and it is the purpose of the present paper
        to develop both their geometric version and their analytic content.

      - "a geometric concretization (Versinnlichung) of the group G."
        like the theory of fuchsian groups.

        tessellation of the hyperbolic disk

      - Burnside's textbooks.

      - De Siguier used Cantor's set theory
        and coined the term 'semigroup'.

      - What we called Proposition 1
        [there exist free group for a set of generators]
        is then what Dehn called the solution of the word problem for free groups.

      - x -
        當 [像 Dehn 一樣]
        用 模型的實現 與 算法 來理解這些理論時
        某些堂皇的命題就是顯然的事實了

        作者區分了 The existence proof 與 The combinatorial proof
        後者是 構造主義 的

***** 3 The Origin: The Theory of Discontinuous Groups

      - poincare and klein

      - discontinuous action
        discontinuous group acting on space

      - the early theory of discontinuous groups did not stimulate
        the development of the theory of group presentations,
        because the discontinuous groups are not primarily given by presentations.
        They are defined either by a set of generating elements
        which describe circle-preserving conformal self-mappings of the complex plane [geometric]
        or as a set of 2x2 matrices, subject to arithmetic conditions [arithmetic].

***** 4 Motivation: The Fundamental Groups of Topological Spaces

      - poincare -> tietze -> dehn

      - [bib]

        - Birman, J. S.
          Poincare's conjecture and the homeotopy group of a closed, orientable 2-manifold
          1973

        - heinrich tietze
          on the topological invariants of multidimensional manifolds
          1908

      - Tietze's results are motivated by an observation of a specific difficulty
        arising when working with groups which are merely givenby a presentation.

      - Dehn recognized that the difficulties of combinatorial group theory
        start at a much lower level than that of the isomorphism problem as stated by Tietze.

      - [bib]

        - Greendlinger, M, 1960a,
          Dehn's algorithm for the word problem,
          Comm. Pure and Appl.Math.

        - Greendlinger, M., 1960b,
          Dehn's algorithm for the conjugacy and word problems, with applications,
          Comm. Pure and Appl. Math.

***** 5 The Graphical Representation of Groups

      - cayley diagram -> burnside [finite order] -> coxeter [finite order]

      - The point to be made here is that
        this is such an extremely simple definition
        when phrased in topological terms.
        Any possible translation into algebraic terms
        appears to be clumsy and opaque.
        Of course, one may say that
        all that matters about a definition is its precision.
        But this was certainly not Dehn's opinion.
        In a public talk for a nonmathematical academic audience,
        Dehn [1928] explained that the continued growth of mathematics
        requires the continued emergence of new ideas which reduce its complexity.
        He also expressed the hope that
        topology would renew its power through such an injection of new ideas.
        The reader should note the year when this was said.
        Within the following 10 years,
        there appeared monographs on topology by
        Alexandroff and Hopf,
        by Lefshetz, and by Seifert and Threlfall,
        documenting an upsurge in topological research which has not yet abated.

        - Dehn, M, 1928,
          Uber die geistige Eigenart des Mathematikers,
          Frankfurter Universitatsreden No. 27. 25 pp.,
          Universitatsdruckerei Wemer und Winter, Frankfurt am Main.
          Preface and I.5,

***** 6 Precursors of Later Developments

******* note

        - x -
          這章節值得仔細分析
          既然 羣論 可以用於描述諸多現象
          那麼 推廣而得到的 高階代數 是否也能描述這些現象的推廣呢 ?

        - k -
          如果可以的話
          就可以說 羣論 到 高階代數 的推廣是一個成功的推廣了

******* A. Arithmetically Defined Linear Groups in Higher Dimensions

        - siegel

******* B. Arithmetically Defined Linear Groups in Two Dimensions

        - magnus

******* C. Geometric Constructions. Fuchsian Groups

******* D. Braid Groups and Mapping Class Groups

        - hurwitz
          in a fiber space, the fundamental group of the base space
          acts as a group of self-mappings on the fiber.

******* E. Differential Equations, Linear Groups,and Lie Groups

******* F. Finite Groups

***** 7 Summary

      - Group theory started as the theory of groups of transformations,
        i.e., of one-to-one and onto self-mappings of a mathematical object.
        If the object is a finite set, the group appears as a permutation group.
        [Camille Jordan on "substitutions and algebraic equations"]

      - Infinite transformation groups
        became a topic of extensive research at about the same time.
        But this development was initiated not by a fundamental work but by a manifesto.
        [Felix Klein at Erlangen]
        [Sophus Lie]
        a program, according to which
        geometry should be considered from the point of view
        of transformation groups which act on certain spaces.

        for to get the generators of the group of Klein as in combinatorial group theory,
        the concept of generators has to be modified
        in the sense of Lie's "infinitesimal substitutions".

      - the tiling designs or tessellations
        of the euclidean or non-euclidean plane
        with a polygon as the basic tile,
        The generators and their inverses
        simply correspond to the edges of the basic polygonal tile,
        and the defining relations correspond to its vertices.

        this is the dual of the cayley-graph,
        so we have three graphs now,
        (1) underlying-space [classifying-space]
        (2) covering-space [cayley-graph]
        (3) acting-space [dual-cayley-graph]

      - finite group vs infinite group
        for finite group, we have :
        | finite group            | number            |
        | finite simple group     | prime number      |
        | direct product of group | product of number |
        but for infinite group, we do not have such.
x
      - The object on which a group of transformations acts
        has disappeared completely
        if we define a group through a presentation by generators and relations.

        while Poincare's fundamental group
        makes group generators and relations worth study.

      - the theory of representations of groups
        as linear transformations of finite-dimensional vector spaces

        [Frobenius Burnside, and L. E. Dickson]
        [linear groups over finite fields]

      - combinatorial group theory emphasis on algorithms.
        "to find a method of deciding in a finite number of steps"

      - combinatorial group theory
        geometric -> geometric interpretation
        algebraic -> classify and decomposition

***** 8 Modes of Communication. Growth and Distribution of Research in Group Theory

***** 9 Biographical Notes

***** 10 Notes on Terminology and Definitions

      - It is part of the purpose of every historical essay
        to make it easier to go back to the sources for those readers
        who may be interested in doing so.

***** 11 Sources

*** Part II The Emergence of Combinatorial Group Theory as an Independent Field

***** 1 Introduction to Part II

      - This part of our book deals mainly with the developments during the period
        from 1918 to 1945, that is, from the end of World War I
        to the end of World War II.

      - the mapping class group of a surface
        is the group of automorphisms
        of the fundamental group of the surface.

        - x -
          how about mapping-class-group with fixed boundary ?

***** 2 Free Groups and Their Automorphisms

      - Nielsen
        Hopf
        McCool

      - [bib]

        - McCool, J., 1974,
          A presentation of the automorphism group of a free group of finite rank

        - McCool, J. 1975a,
          On Nielsen's presentation of the automorphism group of a free group

        - McCool, J., 1975b,
          Some finitely presented subgroups of the automorphism group of a freegroup

***** 3 The Reidemeister-Schreier Method

***** 4 Free Products and Free Products with Amalgamations

***** 5 One-Relator Groups

***** 6 Metabelian Groups and Related Topics

***** 7 Commutator Calculus and the Lower Central Series

***** 8 Varieties of Groups

***** 9 Topological Properties of Groups and Group Extensions

      - this may be described as
        a method of associating a topological cell complex
        with the group and deriving results about the group from this association.

      - it was shown that
        the association of cell complexes and groups
        leads to a purely algebraicde finition of homology and cohomology groups
        belonging to any given group G which are invariants of G.

***** 10 Notes on Special Groups

***** 11 Postscript: The Impact of Mathematical Logic

***** 12 Modes of Communication

***** 13 Geographical Distribution of Research and Effects of Migration

***** 14 Organization of Knowledge

* (1989) (daniel cohen) combinatorial group theory: a topological approach

*** info

    - the author, daniel cohen, is influenced by
      ralph fox, hanna neumann and roger lyndon.

*** 1 combinatorial group theory

***** 1.1 free groups

***** 1.2 generators and relators

***** 1.3 free products

***** 1.4 pushouts and amalgamated free products

***** 1.5 hnn extensions

*** 2 spaces and their paths

***** 2.1 some point-set topology

***** 2.2 paths and homotopies

*** 3 groupoids

***** 3.1 groupoids

***** 3.2 direct limits

*** 4 the fundamental groupoid and the fundamental group

***** 4.1 the fundamental groupoid and the fundamental group

***** 4.2 van kampen's theorem

***** 4.3 covering spaces

***** 4.4 the circle and the complex plane

***** 4.5 joins and weak joins

*** 5 complexes

***** 5.1 graphs

***** 5.2 complexes and their fundamental groups

***** 5.3 free groups and their automorphisms

***** 5.4 coverings of complexes

***** 5.5 subdivisions

***** 5.6 geometric realisations

*** 6 coverings of spaces and complexes

*** 7 coverings and group theory

*** 8 bass-serre theory

***** 8.1 trees and free groups

***** 8.2 nielsen's method

***** 8.3 graphs of groups

***** 8.4 the structure theorems

***** 8.5 applications of the structure theorems

***** 8.6 construction of trees

*** 9 decision problems

***** 9.1 decision problems in general

***** 9.2 some easy decision problems in groups

***** 9.3 the word problem

***** 9.4 modular machines and unsolvable word problems

***** 9.5 some other unsolvable problems

***** 9.6 higman's embedding theorem

***** 9.7 groups with one relator

*** 10 further topics

***** 10.1 small cancellation theory

***** 10.2 other topics

* (1993) two-dimensional homotopy and combinatorial group theory
