#+title: combinatorial group theory

* (1946 1967) (maurice frechet and kt fan) initiation combinatorial to topology

*** preface

    - x -
      開篇引用 poincare 對 topology theory 的定義
      以 Elementary Geometry, Projective Geometry, Topology 之間的對比爲例子
      強調 質 與 量 之間的對立

*** chapter one. topological generalities

***** 1 Qualitative Geometric Properties

      - x -
        追隨 poincare 的描述
        來強調 質 與 量 之間的對立

***** 2 Coloring Geographical Maps

      - x -
        染色問題在三維中是平凡的
        即 沒有染色數的上限
        因爲對三維空間的分割可能形成非常複雜的相鄰狀態
        或者說在三維空間中 有很靈活的方式來形成多種相鄰狀態

      - k -
        這種因爲維數增加 而使得理論不能類比的情形
        還真是令人擔心呢

      - x -
        這些都是事實
        我們只要描述它就行了

        這裏需要問的是
        這種複雜的相鄰情況
        是否會使得我們很難形成三階代數

      - k -
        knot 所帶來的複雜性 就有些類似

      - x -
        沒錯
        並且這裏還要注意染色問題是就流形而言的
        對於一階流形 只要兩個顏色就夠了
        當不限於流形的時候 染色問題也是平凡的

      - k -
        人們在考慮一階圖形的時候
        不把自己限制於流形 而是考慮有向圖
        但是在二階的時候 一般的 complex 就過於複雜了
        因而人們把自己限制於流形

      - x -
        我想限制與流形還有一個原因
        那就是要給 complex 以幾何
        但是其實不限制與流形可能也可以給其以幾何

        在之後討論 complex 到流形的限制時
        我們也應該從一階流形開始

***** 3 The Problem of Neighboring Regions

***** 4 Topology, India-Rubber Geometry

      - India-Rubber,
        which we are able to distort as we wish in a continuous fashion without tearing.

      - x -
        這種想法可以給拓撲不變量一個直觀的解釋

***** 5 Homeomorphism

      - x -
        可逆的連續雙射 homeomorphism
        可以用來捕捉之前的
        "to distort as we wish in a continuous fashion without tearing."
        這在於
        想要描述的空間 A 的所有性質
        都是利用連續映射建立的
        比如 (: f (-> X A)) 或者 (: g (-> A Y))
        因此當有 homeomorphism 的時候
        這些 描述已然有效
        並且 所描述的性質之間的關係已然被保持

      - k -
        可以發現
        我們是先發現了很多有趣的不變量
        之後在慢慢得到這個等價關係[同胚]的正確定義的
        但是在講述的時候
        我們會先定義等價關係
        然後再定義這些不變量
        其實對定價關係的定義正是爲了使得這些不變量成爲不變量

      - x -
        用德里達的話來說
        某個具體的 等價關係 並不是研究的中心
        不變量並不附屬於等價關係
        而是正相反
        等價關係起源於所發現的不變量

        當想要描述的不變量不適用於某種等價關係了
        就要修改這個等價關係的定義
        使得這些不變量重新變爲不變量
        [比如 homeomorphism 到 ambient-isotopy]

      ------

      - x -
        在定義連續映射的時候
        作者強調了這裏描述的映射是點到點的
        而不是寫 polar reciprocation 那種點到線的
        但是後者也可以是連續映射
        當把空間看作是線組成的時[而不是點組成的]
        topology 公理可能就是必要的了
        也就是說 topology 公理可能不能被理解爲分析算數化的產物
        而應該被理解爲有效的推廣

      - k -
        但是我們所使用的 uncurry 原則
        則是說
        所有的這種 level-up 映射都應該被 uncurry 爲 level-same 映射

      - x -
        很難想象這種處理方式能夠描述 polar reciprocation
        一種離散的 polar reciprocation ?

      - k -
        我想這是因爲 polar reciprocation 並非純粹的 topology 變換

      - x -
        什麼是純粹的 topology 變換 ?

      - k -
        首先
        當以組合的方式來描述空間時
        我們能夠定義很多空間之間的變換
        這樣
        我們就可以把純 '粹連 topology 變換'
        定義爲 與我們能夠定義的變換同倫的變換

      - x -
        何以見得 polar reciprocation 不能與這種變換同倫呢 ?

      - k -
        我們可以嘗試找 polar reciprocation 的同倫
        正如我們找 dehn twist 的同倫一樣
        映射可要被降階

      - x -
        我想我們需要先找到空間的合適劃分
        然後看看這個描述與點的變換限制於這些劃分的時候的樣子
        這個問題應該先放一放
        因爲我們對 polar reciprocation 與圓錐曲線的理解還不夠
        [注意 圓錐曲線可以被推廣到一般空間所形成的 cone]

        ><><><
        一般描述於點的連續變換的組合化
        以及 polar reciprocation 的組合化

      ------

      - x -
        這裏還指出了
        "to distort as we wish in a continuous fashion without tearing."
        必須用 ambient-isotopy 這個概念來捕捉
        而不能用 homeomorphism 來捕捉
        因爲 homeomorphism 還可以是 cut and re-glue

        同時這裏還指出了 一個線段和一個三角形之間可以有 homeomorphism
        但是這些都是集合論語言的問題
        當我們以組合的方式處理拓撲學時
        這些病態的現象並不會出現

***** 6 Topology, Continuous Geometry

      - It is important to note that
        a topological property of a set
        is not necessarily a topological invariant,

        in which case the property is said to be relative.
        In other words, two homeomorphic sets Ε and F
        can have certain different topological properties,
        as when it is a matter not of properties of Ε and F alone,
        but of properties concerning Ε and F and the spaces which contain them.

      - x -
        也就是說 relative topological properties 起源於拓撲不變量的細化
        而不是 直接起源與 空間與其子空間
        畢竟 子空間 與 空間 之間的關係
        並不直接涉及到 relative 這個詞

***** 7 Comparison of Elementary Geometry, Projective Geometry, and Topology

      - x -
        這裏跟隨開篇對 poincare 的引用

      - "projected from a center onto a figure."
        understood as "make a cone and make a section."

        from the point of view of projective geometry,
        one does not distinguish the three types of conies.

      - x -
        攝影變換下的等價
        可以利用 cone 來理解
        注意
        使用 cone 的時候
        就是增加了一個維度

        類似的
        uncurry 也是通過增加一個維度
        來理解變換之間的等價

      - k -
        但是
        當用變換之間的同倫
        來定義空間之間的同倫等價時
        情況就有些複雜了
        但是也許還是可以通過增加維度來理解

      - x -
        比如 mapping cylinder
        看來我們需要好好總結一下 mapping cylinder

        ><><><
        總結 mapping cylinder
        總結 空間之間同倫等價之判別的簡化

***** note about erlangen program

      - to form a geometry theory
        1. first, the fundamental element of the geometry (point, line,circle, etc.);
        2. next, the manifold or space of these elements
           plane of points, ordinary space of points,
           spherical surface of points, plane of lines,
           pencil of circles, etc.;
        3. and finally, the group of transformations
           to which the manifold of fundamental elements is to be subjected.

***** 8 Relative Topological Properties

      - x -
        這裏所說的是 ambient-isotopy
        所說的相對性是指 sub-space 相對於 ambient-space
        [而不是相對同倫羣中的相對性]

***** 9 Set Topology and Combinatorial Topology

      - Since the figures studied in set topology are extremely general sets,
        it is natural that the results obtained in this way
        are frequently far from intuitive
        and even sometimes in contradiction with intuition.

      - [bib]

        - [28]
          R. L. Wilder,
          "Point sets in three and higher dimensions
          and their investigation by means of a unified analysis situs,"
          Bull. Amer.Math. Soc, 38 (1932), 649-692.

      - Our book, as indicated by its title,
        is directed principally to combinatorial topology,
        accordingly, to the topology of complexes.

        Since complexes are generalizations of surfaces,
        we shall limit ourselves, in the other two chapters of this book,
        to the topology of surfaces.

        - In connection with the topology of surfaces,
          one can also consult: H.Seifert and W. Threlfall,
          "a textbook of topology",
          chapter six, surface topology.

***** 10 The Development of Topology

      - Poincare's combinatorial topology v.s. Cantor's set topology

*** chapter two. topological notions about surfaces

***** 11 Descartes'Theorem

      - A polyhedron is a system of a finite number of polygons
        which are situated in a mutual relationship
        such that the following four conditions are verified:

        1. each pair of polygons of the system
           have no common interior points.

        2. for each side of a polygon,
           there exist two and only two polygons having this sidein common.

        3. each pair of polygons of the system
           can be joined by a sequence of polygons of the system
           in the sense that each of these
           has a side in common with the following one.

           i.e.
           there exist joining sequence of faces, for every pair of two faces.
           thus connectivity is ensured in a non-degenerate way.

        4. the polygons about any vertex
           can be placed in a cyclic order
           so that each consecutive pair
           have a common side passing through the vertex.

           thus exclude some kind of singularity.

        According to this definition,
        when we speak of a polyhedron,
        we always mean the surface of the polyhedron.

      - A polyhedron is said to be simple
        if one can continuously deform it into the surface of a sphere.

***** 12 An Application of Descartes'Theorem

***** 13 Characteristic of a Surface

***** 14 Unilateral Surfaces

***** 15 Orientability and Nonorientability

***** 16 Topological Polygons

***** 17 Construction of Closed Orientable Surfaces from Polygons by Identifying Their Sides

***** 18 Construction of Closed Nonorientable Surfaces from Polygons by Identifying Their Sides

***** 19 Topological Definition of a Closed Surface

*** chapter three. topological classification of closed surfaces

***** 20 The Principal Problem in the Topology of Surfaces

***** 21 Planar Polygonal Schema and Symbolic Representation of a Polyhedron

***** 22 Elementary Operations

***** 23 use of normal forms of polyhedra

***** 24 Reduction to Normal Form: I

***** 25 Reduction to Normal Form: II

***** 26 Characteristic and Orientability

***** 27 The Principal Theorem of the Topology of Closed Surfaces

***** 28 Application to the Geometric Theory of Functions

***** 29 Genus and Connection Number of Closed Orientable Surfaces

* (1966 1976) (wilhelm magnus) combinatorial group theory

*** info

    - presentations of groups in terms of generators and relations

* (1977) (roger lyndon and paul schupp) combinatorial group theory

* (1980 1992) (john stillwell) classical topology and combinatorial group theory

*** info

    - topology is ostensibly the study of arbitrary continuous functions.
      in reality, however, we can comprehend and manipulate
      only functions which relate finite "chunks" of space
      in a simple combinatorial manner,
      and topology originally developed on this basis.

    - x -
      雖然作者在開頭這麼說了
      但是作者在之後的敘述中 還是遵循了拓撲空間那種 算數化的語言
      如下的用詞就是一些徵兆 :
      - neighbourhood
      - local compactness

*** 0 introduction and foundations

***** 0.1 The Fundamental Concepts and Problems ofTopology

******* 0.1.1 The Homeomorphism Problem

        - One may consider a geometric figure to be an arbitrary point set,
          and in fact the homeomorphism problem
          was first stated in this form, by Hurwitz 1897.
          However, this degree of generality
          makes the problem completely intractable,
          for reasons which belong more to set theory than geometry,
          namely the impossibility of describing or enumerating all point sets.

        - x -
          也就是說這種處理問題的方式不具有構造性
          沒法在計算機上用數據結構來實現這個模型
          更沒法用算法來實現就這個模型而敘述的函數

        - For the moment
          we wish to claim that all "natural" geometric figures
          are either simplicial complexes or homeomorphic to them,
          which is just as good for topological purposes.

        - knot complement in R3 is not finitely describable in terms of simplexes.

******* 0.1.2 Continuous Functions, Open and Closed Sets

******* 0.1.3 Examples of Continuous Maps

******* 0.1.4 Identification Spaces

        - x -
          again, glue is handled by quotient-space by the author.
          while in AT1, I handled it by common boundary.

******* 0.1.5 The H-ball and the ^-sphere

******* 0.1.6 Manifolds

        - x -
          這里給出了一個例子來說明
          #+begin_src scheme
          (type space
            (: base (-1 <>))
            (: p (0 base base))
            (: c (1 p p p)))
          #+end_src
          並非是 manifold
          也就是說 group 的 generators 與 relations
          所給出的 underlying-space 並非是 manifold

******* 0.1.7 Bounded Manifolds

        - x -
          既然可以把 manifold 推廣到 bounded manifold
          那麼也沒有什麼理由不把一般的 group 的 underlying-space
          包含到考慮範圍之內
          而所得到的 underlying-space 的差異
          都可以通過 group 的性質來描述

          之前問
          what are the underlying-space and covering-space
          of low order finite groups ?
          現在知道這些就是不是 manifold 的空間了

          之前關於有限生成羣的分類的問題
          二維曲面的分類很簡單 因爲這些曲面是 很特殊的羣的 underlying-space
          而一般的羣的分類很難 對應的 underlying-space 的分類也將很難

          而且之所以我們的討論要限制於
          那些 underlying-space 是 manifold 的羣
          可能就是因爲這種羣的 underlying-space 可以有簡單的嵌入
          從而讓人能夠直觀

          而對一般的羣的 underlying-space 的研究
          其實都是用代數方法來完成的

        - In dimension 2
          we can distinguish manifolds from bounded manifolds
          by the fundamental group (4.2.1 and 5.3.3).

******* 0.1.8 Embedding Problems

        - next to the homeomorphism problem,
          the most important type of topological problem is that of
          distinguishing different embeddings of one figure in another.

        - x -
          這裏的 homeomorphism problem 代數化之後就是空間之間的同倫等價
          即 (~~ A B)
          而後面的的 embedding 問題就是特殊的函數之間的等價
          即 (~ f g)
          其特殊性在於
          證明等價時所用的 (-> (* A I) B) 不能有自交

******* 0.1.9 Homotopy and Isotopy

        - The group properties depend crucially on the fact that
          the curve is not required to be simple at any stage,
          and in fact the deformation may create more singularities
          than were present at the beginning.

          Only then can one introduce a product of closed curves,
          and cancel a closed curve by its inverse.

        - x -
          同倫羣的定義依賴於各階球面的自交的映射

        - isotopy seems to be a more natural notion of deformation,
          but it is not algebraically tractable.
          In the case of simple curves on a 2-manifold
          the situation is saved by a theorem of Baer 1928 (6.2.5)
          which says that simple curves are isotopic
          if and only if they are homotopic.

        - note the difference between

          - isotopy
            the "knotted part" can be shrunk to nothing
            without acquiring asingularity at any stage.

          - ambient-isotopy
            knot theory

        - x -
          在 AT1 中
          應該如何定義上面兩個概念
          如果要求 證明等價時所用的 (-> (* A I) B) 不能有自交
          是否就有了 ambient-isotopy ?

          有可能不行
          因爲 ambient-isotopy 是用 (-> (* B I) B) 定義的

***** 0.2 Simplicial Complexes

******* 0.2.1 Definition and Basic Properties

        - simplicial complex as schema.
          It is a consequence of the triangulation and Hauptvermutung that
          all homeomorphism questions for 2- and 3-manifolds
          reduce to combinatorial questions about schemata.

******* 0.2.2 Orientation

        - in general,
          we interpret the ordered (n + 1)-tuple (P0, ..., Pn+1)
          as an orientation of the n-simplex.

          orientations are equivalent
          if they differ by an even permutation of the vertices,
          so there are in fact two possible orientations,
          - (+ (P0, ..., Pn+1)) which is just (P0, ..., Pn+1)
          - (— (P0, ..., Pn+1)) obtained by
            an odd number of exchanges of vertices.

        - an orientation of an n-complex
          is an assignment of orientations to its simplexes.
          The orientation is coherent
          if n-simplexes which share an (n-1)-dimensional face
          induce opposite orientations in that face.

******* 0.2.3 Realization in Euclidean Space

        - any n-complex can be embedded in R^(2n+1)

******* 0.2.4 Cell Complexes

        - in the last resort,
          one can always view cells and the dividing cells inside them
          as unions of simplexes in a simplicial decomposition.
          The point of considering cell complexes at all
          is to minimize the number of cells,
          which usually helps to shorten computations.

        - x -
          作者有使用 simplicial complex 的傾向

******* 0.2.5 Triangulation and Hauptvermutung

        - The Hauptvermutung (main conjecture) of Steinitz 1908
          states that homeomorphic manifolds are combinatorially homeomorphic.

***** 0.3 The Jordan Curve Theorem

******* 0.3.1 Connectedness and Separation

        - The statement, as a theorem,
          that every simple closed curve in R2
          separates it into two regions (Jordan 1887)
          was important in the history of topology
          as the first moment when an "obvious" fact
          was seen to require proof.

******* 0.3.2 The Polygonal Jordan Curve Theorem

******* 0.3.3 0-graphs

******* 0.3.4 Arcs Across a Polygon

******* 0.3.5 The Jordan Separation Theorem

******* 0.3.6 Arcs in a Polygon

******* 0.3.7 No Simple Arc Separates R2

******* 0.3.8 The Jordan Curve Theorem

******* 0.3.9 The Jordan-Schoenflies Theorem

        - there are topologically distinct embeddings of S2 in R3.

***** 0.4 Algorithms

******* 0.4.1 Algorithmic Problems

******* 0.4.2 Recursively Enumerable Sets

******* 0.4.3 The Diagonal Argument

***** 0.5 Combinatorial Group Theory

******* 0.5.1 The Fundamental Group

******* 0.5.2 Generators, Words, and Relations

******* 0.5.3 Group Presentations

******* 0.5.4 Coset Decomposition, Normal Subgroups

        - a set of elements v < G
          generates a normal subgroup N of G
          #+begin_src scheme
          (-> [(: :g G) (: :v V)]
              [(: [:g :v :g rev] N)
               (: [:g :v rev :g rev] N)])
          #+end_src

        - generating a subgroup by inverse and product,
          generating a normal subgroup also by conjugation.

        - x -
          how about the fact that
          the fundamental group of a covering space of (underlying-space G)
          is a subgroup of G ?

******* 0.5.5 Quotient Groups and Homomorphisms

        - we can get quotient group of a group representation
          by adding new relations.
          [where new relations generates a normal subgroup.]

        - isomorphism = (kernel = id)

******* 0.5.6 Dyck's Theorem (Dyck 1882)
******* 0.5.7 The Word Problem and Cayley Diagrams

        - solution of the word problem for G
          is equivalent to the construction of Cayley diagram of G.

        - x -
          如何等同呢 ?
          用有向圖實現這個 [有可能是無限的] cayley diagram 嗎 ?
          path 到 vertex 的 hash function 嗎 ?

******* 0.5.8 Tietze Transformations

        - Tietze's Theorem.
          Any two finite presentations of a group G
          are convertible into each other
          by a finite sequence of Tietze transformations.

******* 0.5.9 Coset Enumeration

        - x -
          這裏作者給出了不計算法複雜性的傻瓜算法

*** 1 complex analysis and surface topology

***** 1.1 Riemann Surfaces

******* 1.1.1 Introduction

        - A complex function is a map from sphere onto sphere.
          [a covering map.]

        - The general purpose of Riemann surfaces in function theory
          is to provide domains on which
          all algebraic functions become single-valued.

******* 1.1.2 Branched Coverings of the 2-sphere

        - torus can cover sphere.

******* 1.1.3 Connectivity and Genus

        - In general
          the connectivity of a surface
          can be measured
          by the maximu mnumber of disjoint closed curves
          which can be drawn on the surface without separating it.
          [This number is called the genus of the surface.]

        - mobius
          clifford
          klein

******* 1.1.4 Branched Coverings of Higher Dimension

        - for 3-dim covering-space

        - james w. alexander

***** 1.2 Nonorientable Surfaces

******* 1.2.1 The Mobius Band

        - Klein imagines a small oriented circle (the indicatrix)
          placed on the surface,
          then transported round an arbitrary closed curve.

******* 1.2.2 The Projective Plane

******* 1.2.3 The Klein Bottle

******* 1.2.4 Dyck's Classification of Nonorientable Surfaces

        - crosscap + handle = 3 crosscaps.

        - special underlying-space
          | group                   | underlying-space |
          |-------------------------+------------------|
          | general                 | cell-complex     |
          | orientable manifold     | ...              |
          | non-orientable manifold | ...              |
          | manifold with boundary  | ...              |

***** 1.3 The Classification Theorem for Surfaces

******* 1.3.1 Combinatorial Definition of a Surface

        - Dehn and Heegaard (1907)
          define a closed surface to be
          a finite 2-dimensional simplicial complex.

******* 1.3.2 Schemata

        - build surfaces from polygons instead of only using triangles.

******* 1.3.3 Reduction to a Single Polygon with a Single Vertex

        - amalgamate polygons to one polygon.
          reduce the number of vertices of the polygon.

******* 1.3.9 Bounded Surfaces

        - x -
          Dehn's paper about 1-holed sphere, 2-holed sphere, and so on,
          is based on the normalization of surface.

***** 1.4 Covering Surfaces

******* 1.4.1 The Universal Covering Surface

        - covering without branch points
          covering with branch points

******* 1.4.2 The Universal Cover of an Orientable Surface of Genus > 1

******* 1.4.3 Fuchsian Groups

******* 1.4.4 The 2-sheeted Cover of a Nonorientable Surface

*** 2 graphs and free groups

***** 2.1 Realization of Free Groups by Graphs

******* 2.1.1 intro

        - to vividly illustrate the dual view of
          a group as fundamental group of a space
          and automorphism group of a covering-space.

******* 2.1.2 Graphs, Paths, and Trees
******* 2.1.3 The Cay ley Diagram of a Free Group
******* 2.1.4 Solution of the Word Problem for Free Groups
******* 2.1.5 Spanning Trees
******* 2.1.7 Generators for the Fundamental Group
******* 2.1.8 Freeness of the Generators
******* 2.1.9 The Tree as the Universal Covering Graph of the Bouquet of Circles

***** 2.2 Realization of Subgroups

******* 2.2.1 Covering Graphs

        - covering-map can be adequately represented
          by labelling and orienting the edges in covering-space.

******* 2.2.2 The Subgroup Property

        - x -
          帶有類型的代數結構之間的同態
          誘導出去掉類型的代數結構之間的單同態

******* 2.2.3 Realization of an Arbitrary Subgroup of a Free Group

******* 2.2.4 The Nielsen-Schreier Theorem

        - Every subgroup of a free group is free.

******* 2.2.6 Schreier Transversals

******* 2.2.7 Normal Subgroups and Cayley Diagrams

        - (: covering (-> X (underlying-space G)))
          if (fundamental-group X) is normal subgroup of G,
          then (= X (cayley-graph (/ G (fundamental-group X))))

*** 3 foundations for the fundamental group

***** 3.1 The Fundamental Group

******* 3.1.1 IntroductionThe fundamental group

        - Such a definition
          makes the computation of generators and relations routine,
          but it is open to the objection that
          the group is not obviously a topological invariant.

          Since the topologists of the time
          pinned their hopes on the Hauptvermutung,
          they could be satisfied with a proof that
          the fundamental group was invariant under combinatorial homeomorphisms,
          which was supplied by Tietze 1908.

        - The only group which has to be derived from first principles
          is that of the circle;
          all the other fundamental groups we need
          are then obtained by combining the simple technique of
          deformation retraction
          with the Seifert-Van Kampen theorem.

***** 3.2 The Fundamental Group of the Circle

******* 3.2.2 Tightening a Path

        - x -
          證明某些生成子能過生成整個函數空間
          要證明函數空間中的任意元素都能化爲生成子所生成的正規形式

        - k -
          但是這與我們理解基本羣的方式並不相同
          計算基本羣的方式也不同
          我們計算同倫羣的方式是
          把一個 groupoid 化爲 group

        - x -
          groupoid 化爲 group 的過程
          可以看作是收縮那些沒有自交的 path
          最終得到的全是 circle

          二維圖形也可以如此
          最終得到的卻不全是 sphere
          而是什麼 ?

        - k -
          我們必須找一些例子來觀察

        - x -
          在這個正規化的過程中
          我們也可以先處理點
          即 用一個支撐樹
          把所有的點收縮成一個點

        - k -
          這樣我們就會得到一個高階 group 了

******* 3.2.3 Brouwer Degree

******* 3.2.4 Invariance of the Brouwer Degree under Homotopy

***** 3.3 Deformation Retracts

***** 3.4 The Seifert-Van Kampen Theorem

***** 3.5 Direct Products

*** 4 fundamental groups of complexes

***** 4.1 Poincare's Method for Computing Presentations

***** 4.2 Examples

***** 4.3 Surface Complexes and Subgroup Theorems

*** 5 homology theory and abelianization

***** 5.1 Homology Theory

***** 5.2 The Structure Theorem for Finitely Generated Abelian Groups

***** 5.3 Abelianization

*** 6 curves on surfaces

***** 6.1 Dehn's Algorithm

***** 6.2 Simple Curves on Surfaces

***** 6.3 Simplification of Simple Curves by Homeomorphisms

***** 6.4 The Mapping Class Group of the Torus

*** 7 knots and braids

***** 7.1 Dehn and Schreier's Analysis of the Torus Knot Groups

***** 7.2 Cyclic Coverings

***** 7.3 Braids

*** 8 three-dimensional manifolds

***** 8.1 Open Problems in Three-Dimensional Topology

***** 8.2 Polyhedral Schemata

******* 8.2.4 Remarks

        - Polyhedral schemata
          have never been used in a systematic way
          for the construction of 3-manifolds,
          even though some interesting manifolds
          originally arose in this way
          (for example lens spaces, cf. 4.2.8.
           See also Threlfall and Seifert 1930, 1932
           and Weber and Seifert 1933
           for manifolds obtainedfrom the Platonic solids).

          Apparently polyhedral schemata
          do not admit anything like the reductions applicable to polygon schemata,
          but it is not clear that anyone has worked very hard on the problem.

          Only recently, Thurston 1977 has found
          polyhedral forms of many 3-manifolds
          which can be used to tesselate hyperbolic 3-space,
          yielding a theory like the classical theory of 2-manifolds.

***** 8.3 Heegaard Splittings

******* 8.3.1 Existence

******* 8.3.2 Heegaard Diagrams

        - A manifold which splits into handlebodies H1 H2
          is determined up to homeomorphism
          by the map (: h (-> [H1 boundary] [H2 boundary]))
          [which is determined by the images of the canonical meridians.]

***** 8.4 Surgery

***** 8.5 Branched Coverings

*** 9 unsolvable problems

***** 9.1 Computation

***** 9.2 HNN Extensions

***** 9.3 Unsolvable Problems in Group Theory

***** 9.4 The Homeomorphism Problem

* (1982) (bruce chandler and wilhelm magnus) the history of combinatorial group theory: a case study in the history of ideas

*** info

    - Nearly the entire body of research in the field
      is due to mathematicians who either are still alive
      or who were the teachers or senior colleagues of living mathematicians.
      This makes it possible to supplement the written tradition
      with oral information which is particularly valuable
      when dealing with questions of motivation
      for a particular investigation or of the transfer of ideas.

    - x -
      it seems the tradition of writing hides motivations,
      while the dialog reveals motivations.

      it might also be the authors who fail to convey their motivations
      are not good at their art.

*** Part I The Beginning of Combinatorial Group Theory

***** 1 Introduction to Part I

      - Part I of our book covers the period from 1882 to 1918,
        the end of the first World War.

***** 2 The Foundation: Dyck's Group-Theoretical Studies

      - in Dyck's paper :
        For the further development of the present group theoretical problems
        the analytic (combinatorial) formulation has to replace every geometric description.
        However, the primary geometric interpretation has produced certain viewpoints
        and it is the purpose of the present paper
        to develop both their geometric version and their analytic content.

      - "a geometric concretization (Versinnlichung) of the group G."
        like the theory of fuchsian groups.

        tessellation of the hyperbolic disk

      - Burnside's textbooks.

      - De Siguier used Cantor's set theory
        and coined the term 'semigroup'.

      - What we called Proposition 1
        [there exist free group for a set of generators]
        is then what Dehn called the solution of the word problem for free groups.

      - x -
        當 [像 Dehn 一樣]
        用 模型的實現 與 算法 來理解這些理論時
        某些堂皇的命題就是顯然的事實了

        作者區分了 The existence proof 與 The combinatorial proof
        後者是 構造主義 的

***** 3 The Origin: The Theory of Discontinuous Groups

      - poincare and klein

      - discontinuous action
        discontinuous group acting on space

      - the early theory of discontinuous groups did not stimulate
        the development of the theory of group presentations,
        because the discontinuous groups are not primarily given by presentations.
        They are defined either by a set of generating elements
        which describe circle-preserving conformal self-mappings of the complex plane [geometric]
        or as a set of 2x2 matrices, subject to arithmetic conditions [arithmetic].

***** 4 Motivation: The Fundamental Groups of Topological Spaces

      - poincare -> tietze -> dehn

      - [bib]

        - Birman, J. S.
          Poincare's conjecture and the homeotopy group of a closed, orientable 2-manifold
          1973

        - heinrich tietze
          on the topological invariants of multidimensional manifolds
          1908

      - Tietze's results are motivated by an observation of a specific difficulty
        arising when working with groups which are merely givenby a presentation.

      - Dehn recognized that the difficulties of combinatorial group theory
        start at a much lower level than that of the isomorphism problem as stated by Tietze.

      - [bib]

        - Greendlinger, M, 1960a,
          Dehn's algorithm for the word problem,
          Comm. Pure and Appl.Math.

        - Greendlinger, M., 1960b,
          Dehn's algorithm for the conjugacy and word problems, with applications,
          Comm. Pure and Appl. Math.

***** 5 The Graphical Representation of Groups

      - cayley diagram -> burnside [finite order] -> coxeter [finite order]

      - The point to be made here is that
        this is such an extremely simple definition
        when phrased in topological terms.
        Any possible translation into algebraic terms
        appears to be clumsy and opaque.
        Of course, one may say that
        all that matters about a definition is its precision.
        But this was certainly not Dehn's opinion.
        In a public talk for a nonmathematical academic audience,
        Dehn [1928] explained that the continued growth of mathematics
        requires the continued emergence of new ideas which reduce its complexity.
        He also expressed the hope that
        topology would renew its power through such an injection of new ideas.
        The reader should note the year when this was said.
        Within the following 10 years,
        there appeared monographs on topology by
        Alexandroff and Hopf,
        by Lefshetz, and by Seifert and Threlfall,
        documenting an upsurge in topological research which has not yet abated.

        - Dehn, M, 1928,
          Uber die geistige Eigenart des Mathematikers,
          Frankfurter Universitatsreden No. 27. 25 pp.,
          Universitatsdruckerei Wemer und Winter, Frankfurt am Main.
          Preface and I.5,

***** 6 Precursors of Later Developments

******* note

        - x -
          這章節值得仔細分析
          既然 羣論 可以用於描述諸多現象
          那麼 推廣而得到的 高階代數 是否也能描述這些現象的推廣呢 ?

        - k -
          如果可以的話
          就可以說 羣論 到 高階代數 的推廣是一個成功的推廣了

******* A. Arithmetically Defined Linear Groups in Higher Dimensions

        - siegel

******* B. Arithmetically Defined Linear Groups in Two Dimensions

        - magnus

******* C. Geometric Constructions. Fuchsian Groups

******* D. Braid Groups and Mapping Class Groups

        - hurwitz
          in a fiber space, the fundamental group of the base space
          acts as a group of self-mappings on the fiber.

******* E. Differential Equations, Linear Groups,and Lie Groups

******* F. Finite Groups

***** 7 Summary

      - Group theory started as the theory of groups of transformations,
        i.e., of one-to-one and onto self-mappings of a mathematical object.
        If the object is a finite set, the group appears as a permutation group.
        [Camille Jordan on "substitutions and algebraic equations"]

      - Infinite transformation groups
        became a topic of extensive research at about the same time.
        But this development was initiated not by a fundamental work but by a manifesto.
        [Felix Klein at Erlangen]
        [Sophus Lie]
        a program, according to which
        geometry should be considered from the point of view
        of transformation groups which act on certain spaces.

        for to get the generators of the group of Klein as in combinatorial group theory,
        the concept of generators has to be modified
        in the sense of Lie's "infinitesimal substitutions".

      - the tiling designs or tessellations
        of the euclidean or non-euclidean plane
        with a polygon as the basic tile,
        The generators and their inverses
        simply correspond to the edges of the basic polygonal tile,
        and the defining relations correspond to its vertices.

        this is the dual of the cayley-graph,
        so we have three graphs now,
        (1) underlying-space [classifying-space]
        (2) covering-space [cayley-graph]
        (3) acting-space [dual-cayley-graph]

      - finite group vs infinite group
        for finite group, we have :
        | finite group            | number            |
        | finite simple group     | prime number      |
        | direct product of group | product of number |
        but for infinite group, we do not have such.
x
      - The object on which a group of transformations acts
        has disappeared completely
        if we define a group through a presentation by generators and relations.

        while Poincare's fundamental group
        makes group generators and relations worth study.

      - the theory of representations of groups
        as linear transformations of finite-dimensional vector spaces

        [Frobenius Burnside, and L. E. Dickson]
        [linear groups over finite fields]

      - combinatorial group theory emphasis on algorithms.
        "to find a method of deciding in a finite number of steps"

      - combinatorial group theory
        geometric -> geometric interpretation
        algebraic -> classify and decomposition

***** 8 Modes of Communication. Growth and Distribution of Research in Group Theory

***** 9 Biographical Notes

***** 10 Notes on Terminology and Definitions

      - It is part of the purpose of every historical essay
        to make it easier to go back to the sources for those readers
        who may be interested in doing so.

***** 11 Sources

*** Part II The Emergence of Combinatorial Group Theory as an Independent Field

***** 1 Introduction to Part II

      - This part of our book deals mainly with the developments during the period
        from 1918 to 1945, that is, from the end of World War I
        to the end of World War II.

      - the mapping class group of a surface
        is the group of automorphisms
        of the fundamental group of the surface.

        - x -
          how about mapping-class-group with fixed boundary ?

***** 2 Free Groups and Their Automorphisms

      - Nielsen
        Hopf
        McCool

      - [bib]

        - McCool, J., 1974,
          A presentation of the automorphism group of a free group of finite rank

        - McCool, J. 1975a,
          On Nielsen's presentation of the automorphism group of a free group

        - McCool, J., 1975b,
          Some finitely presented subgroups of the automorphism group of a freegroup

***** 3 The Reidemeister-Schreier Method

***** 4 Free Products and Free Products with Amalgamations

***** 5 One-Relator Groups

***** 6 Metabelian Groups and Related Topics

***** 7 Commutator Calculus and the Lower Central Series

***** 8 Varieties of Groups

***** 9 Topological Properties of Groups and Group Extensions

      - this may be described as
        a method of associating a topological cell complex
        with the group and deriving results about the group from this association.

      - it was shown that
        the association of cell complexes and groups
        leads to a purely algebraicde finition of homology and cohomology groups
        belonging to any given group G which are invariants of G.

***** 10 Notes on Special Groups

***** 11 Postscript: The Impact of Mathematical Logic

***** 12 Modes of Communication

***** 13 Geographical Distribution of Research and Effects of Migration

***** 14 Organization of Knowledge

* (1989) (daniel cohen) combinatorial group theory: a topological approach

*** info

    - the author, daniel cohen, is influenced by
      ralph fox, hanna neumann and roger lyndon.

*** 1 combinatorial group theory

***** 1.1 free groups

***** 1.2 generators and relators

***** 1.3 free products

***** 1.4 pushouts and amalgamated free products

***** 1.5 hnn extensions

*** 2 spaces and their paths

***** 2.1 some point-set topology

***** 2.2 paths and homotopies

*** 3 groupoids

***** 3.1 groupoids

***** 3.2 direct limits

*** 4 the fundamental groupoid and the fundamental group

***** 4.1 the fundamental groupoid and the fundamental group

***** 4.2 van kampen's theorem

***** 4.3 covering spaces

***** 4.4 the circle and the complex plane

***** 4.5 joins and weak joins

*** 5 complexes

***** 5.1 graphs

***** 5.2 complexes and their fundamental groups

***** 5.3 free groups and their automorphisms

***** 5.4 coverings of complexes

***** 5.5 subdivisions

***** 5.6 geometric realisations

*** 6 coverings of spaces and complexes

*** 7 coverings and group theory

*** 8 bass-serre theory

***** 8.1 trees and free groups

***** 8.2 nielsen's method

***** 8.3 graphs of groups

***** 8.4 the structure theorems

***** 8.5 applications of the structure theorems

***** 8.6 construction of trees

*** 9 decision problems

***** 9.1 decision problems in general

***** 9.2 some easy decision problems in groups

***** 9.3 the word problem

***** 9.4 modular machines and unsolvable word problems

***** 9.5 some other unsolvable problems

***** 9.6 higman's embedding theorem

***** 9.7 groups with one relator

*** 10 further topics

***** 10.1 small cancellation theory

***** 10.2 other topics

* (1993) two-dimensional homotopy and combinatorial group theory

* (2008) (dmitry kozlov) combinatorial algebraic topology

* (2005) The Geometry of the Word Problem for Finitely Generated Groups

*** (Noel Brady) Dehn Functions and Non-Positive Curvature

*** (Tim Riley) Filling Functions

***** Introduction

      - Group action
      - word metric
      - Cayley graph
      - Cayley 2-complex
      - Asymptotic cones
      - Filling functions

***** 1 Filling Functions

******* 1.1 Van Kampen diagrams

        - (cayley-2-complex x) :=
          (universal-covering presentation-2-complex x)

        - van Kampen diagram of (= w identity)

******* 1.2 Filling functions via van Kampen diagrams

        - for a van Kampen diagram we can define :
          area
          intrinsic diameter
          extrinsic diameter
          gallery length
          filling length
          DGL

        - A shelling of ∆
          is a combinatorial null-homotopy of ∆
          down to its base vertex.
          [note about the concept of "combinatorial homotopy"]

******* 1.3 Example: combable groups

******* 1.4 Filling functions interpreted algebraically

******* 1.5 Filling functions interpreted computationally

******* 1.6 Filling functions for Riemannian manifolds

******* 1.7 Quasi-isometry invariance

***** 2 Relationships Between Filling Functions

******* 2.1 The Double Exponential Theorem

******* 2.2 Filling length and duality of spanning trees in planar graphs

******* 2.3 Extrinsic diameter versus intrinsic diameter

******* 2.4 Free filling length

***** 3 Example: Nilpotent Groups

******* 3.1 The Dehn and filling length functions

******* 3.2 Open questions

***** 4 Asymptotic Cones

******* 4.1 The definition

******* 4.2 Hyperbolic groups

******* 4.3 Groups with simply connected asymptotic cones

******* 4.4 Higher dimensions

*** (Hamish Short) Diagrams and Groups

* (2009) (jean gallier) notes on convex sets, polytopes, polyhedra, combinatorial topology, voronoi diagrams and delaunay triangulations

*** 1 Introduction

***** 1.1 Motivations and Goals

      - Chapter 6 on combinatorial topology is hardly original.
        However, most texts covering this material
        are either old fashion or too advanced.
        Yet, this material is used extensively in meshing and geometric modeling.
        We tried to give a rather intuitive yet rigorous exposition.
        We decided to introduce the terminology combinatorial manifold,
        a notion usually referred to as triangulated manifold.

      - A recurring theme in these notes
        is the process of "conification" (algebraically, "homogenization"),
        that is, forming a cone from some geometric object.

        Indeed, "conification" turns an object into a set of lines,
        and since lines play the role of points in projective geometry,
        "conification" ("homogenization")
        is the way to "projectivize" geometric affine objects.

        Then, these (affine) objects
        appear as "conic sections" of cones by hyperplanes,
        just the way the classical conics (ellipse, hyperbola, parabola)
        appear as conic sections.

      - [bib]

        - [43]
          Gunter Ziegler.
          Lectures on Polytopes.
          GTM No. 152. Springer Verlag, first edition,
          1997

        - [38]
          Rekha R. Thomas.
          Lectures in Geometric Combinatorics.
          STML, Vol. 33. AMS, first edition,
          2006

*** 2 Basic Properties of Convex Sets

***** 2.1 Convex Sets

***** 2.2 Carathéodory’s Theorem

***** 2.3 Vertices, Extremal Points and Krein and Milman’s Theorem

***** 2.4 Radon’s and Helly’s Theorems and Centerpoints

*** 3 Separation and Supporting Hyperplanes

***** 3.1 Separation Theorems and Farkas Lemma

***** 3.2 Supporting Hyperplanes and Minkowski’s Proposition

***** 3.3 Polarity and Duality

*** 4 Polyhedra and Polytopes

***** 4.1 Polyhedra, H-Polytopes and V-Polytopes

***** 4.2 The Equivalence of H-Polytopes and V-Polytopes

***** 4.3 The Equivalence of H-Polyhedra and V-Polyhedra

***** 4.4 Fourier-Motzkin Elimination and Cones

*** 5 Projective Spaces and Polyhedra, Polar Duality

***** 5.1 Projective Spaces

***** 5.2 Projective Polyhedra

***** 5.3 Tangent Spaces of Hypersurfaces

***** 5.4 Quadrics (Affine, Projective) and Polar Duality

*** 6 Basics of Combinatorial Topology

***** note 幾何與拓撲

      - x -
        在這本書的處理方式下
        幾何與拓撲是沒有分離的
        當考慮的是嵌入在歐氏空間中的圖形的時候
        [当强调 complex 有一种几何实现的时候]
        沒有考慮過還能給這些圖形以別樣的幾何

***** note 細節

      - x -
        可以發現這本書中對理論的處理非常細緻
        但是我覺得例子還是不夠

      - k -
        也許你可以仔細讀這本書
        然後自己補充例子
        也可以形成自己的理解方式與描述方式

***** 6.1 Simplicial and Polyhedral Complexes

      - Recall that
        a simplex is just the convex hull of a finite number of affinely independent points.
        We also need to define faces, the boundary, and the interior of a simplex.

      - x -
        在一般的處理代數拓撲的方式中
        把 simplex 定義成這樣看似是沒有必要的
        但是
        可能只有這種定義才能讓人把 simplicial complex 展示出來

      - k -
        但是重點是不要把這些圖形化出來不是嗎
        是要在不畫出來它們的條件下研究它們的性質

      - x -
        在這種構造方式中
        不能假設各個 simplex 的內點是不交的

      - k -
        但是這些以代數方式[組合方式]定義的圖形[尤其是流形]
        都可以被嵌入在高維的歐式空間中 [geometric realization]
        因此可以假定內點不交
        因此這種定義方式是具有一般性的

      - x -
        但是如此嵌入在高維空間中的圖形
        並不能被人所直觀
        如果說算數化的構造方式是爲了展示給人的化
        這種構造就也沒有什麼用處

      - A polytope is the geometric realization of some simplicial complex.

***** 6.2 Combinatorial and Topological Manifolds

      - A combinatorial d-manifold is any space, X,
        homeomorphic to the geometric realization, |K| ⊆ En,
        of some pure (simplicial or polyhedral) complex, K,
        of dimension d, whose faces are all nonsingular.

      - x -
        因此有關 manifold 的終點就在於 singularity 的定義
        但是當考慮 homotopy 的時候
        singularity 可以被化解掉

      - k -
        可能我們需要把這種化解 singularity 的想法構建到我們的語言中來

      - x -
        可能不光是要化解 singularity
        我們還要能夠在不同維度之間自由的變換
        利用 refl
        我們要能夠把點視爲線
        把線視爲面 等等

*** 7 Shellings and the Euler-Poincaré Formula

***** 7.1 Shellings

      - the aim is to proof Euler-Poincaré Formula inductively.
        but also can be viewed as finding the normal form.

***** 7.2 The Euler-Poincaré Formula for Polytopes

***** 7.3 Dehn-Sommerville Equations for Simplicial Polytopes

***** 7.4 The Upper Bound Theorem

*** 8 Dirichlet–Voronoi Diagrams

***** 8.1 Dirichlet–Voronoi Diagrams

***** 8.2 Triangulations

***** 8.3 Delaunay Triangulations

***** 8.4 Delaunay Triangulations and Convex Hulls

***** 8.5 Stereographic Projection and the Space of Spheres

***** 8.6 Stereographic Projection and Delaunay Polytopes

***** 8.7 Applications
