#+title: notes about continuum

* brentano

*** on what is continuous (1914)

    - The question concerning the concept of continuity
      cannot be framed in such a way that
      one would call into doubt whether we do in fact possess such a concept.
      For otherwise we would not be able to understand ourselves
      when arguing about other aspects of this concept.

    - All our concepts are either taken immediately from an intuition
      or combined out of marks that are taken from intuition.

    - The concept of what is continuous, firstly, must be viewed as primitive instead of compound.
      (1) 'primitive' as been taken immediately from an intuition.
      (2) 'compound' as been combination of individual marks distilled from intuition.

    - 當試圖描述連續體爲複合概念時
      我們形成的理論如此玄虛
      以至於 我們在觀察中所直覺到的連續體的簡單性質
      比如 邊界 等等
      必須要以迂迴複雜的方式才能被表述出來

    - 想要分解連續體 把這個概念劃歸到更簡單的概念
      我可以理解這種意圖
      但是我認爲這個計劃失敗了

    - 我重申
      The concept of the continuous is acquired
      not through combinations of marks taken from different intuitions
      and experiences, but through abstraction from unitary intuitions.

    - 我要提出理解連續體的直覺方式
      尤其我要能很好地描述 連續體之邊界 和 邊界之重合

    - 我斷言 有關我們的 外部感知 內部感知 和 記憶
      的任何一個直覺 都揭示着連續體這個抽象概念

    - Thus in seeing we have as object something
      that is extended in length and breadth which
      at the same time shows itself clearly
      as allowing us to distinguish a front and rear side
      and thus as characterised as the two-dimensional boundary
      of something extended in three dimensions.

    - 當觀看一個呈現於我們面前的連續體的時候
      我們同時也能夠想象自己的觀看行爲本身
      當繞着被觀看物運動時 它呈現於我們的表面也連續變化着
      當我們靜止時 我們還能想象被觀察的連續體自身隨時間而形變
      如此說來
      運動於靜止 恆定與漸變 都是我們想象的基本性質[或基本元素]

    - 這樣就算解決了連續體這個概念的起源問題了嗎 ?

    - 我們可以在需要的時候細分一個連續體
      細分是潛在無窮的 但是總是有限的
      我們不應想象在無窮的細分一條線之後 能獲得點
      我們不應該聲稱這些點構成了這條線

    - [染色的棋盤]
      一個無法感知但是可以想象的例子
      爲討論連續體的邊界做準備
      因爲我們是沒法感知構成一個連續的邊界的所有點的
      但是我們能夠想象其邊界
      正如
      我們沒法感知到[觀看到 觸碰到 等等]沒有寬度的線
      但是我們能想象沒有寬度的線

    - 想必於用合成的方式來構造連續體之概念
      用直覺來抽象出連續體之概念 的好處是
      我們可以附加別的直覺概念到它上面 使這個概念更豐富
      我們還可以通過區分別的直覺概念 來分類連續體
      1. 一維連續體 定義爲只有不連續的邊界的連續體
         比如時間作爲一個一維連續體 其邊界是此刻
         而此刻本身沒有時間延展[temporal extension]
         我們把它們稱爲瞬間
      2. 最多以一維連續體爲邊界的連續體 就稱爲二維連續體
         依此類推
      3. 有些二維曲面沒有邊界
         但是一個一維曲線可以將其分離爲兩部分
         因此 在這種特殊情況下
         我們也有有效的判別維數的方式

    - Boundaries can be distinguished as inner and outer.
      #+begin_src scheme
      (def cylinder
        (type space
          (: [a0, a1] (-1 <>))
          (: b0 (0 a0 a0))
          (: b1 (0 a1 a1))
          (: h  (0 a0 a1))
          (: c0 (1 h b1 h rev b0 rev))))
      #+end_src
      這裏 h 就是 inner-boundary
      而 b0 與 b1 是 outer-boundary
      只因爲在 c0 的邊界 (1 h b1 h rev b0 rev) 中 h 重複出現了
      - 如果重複出現是判斷 inner-boundary 的標準的話
        那麼 一個 disk 的邊界繞着 circle 盤繞兩圈所形成的連續體
        將只有 inner-boundary 而沒有 outer-boundary
        因爲每個邊界都重複出現了一次

    - brentano 用 plerosis 這個詞來描述邊界的重複出現次數
      重複出現的地方不一定是同一個 cell
      一部分邊界也可能重複出現在很多不同的 cell 的邊界中

    - plerosis
      - noun
        Originally Theology. The action or process of being made full or complete, fulfilment.
      - Origin
        Early 19th century (in an earlier sense).
        From ancient Greek πλήρωσις filling up, filling, becoming full,
        repletion from πληροῦν to fill + -σις.

    - 我想 brentano 這個詞的用意是
      要描述 連續體的邊界的各個部分
      都沾染了這個連續體的性質[比如 顏色]
      因此 一段邊界 重複出現在多個連續體的邊界中
      就沾染上了豐富的性質

    - Boundaries require belongingness.
      就是說 一個連續體的邊界被看作是連續體的部分
      即 '屬於' 連續體
      但是有趣的是
      在關於連續體的形式語言的類型論中
      邊界是連續體的類型
      連續體 反過來 '屬於' 其邊界

    - 我想
      如果回到之前對感知與想象的討論
      只有連續體最高維數的部分纔是可感知的
      而其邊界只能是想象出來的

    - 之後的一節
      討論時間這個概念的難點
      homotopy 的概念以時間爲直覺基礎
      但是在形式化的處理中
      時間這個維度的特殊性被消除了
      證明同倫等價的時候
      只要解決有關 I 的 extension-problem
      #+begin_src scheme
      (let ([f0 (lambda (-> A B) ...)]
            [f1 (lambda (-> A B) ...)])
        (lambda (-> (* A I) B)
          (extend-from
            (lambda (-> (* A (0 I)) B)
              (-> (* :a i0) [:a f0])
              (-> (* :a i1) [:a f1])))
          ...))
      #+end_src

    - 有趣的是如此的形式語言
      使得我們獲得了兩種想象同倫的方式
      一種是想象出在時間中的運動與形變
      一種是想象高維連續體被揉入低維連續體

* aristotle

*** categories, section 1, part 6

    Quantity is either discrete or continuous. Moreover, some quantities
    are such that each part of the whole has a relative position to the
    other parts: others have within them no such relation of part to part.

    Instances of discrete quantities are number and speech; of continuous,
    lines, surfaces, solids, and, besides these, time and place.

    In the case of the parts of a number, there is no common boundary
    at which they join. For example: two fives make ten, but the two fives
    have no common boundary, but are separate; the parts three and seven
    also do not join at any boundary. Nor, to generalize, would it ever
    be possible in the case of number that there should be a common boundary
    among the parts; they are always separate. Number, therefore, is a
    discrete quantity.

    The same is true of speech. That speech is a quantity is evident:
    for it is measured in long and short syllables. I mean here that speech
    which is vocal. Moreover, it is a discrete quantity for its parts
    have no common boundary. There is no common boundary at which the
    syllables join, but each is separate and distinct from the rest.

    A line, on the other hand, is a continuous quantity, for it is possible
    to find a common boundary at which its parts join. In the case of
    the line, this common boundary is the point; in the case of the plane,
    it is the line: for the parts of the plane have also a common boundary.
    Similarly you can find a common boundary in the case of the parts
    of a solid, namely either a line or a plane.

    Space and time also belong to this class of quantities. Time, past,
    present, and future, forms a continuous whole. Space, likewise, is
    a continuous quantity; for the parts of a solid occupy a certain space,
    and these have a common boundary; it follows that the parts of space
    also, which are occupied by the parts of the solid, have the same
    common boundary as the parts of the solid. Thus, not only time, but
    space also, is a continuous quantity, for its parts have a common
    boundary.
