#+title: computational geometry

* note

*** 編碼

    - x -
      計算幾何 與 其在三維建模中的應用 這將涉及到對度量性質的建模
      計算幾何如何編碼圖形?

    - k -
      我發現在敘述某些函數 比如 neighborhood 的時候
      在古典語言中很容易表達的東西
      在我們的語言中卻要想很久
      這是純粹是因爲形式語法的設計問題嗎?

      計算幾何是如何定義各種概念的?

    - x -
      既然計算幾何形成了一個穩定的研究領域
      那麼就一定有一些固定的對圖形的編碼方式

* (2011) (satyan l. devadoss and joseph o'rourke) discrete and computational geometry

*** polygons

***** 1.1 diagonals and triangulations

      - Definition.
        A triangulation of a polygon P
        is a decomposition of P into triangles
        by a maximal set of noncrossing diagonals.

        - thus it is not allowed to add vertices into the polygon.

      - Lemma 1.3.
        Every polygon with more than three vertices has a diagonal.

      - Theorem 1.4. Every polygon has a triangulation.

      - a tetrahedralization of a polyhedron
        is a partition of its interior into tetrahedra
        whose edges are diagonals of the polyhedron.

***** 1.2 basic combinatorics

***** 1.3 the art gallery theorem

***** 1.4 scissors congruence in 2d

***** 1.5 scissors congruence in 3d

*** convex hulls

***** 2.1 convexity

***** 2.2 the incremental algorithm

***** 2.3 analysis of algorithms

***** 2.4 gift wrapping and graham scan

***** 2.5 lower bound

***** 2.6 divide-and-conquer

***** 2.7 convex hull in 3d

*** triangulations

***** 3.1 basic constructions

***** 3.2 the flip graph

***** 3.3 the associahedron

***** 3.4 delaunay triangulations

***** 3.5 special triangulations

*** voronoi diagrams

***** 4.1 voronoi geometry

***** 4.2 algorithms to construct the diagram

***** 4.3 duality and the delaunay triangulation

***** 4.4 convex hull revisited

*** curves

***** 5.1 medial axis

***** 5.2 straight skeleton

***** 5.3 minkowski sums

***** 5.4 convolution of curves

***** 5.5 curve shortening

***** 5.6 the heat equation

***** 5.7 curve reconstruction

*** polyhedra

***** 6.1 platonic solids

***** 6.2 euler’s polyhedral formula

***** 6.3 the gauss-bonnet theorem

***** 6.4 cauchy rigidity

***** 6.5 shortest paths

***** 6.6 geodesics

*** configuration spaces

***** 7.1 motion planning

***** 7.2 polygonal chains

***** 7.3 rulers and locked chains

***** 7.4 polygon spaces

***** 7.5 particle collisions

*** appendix computational complexity

* (1997) (joseph o'rourke) computational geometry in с

* (2005) (afra j. zomorodian) topology for computing

* (2003) (sergei matveev) algorithmic topology and classification of 3-manifolds

*** 1 simple and special polyhedra

***** 1.1 spines of 3-manifolds

******* 1.1.1 collapsing

        - elementary simplicial collapse of simplicial complex

        - elementary polyhedral collapse
          defined by triangulation
          and elementary simplicial collapses

        - simplicial collapse and polyhedral collapse

******* 1.1.2 spines

        - a spine of a compact connected 3-dimensional manifold with boundary M.
          is a subpolyhedron P that M collapses to.

          a spine of a closed connected 3-manifold M
          is a spine of M with a 3-ball removed.

          a spine of a disconnected 3-manifold
          is an union of spines of its connected components.

        - any compact triangulated 3-manifold M
          always possesses a spine of dimension <= 2.

        - It is often convenient to view a 3-manifold
          as a mapping cylinder over its spine
          - by a map from its boundary to its spine

          and as regular neighborhoods of the spines
          - a regular neighborhood of P in M
            is a submanifold of M that can be collapsed onto P

******* 1.1.3 simple and special polyhedra

        - A spine of a 3-manifold M carries much information about M.
          In particular, if boundary of M is not empty,
          then any spine P of M is homotopy equivalent to M.

          but, two nonhomeomorphic manifolds can have homeomorphic spines.
          [annulus and möbius-strip both collapse to circle]

        - Any compact 3-manifold possesses a special spine.
          - x -
            這裏描述的是 3-manifold 的 2-skeleton 的限制

        - If two compact connected 3-manifolds have homeomorphic special spines
          and either both are closed or both have nonempty boundaries,
          then these 3-manifolds are homeomorphic.

******* 1.1.4 special spines

******* 1.1.5 special polyhedra and singular triangulations

***** 1.2 elementary moves on special spines

******* 1.2.1 moves on simple polyhedra

******* 1.2.2 2-cell replacement lemma

******* 1.2.3 bubble move

******* 1.2.4 marked polyhedra

***** 1.3 special polyhedra which are not spines

******* 1.3.1 various notions of equivalence for polyhedra

******* 1.3.2 moves on abstract simple polyhedra

******* 1.3.3 how to hit the target without inverse u-turns

******* 1.3.4 zeeman’s collapsing conjecture

* (1972) (c p rourke and b j sanderson) introduction to piecewise linear topology
* (2009) (jean gallier) notes on convex sets, polytopes, polyhedra, combinatorial topology, voronoi diagrams and delaunay triangulations

*** 1 Introduction

***** 1.1 Motivations and Goals

      - Chapter 6 on combinatorial topology is hardly original.
        However, most texts covering this material
        are either old fashion or too advanced.
        Yet, this material is used extensively in meshing and geometric modeling.
        We tried to give a rather intuitive yet rigorous exposition.
        We decided to introduce the terminology combinatorial manifold,
        a notion usually referred to as triangulated manifold.

      - A recurring theme in these notes
        is the process of "conification" (algebraically, "homogenization"),
        that is, forming a cone from some geometric object.

        Indeed, "conification" turns an object into a set of lines,
        and since lines play the role of points in projective geometry,
        "conification" ("homogenization")
        is the way to "projectivize" geometric affine objects.

        Then, these (affine) objects
        appear as "conic sections" of cones by hyperplanes,
        just the way the classical conics (ellipse, hyperbola, parabola)
        appear as conic sections.

      - [bib]

        - [43]
          Gunter Ziegler.
          Lectures on Polytopes.
          GTM No. 152. Springer Verlag, first edition,
          1997

        - [38]
          Rekha R. Thomas.
          Lectures in Geometric Combinatorics.
          STML, Vol. 33. AMS, first edition,
          2006

*** 2 Basic Properties of Convex Sets

***** 2.1 Convex Sets

***** 2.2 Carathéodory’s Theorem

***** 2.3 Vertices, Extremal Points and Krein and Milman’s Theorem

***** 2.4 Radon’s and Helly’s Theorems and Centerpoints

*** 3 Separation and Supporting Hyperplanes

***** 3.1 Separation Theorems and Farkas Lemma

***** 3.2 Supporting Hyperplanes and Minkowski’s Proposition

***** 3.3 Polarity and Duality

*** 4 Polyhedra and Polytopes

***** 4.1 Polyhedra, H-Polytopes and V-Polytopes

***** 4.2 The Equivalence of H-Polytopes and V-Polytopes

***** 4.3 The Equivalence of H-Polyhedra and V-Polyhedra

***** 4.4 Fourier-Motzkin Elimination and Cones

*** 5 Projective Spaces and Polyhedra, Polar Duality

***** 5.1 Projective Spaces

***** 5.2 Projective Polyhedra

***** 5.3 Tangent Spaces of Hypersurfaces

***** 5.4 Quadrics (Affine, Projective) and Polar Duality

*** 6 Basics of Combinatorial Topology

***** note 幾何與拓撲

      - x -
        在這本書的處理方式下
        幾何與拓撲是沒有分離的
        當考慮的是嵌入在歐氏空間中的圖形的時候
        [当强调 complex 有一种几何实现的时候]
        沒有考慮過還能給這些圖形以別樣的幾何

***** note 細節

      - x -
        可以發現這本書中對理論的處理非常細緻
        但是我覺得例子還是不夠

      - k -
        也許你可以仔細讀這本書
        然後自己補充例子
        也可以形成自己的理解方式與描述方式

***** 6.1 Simplicial and Polyhedral Complexes

      - Recall that
        a simplex is just the convex hull of a finite number of affinely independent points.
        We also need to define faces, the boundary, and the interior of a simplex.

      - x -
        在一般的處理代數拓撲的方式中
        把 simplex 定義成這樣看似是沒有必要的
        但是
        可能只有這種定義才能讓人把 simplicial complex 展示出來

      - k -
        但是重點是不要把這些圖形化出來不是嗎
        是要在不畫出來它們的條件下研究它們的性質

      - x -
        在這種構造方式中
        不能假設各個 simplex 的內點是不交的

      - k -
        但是這些以代數方式[組合方式]定義的圖形[尤其是流形]
        都可以被嵌入在高維的歐式空間中 [geometric realization]
        因此可以假定內點不交
        因此這種定義方式是具有一般性的

      - x -
        但是如此嵌入在高維空間中的圖形
        並不能被人所直觀
        如果說算數化的構造方式是爲了展示給人的化
        這種構造就也沒有什麼用處

      - A polytope is the geometric realization of some simplicial complex.

***** 6.2 Combinatorial and Topological Manifolds

      - A combinatorial d-manifold is any space, X,
        homeomorphic to the geometric realization, |K| ⊆ En,
        of some pure (simplicial or polyhedral) complex, K,
        of dimension d, whose faces are all nonsingular.

      - x -
        因此有關 manifold 的終點就在於 singularity 的定義
        但是當考慮 homotopy 的時候
        singularity 可以被化解掉

      - k -
        可能我們需要把這種化解 singularity 的想法構建到我們的語言中來

      - x -
        可能不光是要化解 singularity
        我們還要能夠在不同維度之間自由的變換
        利用 refl
        我們要能夠把點視爲線
        把線視爲面 等等

*** 7 Shellings and the Euler-Poincaré Formula

***** 7.1 Shellings

      - the aim is to proof Euler-Poincaré Formula inductively.
        but also can be viewed as finding the normal form.

***** 7.2 The Euler-Poincaré Formula for Polytopes

***** 7.3 Dehn-Sommerville Equations for Simplicial Polytopes

***** 7.4 The Upper Bound Theorem

*** 8 Dirichlet–Voronoi Diagrams

***** 8.1 Dirichlet–Voronoi Diagrams

***** 8.2 Triangulations

***** 8.3 Delaunay Triangulations

***** 8.4 Delaunay Triangulations and Convex Hulls

***** 8.5 Stereographic Projection and the Space of Spheres

***** 8.6 Stereographic Projection and Delaunay Polytopes

***** 8.7 Applications
