#+title: THE EMOTION MACHINE
#+author: Marvin Minsky
#+date: 2006

* INTRODUCTION

** Xie, How do you think about the "resourcefulness" discussed by the author?

在寫程序解決問題的時候
[比如 proof search 這類問題]
如果程序有多種解決同一個問題的方法
並且能在一個方法遇到困難時切換另一個方法
並且還能根據結果和效率批判各種解法的有效性
- reflective think 所要求的，可能不是简单的「根據結果批判」
那麼就像是智能了

** What is the author's aim in this book?

Analysis popular psychology concepts,
such as "feelings", "emotions" or "consciousness",
into more primitive concepts,
to help people understand how human minds work,
and to help people build smarter machines.

First is the concept of "resources",
then we explain mental activity (such as Anger, Love, or Embarrassment)
by trying to show how that state of mind might result from
the activities of a certain collection of mental resources.

Each of our major Ways to Think results from
turning certain resources on
while turning certain others off
-- and thus changing some ways that our brains behave.

** ><

Ch1. We are born with many mental resources.
Ch2. We learn more from interacting with others.
Ch3. Emotions are different Ways to Think.
Ch4. We learn to think about our recent thoughts.
Ch5. We learn to think on multiple levels.
Ch6. We accumulate huge stores of commonsense knowledge.
Ch7. We switch among different Ways to Think.
Ch8. We find multiple ways to represent things.
Ch9. We build multiple models ofourselves.

* FALLING IN LOVE

* ATTACHMENTS AND GOALS

* FROM PAIN TO SUFFERING

* CONSCIOUSNESS

* LEVELS OF MENTAL ACTIVITIES

* COMMON SENSE

* THINKING

* RESOURCEFULNESS

* THE SELF
