#+title: How to Solve it
#+author: Polya
#+date: 1945

* Edition

Expanded Princeton Science Library Edition,
with a new foreword by John H. Conway, 2004

* OUR LIST

** UNDERSTANDING THE PROBLEM

First. You have to understand the problem.

What is the unknown?
What are the data?
What is the condition?

Is it possible to satisfy the condition?
Is the condition sufficient to determine the unknown?
Or is it insufficient?
Or redundant?
Or contradictory?

Draw a figure.
Introduce suitable notation.

Separate the various parts of the condition.
Can you write them down?

** DEVISING A PLAN

Second. Find the connection between the data and the unknown.
You may be obliged to consider auxiliary problems if an immediate connection cannot be found.
You should obtain eventually a plan of the solution.

Have you seen if before?
Or have you seen the same problem in a slightly different form?

Do you know a related problem?
Do you know a theorem that could be useful?

Look at the unknown!
And try to think of a familiar problem having the same or a similar unknown.

Here is a problem related to yours and solved before.
Could you use it?
Could you use its result?
Could you use its method?
Should you introduce some auxiliary element in order to make its use possible?

Could you restate the problem?
Could you restate it still differently?
Go back to the definitions.

If you cannot solve the proposed problem try to solve first some related problem.
Could you imagine a more accessible related problem?
A more general problem?
A more special problem?
An analogous problem?
Could you solve part of the problem?
Keep only a part of the condition, drop the other part;
how far is the unknown then determined, how can it vary?
Could you derive something useful from the data?
Could you think of other data appropriate to determine the unknown?
Could you change the unknown or the data, or both if necessary,
so the new unknown and the new data are nearer to each other?

Did you use all the data?
Did you use the whole condition?
Have you taken into account all essential notions involved in the problem?

** CARRYING OUT THE PLAN

Third. Carry out your plan.

Carrying out your plan of the solution, check each step.
Can you see clearly that the step is correct?
Can you prove that it is correct?

** LOOKING BACK

Fourth. Examine the solution obtained.

Can you check the result?
Can you check the argument?

Can you derive the result differently?
Can you see it at a glance?

Can you use the result, or method, for some other problem?

* PART I. IN THE CLASSROOM

** 1. Helping the student.

** 2. Questions, recommendations, mental operations.

It seemed to the author that it might be worth while
to collect and to group questions and suggestions
which are typically helpful in discussing problems with students.

The list we study contains questions and suggestions of this sort,
carefully chosen and arranged; they are equally useful
to the problem-solver who works by himself.

If the reader is sufficiently acquainted with the list
and can see, behind the suggestion, the action suggested,
he may realize that the list enumerates, indirectly,
mental operations typically useful for the solution of problems.

These operations are listed in the order
in which they are most likely to occur.

** 3. Generality

** 4. Common sense.

** 5. Teacher and student. Imitation and practice.

学生必须关心问题，老师为了让学生关心问题，可以把自己的解题过程表演地很戏剧化。

** 6. Four phases.

Trying to find the solution,
we may repeatedly change our point of view,
our way of looking at the problem.
We have to shift our position again and again.

Our conception of the problem is likely to be rather incomplete when we start the work;
our outlook is different when we have made some progress;
it is again different when we have almost obtained the solution.

- (1) understand  -- clarity
- (2) plan        -- connections
- (3) carry out   -- check each steps
- (4) look back   -- to gain the most from our works

It is important to go through all the phases,
to advance while avoiding obvious mistakes,
and to gain the most from our works.

Note that:
- (1) understand & (2) plan -- like DDD
- (3) carry out -- like TDD
- (4) look back -- like refactoring

About looking back:

When looking back a solution, we should try to shift context, think the context larger,
like creative art showing the viewer context they had not noticed before

** 7. Understanding the problem.

The student should understand the problem.
But he should not only understand it, he should also desire its solution.

If the student is lacking in understanding or in interest,
it is not always his fault; the problem should be well chosen,
not too difficult and not too easy, natural and interesting,
and some time should be allowed for natural and interesting presentation.

* PART II. HOW TO SOLVE IT

* PART III. SHORT DICTIONARY OF HEURISTIC

** Problems to find, problems to prove.

在构造主义数学中，「problems to prove」与「problems to find」相同。

* PART IV. PROBLEMS, HINTS, SOLUTIONS
