MVC -- Model View Controller

* ruby on rails

- https://guides.rubyonrails.org/getting_started.html
- https://rubyonrails.org/everything-you-need
- https://rubyonrails.org/doctrine

** route

 - What does a route do?

   A route maps a request to a controller action.

 - How are routes implemented?

   Routes are implemented by declarative rules.

** controller

 - What does a controller do?

   A controller action performs the necessary work to handle the request,
   and prepares any data for the view.

 - How are controllers implemented?

   Controllers are implemented as classes, and their public methods are actions.

 - How does a controller do its job?

   A controller's job is to prepare data for view.
   To prepare data for view, controller can use model.

** view

 - What does a view do?

   A view displays data in a desired format.

 - How are views implemented?

   Views are templates, usually written in HTML.

 - How does view get data?

   Controller instance variables can be accessed by the view.

** model

 - What does a model do?

   A model provide interface to the database.

* wikipedia

- https://en.wikipedia.org/wiki/Model-view-controller

- Model

  The central component of the pattern.
  It is the application's dynamic data structure,
  independent of the user interface.

  It directly manages the data, logic and rules of the application.

- View

  Any representation of information such as a chart, diagram or table.
  Multiple views of the same information are possible,
  such as a bar chart for management and a tabular view for accountants.

- Controller

  Accepts input and converts it to commands for the model or view.

- Interactions

  - The model is responsible for managing the data of the application.
    It receives user input from the controller.
  - The view means presentation of the model in a particular format.
  - The controller responds to the user input and performs interactions on the data model objects.
    The controller receives the input, optionally validates it and then passes the input to the model.
