#+include: use-org-page.org
#+title:  is god a taoist / 上帝是道家的嗎
#+author: Raymond Smullyan

* 題解

  * 古代的聖賢在觀察和思考自然時之興趣盎然
    在如今已經鮮見了
    而本文的作者 *薩繆里安* 就是這樣一個興趣盎然的人

  * 我的翻譯只爲與朋友消遣而已別無它意

  * 中國的讀者需對西方信仰上帝的宗教有一定的瞭解
    而後才能理解作者的某些論點
    然而 如果讀者耐心的話
    在閱讀本文的過程中也足以能對西方這類宗教稍加瞭解了

  * 如果在閱讀的過程中
    您發現我的翻譯的任何方面有需要改進的地方
    請您給我發電子郵件以告知我
    我將改正


* 譯文

  * 凡人：
    上帝啊
    我向您祈禱
    打被您創造之日起 我就多災多難
    倘若您能再賜哪怕一丁點兒福給我的話
    就請赦免我 讓我不再擁有 *自由意志* ！

  * 上帝：
    你要拒絕我賜予你的最珍貴之物？

  * 凡人：
    那是強加給我的啊 您怎麼能說那是賜予呢？
    我擁有自由意志 但那並不是我選擇去擁有的
    我從來沒有自由地去選擇要擁有自由意志
    不論我情願與否 我都必須得擁有自由意志

  * 上帝：
    你爲何不想再擁有自由意志？

  * 凡人：
    因爲自由意志意味着 *道德責任* 而道德責任是我所承擔不了的！

  * 上帝：
    爲何你會覺得道德責任如此難以承擔？

  * 凡人：
    爲何？ 我真的說不清楚 但是我就知道我沒法承擔

  * 上帝：
    既然如此 如若我免除你的一切道德責任 但仍然保留你的自由意志 你滿意嗎？

  * 凡人：
    （想了一會而） 不 我不滿意

  * 上帝：
    哈
    不出我所料！
    所以說 你不光討厭自由意志所帶來的道德責任
    那麼 你還討厭自由意志什麼嗎？

  * 凡人：
    有了自由意志 我就有可能犯罪 而我討厭 *罪* ！

  * 上帝：
    如果你不想犯罪 那麼你怎麼會犯罪呢？

  * 凡人：
    上帝啊！
    我不知道爲什麼我會犯罪 但是我就是有可能犯罪！
    罪惡的誘惑隨時可能出現
    就算我努力 我也不一定能底擋住誘惑

  * 上帝：
    如果你真是因爲抵擋不住罪惡的誘惑
    那麼你就不是依你的自由意志在行事
    那麼 （至少在我看來） 那就根本不是犯罪了

  * 凡人：
    不 不！
    我還是覺得只要我再加努力就能避免犯罪的
    我也知道意志的力量是無窮的
    如果一個人全然意志於不犯罪
    那麼這個人就能不犯罪

  * 上帝：
    那麼 既知此理
    你是否盡你所能以避免犯罪了呢？

  * 凡人：
    我真的不知道！
    當下我感覺我在盡我所能以避免犯罪
    但是回想起來恐怕我並不總是如此！

  * 上帝：
    也就是說
    你並不知道你之前是否犯過罪
    所以你從來沒有犯過罪的可能性也是存在的！

  * 凡人：
    這種可能性確實存在
    但是也許我犯過罪
    這種想法讓我恐懼！

  * 上帝：
    爲什麼想到你的罪會讓你恐懼呢？

  * 凡人：
    我不知道爲什麼
    但是我知道 你確實有在來生給犯罪者分配以可怕刑罰的名聲！

  * 上帝：
    哦
    你討厭這一點嗎！
    你怎麼不早說？
    與其拐彎抹角地從自由意志談到道德責任
    爲什麼你不直接要求我不要懲罰你的罪惡？

  * 凡人：
    我是個現實主義者
    我想您不會答應那種請求的！

  * 上帝：
    這麼說來
    作爲一個現實主義者
    你瞭解我會答應什麼樣的請求了？
    我來告訴你我將怎麼辦吧！
    我將授予你一個非常特殊的豁免權
    豁免你所將犯下的任何罪行
    你想怎麼犯罪就怎麼犯罪
    我以我神聖之言的榮譽保證
    我一丁點兒也不會懲罰你
    行嗎？

  * 凡人：
    （嚇壞了）
    不 不 別這樣做！

  * 上帝：
    爲什麼？
    你不相信我的神聖之言嗎？

  * 凡人：
    我當然相信！
    但是您還不明白嗎？
    我並不想犯罪！
    對於犯罪我有的只是全然的厭惡
    這與它所帶來的懲罰無關

  * 上帝：
    這樣的話
    我來授予你更好的東西吧
    我將消除你對罪惡的厭惡
    這裏是一粒神聖的藥丸
    吃下它 你就對罪惡就沒有任何厭惡了
    你將歡天喜地地去犯罪
    你將不會後悔也不會厭惡
    並且我還向你保證
    你不會被我或被你或任何東西懲罰
    你將獲得永恆的喜悅
    來吧 吃下這粒藥丸

  * 凡人：
    不 不！

  * 上帝：
    你失去理智了嗎？
    我甚至除去了你對罪惡的厭惡
    這是你最後的障礙了

  * 凡人：
    我還是不接受！

  * 上帝：
    爲何？

  * 凡人：
    我相信這粒藥丸確實會消除我今後對罪惡的厭惡
    但是我現在對罪惡的厭惡就足以阻止我吃下它了

  * 上帝：
    我建議你吃了它！

  * 凡人：
    我拒絕！

  * 上帝：
    那麼 你是在依你的自由意志來拒絕的嗎？

  * 凡人：
    是！

  * 上帝：
    所以
    看來你的自由意志很好用啊
    不是嗎？

  * 凡人：
    我不明白！

  * 上帝：
    你現在能夠用自由意志來拒絕這樣一個可怕的提議
    你難道不感到高興嗎？
    你覺得我強迫你吃下它怎麼樣？
    你願意嗎？

  * 凡人：
    不 不 請別！

  * 上帝：
    我當然不會
    我只是在舉例說明自由意志的作用而已
    現在 我來這樣做
    不強迫你吃藥丸了
    假使我現在答應你原初的祈禱
    我消除你的自由意志
    但是要知道
    當你沒有了自由意志的時候
    你就會吃下這個藥丸了
    如何？

  * 凡人：
    當我沒有了自由意志
    我怎麼還能選擇接受藥丸呢？

  * 上帝：
    我沒說你會選擇去接受
    我只是說你會接受
    讓我們假設你會依照純粹的註定的命運而行動
    而這個註定的命運就是
    你確實會吃下藥丸

  * 凡人：
    我還是拒絕

  * 上帝：
    那麼
    你拒絕我消除你自由意志的提議了
    這有背於你原初的祈禱
    不是嗎？

  * 凡人：
    現在我明白你的論點了
    你的論證很精妙
    但是我不確信它們真的正確
    我們需要重新回顧一下其中的某些要點

  * 上帝：
    當然可以

  * 凡人：
    你的論述中有兩點在我看來是矛盾的
    首先你說 不是依自己的自由意志的行爲就不算犯罪
    而後你又說 你會給我一個藥丸它可以使我喪失自由意志
    這樣我就能盡情犯罪了
    但是 照你先前所說
    當我沒了自由意志之後
    我怎麼還能犯罪呢？

  * 上帝：
    你混淆了我們對話的不同的兩部分
    我從來沒有說藥丸會消除你的自由意志
    它只會消除你對罪惡的厭惡而已

  * 凡人：
    我想我確實有點兒困惑

  * 上帝：
    沒關係
    讓我們從新開始
    假設我同意消除你的自由意志
    但是條件是
    你得知了你將施行很多行爲
    而這些行爲在你現在看來都是罪行
    按照定義來說
    你將不會犯罪了 因爲你的行爲並非源於你的自由意志
    這些行爲將不背負任何道德責任或懲罰或任何東西
    然而確實 這些行爲在你現在看來都是罪行
    你現在確實會對這些行爲感到厭惡
    但是這些厭惡會消失的
    一旦自由意志被消除了
    你就不會再對這些行爲感到厭惡了

  * 凡人：
    不
    但是我現在對這些行爲感到厭惡
    現在的厭惡之情以足以阻止我接受你的提議了

  * 上帝：
    哦！
    讓我清清楚楚把話說明白了
    你現在不再希望我消除你的自由意志了

  * 凡人：
    （不情願地）
    沒錯 我想是的

  * 上帝：
    好吧
    我也同意不這麼做
    但是 我還是不明確地明白
    你現在爲什麼不希望自由意志被消除了
    請在告訴我一遍

  * 凡人：
    因爲 如你所說
    沒有了自由意志 我將比我現在更罪惡

  * 上帝：
    但是我已經告訴你了
    沒有自由意志你就沒有罪惡了

  * 凡人：
    但是如果我現在選擇不要自由意志
    那麼我的行爲還是罪惡的
    不是就將來而言
    而是就現在而言
    對於現在的我而言
    這個選擇本身就是罪惡的

  * 上帝：
    看來你掉進了一個圈套裏
    不是嗎？

  * 凡人：
    我當然中了圈套！
    你把我置於了兩難的境地！
    我現在怎麼做都是錯
    如果我保留自由意志那麼我就繼續可能犯罪
    如果我在你的幫助下消除自由意志
    這樣做對我來說就是罪惡的

  * 上帝：
    但是同樣
    你也將我置於了兩難的境地
    我願意依照你的選擇 保留或者消除你的自由意志
    但是哪樣都不能讓你滿足
    我希望幫你
    但是看來我沒法幫你

  * 凡人：
    沒錯！

  * 上帝：
    但是既然這並不是我的錯
    你又爲何遷怒於我？

  * 凡人：
    因爲你一開始就把我置於了如此可怕的處境！

  * 上帝：
    但是
    你剛才同意了
    我做什麼也不能令你滿意

  * 凡人：
    確實
    你現在做什麼也不能令我滿意
    但是這並不代表你之前不能有所作爲

  * 上帝：
    爲什麼？
    我之前所能所爲何？

  * 凡人：
    很顯然你一開始就不應該給我自由意志
    既然你已經給我了
    已經太晚了
    我現在做什麼都是不好的
    你在最初就不應該給我自由意志

  * 上帝：
    哦
    原來是這樣！
    爲什麼我從來沒有給你過自由意志會更好呢？

  * 凡人：
    因爲這樣我就根本不能犯罪了

  * 上帝：
    我總是願意從我所犯的錯誤中學習些知識

  * 凡人：
    什麼！

  * 上帝：
    我知道
    這聽起來有點 自己褻瀆神靈 不是嗎？
    這甚至涉及到了一個邏輯悖論！
    一方面 正如你所被教導的
    聲稱我能夠犯錯的 任何有意識的生物 從道德上將都是錯誤的
    而另一方面
    我有做任何事的權利
    並且我也是一個有意識的生物
    所以問題是
    我有沒有權利去聲稱自己能夠犯錯？

  * 凡人：
    你是在說笑嗎？
    你的前提之一就是錯誤的
    我並沒有被教導說
    任何有意識的生物對你的全知全能的質疑都是錯誤的
    只有這樣做的凡人才是錯誤的
    而因爲你不是凡人
    所以你顯然不受這個禁令的約束

  * 上帝：
    很好
    你的有很高水準的理性才能認識到這一點
    然而
    對於我所說的
    “我總是願意從我所犯的錯誤中學習些知識"
    你又確實顯現出了驚訝之情

  * 凡人：
    我當然驚訝了
    不是驚訝與你所戲稱的自己褻瀆神靈
    也不是驚訝與你有權利這樣說
    而僅僅是驚訝與你這樣說了這句話
    因爲我確實被教導說 你從來不會犯任何錯誤
    所以我驚訝與你說你能夠犯錯誤

  * 上帝：
    我並沒有說我能夠犯錯誤
    我只是說
    如果我犯錯誤 我將樂於從我所犯的錯誤中學習些知識
    對這個命題的陳述
    與 這個命題的前提是否能被實現
    並沒有關係

  * 凡人：
    讓我們停止在這一個問題上的詭辯吧
    你到底是否承認給我自由意志是一個錯誤呢？

  * 上帝：
    這也正是我想要建議我們去一起探究的問題
    讓我來回顧一下你當前的困境
    你不想要自由意志
    因爲有了自由意志你就能犯罪
    而你不想犯罪
    （然而我還是覺得這一點令人不解 因爲畢竟只有當你想要犯罪你才能夠犯罪 但是讓我們先暫時掠過這個話題）
    另一方面
    如果你同意放棄你的自由意志
    你現在將會對未來的罪行承擔責任
    因此 我從以開始就不應該給你自由意志

  * 凡人：
    沒錯！

  * 上帝：
    我很瞭解你的感受
    很多凡人 甚至沒有神學家
    都抱怨過在這個問題上我的做法是不公平的
    即 是我 而不是衆生們 來決定他們是否應該擁有自由意志的
    這樣我就保持了衆生對其行爲的責任
    換句話說
    他們感覺跟我簽訂了一個在一開始他們就從未認同的條約

  * 凡人：
    沒錯！

  * 上帝：
    如我所說
    我完全明白這種感受
    我能理解這種抱怨之產生
    但是這種抱怨卻只產生與對這裏的真正重要的問題的虛假的理解
    我將啓示你它們是什麼
    我想結果會令你驚訝的
    但是與其直接告訴你
    我將繼續使用蘇格拉底的教學法
    重申一下
    你惋惜我給了你自由意志
    我斷言當你明白真正的因果之後你將不再有這種遺憾
    爲了證明我的斷言
    我將這樣來做
    我去創造一個新的宇宙 即一個新的連續統
    在這個新的宇宙中
    將生出向你一般的凡人
    爲了討論起來方便
    我們可以說 你將重生
    現在
    對於給這個新的凡人自由意志與否
    你希望我怎麼做？

  * 凡人：
    （如釋重負）
    哦 請求您！ 免除他對自由意志的擁有吧！

  * 上帝：
    好的
    我將如你所願
    但是你有沒有認識到新的凡人將犯下各種可怕的罪行？

  * 凡人：
    但是他們將不是罪惡的
    因爲他們根本沒有自由意志

  * 上帝：
    不論你稱其爲罪惡與否
    事實是
    他們的可怕行爲將給很多有知覺的生靈帶來極大的痛苦

  * 凡人：
    （停了一會兒）
    上帝啊
    你又讓我進入了圈套！
    總是同樣的把戲！
    如果我說
    在創造他們的時候不要給他們自由意志
    他們還是會犯下殘暴的行徑
    那麼 他們是當真沒有犯罪了
    但是我卻又成了合準此決定的罪人

  * 上帝：
    這樣的話
    讓我給你個更好的提議！
    現在
    我已經決定了是非給他們自由意志
    我把我的決定寫在這片紙上
    只有之後才讓你看
    但是我意已決而不可挽回
    你做任何事也改變不了我的決定了
    你對這件事沒有責任
    而我只想知道
    你希望我如何決定？
    責任全然在我 而不在你
    所以你可以告訴我你的真實想法而不用害怕
    那麼你希望我如何決定呢？

  * 凡人：
    （停了好一會兒）
    我希望你給他們自由意志

  * 上帝：
    有趣極了！
    我消除了你最後的障礙！
    如果我不給他們自由意志
    也沒有罪責會被加於任何人
    那麼爲什麼你希望我給他們自由意志呢？

  * 凡人：
    因爲不論罪惡與否
    重點在於如果你不給他們自由意志
    那麼 如你所述
    他們將到處傷害他人
    而我不想有人受到傷害

  * 上帝：
    （常疏一口氣）
    終於！
    你明白了真正的重點！

  * 凡人：
    重點何在？

  * 上帝：
    犯罪並不是重點！
    重點是人和其他生靈不受傷害！

  * 凡人：
    看來你是個功利主義者！

  * 上帝：
    我是個功利主義者！

  * 凡人：
    什麼！

  * 上帝：
    無論你是否驚訝
    我都是個功利主義者
    不是一神論者
    注意了
    而是個功利主義者

  * 凡人：
    我真不敢相信這一點！

  * 上帝：
    使得我明白
    你所接受的宗教教育所教導你的正相反
    你可能想我會更像一個康德主義者
    而不是一個功利主義者
    但是你所接受的教育是錯誤的

  * 凡人：
    你讓我啞口無言了！

  * 上帝：
    我讓你啞口無言了
    是嗎！
    這也許並不是什麼壞事
    你確實有過量說話的傾向 ^-^
    但是
    撇開玩笑不談
    嚴肅地說
    你認爲爲什麼我在一開始就給予了你自由意志？

  * 凡人：
    爲什麼？
    我從來沒有仔細想過你爲什麼這樣做
    我所爭論的只是你是否應該這樣做而已！
    那麼爲什麼呢？
    我所能想到的就只是標準的宗教解釋而已
    即 沒有自由意志
    一個人就沒法被記功記過 而接受救贖或被罰下地獄
    所以沒有自由意志
    我們就沒法賺取獲得永生的權利了

  * 上帝：
    太有趣了！
    我有永恆的生命
    你覺得我是做了什麼而轉來它的嗎？

  * 凡人：
    當然不是！
    對你而言這是不同的
    你本爲至善者
    沒有必要記功記過以賺取永生

  * 上帝：
    真的嗎？
    這就把我置於了一個令人嫉妒的境地
    不是嗎？

  * 凡人：
    我不明白

  * 上帝：
    我是永遠地幸福快樂的
    不曾有任何磨難 或犧牲 或掙扎 或邪惡的誘惑 或任何類似的事
    沒有任何形式的記功記過
    我享受着快樂幸福的永生
    而相反
    可憐的凡人們必須付出辛勞 經歷磨難 還有各種道德衝突
    這都是爲了什麼？
    你甚至不知道我是否真的存在
    你也不知道來世是否真的存在
    就算存在你也不知道來世你將如何
    無論你向我奉獻 何等貢品 何等犧牲
    你都不會被保證你之奉獻已經足夠讓你獲得救贖
    要知道 我已經擁有類似救贖的境地了
    而我從沒有經歷過任何悲慘的過程以賺取它
    你難道不嫉妒我這一點嗎？

  * 凡人：
    但是嫉妒你是瀆神的！

  * 上帝：
    哦 不必這樣！
    你又不是在跟你主日学的老師談話
    你是在跟我談話
    瀆神與否 都不重要
    重要的是你是否嫉妒我
    而不是你是否有權利嫉妒我
    那麼你嫉妒我嗎？

  * 凡人：
    我當然嫉妒了！

  * 上帝：
    很好！
    依你現在的世界觀來看
    你應該非常之嫉妒我才對
    但是我想
    當獲得了更具現實意義的世界觀之後
    你就不會嫉妒我了
    所以你是當真囫圇吞棗地學下了用以教導你用的想法了
    即 你的人生其實是一場考驗
    給你自由意志是爲了試探你
    看看你的功過是否可以讓你賺得幸福永生
    但是令我疑惑的是
    如果你真的相信我如衆人所言的那般仁慈善良
    爲什麼我還會要求人們記功記過以賺幸福和永生呢？
    爲什麼我不直接把這些福祉賜予大家而不論功過呢？

  * 凡人：
    我被教導說
    你之道德與公証要求善有善報惡有惡報

  * 上帝：
    那麼 所受的教育是錯誤的

  * 凡人：
    但是宗教的文本充滿了類似的言論！
    比如 喬納森·愛德華茲的 《落在忿怒之神手中的罪人》
    在其中作者描述你手握你的敵人如可恨的毒蠍
    並將其吊於地獄的烈火之上
    只因你的憐憫他們方可不如地獄

  * 上帝：
    幸好我從未聽過喬納森·愛德華茲先生的言辭激烈的佈道
    某些佈道所傳教都只是誤解而已
    其題目 《落在忿怒之神手中的罪人》 即爲虛言
    首先我從不忿怒
    其次我不用 “罪” 這個詞來思考
    最後我沒有敵人

  * 凡人：
    你的意思時說你不恨任何人
    還是沒有任何人恨你？

  * 上帝：
    我的意思是前者
    然而後者也是正確的論斷

  * 凡人：
    哦 不對 不對
    我就知道有人公開宣稱過他們恨你
    有時我也恨過你！

  * 上帝：
    是你恨過你對我的想像而已
    這與恨我本尊不同

  * 凡人：
    你是說恨一個你的虛假的幻想沒有錯
    只有恨你本尊才有錯？

  * 上帝：
    不
    根本不是那個意思
    我所說的是更多
    我所說的與對錯無關
    我所說的是 識我本真者將會發現
    從心理學角度講 恨我是一件根本不可能的事

  * 凡人：
    那麼
    既然我們凡人對你的真正性質有太多的誤解
    爲什麼你不啓示我們？
    爲什不把我們引入坦途正路？

  * 上帝：
    你何以認爲我沒有這麼做呢？

  * 凡人：
    我的意思是
    爲什麼你不顯現於我們的知覺之中
    然後向我們指出我們的謬誤之處呢？

  * 上帝：
    你當真如此天真地相信我是那種能夠顯現於你知覺者？
    不如說我就是你的知覺

  * 凡人：
    （震驚地）
    你是我的知覺？

  * 上帝：
    不全然如此
    我是更多
    但是 相比於我是能被知覺感知者而言
    這已經更接近真實了
    我並不是一個客體
    與你同類地我是一個主體
    而主體可以感知但是不能被感知
    汝之視我 猶汝之觀己之思
    你可以去看一個蘋果
    但是你看蘋果這件事是無法被看到的
    我更像是後者而不是前者

  * 凡人：
    如果我不能看到你
    我怎麼能知道你的存在呢？

  * 上帝：
    問得好！
    你到底是如何知道我的存在的呢？

  * 凡人：
    我正在跟你說話
    不是嗎？

  * 上帝：
    你怎麼知道你是在跟我說話呢？
    如果你告訴一個心理醫生
    “昨天我跟上帝談話了"
    你覺得心理醫生會怎麼說？

  * 凡人：
    這取決於那個心理醫生了
    他們大多是無神論者
    所以我想他們大多會告訴我
    我其實是在跟自己說話

  * 上帝：
    那麼他們就說對了！

  * 凡人：
    什麼？
    你的意思是你不存在？

  * 上帝：
    你真是有很強的形成錯誤結論的能力！
    只因你在跟你自己說話
    就能得出 我不存在 個結論？

  * 凡人：
    如果我想我是在跟你說話
    而其實我是在跟我自己說話
    那麼你還怎麼能存在呢？

  * 上帝：
    你的問題基於謬論和誤解
    首先 你現在是否在跟我說話 和 我之存在 是完全不相關的兩個問題
    即使你不是在跟我說話 （顯然你是在跟我說話）
    那也不能得出 我不存在 這個論斷

  * 凡人：
    好吧 你說的對！
    那麼我不說 “如果我在跟我自己說話 那麼你就不存在"
    我轉而說 “如果我在跟我自己說話 那麼我就不是在跟你說話"

  * 上帝：
    不同的命題
    但是還是錯的

  * 凡人：
    哦
    如果我僅僅是在跟自己說話
    那麼我怎麼還能是在跟你說話？

  * 上帝：
    你用 “僅僅” 這個詞會導致誤解！
    我可以提出幾個邏輯上的可能性
    在其中 你在跟你說話
    並不蘊含 你不在跟我說話

  * 凡人：
    就告訴我一個可能性！

  * 上帝：
    顯然 一個可能新是 你和我是同一的

  * 凡人：
    真是瀆神的想法
    我認爲這完全是瀆神的想法！

  * 上帝：
    就某些宗教信仰而言 這確實是瀆神的想法
    但是就另一些宗教信仰而言 這是樸素而簡單的 即可就被認識到的 事實 而已

  * 凡人：
    所以說
    解決我的邏輯困境的唯一方法就是相信你我是同一的？

  * 上帝：
    當然不是！
    這只是方法之一而已
    還有別的方法
    比如
    也許你是我的一部分
    這樣你就是在跟一部分我說話
    也許我是你的一部分
    這樣你也許是在跟一部分的你說話
    也許你我只是部分地相衝和
    這樣你也許在跟我們的交集說話
    即使是在 你我是全然分離的情況下
    也可以想像你是在同時和你我說話

  * 凡人：
    所以你宣稱你不存在

  * 上帝：
    沒有
    你又在形成錯誤的結論了！
    我是否存在的問題還根本沒有關係
    我所說的只是
    根據你在跟你自己說話這個事實
    不能得出我不存在這個結論

  * 凡人：
    好吧 我承認你的論點
    但是我真正想知道的是你是否存在？

  * 上帝：
    多麼奇怪的問題！

  * 凡人：
    爲什麼這麼說？
    人們問這個問題有數個世紀了

  * 上帝：
    我知道！
    這個問題本身並不奇怪
    奇怪的是你在問我

  * 凡人：
    爲什麼？

  * 上帝：
    因爲你就單單質疑我的存在！
    我完全能理解你的焦慮
    你擔心你現在跟我有關的經歷都只是幻覺
    但是
    當你陷於對其存在質疑中
    你又何以能確知其存呢？

  * 凡人：
    所以說你不會告訴我你是否存在了？

  * 上帝：
    我並非有意爲之！
    我只是想說明 我能給出的回答不能滿足你而已
    比如我直接說 “我存在” 或 “我不存在"
    你會信服嗎？

  * 凡人：
    如果你都不能告訴我你是否存在
    那麼還有誰可以呢？

  * 上帝：
    那是一個沒人能告知你答案的問題
    你必須自己找尋

  * 凡人：
    如何我才能自己找到這個問題的答案呢？

  * 上帝：
    這也是一個沒人能告知你答案的問題
    你必須自己找尋

  * 凡人：
    這麼說來 你根本幫不了我了？

  * 上帝：
    我是說
    我不能直接告知你答案
    但是那並不代表我不能幫助你

  * 凡人：
    你還能如何幫我呢？

  * 上帝：
    這個問題留於我即可 ^-^
    我們已經離題很遠了
    我想回到關於 我給你自由意志的原因的問題
    你最初的想法是 我這麼做是爲了考驗你的德行是否足夠獲得救贖
    道德家們可能喜歡這種想法
    但是我很討厭這種想法
    你不能想到任何更好的 更人性的理由
    爲什麼我給你自由意志？

  * 凡人：
    我有一次向一位正統的拉比提了這個問題
    他告訴我
    我們被創造的方式決定了
    只有當我們認爲是我們依德行賺取了救贖之後我們才能享受救贖
    而爲了賺取救贖 我們當然就需要自由意志了

  * 上帝：
    這個解釋比之前的好多了
    但是還是去真理甚遠
    按正統的猶太教之說法
    我創造了天使
    天使沒有自由意志
    它們因體現了我之真見而如此徹底地被善吸引
    它們從來沒有哪怕一丁點兒被引向惡
    它們真是沒得選擇
    並且儘管它們不必賺取 它們還是能有永恆的幸福
    那麼
    如果你的那位拉比的解釋是正確的
    爲什麼我不只造天使而不造凡人呢？

  * 凡人：
    真是難倒我了！
    你爲什麼不只造天使呢？

  * 上帝：
    因爲拉比的解釋是錯誤的
    首先我從來沒創造過任何現成的天使
    所有有知覺的生命都最終所趨向的狀態可以被成爲是 “天使態"
    但是正如同人這個物種是生物進化中的一個階段
    天使只是宇宙演化的最終結果而已
    所謂聖人與罪人之間的區別只在於
    前者比後者老很多
    不幸的是
    只有經過了數代生命的輪迴之後
    人們才學習到了 邪惡是痛苦的 這個重要的真理
    道德家的 所有的 用以勸解人們不要犯下罪惡邪行的 論述與說教
    在這個基本的真理面前變得蒼白無力
    即 邪惡就是痛苦的
    不 我親愛的朋友
    我不是一個道德家
    我是一個徹頭徹尾的功利主義者
    我被想成是一個道德家的典範這件事
    是人類最大的悲劇之一
    我在萬物之藍圖中的角色
    （如果你願意使用這種錯誤的表達方式的話）
    不是去懲罰或獎勵
    而是去促進其進程
    其進程就在於 所有的生命都臻於完美

  * 凡人：
    爲什麼說你的表達式錯誤的呢？

  * 上帝：
    在兩個方面這種表達會引起誤解
    首先 說我在萬物之藍圖中的角色即是不恰當的
    我就萬物之藍圖本身
    其次 同樣地
    說我對進程的幫助是不恰當的
    萬物之藍圖中的角色即是不恰當的
    我就是其進程本身
    當古代的道家稱我爲道並述我之無爲時
    他們就很接近真理了
    然而儘管無爲
    萬物因我而爲
    用現代的詞來說
    我不是宇宙演化的起因
    而是宇宙之演化本身
    我認爲 就人類現在演化過程中的位置而言
    對於我 人們所能建構的最精確而豐富的定義就是
    我就是啓示過程本身
    而那些想要戲考什麼是魔鬼的人 （儘管我希望他們根本別這樣做！）
    可以以類比的方式把魔鬼定義爲
    這個過程所需時間之漫長
    從這個角度看來魔鬼是必要的
    因爲其過程本身確實很漫長
    對此我也無能爲力
    但是我向你保證
    一旦其過程被正確地理解了
    那麼其所耗時間之漫長也就不會再被認爲是嚴重的缺陷或是邪惡了
    它將被認爲是其過程本身
    我知道你現在因處於有限之苦海而不會安於這種想法
    但是其妙在於
    一旦你知悉了基本的態度
    你的有限之苦海就會開始消弭並最終止息了

  * 凡人：
    我聽說過這種論點
    並且我也樂意去相信它
    但是
    假設我自己成功地從你的永恆的視角來看待一切了
    我想必會因而變得更幸福
    那麼我對他人的責任呢？

  * 上帝：
    （笑）
    你讓我想起了大乘佛教！
    其人人階言 “后於萬物入極樂"
    所以每個人都等着他人先行 怪不得會耗費很長時間呢！
    而小乘佛教也錯了
    其人人階信 救贖之路無人可以相助 人人必無所依賴
    這樣每個人都獨自找尋自己的救贖
    殊不知此出世超然的態度只會讓救贖變得不可能
    其實
    救贖是這樣一個過程
    它部分是就個體而言的
    而部分是就集體而言的
    執其一端而堅信者大錯特錯矣
    要知道
    幫助他人之最好辦法就是先使自己獲得啓蒙

  * 凡人：
    你的自我描述中有一點令我大惑不解
    你描述自己之本質爲一個過程
    這就把你置於了一個不人性的境地
    然而有很多人是需要一種人性的上帝的

  * 上帝：
    只因衆人之需要
    我就需如此？

  * 凡人：
    當然不是
    但是爲了使凡人能夠接受
    一個宗教必須滿足凡人的需求

  * 上帝：
    我明白了
    但是人性與否
    實爲觀者之觀 而非是者所是
    關於我之具人性與否的爭論有很多
    但是這都很愚蠢 因爲二者皆是錯的
    依某之見 我是人性的
    依某之見 我又不是
    人也如此
    例如 一個外星生命 可能視人爲 “非人性的"
    只如遵照預先給定的嚴格物理定律而運作的原子的集合而已
    外星生命之視人
    正如一般人類之視螞蟻
    而對於像我這種真正瞭解螞蟻的生命而言
    螞蟻也具有和人一般的 “人性"
    視一物之有人性與否 並無對錯之分
    而大體上說
    你越是瞭解一物 它於你就越有 “人性"
    舉例來說
    你認爲我是有人性的嗎？

  * 凡人：
    我正在跟你說話呢
    不是嗎？

  * 上帝：
    沒錯！
    這樣看來你是視我爲有人性的
    然而在別的觀點下視我爲無人性的也沒錯

  * 凡人：
    但是
    如果當真如你所說
    你是一個抽象的如一個過程一般的東西
    我不認爲我和區區一個 “過程” 說話有什麼意義

  * 上帝：
    你用了 “區區” 這個詞
    也也可以說你生活在 “區區一個宇宙中"
    並且
    爲什麼一個人物所做的所有的事情必須有意義呢？
    閬一棵樹說話有意義嗎？

  * 凡人：
    當然沒有！

  * 上帝：
    但是很多小孩或者原始人都和樹說話呢

  * 凡人：
    但是我不是小孩和原始人

  * 上帝：
    我知道的
    但是這真不幸

  * 凡人：
    爲什麼不幸？

  * 上帝：
    因爲很多小孩和原始人都擁有你們這類人沒有的 *原初直覺*
    我想以後樹說說話對你可能是有好處的
    也許比跟我說話更受益呢！
    但是我們又離題了！
    之前我們是想要明白爲什麼我給你了自由意志

  * 凡人：
    我一直在想這個問題呢

  * 上帝：
    你並沒有專注於我的對話嗎？

  * 凡人：
    我當然有
    但是同時在另一個層上我並沒有忘記原來的問題

  * 上帝：
    那麼你有結論了嗎？

  * 凡人：
    你說了 自由意志不爲測試我們的價值
    你否定了我們需要記功記過以賺取福祉
    你聲稱自己爲一個功利主義者
    並且
    你爲我能形成關於罪的更好的認識而感到高興
    即 罪本身並非不好 而不好的是它所帶來的痛苦

  * 上帝：
    畢竟除此之外罪之爲罪還有什麼不好呢？

  * 凡人：
    我現在也認識到這一點了
    但是
    恐怕我一直都是受這些道德家的說教的影響的
    他們認爲罪之爲罪本身就不好
    這樣看來
    我想你給我們自由意志的唯一原因就是
    擁有自由意志人們就將更少地傷害他人與他們自己

  * 上帝：
    太好了！
    這是目前你所給出的最好的緣由了！
    我向你保證
    如果我能選擇給予自由意志與否的話
    這就將是我給予自由意志的原因了

  * 凡人：
    什麼！
    你是說你並沒有選擇給我們自由意志嗎？

  * 上帝：
    我親愛的朋友
    我不能選擇給予你自由意志
    正如我不能選擇讓等邊三角形的三個角相等一樣
    我可以選擇去畫或不去畫一個等邊三角形
    但是當我畫出一個等邊三角形之後
    它的三個角就必定是相等的

  * 凡人：
    我想你能做任何事！

  * 上帝：
    只有邏輯上可能的事而已
    正如聖托馬斯所言
    “上帝不能爲不可爲之事 視此爲上帝之缺陷者是罪惡的"
    我同意他的觀點
    但是我會把他所用的 “罪惡” 這個詞 換成 “錯誤” 這個詞

  * 凡人：
    不論如何
    我還是不明白
    你說 你沒有給我自由意志 是什麼意思

  * 上帝：
    是時候告知你了
    所有的這些討論從一開始就是基於很多謬見的
    在開始的時候你抱怨我給你了自由意志
    由此
    我們僅從倫理學層次討論了我應該不應該這樣做
    你從來沒有想過就這件事而言
    我根本無以選擇

  * 凡人：
    我還是不明白！

  * 上帝：
    當然如此了！
    因爲你只能從道德家的角度來看問題
    這個問題的更基本的形而上的方面
    你根本就沒有考慮過

  * 凡人：
    我還是看不出你論證的目的

  * 上帝：
    在你要求我消除你的自由意志的時候
    是否你首先應該問的問題是
    你有沒有自由意志呢？

  * 凡人：
    我不假思索地肯定了這個命題

  * 上帝：
    爲何？

  * 凡人：
    我不知道
    那麼 我有自由意志嗎？

  * 上帝：
    有

  * 凡人：
    那麼
    你沒什麼說 我不應 不假思索地肯定這個命題 呢？

  * 上帝：
    因爲你不應
    因爲一個命題是真命題
    並不代表你應該不假思索
    而直接肯定這個命題

  * 凡人：
    不論如何
    得知我關於我有自由意志的直覺是正確的
    我就放心了
    有時我還擔心宿命決定論者是正確的呢

  * 上帝：
    他們是正確的

  * 凡人：
    等一下
    那我到底有沒有自由意志？

  * 上帝：
    我告訴你了 你有
    但是這並不代表 *宿命決定論者* 是錯誤的

  * 凡人：
    那麼
    我的行爲都是由自然之律決定的嗎？

  * 上帝：
    “決定” 一詞 在此很具有很強的誤導性
    關於 自由意志與決定論 的論戰 正是歸咎於此誤解
    你的行爲當然與自然之律相諧
    但是
    說你的行爲被自然之律決定
    就會引起錯誤的心理假象
    好像你本可以與自然之律向衝突
    而自然之律是如此強力
    以至於不論你喜歡與否它都會 “決定” 你的行爲
    但是
    其實你的意志根本不可能與自然之律向衝突
    你和自然之律本爲一物

  * 凡人：
    你時說我不能違背自然？
    假使我非常固執
    並且我決定不遵循自然之律
    什麼能阻止我呢？
    只要我足以固執
    甚至連你都無以阻止我

  * 上帝：
    你非常對！
    我並不能阻止你
    沒有什麼能阻止你
    但是根本不必阻止你
    因爲你從來也不能開始去違背自然之律
    正如歌德之言
    “試以行有違自然之行 於此行中 我亦必依自然之律"
    你難道還沒發現？
    所謂的 “自然之律"
    只不過是對你 和其他生命 和萬物 之行爲的描述而已
    是對你行爲的描述
    而非對你行爲的指定
    亦非一決定你行爲的力量
    你的行爲必蘊含於自然之律
    你也可以說
    你的選擇也必蘊含於自然之律

  * 凡人：
    所以你聲稱我沒有決定去違反自然之律的能力？

  * 上帝：
    『譯者： 這裏 我的翻譯略去了關於一以英文語法爲依據的次要論點』
    要知道
    自由意志的學說會告訴你是你在做決定
    而決定論的學說會告訴你是你之外之物在決定着你
    這裏的難點在於
    你把世界分類了 “我” 與 “非我"
    那麼
    你是從什麼地方區分出你與外部世界的邊界的呢？
    一旦你認識到了
    所謂的你與外部世界實爲連續的一體
    那麼
    你就再也不會被
    是你在控制自然還是自然在控制你
    之類的問題困擾了
    這樣關於自由意志與決定論的困惑也就消除了
    讓我來做一個粗糙的類比
    想像兩個星體在萬有引力的作用下相向運動
    如果這兩個星體是有知覺的話
    那麼 它們可能會疑問 是誰在產生拉力
    可以說拉力由二者同時產生
    也可以說拉力並非由二者之一獨自產生
    更應該說
    這二者所共同組成的結構本身才是重點

  * 凡人：
    你之前說我們的討論都基於謬見
    你還沒告訴我這些謬見是什麼

  * 上帝：
    你覺得我可以創造你而不給你自由意志
    你認爲這是真的可行的
    並且你疑問爲什麼我沒有選擇這樣做！
    你從來沒有想過
    說一個沒有自由意志的有意識的生命
    正如同說一個不產生萬有引理的有質量的物體
    （二者之間所能形成的類比還有很多呢！）
    你能想像一個沒有自由意志的有意識的生命嗎？
    那將會是什麼樣的呢？
    我想一直以來誤導者着你的是
    你受到了錯誤的教育
    說
    我給人以自由意志這個天賦
    好像我先創造了人
    然後賜予了人自由意志這個額外的屬性
    也許你認爲我有一只 “畫筆"
    我給某些造物點上了自由意志這個屬性
    而對於另一些造物我沒有這麼做
    不是的
    自由意志不是額外的
    自由意志是 *意識* 之本質成分
    一個沒有自由意志的有意識的生物就是一個形而上的悖論而已

  * 凡人：
    既然依你所說
    我其實是
    把一個形而上的問題 誤解成了一個道德的問題
    那麼你有爲何跟我進行這些討論呢？

  * 上帝：
    因爲我想
    這種對話對於你的 關於道德的思想之毒 是一味良藥
    你的大部分形而上的謬見都歸咎於錯誤的關於道德的概念
    所以這後者是先要被肅清的
    現在我們必須分別了
    直到你在此需要我
    我想我們如今的匯聚應該能支撐你的思想很長一段時間
    但是別忘了我跟你說的 *樹*
    當然
    如果你覺得很傻的話 也不必真的去跟樹說話
    但是
    你能從它們學到太多的東西了
    從岩石也如此
    從河流也如此
    從自然界的其他方面也如此
    沒有比這種自然主義的傾向
    更能摒除所有那些 關於 “罪” “自由意志” “道德責任” 的 病態的 扭曲的 思想了
    在歷史的某一階段
    這些思想觀念也許確實有用處
    即 那些君主擁有無限權利的時代
    只有對可怕的地獄的極端恐懼
    才能限制這些君主的行爲
    但
    人類進步了
    那種可怕的思考方式不再必要了
    鉴智禅师的這首詩 也許能在今後助你回憶起我的講話
    『譯者： 本文的作者所引的詩句是 《信心銘》 中四句的英譯
    而我的翻譯從英文譯回中文 而不引源詩』
    欲見本真 莫守是非 是非之爭 是爲心病

* 原文

  * Mortal:
    And therefore, O God, I pray thee,
    if thou hast one ounce of mercy for this thy suffering creature,
    absolve me of having to have free will!

  * God:
    You reject the greatest gift I have given thee?

  * Mortal:
    How can you call that which was forced on me a gift?
    I have free will, but not of my own choice.
    I have never freely chosen to have free will.
    I have to have free will, whether I like it or not!

  * God:
    Why would you wish not to have free will?

  * Mortal:
    Because free will means moral responsibility,
    and moral responsibility is more than I can bear!

  * God:
    Why do you find moral responsibility so unbearable?

  * Mortal:
    Why? I honestly can't analyze why;
    all I know is that I do.

  * God:
    All right,
    in that case suppose I absolve you from all moral responsibility
    but leave you still with free will.
    Will this be satisfactory?

  * Mortal:
    (after a pause)
    No, I am afraid not.

  * God:
    Ah, just as I thought!
    So moral responsibility is not the only aspect of free will to which you object.
    What else about free will is bothering you?

  * Mortal:
    With free will I am capable of sinning,
    and I don't want to sin!

  * God:
    If you don't want to sin,
    then why do you?

  * Mortal:
    Good God!
    I don't know why I sin,
    I just do!
    Evil temptations come along,
    and try as I can, I cannot resist them.

  * God:
    If it is really true that you cannot resist them,
    then you are not sinning of your own free will
    and hence (at least according to me) not sinning at all.

  * Mortal:
    No, no!
    I keep feeling that if only I tried harder I could avoid sinning.
    I understand that the will is infinite.
    If one wholeheartedly wills not to sin, then one won't.

  * God:
    Well now, you should know.
    Do you try as hard as you can to avoid sinning or don't you?

  * Mortal:
    I honestly don't know!
    At the time,
    I feel I am trying as hard as I can,
    but in retrospect,
    I am worried that maybe I didn't!

  * God:
    So in other words,
    you don't really know whether or not you have been sinning.
    So the possibility is open that you haven't been sinning at all!

  * Mortal:
    Of course this possibility is open,
    but maybe I have been sinning,
    and this thought is what so frightens me!

  * God:
    Why does the thought of your sinning frighten you?

  * Mortal:
    I don't know why!
    For one thing,
    you do have a reputation for meting out
    rather gruesome punishments in the afterlife!

  * God:
    Oh, that's what's bothering you!
    Why didn't you say so in the first place
    instead of all this peripheral talk about free will and responsibility?
    Why didn't you simply request me not to punish you for any of your sins?

  * Mortal:
    I think I am realistic enough to know that
    you would hardly grant such a request!

  * God:
    You don't say!
    You have a realistic knowledge of what requests I will grant, eh?
    Well, I'll tell you what I'm going to do!
    I will grant you a very, very special dispensation to sin as much as you like,
    and I give you my divine word of honor that
    I will never punish you for it in the least.
    Agreed?

  * Mortal: (in great terror)
    No, no, don't do that!

  * God:
    Why not?
    Don't you trust my divine word?

  * Mortal:
    Of course I do!
    But don't you see, I don't want to sin!
    I have an utter abhorrence of sinning,
    quite apart from any punishments it may entail.

  * God:
    In that case, I'll go you one better.
    I'll remove your abhorrence of sinning.
    Here is a magic pill!
    Just swallow it, and you will lose all abhorrence of sinning.
    You will joyfully and merrily sin away,
    you will have no regrets, no abhorrence and
    I still promise you will never be punished
    by me, or yourself, or by any source whatever.
    You will be blissful for all eternity.
    So here is the pill!

  * Mortal:
    No, no!

  * God:
    Are you not being irrational?
    I am even removing your abhorrence of sin,
    which is your last obstacle.

  * Mortal:
    I still won't take it!

  * God:
    Why not?

  * Mortal:
    I believe that the pill will indeed remove my future abhorrence for sin,
    but my present abhorrence is enough to prevent me from being willing to take it.

  * God:
    I command you to take it!

  * Mortal:
    I refuse!

  * God:
    What, you refuse of your own free will?

  * Mortal:
    Yes!

  * God:
    So it seems that your free will comes in pretty handy, doesn't it?

  * Mortal:
    I don't understand!

  * God:
    Are you not glad now that you have the free will to refuse such a ghastly offer?
    How would you like it if I forced you to take this pill,
    whether you wanted it or not?

  * Mortal:
    No, no! Please don't!

  * God:
    Of course I won't;
    I'm just trying to illustrate a point.
    All right, let me put it this way.
    Instead of forcing you to take the pill,
    suppose I grant your original prayer of removing your free will
    -- but with the understanding that
    the moment you are no longer free,
    then you will take the pill.

  * Mortal:
    Once my will is gone,
    how could I possibly choose to take the pill?

  * God:
    I did not say you would choose it;
    I merely said you would take it.
    You would act, let us say, according to purely deterministic laws
    which are such that you would as a matter of fact take it.

  * Mortal:
    I still refuse.

  * God:
    So you refuse my offer to remove your free will.
    This is rather different from your original prayer, isn't it?

  * Mortal:
    Now I see what you are up to.
    Your argument is ingenious,
    but I'm not sure it is really correct.
    There are some points we will have to go over again.

  * God:
    Certainly.

  * Mortal:
    There are two things you said which seem contradictory to me.
    First you said that one cannot sin unless one does so of one's own free will.
    But then you said you would give me a pill which would deprive me of my own free will,
    and then I could sin as much as I liked.
    But if I no longer had free will,
    then, according to your first statement,
    how could I be capable of sinning?

  * God:
    You are confusing two separate parts of our conversation.
    I never said the pill would deprive you of your free will,
    but only that it would remove your abhorrence of sinning.

  * Mortal:
    I'm afraid I'm a bit confused.

  * God:
    All right, then let us make a fresh start.
    Suppose I agree to remove your free will,
    but with the understanding that you will then commit an enormous number of acts which you now regard as sinful.
    Technically speaking, you will not then be sinning since you will not be doing these acts of your own free will.
    And these acts will carry no moral responsibility, nor moral culpability, nor any punishment whatsoever.
    Nevertheless, these acts will all be of the type which you presently regard as sinful;
    they will all have this quality which you presently feel as abhorrent,
    but your abhorrence will disappear;
    so you will not then feel abhorrence toward the acts.

  * Mortal:
    No, but I have present abhorrence toward the acts,
    and this present abhorrence is sufficient to prevent me from accepting your proposal.

  * God:
    Hm! So let me get this absolutely straight.
    I take it you no longer wish me to remove your free will.

  * Mortal: (reluctantly)
    No, I guess not.

  * God:
    All right, I agree not to.
    But I am still not exactly clear as to why you now no longer wish to be rid of your free will.
    Please tell me again.

  * Mortal:
    Because, as you have told me,
    without free will I would sin even more than I do now.

  * God:
    But I have already told you that without free will you cannot sin.

  * Mortal:
    But if I choose now to be rid of free will,
    then all my subsequent evil actions will be sins, not of the future,
    but of the present moment in which I choose not to have free will.

  * God:
    Sounds like you are pretty badly trapped, doesn't it?

  * Mortal:
    Of course I am trapped!
    You have placed me in a hideous double bind! Now whatever I do is wrong.
    If I retain free will, I will continue to sin, and
    if I abandon free will (with your help, of course) I will now be sinning in so doing.

  * God:
    But by the same token, you place me in a double bind.
    I am willing to leave you free will or remove it as you choose,
    but neither alternative satisfies you.
    I wish to help you, but it seems I cannot.

  * Mortal:
    True!

  * God:
    But since it is not my fault,
    why are you still angry with me?

  * Mortal:
    For having placed me in such a horrible predicament in first place!

  * God:
    But, according to you,
    there is nothing satisfactory I could have done.

  * Mortal:
    You mean there is nothing satisfactory you can now do,
    that does not mean that there is nothing you could have done.

  * God:
    Why? What could I have done?

  * Mortal:
    Obviously you should never have given me free will in the first place.
    Now that you have given it to me, it is too late
    -- anything I do will be bad.
    But you should never have given it to me in the first place.

  * God:
    Oh, that's it!
    Why would it have been better had I never given it to you?

  * Mortal:
    Because then I never would have been capable of sinning at all.

  * God:
    Well, I'm always glad to learn from my mistakes.

  * Mortal:
    What!

  * God:
    I know, that sounds sort of self-blasphemous, doesn't it?
    It almost involves a logical paradox!
    On the one hand, as you have been taught,
    it is morally wrong for any sentient being to claim that
    I am capable of making mistakes.
    On the other hand, I have the right to do anything.
    But I am also a sentient being.
    So the question is,
    Do, I or do I not have the right to claim that
    I am capable of making mistakes?

  * Mortal:
    That is a bad joke!
    One of your premises is simply false.
    I have not been taught that
    it is wrong for any sentient being to doubt your omniscience,
    but only for a mortal to doubt it.
    But since you are not mortal,
    then you are obviously free from this injunction.

  * God:
    Good, so you realize this on a rational level.
    Nevertheless, you did appear shocked
    when I said, "I am always glad to learn from my mistakes."

  * Mortal:
    Of course I was shocked.
    I was shocked not by your self-blasphemy (as you jokingly called it),
    not by the fact that you had no right to say it,
    but just by the fact that you did say it,
    since I have been taught that as a matter of fact you don't make mistakes.
    So I was amazed that you claimed that it is possible for you to make mistakes.

  * God:
    I have not claimed that it is possible.
    All I am saying is that if I make mistakes,
    I will be happy to learn from them.
    But this says nothing about
    whether the if has or ever can be realized.

  * Mortal:
    Let's please stop quibbling about this point.
    Do you or do you not admit it was a mistake to have given me free will?

  * God:
    Well now, this is precisely what I propose we should investigate.
    Let me review your present predicament.
    You don't want to have free will because with free will you can sin,
    and you don't want to sin.
    (Though I still find this puzzling;
     in a way you must want to sin,
     or else you wouldn't.
     But let this pass for now.)
    On the other hand,
    if you agreed to give up free will,
    then you would now be responsible for the acts of the future.
    Ergo, I should never have given you free will in the first place.

  * Mortal:
    Exactly!

  * God:
    I understand exactly how you feel.
    Many mortals -- even some theologians -- have complained that
    I have been unfair in that it was I, not they, who decided that
    they should have free will, and then I hold them responsible for their actions.
    In other words, they feel that
    they are expected to live up to a contract with me
    which they never agreed to in the first place.

  * Mortal:
    Exactly!

  * God:
    As I said, I understand the feeling perfectly.
    And I can appreciate the justice of the complaint.
    But the complaint arises only from an unrealistic understanding of the true issues involved.
    I am about to enlighten you as to what these are,
    and I think the results will surprise you!
    But instead of telling you outright,
    I shall continue to use the Socratic method.
    To repeat, you regret that I ever gave you free will.
    I claim that when you see the true ramifications you will no longer have this regret.
    To prove my point, I'll tell you what I'm going to do.
    I am about to create a new universe -- a new space-time continuum.
    In this new universe will be born a mortal
    just like you -- for all practical purposes,
    we might say that you will be reborn.
    Now, I can give this new mortal -- this new you -- free will or not.
    What would you like me to do?

  * Mortal (in great relief):
    Oh, please!
    Spare him from having to have free will!

  * God:
    All right, I'll do as you say.
    But you do realize that this new you without free will,
    will commit all sorts of horrible acts.

  * Mortal:
    But they will not be sins since he will have no free will.

  * God:
    Whether you call them sins or not,
    the fact remains that they will be horrible acts in the sense that
    they will cause great pain to many sentient beings.

  * Mortal: (after a pause)
    Good God, you have trapped me again!
    Always the same game!
    If I now give you the go-ahead to create this new creature with no free will
    who will nevertheless commit atrocious acts,
    then true enough he will not be sinning,
    but I again will be the sinner to sanction this.

  * God:
    In that case, I'll go you one better!
    Here, I have already decided whether to create this new you with free will or not.
    Now, I am writing my decision on this piece of paper
    and I won't show it to you until later.
    But my decision is now made and is absolutely irrevocable.
    There is nothing you can possibly do to alter it;
    you have no responsibility in the matter.
    Now, what I wish to know is this: Which way do you hope I have decided?
    Remember now,
    the responsibility for the decision falls entirely on my shoulders, not yours.
    So you can tell me perfectly honestly and without any fear,
    which way do you hope I have decided?

  * Mortal:
    (after a very long pause)
    I hope you have decided to give him free will.

  * God:
    Most interesting!
    I have removed your last obstacle!
    If I do not give him free will,
    then no sin is to be imputed to anybody.
    So why do you hope I will give him free will?

  * Mortal:
    Because sin or no sin,
    the important point is that if you do not give him free will,
    then (at least according to what you have said)
    he will go around hurting people,
    and I don't want to see people hurt.

  * God:
    (with an infinite sigh of relief)
    At last! At last you see the real point!

  * Mortal:
    What point is that?

  * God:
    That sinning is not the real issue!
    The important thing is that
    people as well as other sentient beings don't get hurt!

  * Mortal:
    You sound like a utilitarian!

  * God:
    I am a utilitarian!

  * Mortal:
    What!

  * God:
    Whats or no whats, I am a utilitarian.
    Not a unitarian, mind you, but a utilitarian.

  * Mortal:
    I just can't believe it!

  * God:
    Yes, I know, your religious training has taught you otherwise.
    You have probably thought of me more like a Kantian than a utilitarian,
    but your training was simply wrong.

  * Mortal:
    You leave me speechless!

  * God:
    I leave you speechless, do I!
    Well, that is perhaps not too bad a thing
    -- you have a tendency to speak too much as it is.
    Seriously, though,
    why do you think I ever did give you free will in the first place?

  * Mortal:
    Why did you?
    I never have thought much about why you did;
    all I have been arguing for is that you shouldn't have! But why did you?
    I guess all I can think of is the standard religious explanation:
    Without free will, one is not capable of meriting either salvation or damnation.
    So without free will, we could not earn the right to eternal life.

  * God:
    Most interesting!
    I have eternal life;
    do you think I have ever done anything to merit it?

  * Mortal:
    Of course not! With you it is different.
    You are already so good and perfect (at least allegedly) that
    it is not necessary for you to merit eternal life.

  * God:
    Really now?
    That puts me in a rather enviable position, doesn't it?

  * Mortal:
    I don't think I understand you.

  * God:
    Here I am eternally blissful
    without ever having to suffer or make sacrifices
    or struggle against evil temptations
    or anything like that.
    Without any of that type of "merit,"
    I enjoy blissful eternal existence.
    By contrast,
    you poor mortals have to sweat and suffer
    and have all sorts of horrible conflicts about morality,
    and all for what?
    You don't even know whether I really exist or not,
    or if there really is any afterlife,
    or if there is, where you come into the picture.
    No matter how much you try to placate me by being "good,"
    you never have any real assurance that your "best" is good enough for me,
    and hence you have no real security in obtaining salvation.
    Just think of it!
    I already have the equivalent of "salvation"
    -- and have never had to go through this infinitely lugubrious process of earning it.
    Don't you ever envy me for this?

  * Mortal:
    But it is blasphemous to envy you!

  * God:
    Oh come off it!
    You're not now talking to your Sunday school teacher,
    you are talking to me.
    Blasphemous or not,
    the important question is not
    whether you have the right to be envious of me
    but whether you are.
    Are you?

  * Mortal:
    Of course I am!

  * God:
    Good!
    Under your present world view,
    you sure should be most envious of me.
    But I think with a more realistic world view,
    you no longer will be.
    So you really have swallowed the idea
    which has been taught you that
    your life on earth is like an examination period
    and that the purpose of providing you with free will is to test you,
    to see if you merit blissful eternal life.
    But what puzzles me is this:
    If you really believe I am as good and benevolent as I am cracked up to be,
    why should I require people to merit things like happiness and eternal life?
    Why should I not grant such things to everyone regardless of whether or not he deserves them?

  * Mortal:
    But I have been taught that
    your sense of morality
    -- your sense of justice -- demands that
    goodness be rewarded with happiness
    and evil be punished with pain.

  * God:
    Then you have been taught wrong.

  * Mortal:
    But the religious literature is so full of this idea!
    Take for example Jonathan Edwards's "Sinners in the Hands of an Angry God."
    How he describes you as holding your enemies like loathsome scorpions over the flaming pit of hell,
    preventing them from falling into the fate that they deserve only by dint of your mercy.

  * God:
    Fortunately, I have not been exposed to the tirades of Mr. Jonathan Edwards.
    Few sermons have ever been preached which are more misleading.
    The very title "Sinners in the Hands of an Angry God" tells its own tale.
    In the first place, I am never angry.
    In the second place, I do not think at all in terms of "sin."
    In the third place, I have no enemies.

  * Mortal:
    By that do you mean that
    there are no people whom you hate,
    or that there are no people who hate you?

  * God:
    I meant the former although the latter also happens to be true.

  * Mortal:
    Oh come now, I know people who have openly claimed to have hated you.
    At times I have hated you!

  * God:
    You mean you have hated your image of me.
    That is not the same thing as hating me as I really am.

  * Mortal:
    Are you trying to say that it is not wrong to hate a false conception of you,
    but that it is wrong to hate you as you really are?

  * God:
    No, I am not saying that at all;
    I am saying something far more drastic!
    What I am saying has absolutely nothing to do with right or wrong.
    What I am saying is that
    one who knows me for what I really am
    would simply find it psychologically impossible to hate me.

  * Mortal:
    Tell me, since we mortals seem to have such erroneous views about your real nature,
    why don't you enlighten us?
    Why don't you guide us the right way?

  * God:
    What makes you think I'm not?

  * Mortal:
    I mean, why don't you appear to our very senses
    and simply tell us that we are wrong?

  * God:
    Are you really so naive as to believe that
    I am the sort of being which can appear to your senses?
    It would be more correct to say that I am your senses.

  * Mortal: (astonished)
    You are my senses?

  * God:
    Not quite, I am more than that.
    But it comes closer to the truth than the idea that I am perceivable by the senses.
    I am not an object; like you, I am a subject,
    and a subject can perceive,
    but cannot be perceived.
    You can no more see me than you can see your own thoughts.
    You can see an apple,
    but the event of your seeing an apple is itself not seeable.
    And I am far more like the seeing of an apple than the apple itself.

  * Mortal:
    If I can't see you, how do I know you exist?

  * God:
    Good question! How in fact do you know I exist?

  * Mortal:
    Well, I am talking to you, am I not?

  * God:
    How do you know you are talking to me?
    Suppose you told a psychiatrist,
    "Yesterday I talked to God."
    What do you think he would say?

  * Mortal:
    That might depend on the psychiatrist.
    Since most of them are atheistic,
    I guess most would tell me I had simply been talking to myself.

  * God:
    And they would be right!

  * Mortal:
    What? You mean you don't exist?

  * God:
    You have the strangest faculty of drawing false conclusions!
    Just because you are talking to yourself,
    it follows that I don't exist?

  * Mortal:
    Well, if I think I am talking to you,
    but I am really talking to myself,
    in what sense do you exist?

  * God:
    Your question is based on two fallacies plus a confusion.
    The question of whether or not you are now talking to me
    and the question of whether or not I exist are totally separate.
    Even if you were not now talking to me (which obviously you are),
    it still would not mean that I don't exist.

  * Mortal:
    Well, all right, of course!
    So instead of saying "if I am talking to myself, then you don't exist,"
    I should rather have said, "if I am talking to myself, then I obviously am not talking to you."

  * God:
    A very different statement indeed,
    but still false.

  * Mortal:
    Oh, come now,
    if I am only talking to myself,
    then how can I be talking to you?

  * God:
    Your use of the word "only" is quite misleading!
    I can suggest several logical possibilities
    under which your talking to yourself
    does not imply that you are not talking to me.

  * Mortal:
    Suggest just one!

  * God:
    Well, obviously one such possibility is that
    you and I are identical.

  * Mortal:
    Such a blasphemous thought -- at least had I uttered it!

  * God:
    According to some religions, yes.
    According to others,
    it is the plain, simple, immediately perceived truth.

  * Mortal:
    So the only way out of my dilemma
    is to believe that you and I are identical?

  * God:
    Not at all!
    This is only one way out.
    There are several others.
    For example, it may be that you are part of me,
    in which case you may be talking to that part of me which is you.
    Or I may be part of you,
    in which case you may be talking to that part of you which is me.
    Or again, you and I might partially overlap,
    in which case you may be talking to the intersection
    and hence talking both to you and to me.
    The only way your talking to yourself might seem to imply that
    you are not talking to me
    is if you and I were totally disjoint
    -- and even then,
    you could conceivably be talking to both of us.

  * Mortal:
    So you claim you do exist.

  * God:
    Not at all.
    Again you draw false conclusions!
    The question of my existence has not even come up.
    All I have said is that
    from the fact that you are talking to yourself
    one cannot possibly infer my nonexistence,
    let alone the weaker fact that you are not talking to me.

  * Mortal:
    All right, I'll grant your point!
    But what I really want to know is do you exist?

  * God:
    What a strange question!

  * Mortal:
    Why?
    Men have been asking it for countless millennia.

  * God:
    I know that!
    The question itself is not strange;
    what I mean is that it is a most strange question to ask of me!

  * Mortal:
    Why?

  * God:
    Because I am the very one whose existence you doubt!
    I perfectly well understand your anxiety.
    You are worried that your present experience with me is a mere hallucination.
    But how can you possibly expect to obtain reliable information
    from a being about his very existence
    when you suspect the nonexistence of the very same being?

  * Mortal:
    So you won't tell me whether or not you exist?

  * God:
    I am not being willful!
    I merely wish to point out that no answer I could give could possibly satisfy you.
    All right, suppose I said, "No, I don't exist."
    What would that prove?
    Absolutely nothing!
    Or if I said, "Yes, I exist."
    Would that convince you?
    Of course not!

  * Mortal:
    Well,
    if you can't tell me whether or not you exist,
    then who possibly can?

  * God:
    That is something which no one can tell you.
    It is something which only you can find out for yourself.

  * Mortal:
    How do I go about finding this out for myself?

  * God:
    That also no one can tell you.
    This is another thing you will have to find out for yourself.

  * Mortal:
    So there is no way you can help me?

  * God:
    I didn't say that.
    I said there is no way I can tell you.
    But that doesn't mean there is no way I can help you.

  * Mortal:
    In what manner then can you help me?

  * God:
    I suggest you leave that to me!
    We have gotten sidetracked as it is,
    and I would like to return to the question of what you believed my purpose to be in giving you free will.
    Your first idea of my giving you free will in order to test
    whether you merit salvation or not may appeal to many moralists,
    but the idea is quite hideous to me.
    You cannot think of any nicer reason
    -- any more humane reason -- why I gave you free will?

  * Mortal:
    Well now, I once asked this question of an Orthodox rabbi.
    He told me that the way we are constituted,
    it is simply not possible for us to enjoy salvation unless we feel we have earned it.
    And to earn it, we of course need free will.

  * God:
    That explanation is indeed much nicer than your former but still is far from correct.
    According to Orthodox Judaism, I created angels,
    and they have no free will.
    They are in actual sight of me
    and are so completely attracted by goodness that
    they never have even the slightest temptation toward evil.
    They really have no choice in the matter.
    Yet they are eternally happy even though they have never earned it.
    So if your rabbi's explanation were correct,
    why wouldn't I have simply created only angels rather than mortals?

  * Mortal:
    Beats me! Why didn't you?

  * God:
    Because the explanation is simply not correct.
    In the first place, I have never created any ready-made angels.
    All sentient beings ultimately approach the state which might be called "angelhood."
    But just as the race of human beings is in a certain stage of biologic evolution,
    so angels are simply the end result of a process of Cosmic Evolution.
    The only difference between the so-called saint
    and the so-called sinner is that
    the former is vastly older than the latter.
    Unfortunately it takes countless life cycles to learn
    what is perhaps the most important fact of the universe
    -- evil is simply painful.
    All the arguments of the moralists
    -- all the alleged reasons why people shouldn't commit evil acts --
    simply pale into insignificance in light of the one basic truth that
    evil is suffering.
    No, my dear friend, I am not a moralist.
    I am wholly a utilitarian.
    That I should have been conceived in the role of a moralist
    is one of the great tragedies of the human race.
    My role in the scheme of things (if one can use this misleading expression)
    is neither to punish nor reward,
    but to aid the process by which all sentient beings achieve ultimate perfection.

  * Mortal:
    Why did you say your expression is misleading?

  * God:
    What I said was misleading in two respects.
    First of all it is inaccurate to speak of my role in the scheme of things.
    I am the scheme of things.
    Secondly, it is equally misleading to speak of
    my aiding the process of sentient beings attaining enlightenment.
    I am the process.
    The ancient Taoists were quite close
    when they said of me (whom they called "Tao")
    that I do not do things,
    yet through me all things get done.
    In more modem terms,
    I am not the cause of Cosmic Process,
    I am Cosmic Process itself.
    I think the most accurate and fruitful definition of me
    which man can frame
    -- at least in his present state of evolution --
    is that I am the very process of enlightenment.
    Those who wish to think of the devil
    (although I wish they wouldn't!)
    might analogously define him as
    the unfortunate length of time the process takes.
    In this sense, the devil is necessary;
    the process simply does take an enormous length of time,
    and there is absolutely nothing I can do about it.
    But, I assure you,
    once the process is more correctly understood,
    the painful length of time will no longer be regarded
    as an essential limitation or an evil.
    It will be seen to be the very essence of the process itself.
    I know this is not completely consoling to you
    who are now in the finite sea of suffering,
    but the amazing thing is that once you grasp this fundamental attitude,
    your very finite suffering will begin to diminish
    -- ultimately to the vanishing point.

  * Mortal:
    I have been told this,
    and I tend to believe it.
    But suppose I personally succeed in seeing things through your eternal eyes.
    Then I will be happier,
    but don't I have a duty to others?

  * God: (laughing)
    You remind me of the Mahayana Buddhists!
    Each one says,
    "I will not enter Nirvana until I first see that all other sentient beings do so."
    So each one waits for the other fellow to go first.
    No wonder it takes them so long!
    The Hinayana Buddhist errs in a different direction.
    He believes that no one can be of the slightest help to others in obtaining salvation;
    each one has to do it entirely by himself.
    And so each tries only for his own salvation.
    But this very detached attitude makes salvation impossible.
    The truth of the matter is that salvation is partly an individual and partly a social process.
    But it is a grave mistake to believe
    -- as do many Mahayana Buddhists --
    that the attaining of enlightenment puts one out of commission,
    so to speak, for helping others.
    The best way of helping others is by first seeing the light oneself.

  * Mortal:
    There is one thing about your self-description which is somewhat disturbing.
    You describe yourself essentially as a process.
    This puts you in such an impersonal light,
    and so many people have a need for a personal God.

  * God:
    So because they need a personal God,
    it follows that I am one?

  * Mortal:
    Of course not.
    But to be acceptable to a mortal a religion must satisfy his needs.

  * God:
    I realize that.
    But the so-called "personality" of a being is
    really more in the eyes of the beholder than in the being itself.
    The controversies which have raged, about whether I am a personal
    or an impersonal being are rather silly
    because neither side is right or wrong.
    From one point of view, I am personal,
    from another, I am not.
    It is the same with a human being.
    A creature from another planet may look at him purely impersonally
    as a mere collection of atomic particles behaving according to strictly prescribed physical laws.
    He may have no more feeling for the personality of a human
    than the average human has for an ant.
    Yet an ant has just as much individual personality as a human to beings like myself who really know the ant.
    To look at something impersonally is no more correct or incorrect than to look at it personally,
    but in general,
    the better you get to know something,
    the more personal it becomes.
    To illustrate my point,
    do you think of me as a personal or impersonal being?

  * Mortal:
    Well, I'm talking to you, am I not?

  * God:
    Exactly!
    From that point of view,
    your attitude toward me might be described as a personal one.
    And yet, from another point of view -- no less valid --
    I can also be looked at impersonally.

  * Mortal:
    But if you are really such an abstract thing as a process,
    I don't see what sense it can make my talking to a mere "process."

  * God:
    I love the way you say "mere."
    You might just as well say that you are living in a "mere universe."
    Also, why must everything one does make sense?
    Does it make sense to talk to a tree?

  * Mortal:
    Of course not!

  * God:
    And yet, many children and primitives do just that.

  * Mortal:
    But I am neither a child nor a primitive.

  * God:
    I realize that, unfortunately.

  * Mortal:
    Why unfortunately?

  * God:
    Because many children and primitives have a primal intuition which the likes of you have lost.
    Frankly, I think it would do you a lot of good to talk to a tree once in a while,
    even more good than talking to me!
    But we seem always to be getting sidetracked!
    For the last time,
    I would like us to try to come to an understanding about why I gave you free will.

  * Mortal:
    I have been thinking about this all the while.

  * God:
    You mean you haven't been paying attention to our conversation?

  * Mortal:
    Of course I have.
    But all the while, on another level,
    I have been thinking about it.

  * God:
    And have you come to any conclusion?

  * Mortal:
    Well, you say the reason is not to test our worthiness.
    And you disclaimed the reason that
    we need to feel that we must merit things in order to enjoy them.
    And you claim to be a utilitarian.
    Most significant of all, you appeared so delighted
    when I came to the sudden realization that
    it is not sinning in itself which is bad but only the suffering which it causes.

  * God:
    Well of course!
    What else could conceivably be bad about sinning?

  * Mortal:
    All right, you know that, and now I know that.
    But all my life I unfortunately have been under the influence of those moralists
    who hold sinning to be bad in itself.
    Anyway, putting all these pieces together,
    it occurs to me that
    the only reason you gave free will is because of your belief that with free will,
    people will tend to hurt each other -- and themselves --
    less than without free will.

  * God:
    Bravo!
    That is by far the best reason you have yet given!
    I can assure you that had I chosen to give free will,
    that would have been my very reason for so choosing.

  * Mortal:
    What!
    You mean to say you did not choose to give us free will?

  * God:
    My dear fellow,
    I could no more choose to give you free will than I could choose to make an equilateral triangle equiangular.
    I could choose to make or not to make an equilateral triangle in the first place,
    but having chosen to make one,
    I would then have no choice but to make it equiangular.

  * Mortal:
    I thought you could do anything!

  * God:
    Only things which are logically possible.
    As St. Thomas said,
    "It is a sin to regard the fact that God cannot do the impossible, as a limitation on His powers."
    I agree, except that
    in place of his using the word sin I would use the term error.

  * Mortal:
    Anyhow, I am still puzzled by your implication that
    you did not choose to give me free will.

  * God:
    Well, it is high time I inform you that
    the entire discussion -- from the very beginning --
    has been based on one monstrous fallacy!
    We have been talking purely on a moral level
    -- you originally complained that
    I gave you free will, and raised the whole question as to whether I should have.
    It never once occurred to you that I had absolutely no choice in the matter.

  * Mortal:
    I am still in the dark!

  * God:
    Absolutely!
    Because you are only able to look at it through the eyes of a moralist.
    The more fundamental metaphysical aspects of the question you never even considered.

  * Mortal:
    I still do not see what you are driving at.

  * God:
    Before you requested me to remove your free will,
    shouldn't your first question have been
    whether as a matter of fact you do have free will?

  * Mortal:
    That I simply took for granted.

  * God:
    But why should you?

  * Mortal:
    I don't know. Do I have free will?

  * God:
    Yes.

  * Mortal:
    Then why did you say I shouldn't have taken it for granted?

  * God:
    Because you shouldn't.
    Just because something happens to be true,
    it does not follow that it should be taken for granted.

  * Mortal:
    Anyway, it is reassuring to know that
    my natural intuition about having free will is correct.
    Sometimes I have been worried that determinists are correct.

  * God:
    They are correct.

  * Mortal:
    Wait a minute now, do I have free will or don't I?

  * God:
    I already told you you do.
    But that does not mean that determinism is incorrect.

  * Mortal:
    Well, are my acts determined by the laws of nature or aren't they?

  * God:
    The word determined here is subtly but powerfully misleading
    and has contributed so much to the confusions of the free will versus determinism controversies.
    Your acts are certainly in accordance with the laws of nature,
    but to say they are determined by the laws of nature creates a totally misleading psychological image
    which is that your will could somehow be in conflict with the laws of nature
    and that the latter is somehow more powerful than you,
    and could "determine" your acts whether you liked it or not.
    But it is simply impossible for your will to ever conflict with natural law.
    You and natural law are really one and the same.

  * Mortal:
    What do you mean that I cannot conflict with nature?
    Suppose I were to become very stubborn,
    and I determined not to obey the laws of nature.
    What could stop me?
    If I became sufficiently stubborn even you could not stop me!

  * God:
    You are absolutely right!
    I certainly could not stop you.
    Nothing could stop you.
    But there is no need to stop you,
    because you could not even start!
    As Goethe very beautifully expressed it,
    "In trying to oppose Nature,
     we are, in the very process of doing so,
     acting according to the laws of nature!"
    Don't you see that the so-called "laws of nature"
    are nothing more than a description of
    how in fact you and other beings do act?
    They are merely a description of how you act,
    not a prescription of of how you should act,
    not a power or force which compels or determines your acts.
    To be valid a law of nature must take into account how in fact you do act,
    or, if you like, how you choose to act.

  * Mortal:
    So you really claim that I am incapable of determining to act against natural law?

  * God:
    It is interesting that you have twice now used the phrase "determined to act"
    instead of "chosen to act."
    This identification is quite common.
    Often one uses the statement "I am determined to do this" synonymously with
    "I have chosen to do this."
    This very psychological identification should reveal that
    determinism and choice are much closer than they might appear.
    Of course, you might well say that
    the doctrine of free will says that
    it is you who are doing the determining,
    whereas the doctrine of determinism appears to say that
    your acts are determined by something apparently outside you.
    But the confusion is largely caused by your bifurcation of reality into the "you" and the "not you."
    Really now, just where do you leave off and the rest of the universe begin?
    Or where does the rest of the universe leave off and you begin?
    Once you can see the so-called "you" and the so-called "nature" as a continuous whole,
    then you can never again be bothered by such questions as
    whether it is you who are controlling nature or nature who is controlling you.
    Thus the muddle of free will versus determinism will vanish.
    If I may use a crude analogy,
    imagine two bodies moving toward each other by virtue of gravitational attraction.
    Each body, if sentient, might wonder
    whether it is he or the other fellow who is exerting the "force."
    In a way it is both, in a way it is neither.
    It is best to say that it is the configuration of the two which is crucial.

  * Mortal:
    You said a short while ago that our whole discussion was based on a monstrous fallacy.
    You still have not told me what this fallacy is.

  * God:
    Why, the idea that I could possibly have created you without free will!
    You acted as if this were a genuine possibility,
    and wondered why I did not choose it!
    It never occurred to you that a sentient being without free will
    is no more conceivable than a physical object
    which exerts no gravitational attraction.
    (There is, incidentally, more analogy than you realize
     between a physical object exerting gravitational attraction
     and a sentient being exerting free will!)
    Can you honestly even imagine a conscious being without free will?
    What on earth could it be like?
    I think that one thing in your life that has so misled you is
    your having been told that I gave man the gift of free will.
    As if I first created man,
    and then as an afterthought endowed him with the extra property of free will.
    Maybe you think I have some sort of "paint brush"
    with which I daub some creatures with free will and not others.
    No, free will is not an "extra";
    it is part and parcel of the very essence of consciousness.
    A conscious being without free will is simply a metaphysical absurdity.

  * Mortal:
    Then why did you play along with me all this
    while discussing what I thought was a moral problem,
    when, as you say, my basic confusion was metaphysical?

  * God:
    Because I thought it would be good therapy for you to get some of this moral poison out of your system.
    Much of your metaphysical confusion was due to faulty moral notions,
    and so the latter had to be dealt with first.
    And now we must part
    -- at least until you need me again.
    I think our present union will do much to sustain you for a long while.
    But do remember what I told you about trees.
    Of course, you don't have to literally talk to them if doing so makes you feel silly.
    But there is so much you can learn from them,
    as well as from the rocks and streams and other aspects of nature.
    There is nothing like a naturalistic orientation
    to dispel all these morbid thoughts of "sin" and "free will" and "moral responsibility."
    At one stage of history,
    such notions were actually useful.
    I refer to the days
    when tyrants had unlimited power
    and nothing short of fears of hell could possibly restrain them.
    But mankind has grown up since then,
    and this gruesome way of thinking is no longer necessary.
    It might be helpful to you to recall
    what I once said through the writings of the great Zen poet Seng-Ts'an:
    - If you want to get the plain truth,
    - Be not concerned with right and wrong.
    - The conflict between right and wrong
    - Is the sickness of the mind.
