#+include: use-org-page.org
#+title: schizophrenia in contemporary mathematics / 當代數學之精神分裂症
#+author: Errett Bishop

* 題解

  - 原文來源
    書名 errett bishop : reflections on him and his research
    Bishop 逝於 1983 年四月
    本書爲 1983 年九月 紀念 Bishop 逝世的會議記錄 出版於 1985 年

  - 其中只有一篇文章爲作者本人所寫 [其餘 階爲他人紀念 Bishop 所作]
    所譯正是此篇 schizophrenia in contemporary mathematics
    文章爲作者晚年所作
    1973 年首次出版

* 排版

  - 排版用 雙文
    譯文在先 原文在後
    原文 譯文 段段交叉 以便讀者對比 並指正譯文中不當之處

  - 譯文中
    方形括號內的段落爲我的筆記

  - 文章本不分節
    分節 與 章節標題 皆爲我所加

  - 文末有引用索引
    略而不譯
    有興趣者請自查原文

* 精神分裂諸症狀 / schizophrenic attributes of contemporary mathematics

*** 譯文

    - 過去的十年間
      我做了很多關於 構造主義數學 的演講
      我感覺我沒能把 我所體會到的 其中所涉及的哲學問題 傳達清楚

      既然今天我在這裏
      我還是希望能成功

      部分困難在於
      害怕太過消極
      或害怕產生太多敵意

      構造主義 是對所聲稱的 古典數學之濫用 的反應
      去檢驗這些 濫用 看似苦口
      但是唯有如此才能理解 構造主義之動機

    - 布勞維爾對古典數學的批評
      我總結其爲 意義之降質

      他機敏的批評 是他對構造主義的兩個主要貢獻之一
      另一個是 確立新的術語
      重新解釋邏輯連詞與量詞 賦予它們顯要的意義
      這些都是古典術語所缺乏的

    - 意義之降質 只是當代數學的問題點之一
      歸總起來 諸多的問題點揭示出一種匱乏 大部分數學領域有一種 '哲學短缺'
      所匱乏的是什麼 可能不明瞭
      但是各個方面的匱乏綜合起來的症狀
      我暫時稱之爲 '精神分裂症'

    - 我們可以列出很多當代數學的精神分裂症狀
      但是我想 如下種種 概括了很大範圍
      1. 放棄常識 而喜愛形式
      2. 執意拒絕適應現實 而致意義降質
      3. 不適合目的的方法
      4. 晦澀隱祕的交流方式
      5. 分裂
      ------

      1. 常識經常遭到攻擊
         取而代之的是方法論 進而退化成教條

         整理觀察與領悟 以形成方法 是不錯
         但是將方法提升爲教條 則有錯
         因爲那將阻礙新的觀察與領悟

         當代數學見證了形式主義教條的勝利
         起初形式主義所領悟的是
         現代數學中的論證都可以拆解開來
         然後以相繼施用一些基本策略的方式重新呈現出來
         這方面的專家們 常常視 如此這般的形式系統 爲數學之全貌
         證明 被認爲是操作字符串與符號
         數學哲學 則被認爲是 創造 對比 和研究 這些形式系統
         一致性 就是形式系統的目標
         導致 意義降質 甚至根本就不存在於主要層次中

      2. 意義降質還有一個源頭
         即 當代數學家執意拒絕檢驗他們某些術語的內含
         例如 '存在' 一詞
         他拒絕區分這個詞所能包含的不同意義
         而且 這個詞對他而言的意義 他含糊不清
         黨遭追問時 他就躲入形式主義的庇護所里
         宣稱 這個詞 還有使用了這個詞的語句
         只有在整個 假設和操作的集合 所形成的語境中 纔有意義

         這樣 他就本末倒置了
         他本應先發展出意義
         然後再把他的 假設與操作 構建在意義的根基上

         思考這種 意義之降質
         就是構造主義的首要動力

      3. 既然 意義已降質
         又 棄絕了常識
         那麼 發現 所用的方法 不適合目的
         也就沒有什麼大驚小怪的了

         應用數學中 大多數概念都來源於具體模型
         然後 通過這些概念 利用數學方法來理解現實

         黨 模型本身並非現實的合適表示時
         方法就是不適合的 (這種情況經常出現)

         人們的印象是
         模型的構建者 已經不關心現實了
         他們的模型已經變得自治
         這種現象就發生在數學哲學中
         - 模型就是形式體系
           它們既被當作研究數學本質的工具
           也被當作意義的載體

      4. 每個被教了大學數學的人
         一定對其 晦澀隱祕的交流方式 有印象
         'A 蘊含 B' 的意思是 '非 A 或 B'
         這是不自然的
         如果給學生機會的話 學生也會告訴你的

         當然 這不是致命的缺點
         關鍵是 蘊含式 的標準定義是否有用
         而不是其定義是否自然

         構造主義者 跟隨布勞維爾
         爭論說 蘊含式 的更自然的定義是更有用的
         這一點我們之後再展開

         很難傳達給學生的概念之一是 證明
         其原因就是 我們的表達方式太過晦澀隱祕

         大多數數學家
         黨被追問什麼是證明時
         都會援引形式主義的原則
         而與此相反
         證明這個概念 對於構造主義來說 就非常簡單
         我們將在適當的時候說明這一點

         同樣晦澀的 也許更困難的
         是 存在 這個概念
         與這個概念有關的問題已經提到了一些
         之後我們也會回到這個概念的討論

         最後 我想指出另一個晦澀的概念
         即 古典的 真 這個概念
         之後我們將會看到
         這對構造主義者來說 並沒有任何困難
         因爲他強調意義

      5. 數學的分裂
         部分原因是這個學科之曠闊
         但是分裂的現象被我們的教育系統惡化了
         純數學的研究生
         也許不會被要求通過多個數學分支的考試來拓寬自己的視野
         但是 他絕對不會被要求學習 (甚至是不鼓勵學習)
         數學的哲學 數學的歷史 或 數學的應用

         我們的教育系統使得我們生產
         能夠馬上發論文的研究型數學家
         這種 反社會 反理智 的行爲
         就它自己狹隘的目的而言 也是失敗的

         這種情況可能不會改變
         直到我們更改了我們對數學的認識
         在我們的教育體系還有職業價值有所改變之前
         我們首先要明白定理和證明的意義

         如果我們繼續把注意力集中在生產定理上
         並且繼續 貶值其內容
         那麼分裂就是不可避免的

         所謂 貶值其內容 我指如下這些情形
         - 對某些純數學家而言
           給定理和證明加上某些詮釋的唯一原因
           就是這些詮釋能夠促進生產這些定理和證明
           對他們而言所詮釋出的內容是工具 而不是目的
         - 另外一些人覺得 有某些內容是重要的
           但是並不在意找到它們
         - 還有一些人
           (Godel 看來是其代言人 參考例如
            [Godel, K., "What is Cantor's Continuum Problem?"
            Amer. Math. Monthly, 54 (1947), 515-525.])
           他們盡力發展內容
           但是只在廣爲接受的柏拉圖理想主義的框架之內

         有人懷疑大多數的純數學家 (屬上述中的前兩種)
         儘可能地忽略內容
         如果你覺得這種懷疑不公正
         可以停下來想想現代概率論
         一個事件的概率 常常被取作 0 與 1 之間的實數
         一個人可能天真地推測 概率論家會想要計算出這些實數
         瞧瞧現代的任意一本教材吧
         (比如 Doob 的傑出作品
          [Doob, J. L., "Stochastic Processes," Wiley, New York, 1953.])
         看了之後就能解除他對我們的猜測的疑慮了
         分裂性保證了很多定理 (如果不說是絕大多數定理)
         對與想要實際計算概率的人來說是沒用的
         想要實際計算概率的話
         他要麼設計出自己的理論 要麼利用臨時技術 還有經驗法則
         我並不宣稱
         讓概率論重新包含 有關意義的基礎問題
         就能將分裂的趨勢反過來
         只不過這是必要的第一步
         最近幾年少數構造主義數學家
         (可見 [3], [9], [10], [11],[12], [23], [24])
         [有興趣的讀者請查看原文索引]
         試着幫助概率論學家走出這一步
         他們的努力最終是否會被欣賞 我們拭目以待

    - 當我試圖用積極的詞語來表達
      當代數學所缺乏的特性時
      我把這種缺乏稱作 '精神分裂症'
      我還常常想到 '完整性' 這個術語
      不是說形式主義意義上的孤立的完整性
      那是驕傲地維護自己所制定的標準的優越性
      而我所說的 '完整性' 指
      - 在 數學 應用數學 還有數學向的領域 例如物理學 中
        尋找共同的根基
      - 在每個新的發展中
        尋求萃取出最多的意義
      - 主要爲內容所指引
        而不是形式上優雅
      - 數學對現實的表達
        並不降級爲一個遊戲
      - 尋求理解數學在當代社會中的意義

      這種完整性也許不可能實現
      但是這並不重要
      我喜歡把構造主義想成是
      爲了實現 哪怕是部分實現 這種理想化的完整性
      的一次嘗試
      這種假定起碼能防止構造主義變成另外一個遊戲
      就像某些構造主義者過去所做的

*** 記

    - 關於 晦澀隱祕的交流方式
      我認爲是數學中語言設計的種種失誤所致
      然而 一般人並不認爲數學中需要什麼 '語言設計'

*** 原文

    - During the past ten years
      I have given a number of lectures
      on the subject of constructive mathematics.
      My general impression is that
      I have failed to communicate a real feeling
      for the philosophical issues involved.

      Since I am here today,
      I still have hopes of being able to do so.

      Part of the difficulty is the fear of
      seeming to be too negativistic
      and generating too much hostility.

      Constructivism is a reaction
      to certain alleged abuses of classical mathematics.
      Unpalatable as it may be
      to have those abuses examined,
      there is no other way
      to understand the motivations of the constructivists.

    - Brouwer's criticisms of classical mathematics
      were concerned with what I shall refer to as
      "the debasement of meaning."

      (His incisive criticisms
       were one of his two main contributions to constructivism.
       His other was to establish a new terminology,
       involving a re-interpretation
       of the usual connectives and quantifiers,
       which permits the expression
       of certain important distinctions of meaning
       which the classical terminology does not.)

    - The debasement of meaning
      is just one of the trouble spots in contemporary mathematics.
      Taken all together,
      these trouble spots indicate that something is lacking,
      that there is a philosophical deficit of major proportions.
      What it is that is lacking is perhaps not clear,
      but the lack in all of its aspects constitutes a syndrome
      I shall tentatively describe as "schizophrenia."

    - One could probably make a long list
      of schizophrenic attributes of contemporary mathematics,
      but I think the following short list
      covers most of the ground:
      1. rejection of common sense in favor of formalism;
      2. debasement of meaning
         by wilful refusal to accommodate certain aspects of reality;
      3. inappropriateness of means to ends;
      4. the esoteric quality of the communication;
      5. and fragmentation.
      ---------------

      1. Common sense is a quality that is constantly under attack.
         It tends to be supplanted by methodology, shading into dogma.

         The codification of insight is commendable
         only to the extent that
         the resulting methodology is not elevated to dogma
         and there by allowed to impede the formation of new insight.

         Contemporary mathematics has witnessed the triumph of formalist dogma,
         which had its inception in the important insight that
         most arguments of modern mathematics
         can be broken down and presented
         as successive applications of a few basic schemes.
         The experts now routinely equate the panorama of mathematics
         with the productions of this or that formal system.
         Proofs are thought of as manipulations of strings of symbols.
         Mathematical philosophy
         consists of the creation, comparison, and investigation of formal systems.
         Consistency is the goal.
         In consequence meaning is debased,
         and even ceases to exist at a primary level.

      2. The debasement of meaning has yet another source,
         the wilful refusal of the contemporary mathematician
         to examine the content of certain of his terms,
         such as the phrase "there exists."
         He refuses to distinguish among the different meanings
         that might be ascribed to this phrase.
         Moreover he is vague about what meaning it has for him.
         When pressed he is apt to take refuge in formalisties,
         declaring that
         the meaning of the phrase
         and the statements of which it forms a part
         can only be understood in the context of
         the entire set of assumptions
         and techniques at his command.

         Thus he inverts the natural order,
         which would be to develop meaning first,
         and then to base his assumptions and techniques
         on the rock of meaning.

         Concern about this debasement of meaning
         is a principal force behind constructivism.

      3. Since meaning is debased
         and common sense is rejected,
         it is not surprising to find that
         the means are inappropriate to the ends.

         Applied mathematics makes much of the concept of a model,
         as a tool for dealing with reality by mathematical means.
         When the model is not an adequate representation of reality,
         as happens only too often,
         the means are inappropriate.

         One gets the impression that some of the model-builders
         are no longer interested in reality.
         Their models have become autonomous.
         This has clearly happened in mathematical philosophy:
         - the models (formal systems)
           are accepted as the preferred tools
           for investigation the nature of mathematics,
           and even as the font of meaning.

      4. Everyone who has taught undergraduate mathematics
         must have been impressed by the esoteric quality of the communication.
         It is not natural
         for "A implies B"
         to mean "not A or B"
         and students will tell you so
         if you give them the chance.

         Of course,
         this is not a fatal objection.
         The question is,
         - whether the standard definition of implication is useful,
           not whether it is natural.

         The constructivist, following Brouwer,
         contends that
         a more natural definition of implication
         would be more useful.
         This point will be developed later.

         One of the hardest concepts
         to communicate to the undergraduate
         is the concept of a proof.
         With good reason -- the concept is esoteric.

         Most mathematicians,
         when pressed to say what they mean by a proof,
         will have recourse to formal criteria.
         The constructive notion of proof by contrast is very simple,
         as we shall see in due course.

         Equally esoteric, and perhaps more trouble some,
         is the concept of existence.
         Some of the problems associated with this concept
         have already been mentioned,
         and we shall return to the subject again.

         Finally, I wish to point out the esoteric nature
         of the classical concept of truth.
         As we shall see later,
         truth is not a source of trouble to the constructivist,
         because of his emphasis on meaning.

      5. The fragmentation of mathematics
         is due in part to the vastness of the subject,
         but it is aggravated by our educational system.
         A graduate student in pure mathematics
         may or may not be required to broaden himself
         by passing examinations in various branches of pure mathematics,
         but he will almost certainly not be required or even encouraged
         to acquaint himself with
         the philosophy of mathematics,
         its history,
         or its applications.

         We have geared ourselves
         to producing research mathematicians
         who will begin to write papers as soon as possible.
         This anti-social and anti-intellectual process
         defeats even its own narrow ends.

         The situation is not likely to change
         until we modify our conception of what mathematics is.
         Before important changes will come about
         in our methods of education
         and our professional values,
         we shall have to discover the significance of theorem and proof.

         If we continue to focus attention
         on the process of producing theorems,
         and continue to devalue their content,
         fragmentation is inevitable.

    - By devaluation of content I mean the following.
      - To some pure mathematicians
        the only reason for attaching any interpretation whatever
        to theorem and proof is that
        the process of producing theorems and proofs is thereby facilitated.
        For them content is a means rather than the end.
      - Others feel that it is important to have some content,
        but don't especially care to find out what it is.
      - Still others, for whom Godel seems to be a leading spokesman,
        (see for example
         [Godel, K., "What is Cantor's Continuum Problem?"
          Amer. Math. Monthly, 54 (1947), 515-525.])
        do their best to develop content
        within the accepted framework of platonic idealism.

    - One suspects that the majority of pure mathematicians,
      who belong to the union of the first two groups,
      ignore as much content as they possibly can.
      If this suspicion seems unjust,
      pause to consider the modern theory of probability.
      The probability of an event
      is commonly taken to be a real number between 0 and 1.
      One might naively expect that
      the probabilists would concern themselves
      with the computation of such real numbers.
      If so, a quick look at any one of a number of modern texts,
      for instancethe excellent book of Doob,
      [Doob, J. L., "Stochastic Processes," Wiley, New York, 1953.]
      should suffice to disabuse him of that expectation.

      Fragmentation ensues,
      because much if not most of the theory is useless to someone
      who is concerned with actually finding probabilities.
      He will either develop his own semi-independent theories,
      or else work with ad hoc techniques and rules of thumb.
      I do not claim that
      re-involvement of the probabilists
      with the basic questions of meaning
      would of itself reverse the process of fragmentation of their discipline,
      only that it is a necessary first step.
      In recent years a small number of constructivists
      (see [3], [9], [10], [11],[12], [23], and [24])
      have been trying to help the probabilists take that step.
      Whether their efforts will ultimately be appreciated remains to be seen.

    - When I attempt to express in positive terms that quality
      in which contemporary mathematics is deficient,
      the absence of which I have characterized as "schizophrenia,"
      I keep coming back to the term "integrity."
      Not the integrity of an isolated formalism
      that prides itself on the maintenance of its own standards of excellence,
      but an integrity
      - that seeks common ground
        in the researches of pure mathematics,
        applied mathematics,
        and such mathematically oriented disciplines as physics;
      - that seeks to extract the maximum meaning
        from each new development;
      - that is guided primarily by considerations of content
        rather than elegance and formal attractiveness;
      - that sees to it that
        the mathematical representation of reality
        does not degenerate into a game;
      - that seeks to understand
        the place of mathematics in contemporary society.

      This integrity may not be possible of realization,
      but that is not important.
      I like to think of constructivism
      as one attempt to realize
      at least certain aspects of this idealized integrity.
      This presumption
      at least has the possible merit of
      preventing constructivism from becoming another game,
      as some constructivisms have tended to do in the past.

* 構造主義基本四原則 / four basic principles for constructivism

*** 譯文

    - 在討論構造主義的原則時
      我嘗試區分出 基本哲學原則
      與 僅僅爲方便而設的原則

      四個基本原則凸顯了出來

      (A) 數學即常識

      (B) 別問一個論斷是否真實 除非你明瞭論斷的意思

      (C) 使你信服的論證皆爲證明

      (D) 有意義的區別值得保留

    - 出奇的是
      很多有才能的人 拒絕拒絕在數學中使用常識
      常見的態度是
      數學的形式化價值重大
      因爲形式主義構成了最高法庭
      關於一個證明是否正確的爭論都要在那裏解決
      而相反 嘗試告訴我們
      如果一個證明如此繁雜
      使得我們沒法用非形式化的方式判斷它是否正確
      那麼我們也沒法用形式化的方法檢驗它
      而且 形式主義也不能被用來解決哲學爭論
      因爲形式主義僅僅體現出基礎的哲學
      而哲學爭論必定會上升到形式主義方法的有效性

    - 原則 (B) 解決 構造意義下的真 的問題
      就此而言 它也解決 古典意義下的真 的問題 如果古典主義數學家接受它的話
      我們也許可以說 真 是就約定而言的
      也就是說
      有關任意一個論斷之真假的討論 可能討論雙方都有依據
      這種討論之所以會出現
      就是因爲討論雙方沒有就論斷的意義達成一致
      例如 就如下的問題而言
      "是否 構造主義者相信 不是每個單調有限實數數列都收斂"
      如果我回答 "是"
      ><><><

    - 每當有學生問我 他給出的一個證明是否正確時
      在回答他的問題之前
      我先試着弄清楚 對他而言 證明意味着什麼
      然後我告訴他我的觀點 也就是上面的 原則 (C)
      然後我問他
      他是否徹底信服自己的證明
      又 他是否覺得他已經表達地足夠清晰
      使得別的 充分獲得信息 的智慧生物
      也能徹底信服他的證明

    - 顯然 不接受 原則 (B) 就沒法接受 原則 (C)
      因爲 不明瞭論斷的意義 就談不上信服與否

    - ><><><

    - 古典主義數學家
      沒能發現整數之間的 一種有意義的區別
      這種基本的失敗反映在古典數學發展的各個方面
      設想一個數 n
      定義爲 0 若 黎曼假設爲真
      定義爲 1 若 黎曼假設爲假
      構造主義者無法阻止古典主義數學家使用這類數
      (儘管他個人相信 這類數意義有限)
      然是他的確希望古典主義數學家能夠
      把這類數 和能夠被 "計算" 的數 區分開來
      例如 n1 被定義爲 小於 10^(10^10) 的素數的個數
      古典主義數學家 有時的確會考慮某些數 可否被 "計算"
      但是沒有系統的方法
      在古典數學的系統發展中 這種區別沒能體現出來
      即使他想要觀察
      也沒有工具 能讓古典主義數學家 以系統的方式觀察到這些區別

    - The constructivists are frequently accused of

      ><><><

*** 原文

    - In discussing the principles of constructivism,
      I shall try to
      separate those aspects of constructivism
      that are basic to the philosophy
      from those that are merely convenient
      (or inconvenient, as the case may be).

      Four principles stand out as basis:

      (A) Mathematics is common sense.

      (B) Do not ask whether a statement is true until you know what it means.

      (C) A proof is any completely convincing argument.

      (D) Meaningful distinctions deserve to be maintained.

    - Surprisingly
      many brilliant people
      refuse to apply common sense to mathematics.
      A frequent attitude is that
      the formalization of mathematics has been of great value,
      because the formalism constitutes a court of last resort
      to settle any disputes that might arise
      concerning the correctness of a proof.
      Common sense tells us, on the contrary, that
      if a proof is so involved
      that we are unable to determine its correctness by informal methods,
      then we shall not be able to test it by formal means either.
      Moreover the formalism cannot be used to settle philosophical disputes,
      because the formalism merely reflects the basic philosophy,
      and consequently philosophical disagreements
      are bound to result in disagreements about the validity of the formalism.

    - Principle (B) resolves the problem of constructive truth.
      For that matter, it would resolve the problem of classical truth
      if the classical mathematicians would accept it.
      We might say that truth is a matter of convention.
      This simply means that all arguments concerning the truth or falsity
      of any given statement about which
      both parties possess the same relevant facts
      occur because they have not reached a clear agreement
      as to what the statement means.
      For instance in response to the inquiry
      "Is it true the construetivists believe that
       not every bounded monotone sequence of real numbers converges?,"
      if I am tired I answer "yes."
      ><><><

    - Whenever a student asks me whether a proof he has given is correct,
      before answering his question
      I try to discover his concept of what constitutes a proof.
      Then I tell him my own concept, (C) above,
      and ask him whether he finds his argument completely convincing,
      and whether he thinks he has expressed himself clearly enough
      so that other informed and intelligent people
      will also be completely convinced.

    - Clearly it is impossible to accept (C) without accepting (B),
      because it doesn't make sense to be convinced that
      something is true unless you know what it means.

    - The question often arises,
      whether a constructivist would accept a non-constructive proof
      of a numerical result involving no existential quantifiers,
      such as Goldbach's conjecture
      or Fermat's last theorem.
      My answer is supplied by (C):
      I would want to examine the proof to see
      whether I found it completely convincing.
      Perhaps one should keep an open mind,
      but I find it hard to believe that
      I would find any proof that
      relied on the principle of the
      ><><><

    - Classical mathematics
      fails to observe meaningful distinctions having to do with integers.
      This basic failure reflects itself
      at all levels of the classical development of mathematics.
      Consider the number n,
      defined to be 0 if the Riemann hypothesis is true
      and 1 if it is false.
      The constructivist does not wish to prevent the classicist from
      working with such numbers
      (although he may personally believe that their interest is limited).
      He does want the classicist to distinguish such numbers
      from numbers which can be "computed".
      such as the number n1 of primes less than 10^(10^10).
      Classical mathematicians do concern themselves sporadically
      with whether numbers can be "computed"
      but only on an ad hoc basis.
      The distinction is not observed
      in the systematic development of classical mathematics,
      nor would the tools available to the classicist
      permit him to observe the distinction systematically
      even if he were so inclined.

    - The constructivists are frequently accused of
      displaying the same insensitivity
      to shades of meaning of which they accuse the classicist,
      because they do not distinguish between numbers
      that can be computed in principle, such as the number n defined above,
      and numbers that can be computed in fact.
      Thus they violate their own principle (D).
      This is a serious accusation,
      and one that is not easy to refute.
      Rather than attempting to refute it,
      I shall give you my personal point of view.
      First, it may be demanding too much of the constructivists
      to ask them to lead the way
      in the development of usable and systematic methods
      for distinguishing computability in principle from computability in fact.
      If and when such methods are found,
      the constructivists will gratefully incorporate them
      into their mathematics.
      Second, it is by no means clear that
      such methods are going to be found.
      There is no fast distinction
      between computability in principle and in fact,
      because of the constant progress of
      the state of the art among other reasons.
      The most we can hope for is some good systematic measure
      of the efficiency of a computation.
      Until such is found,
      the problem will continue to be treated on an ad hoc basis.

    - I was careful not to call the number nn defined above an integer.Whether we do call it an integer is of no real importance, as long as wedistinguish it in some way from numbers such as n . For instance we mightcall nn an integer and call n a constructive integer. The constructivistshave not accepted this terminology, in part because of Brouwer's influence,but also because it does not accord with their estimate of the relativeimportance of the two concepts. I shall reserve the term "integer11 for what aclassicist might call a constructive integer, and put aside, at least for now,the problem of what would be an appropriate term for what is classicallycalled an integer (assuming that the classical notion of an integer is indeedviable).

    - Thus we come to the crucial question, "What is an integer? !l As wehave already seen, the question is badly phrased. We are really looking fora definition of an integer that will be an efficient tool for developing the fullcontent of mathematics. Since it is clear that we always work withrepresentations of integers, rather than integers themselves (whatever those maybe), we are really trying to define what we mean by a representation of aninteger. Again, an integer is represented only when some intelligent agentconstructs the representation, or establishes the convention that some artifactconstitutes a representation. Thus in its final version the question is, "Howdoes one represent an integer? If In practice we shall not be so meticulous asall this in our use of language. We shall simply speak of integers, with theunderstanding that we are really speaking of their representations. Thiscauses no harm, because the original concept of an integer, as somethinginvariant standing behind all of its representations, has just been seen to besuperfluous. Moreover we shall not constantly trouble to point out that
      (representations of) integers exist only by virtue of conventions established bygroups of intelligent beings. After this preliminary chatter, which may seemto have been unnecessary, we present our definition of an integer, dignified bythe title of the
      Fundamental Constructivist Thesis
      Every integer can be converted in principle to decimal form by a finite,purely routine, process.

    - Note the phrase "in principle. " It means that although we should beable to program a computer to produce the decimal form of any given integer,
      there are cases in which it would be naive to run the program and wait aroundfor the result.

    - Everything else about integers follows from the above thesis plus therules of decimal arithmetic that we learned in elementary school. Twointegers are equal if their decimal representations are equal in the usualsense. The order relations and the arithmetic of integers are defined interms of their decimal representations.

    - With the constructive definition of the integers, we have begun our studyof the technical implementation of the constructivist philosophy. Our point ofview is to describe the mathematical operations that can be carried out byfinite beings, man's mathematics for short. In contrast, classicalmathematics concerns itself with operations that can be carried out by God. Forinstance, the above number nn is classically a well-defined integer becauseGod can perform the infinite search that will determine whether the Riemannhypothesis is true. As another example, the smart sequences previouslydiscussed may be able to outwit you and me (or any other finite being), but theywill not be able to outwit God. That is why statement (*) is true classicallybut not constructively.

    - You may think that I am making a joke, or attempting to put downclassical mathematics, by bringing God into the discussion. This is not true. I amdoing my best to develop a secure philosophical foundation, based on meaningrather than formalisties, for current classical practice. The most solidfoundation available at present seems to me to involve the consideration of abeing with no n-finite-powers -- call him God or whatever you will --inaddition to the powers possessed by finite beings.

    - What powers should we ascribe to God? At the very least, we shouldcredit him with limited omniscence, as described in the following limitedprinciple of omniscence (LPO for short): If [n,} is any sequence of integers,then either tl = 0 for all k or there exists a k with n ^ 0. By acceptingLPO as valid, we are saying that the being whose capabilities our mathematicsdescribes is able to search through a sequence of integers to determinewhether they all vanish or not.

    - Let us return to the technical development of constructive mathematics,since it is simpler, and postpone the further consideration of classicalmathematics until later. Our first task is to develop an appropriate language todescribe the mathematics of finite beings. For this we are indebted to
      Brouwer. (See references [l], [6], [l5], [20], and [2l] for a morecomplete exposition that we are able to give here.) Brouwer remarked that themeanings customarily assigned to the terms "and, " "or, ,! "not, " "implies, ""there exists, " and "for all" are not entirely appropriate to the constructivepoint of view, and he introduced more appropriate meanings as necessary.

    - The connective "and" causes no trouble. To prove "A and B, " we mustprove A and also prove B, as in classical mathematics. To prove "A or B"we must give a finite, purely routine method which after a finite number ofsteps either leads to a proof of A or to a proof of B. This is very differentfrom the classical use of "or" ; for example, LPO is true classically, but weare not entitled to assert it constructively because of the constructive meaningof "or."

    - The connective "implies" is defined classically by taking "A impliesB"to mean "not A or B. " This definition would not be of much valueconstructively. Brouwer therefore defined "A implies B" to mean that there exists anargument which shows how to convert an arbitrary proof of A into a proof ofB. To take an example, it is clear that "{(A implies B) and (B implies C)}implies (A implies C)" is always true constructively; the argument thatconverts arbitrary proofs of "A implies B" and "B implies C" into a proof of"A implies C" is the following: given any proof of A, convert it into a proofof C by first converting it into a proof of B and then converting that proofinto a proof of C.

    - We define "not A" to mean that A is contradictory. By this we meanthat it is inconceivable that a proof of A will ever be given. For example,"not 0 = 1" is a true statement. The statement "0 = 1" means that when thenumbers "0" and "1" are expressed in decimal form, a mechanicalcomparison of the usual sort checks that they are the same. Since they are already indecimal form, and the comparison in question shows they are not the same, itis impossible by correct methods to prove that they are the same. Any suchproof would be defective, either technically or conceptually. As anotherexample, "not (A and not A)" is always a true statement, because if we provenot A it is impossible to prove A -- therefore, it is impossible to proveboth.

    - Having changed the meaning of the connectives, we should not besurprised to find that certain classically accepted modes of inference are nolonger correct. The most important of these is the principle of the excluded
      middle -- "A or not A.!l Constructively, this principle would mean that wehad a method which, in finitely many purely routine steps, would lead to aproof of disproof of an arbitrary mathematical assertion A. Of course wehave no such method, and nobody has the least hope that we ever shall. It isthe principle of the excluded middle that accounts for almost all of theimportant unconstructivities of classical mathematics. Another incorrect principleis "(not not A) implies A.11 In other words, a demonstration of theimpossibility of the impossibility of a certain construction, for instance, does notconstitute a method for carrying out that construction.

    - I could proceed to list a more or less complete set of constructivelyvalid rules of inference involving the connectives just introduced. This wouldbe superfluous. Now that their meanings have been established, the rest iscommon sense. As an exercise, show that the statement"(A—>0 = 1)«—*not A"is constructively valid.

    - The classical concept of a set as a collection of objects from some pre-existent universe is clearly inappropriate constructively. Constructivemathematics does not postulate a pre-existent universe, with objects lying aroundwaiting to be collected and grouped into sets, like shells on a beach. Theentities of constructive mathematics are called into being by the constructingintelligence. From this point of view, the very question "What is a set? " issuspect. Rather we should ask the question, "What must one do to construct aset? " When the question is posed this way, the answer is not hard to find.

    - Definition. To construct a set, one must specify what must be done toconstruct an arbitrary element of the set, and what must be done to prove twoarbitrary elements of the set are equal. Equality so defined must be shown tobe an equivalence relation.

    - As an example, let us construct the set of rational numbers. Toconstruct a rational number, define integers p and q and prove that q 4 0. Toprove that the rational numbers p/q and P1/q1 are equal, prove pq. =p.q.

    - While we are on the subject, we might as well define a function f: A -* B.It is a rule that to each element x of A associates an element f(x) of B,equal elements of B being associated to equal elements of A.

    - The notion of a subset A of a set A is also of interest. To constructan element of A , one must first construct an element of A , and then provethat the element so constructed satisfies certain additional conditions,characteristic of the particular subset A . Two elements of A are equal if theyare equal as elements of A .

    - Contrary to classical usage, the scope of the equality relation neverextends beyond a particular set. Thus it does not make sense to speak ofelements of different sets as being equal, unless possibly those different sets areboth subsets of the same set. This is because for the constructivist equalityis a convention, whose scope is always a given set; all this is conceptuallyquite distinct from the classical concept of equality as identity. You see nowwhy the constructivist is not forced to resort to the artifice of equivalenceclasses!

    - After this long digression, consider again the quantifiers. Let A(x) bea mathematical assertion depending on a parameter x ranging over a set S.To prove !l V xA(x), n we must give a method which to each element x of Sassociates a proof of A(x). Thus the meaning of the universal quantifier !IV !lis essentially the same as it is classically.

    - We expect the existential quantifier !l3,!l on the other hand, to have anew meaning. It is not clear to the constructivist what the classicist meanswhen he says "there exists." Moreover, the existential quantifier is just aglorified version of "or, !l and we know that a reinterpretation of thisconnective was necessary. Let the variable x range over the set S. Then to prove!l3xA(x)n we must construct an element xn of S, according to the principleslaid down in the definition of S , and then prove the statement ,!A(xn). !l

    - Again, certain classical uses of the quantifiers fail constructively. Forexample, it is not correct to say that "not V xA(x) implies 3 x not A(x). "On the other hand, the implication "not 3 xA(x) implies V x not A(x)" isconstructively valid. I hope all this accords with your common sense, as itdoes with mine.

    - Perhaps you see an objection to these developments -- that they appearto violate constructivist principle (D) above. By accommodating ourterminology to the mathematics of finite beings, have we not replaced the classicalsystem, that does not permit the systematic development of constructivemeaning, by a system that does not permit the systematic development of classicalmeaning? In my opinion the exact opposite is true -- the constructive
      terminology just introduced affords as good a framework as is presentlyavailable for expressing the content of classical mathematics.

    - If you wish to do classical mathematics, first decide what non-finiteattributes you are willing to grant to God. You may wish to grant him LPOand no others. Or you may wish to be more generous and grant him EM, theprinciple of the excluded middle, possibly augmented by some version of theaxiom of choice. When you have made your decision, avail yourself of all theapparatus of the constructivist, and augment it by those additional powers(LPO or EM or whatever) that you have granted to God. Although you will beable to prove more theorems than the constructivist will, because your beingis more powerful than his, his theorems will be more meaningful than yours.Moreover to each of your theorems he will be able to associate one of his,having exactly the same meaning. For example, if LPO is the only non-finiteattribute of your God, then each of your theorems !IA!I he will restate and
      prove as !lLPO implies A.!l Clearly the meaning will be preserved. On theother hand, if he proves a theorem "B, " you will also be able to prove !IB,!lbut your !IB!I will be less meaningful than his. The classical interpretation ofeven such simple results as Goldbach's conjecture is weaker than theconstructive interpretation. In both cases the same phenomena -- the results ofcertain finitely performable computations -- are predicted, but the degree ofconviction that the predicted phenomena will actually be observed is greater inthe constructive case, because to trust the classical predictions one mustbelieve in the theoretical validity of the concept of a God having the specifiedattributes, whereas to trust the constructive predictions one must only believein the theoretical validity of the concept of a being who is able to performarbitrarily involved finite operations.

    - It would thus appear that even a constructive proof of such a result asflthe number of zeros in the first n digits of the decimal expansion of tt doesnot exceed twice the number of ones11 would leave us in some doubt as towhether the prediction is correct for any particular value of n, say for n =1000. We have brought mathematics down to the gut level. My gut tells meto trust the constructive prediction and be wary of the classical prediction. Isee no reason that yours should not tell you to trust both, or to trust neither.

    - In common with other constructivists, I also have gut feelings about therelative merits of the classical and constructive versions of those resultswhich, unlike Goldbach's conjecture, assert the existence of certain quantities.
      If we let "A" be any such result, with the constructive interpretation, then theconstructive version of the corresponding classical result will be (forinstance) "LPO -* A, " as we have seen. My feeling is that is likely to beworth whatever extra effort it takes to prove "A11 rather than "LPO -» A. "

    - The linguistic developments I have outlined could be taken as the basisfor a formalization of constructive (and therefore of classical) mathematics.So as not to create the wrong impression, I wish to emphasize again certainpoints that have already been made.

      FormalismThe devil is very neat. It is his prideTo keep his house in order. Every bitOf trivia has its place. He takes great painsTo see that nothing ever does not fit.And yet his guests are queasy. All their food,Served with a flair and pleasant to the eye,Goes through like sawdust. Pity the perfect host!The devil thinks and thinks and he cannot cry.

      ConstructivismComputation is the heartOf everything we prove.Not for us the velvet wisdomOf a softer love.If Aphrodite spends the night,Let Pallas spend the day.When the sun dispels the starsPut your dreams away.

    - There are at least two reasons for developing formal systems forconstructive mathematics. First, it is good to state as concisely andsystematically as we are able some of the objects, constructions, terminology, andmethods of proof. The development of formal systems that catch these aspectsof constructive practice should help to sharpen our understanding of how bestto organize and communicate the subject. Second and more important,informal mathematics is the appropriate language for communicating withpeople, but formal mathematics is more appropriate for communicating withmachines. Modern computer languages (see the report [30], for example),while rich in facilities, seem to be lacking in philosophical scope. It might beworthwhile to investigate the possibility that constructive mathematics would
      afford a solid philosophical basis for the theory of computation, andconstructive formalism a point of departure for the development of a better computerlanguage. Certainly recursive function theory, which has played a centralrole in the philosophy of computation, is inadequate to the task.

    - The development of a constructive formalism at any given level wouldseem to be no more difficult than the development of a classical formalism atthe same level. See [17], [18], [20], [2l], [22], and [27] for examples.For a discussion of constructive formalism as a computer language, see [2] .

    - Let us return to the technical development of constructive mathematics,and ask what is meant constructively by a function f: 7Z ~* 7Z (where Z is theset of integers). We improve the classical treatment right away - instead oftalking about ordered pairs, we talk about rules. Our definition takes afunction F: Z -» 2 to be a rule that associates to each (constructively defined)integer n a (constructively defined) integer f(n), equal values beingassociated to equal arguments. For a given argument n, the requirement that f(n)be constructively defined means that its decimal form can be computed by afinite, purely routine process. That's all there is to it. Functions f: Z -* Q,f: Q-»Q, f: Z -» Q are defined similarly. (Here Q is the set of rational+ +numbers and Z the set of positive integers.) A function with domain Z iscalled a sequence, as usual.

    - Now that we know what a sequence of rational numbers is, it is easy todefine a real number. A real number is a Cauchy sequence of rationalnumbers! Again, I have improved on the classical treatment, by not mentioningequivalence classes. I shall never mention equivalence classes. To be surewe completely understood this definition, let us expand it a bit. Real numbersare not pre-existent entities, waiting to be discovered. They must beconstructed. Thus it is better to describe how to construct a real number, thanto say what it is. To construct a real number, one must(a) construct a sequence {x } of rational numbers,n(b) construct a sequence {N } of integers,n(c) prove that for each positive integer n we have1 |x. - x. I £ — whenever i ^ N and j J ^ N .i J1 n n nOf course, the proof (c) must be constructive, as well as the constructions (a)and (b).

    - Two real numbers [a } and {b } (the corresponding convergencen nparameters (b) and proofs (c) are assumed without explicit mention) are saidto be equal if for each positive integer k there exists a positive integer N1such that la -b I ^r whenever n <* N. . It can be shown that this notion1 n n* k kof equality is an equivalence relation. Addition and multiplication of realnumbers are also defined in the same way as they are defined classically.The order relation, on the other hand, is more interesting. If a = {a } andnb = {b } are real numbers, we define a < b to mean that there exist posi-n1tive integers 6 M and N such that a £ b - — whenever n ^ N. Then it isn n Measily shown that a < b and b < c imply a < c, that a < b impliesa - c < b - c, and so forth. Some care must be exercised in defining therelation £ We could define a £ b to mean that either a < b or a = b. An.alternate definition would be to define it to mean that b < a is contradictory.We shall not use either of these, although our definition turns out to beequivalent to the latter.

    - DEFINITION, a £ b means that for each positive integer M there existsa positive integer N such that b ^ a - — whenever n ^ N.

    - To make the choice of this definition plausible, I shall construct acertain real number HH- I a 2n= 1where a = 0 in case every even integer between 4 and n is the sum of twon nprimes, primes, r and and a a = =1 1 otherwise. o1 (More precisely, H is given by the Cauchynsequence [a^} , withn
      a = / a.*k=land the sequence {N } of convergence parameters, where N = n. ) Clearlyn nwe wish to have H ^ 0. It certainly is according to the definition we havechosen. (The real number 0 of course is the Cauchy sequence of rationalnumbers all of whose terms are 0.) On the other hand, we would not beentitled to assert that H £ 0 if we had defined H ^ 0 to mean that either H> 0or H = 0, because the assertion f,H> 0 or H = 0" means that we have afinite, purely routine method for deciding which; in this case, a finite, purely
      routine method for proving or disproving Goldbach's conjecture!

    - Most of the usual theorems about ^ and < remain true constructively,with the exception of trichotomy. Not only does the usual form !la < b ora = b or a > b11 fail, but such weaker forms as "a < b or a ^ b,,f or even!,a ^ b or a ^ b11 fail as well. For example, we are not entitled to assert"0 < H or 0 = H or 0 > H.!l If we consider the closely related numberH'= 1 <*, '2n <-2fn .n= -i 1we are not even entitled to assert that "H* ^ 0 or H £ 0. !l

    - Since trichotomy is so fundamental, we might expect constructivemathematics to be hopelessly enfeebled because of its failure. The situation issaved, because trichotomy does have a constructive version, which of courseis considerably weaker than the classical.

    - THEOREM. For arbitrary real numbers a, b, and c, with a < b,either c > a or c < b.
      PROOF. Choose integers M and Nrt such that a £ b - t-t whenever0 n n Mn ^ N_ . Choose integers & N , N, , and N such that la ' -a I £ (6M)~0 a b c n m1whenever n, m^N, lb -b I £ (6M) whenever n,m ^ N, , |c -c I £an m' b n m'(6M) whenever n, m ^ N . Set N = max{NA, N , N, , N } . Since a_.,c 0 a d c JNbN, and cN are all rational numbers, eitherCN<i(aN+V °r CN*2(aN+V •.Consider first the case cN ^ T^aN + bN^' Since aN ^ bKr " M" » ** followsthat aN £ - (2M) . For each n £ N we therefore havecN* + (6M)1 * " (2M)^ + (6M)1an aN CN£c + (6M)"1 - (ZM)"1^-(6M)"1= c - (6M)"1 .n nTherefore, a < c. In the other case, cN < -r (aN + bN), it follows similarlythat c < b. This completes the proof of the theorem.

    - Do not be deceived by the use of the word "choose11 in the above proof,which is simply a carry-over from classical usage. No choice is involved,
      because M and N , for instance, are fixed positive integers, definedexplicitly by the proof of the inequality a < b. Of course we could decide tosubstitute other values for the original values of M and N , if we desired, sosome choice is possible should we wish to exercise it. If we do not explicitlystate what choice we wish to make, it will be assumed that the values of Mand N given by the proof of a < b are chosen.

    - The number H, which is constructively a well-defined real number, isclassically rational, because if the Goldbach conjecture is true then H = 0,and if the conjecture is false then H = 2 , where n is the first eveninteger for which it fails. We are not entitled to assert constructively that His rational: if it is rational, then either H = 0 or H/0, meaning that eitherGoldbach1 s conjecture is true or else it is false; and we are not entitled toassert this constructively, until we have a method for deciding which. We arenot entitled to assert H is irrational either, because if H is irrational, thenH 4 0, therefore Goldbach!s conjecture is false, therefore H is the rationalnumber 2 , a contradiction! Thus H cannot be asserted to be rational,although its irrationality is contradictory. (I am indebted to Halsey Roydenfor this amusing observation.)

    - It is easy to prove the existence of many irrational numbers, by provingthe uncountability of the real numbers, as a corollary of the Baire categorytheorem. For the present, let us merely remark that \TI is irrational. Ofcourse, can be defined by constructing successive decimalapproximations. It is therefore constructively well-defined. The classical proof of theirrationality of n/T shows that if p/q is any rational number then p/q 4 2.Since both p /q and 2 can be written with denominator q , it follows that2-VTI q I . I 12+VT| q = V2 1q qSince clearly p/q 4 *J~Z in case p/q < 0 or p/q > 2 , to show that p/q 4 n/Twe may assume 0 £ p/q £ 2 . Then'I ' '* ' q2 q2 4q2Therefore, n/T 4 p/q. Thus 'v/T is (constructively) irrational.

    - The failure of the usual form of trichotomy means that we must becareful in defining absolute values and maxima and minima of real numbers. For
      example, if x = (x ] is a real number, with sequence [N } of convergencen nparameters, then |x| is defined to be the Cauchy sequence [|x |} ofrational numbers (with sequence {N } of convergence parameters). Similar-nooly, min(x,y} is defined to be the Cauchy sequence (min(xn»yn^n=i » andmax[x,y} to be [maxfx , y }} . .n n n-i

    - This definition of min, in particular, has an amusing consequence.Consider the equationx2 - xH' = 0 .Clearly 0 and the number H* are solutions. Are they the only solutions? Itdepends on what we mean by "only.11 Clearly min{0, H*} is a solution, andwe are unable to identify it with either 0 or H' . Thus it is a third solution!The reader might like to amuse himself looking for others. This discussionincidentally makes the point that if the product of two real numbers is 0 weare not entitled to conclude that one of them is 0. (For example, x(x-H') = 0does not imply that x = 0 or x - H' = 0: set x = min { 0, H'} .)

    - The constructive real number system as I have described it is notaccepted by all constructivists. The intuitionists and the recursive functiontheorists have other versions.

    - For Brouwer, and his followers (the intuitionists), the constructive realnumbers described above do not constitute all of the real number system. Inaddition there are incompletely determined real numbers, corresponding tosequences of rational numbers whose terms are not specified by a masteralgorithm. Such sequences are called "free-choice sequences, l! because thecreating subject, who defines the sequence, does not completely commithimself in advance but allows himself some freedom of choice along the way indefining the individual terms of the sequence.

    - There seem to be at least two motivations for the introduction of free-choice sequences into the real number system. First, since each constructivereal number can presumably be described by a phrase in the English language,on superficial consideration the set of constructive real numbers would appearto be countable. On closer consideration this is seen not to be the case:Cantor's uncountability theorem holds, in the following version. If {x } isnany sequence of real numbers, there exists a real number x with x/x fornall n. Nevertheless it appears that Brouwer was troubled by a certain aura ofthe discrete clinging to the constructive real number system IR. Second,
      every function anyone has ever been able to construct from R to R hasturned out to be continuous, in fact uniformly continuous on bounded subsets.(The function f that is 1 for x £ 0 and 0 for x < 0 does not count, becausefor those real numbers x for which we have no proof of the statement "x ^ 0,or x < 0fl we are unable to compute f(x).) Brouwer had hopes of proving thatevery function from R to R is continuous, using arguments involving freechoice sequences. He even presented such a proof [7] . It is fair to say thatalmost nobody finds his proof intelligible. It can be made intelligible byreplacing Brouwer !s arguments at two critical points by axioms, that Kleene andVesley [21] call "Brouwer's principle11 and !*the bar theorem.I! My objectionto this is, that by introducing such a theorem as !lall f : R -» R arecontinuous11 in the guise of axioms, we have lost contact with numerical meaning.Paradoxically this terrible price buys little or nothing of real mathematicalvalue. The entire theory of free-choice sequences seems to me to be made ofvery tenuous mathematical substance.

    - If it is fair to say that the intuitionists find the constructive concept of asequence generated by an algorithm too precise to adequately describe the realnumber system, the recursive function theorists on the other hand find it toovague. They would like to specify more precisely what is meant by analgorithm, and they have a candidate in the notion of a recursive function. Theyadmit only sequence of integers or rational numbers that are recursive (aconcept we shall not define here: see [20] for details). Their reasons are, thatthe concept is more precise than the naive concept of an algorithm, that everynaively defined algorithm has turned out to be recursive, and it seems unlikelywe shall ever discover an algorithm that is not recursive. This requirementthat every sequence of integers must be recursive is wrong on threefundamental grounds. First and most important, there is no doubt that the naiveconcept is basic, and the recursive concept derives whatever importance it
      has from some presumption that every algorithm will turn out to be recursive.Second, the mathematics is complicated rather than simplified by therestriction to recursive sequences. If there is any doubt as to this, it can beresolved by comparing some of the recursivist developments of elementaryanalysis with the constructivist treatment of the same material. Even if one isoriented to running material on a computer, the recursivist formulation wouldconstitute an obstacle, because very likely the recursive presentation wouldbe translated into computer language by first translating into common
      constructive terminology (at least mentally) and then translating that into thelanguage of whatever computer was being used. Third, no gain in precision isactually achieved. One of the procedures for defining the value of a recursivefunction is to search a sequence of integers one by one, and choose the firstthat is non-zero, having first proved that one of them is non-zero. Thus thenotion of a recursive function is at least as imprecise as the notion of acorrect proof. The latter notion is certainly no more precise than the naivenotion of a (constructive) sequence of integers.

    - The desire to achieve complete precision, whatever that is, is doomedto frustration. What is really being sought is a way to guarantee that nodisagreements will arise. Mathematics is such a complicated activity thatdisagreements are bound to arise. Moreover, mathematicians will always betempted to try out new ideas that are so complicated or innovative that theirmeaning is questionable. What is important is not to develop some framework,such as recursive function theory, in the vain hope of forestalling questionableinnovations, but rather to subject every development to intense scrutiny (interms of the meaning, not on formal grounds).

    - Recursive functions come into their own as the source of certaincounter-examples in constructive mathematics, the most famous being theword-problem in the theory of groups. Since the concept of a (constructively)recursive sequence is narrower than the concept of a (constructive) sequence,it is easier to demonstrate that there exist no recursive sequences satisfyinga given condition G. Such a demonstration makes it extremely unlikely that a(constructive) sequence satisfying G will be found without some radically newmethod for defining sequences being discovered, a discovery that many viewas almost out of the question.

    - Although some very beautiful counter-examples have been given bymeans of recursive functions, they have also been used as a source ofcounterexamples in many situations in which a prior technique due to Brouwer [20]would have been both simpler and more convincing. Brouwer !s idea is tocounter-example a theorem A by proving A -* LPO. Since nobody seriouslythinks LPO will ever be proved, such a counter-example affords a goodindication that A will never be proved. As an instance, Brouwer has shown thatthe statement that every bounded monotone sequence of real numbersconverges implies LPO.

    - Another source of Brouwerian counter-examples is the statement LLPO(for the !llesser limited principle of omniscience11), that if {n, } is anysequence of integers, then either the first non-zero term, if one exists, is evenor else the first non-zero term, if one exists, is odd. Clearly LPO -* LLPO,but there seems to be no way to prove that LLPO -» LPO. Nevertheless, weare just as sceptical that LLPO will ever be proved. Thus A -* LLPO isanother type of Brouwerian counter-example for A. As an instance, thestatement that "either x2:0 or x £ 0 for each real number x11 impliesLLPO, in fact is equivalent to it.

    - Thus we are so sceptical that the statements LPO, LLPO, and their ilkwill ever be proved that we use them for building counter-examples. Thestrongest counter-example to A would be to show that a proof of A isinconceivable, in other words to prove !,not A, !l but proving "A -* LPO11 or11A ■* LLPO11 is almost as good. In fact, I personally find it inconceivablethat LPO (or LLPO for that matter) will ever be proved. Nevertheless Iwould be reluctant to accept !*not LPO11 as a theorem, because my belief inthe impossibility of proving LPO is more of a gut reaction prompted byexperience than something I could communicate by arguments I feel would be sureto convince any objective, well-informed, and intelligent person. Theacceptance of lfnot LPO11 as a theorem would have one amusing consequence, that thetheorems of constructive mathematics would not necessarily be classicallyvalid (on a formal level) any longer. It seems we are doomed to live with!lLPO!l and !,there exists a function from [0, 1] to R that is not uniformlycontinuous'1 and similar statements, of whose impossibilities we are not quitesure enough to assert their negations as theorems.

    - The classical paradoxes are equally viable constructively, the simplestperhaps being "this statement is false. " The concept of the set of all setsseems to be paradoxical (i.e., lead to a contradiction) constructively as wellas classically. Informed common sense seems to be the best way of avoidingthese paradoxes of self reference. Their spectre will always be lurking overboth classical and constructive mathematics. Hermann Weyl made themeticulous avoidance of self reference the basis of a whole new development of thereal number system (see Weyl [32] ) that has since become known aspredicative mathematics. Weyl later abandoned his system in favor of intuitionism.I see no better course at present that to recognize that certain concepts are
      inherently inconsistent and to familiarize oneself with the dangers of self-reference.

    - Not only is there insufficient time, but I would not be competent toreview all of the recent advances of constructive mathematics, including thoseof ad hoc constructivism as well as those taking place under constructivistphilosophies at variance with those that I have presented here, for examplethe recursivist constructivism of Markov and his school in Russia. (I havebeen told that some of the recent advances in differential equations have tendedto present that subject in a more constructive light. Perhaps Felix Browderwill give us some information about those developments.) I shall restrictmyself in what remains to selected developments with which I am familiar, thatseem to me to be of special interest.

    - Brouwer [6] was the first to develop a constructive theory of measureand integration, and the intuitionist tradition (see [19] and [31] for instance)in Holland carried the development further, working with Lebesgue measureon R . In [1] I worked with arbitrary measures (both positive and negative)on locally compact spaces, recovering much of the classical theory. TheDaniell integral was developed in full generality in [5]. The concept of anintegration space postulates a set X, a linear subset L of the set of allpartially-defined functions from X to R, and a linear functional I from Lto R having the properties
      (1) if f € L, then |f| € L and min {f, 1 } € L(2) if f € L and f € L for each n, ' such that f * 0 and» n n£ , 1(f) converges to a sum that is less than 1(f), thenE . f (x) converges and is less than f(x), for some x in the commonn— i ndomain of f and the functions fn(3) I(p) 4 0 for some p € L(4) lim Krnin {f,n}) = 1(f) and lim Kmin { |f | , n"1 }) = 0 forn-»® n-> »all fin L,We define L^ to consist of all partially defined functions f from Xto R such that there exists a sequence ff } of elements of L such thatn(a) E . K|f | ) converges and (b) Z* f (x) = f(x) whenever Z°° , |f (x)|n—i n n-i n n=i nconverges.

    - It turns out to be possible to extend I to L in such a way that(X, L. , I) also satisfy the axioms, and in addition L. is complete under themetric p(f,g) = I(|f-g|).

    - The only real problem in recovering the classical Daniell theory isposed by the classical result that if f € L then the set A = f x € X: f(x) 2>t]is integrable for all t > 0 (in the sense that its characteristic function x ,defined by xtW = 1 if f(x) * t and xfcfe) = 0 if f(x) < t, is in 1^). Theconstructive version is that A is integrable for all except countably manyt > 0. The proof of this requires a rather complex theory, called the theoryof profiles. Y. K. Chan informs me that he has been able to simplify thetheory of profiles considerably. He has also effected a considerablesimplification in another trouble-spot of [5], the proof that a non-negative linearfunctional I on the set L. = C(X) of continuous functions on a compact spaceX satisfies the axioms for an integration space presented above. (Axiom (2)is the troublemaker•)

    - Constructive integration theory affords the point of departure for somerecent constructivizations of parts of probability theory. There is no(constructive) way to prove even the simplest cases of the ergodic theorem,such that if T denotes rotation of a circle X through an angle df then foreach integrable function f: X -* R and almost all x in X, the averagesN*nW = Tf 2 *(Tn*)n= 1converge. (The difficulty comes about because we are unable to decide forinstance whether a = 0.) One way to recover the essence of the ergodictheorem constructively, and in fact deepen it considerably, is to show that thesequence {fN } satisfies certain integral inequalities, analogous to the up-crossing inequalities (see [14]) of martingale theory. This was done in thecontext of the Chacon-Ornstein ergodic theorem in [1], and even moregenerally in [3].

    - John Nuber [23] takes another route, He presents sufficient conditions,close to being necessary, that the sequence {*N} actually converges a. e., inthe context of the classical Birkhoff ergodic theorem. More recently, in anunpublished manuscript, he has generalized his conditions to the context of theclassical Chacon-Ornstein theorem.

    - Y. K. Chan has done much to constructivize the theory of stochasticprocesses. His paper [lO] unifies the two classically distinct cases of therenewal theorem into one constructive result. His paper [l2] contains thefollowing theorem:

    - THEOREM. Let p, and [X ~ be probability measures on R, and f.and f? their characteristic functions (Fourier transforms). Let g be acontinuous function on R, with |g| £ 1. Then for every e > 0 there exist6 > 0 and 9 > 0, depending only on c and the moduli of continuity of f., i~,and g, such thatl/gdU^/gdu^cwhenever |f -fJ<6 on [-6,4].

    - A simple corollary is Levy's theorem, that if [\i } is a sequence ofprobability measures on iR, whose characteristic functions {f } convergeuniformly on compact sets to some function f , then \X converges weakly toa probability measure M whose characteristic function is f

    - Levy's theorem is classically an important tool for provingconvergence of measures. Chan shows that this is also true constructively, by usingit to get constructive proofs of the central limit theorem and of the Levy-Khintchine formula for infinitely divisible distributions.

    - Chan's papers [9] and [ll] are primarily concerned with the problemof constructing a stochastic process. In [9] he gives a constructive versionof Kolmogorov's extension theorem. In [ll], he constructivizes the classicalderivation of a time homogeneous Markov process from a strongly continuoussemi-group of transition operators. In addition he proves Ionescu Tulcea'stheorem and a super martingale convergence theorem.

    - H. Cheng [l3] has given a very pretty version of the Riemann mappingtheorem and Caratheodory's results on the convergence of mapping functions.He defines a simply connected proper open subset U of the complex plane Cto be mappable relative to some distinguished .point z of U if for each€ > 0 there exist finitely many points z , . . . , z in the complement of U1 nsuch that any continuous path beginning at z and having distance ^ e fromeach of the points z , . . ., z lies entirely in U . He shows that mappabilityis necessary and sufficient for the existence of a mapping function. He goeson to study the dependence of the mapping function on the domain, by defining
      natural metrics on the space D of domains (with distinguished points zQ) andthe space M of mapping functions, and proving that the function X * D -* Mthat associates to each domain its mapping function is a homeomorphism. Hethus extends and constructivizes the classical Caratheodory results. Many ofhis estimates are similar to those developed by Warschawski in his studies ofthe mapping function.

    - The problem of constructivizing the classical theory of uniformizationis still open. (Even reasonable conjectures seem difficult to come by. ) So isthe problem of (constructively) constructing canonical maps for multiplyconnected domains, as far as I know.

    - It is natural to define two sets to have the same cardinality if they arein one-one correspondence. The constructive theory of cardinality seemshopelessly involved, due to the constructive failure of the Cantor-Bernsteinlemma, and for other reasons as well.

    - Progress has been made however in constructivizing the theory ofordinal numbers. Brouwer [8] defines ordinals to be ordered sets that arebuilt up from non-empty finite sets by finite and countable addition.F. Richman [26] gives a more general definition. Simple in appearance, hisdefinition constructivizes the property of induction in just the right way. Anordinal number (or well-ordered set) is a set S with a binary relation < suchthat(1) if a <b and b > c, then a < c(2) one and only one of the relations a<b, b<a, a=b holds for givenelements a and b of S(3) let T be any subset of S with the property that every element b ofS, such that a € T for each a in S with a < b, belongs to T; thenT =S.

    - Richman shows that each Brouwerian ordinal satisfies (1), (2), and (3).He gives examples of ordinals (in his sense) that are not Brouwerian. Heshows that every subset of an ordinal is an ordinal (under the induced order).He uses his theory to constructivize the classical theorems of Zippin and Ulmconcerning existence and uniqueness of p-groups with prescribed invariants.

    - The above examples might give the impression that the constructiviza-tion of classical mathematics always proceeds smoothly. I shall now givesome other examples, to show that in fact it does not.

    - In [l] the Gelfand theory of commutative Banach algebras was con-structivized to a certain extent. The theory has to be consideredunsatisfactory, not because the classical content is not recovered (it is), but becauseit is so ugly. It is almost certain that a prettier constructivization willsomeday be found.

    - Stolzenberg [28] gives a meticulous analysis of some of theconsiderations involved in constructivizing a particular classical theory, the openmapping theorem and related material. Again, an incisive constructivization isnot obtained.

    - J. Tennenbaum [29] gives a deep and intricate constructive version ofHilbert's basis theorem. Consider a commutative ring A with unit. It wouldbe tempting to call A (constructively) Noetherian if for each sequence {a }of elements of A there exists an integer N such that for n ^ N the elementa is a linear combination of a.,.. •, a . with coefficients in A. Thisn 1 n-1notion would be worthless -- not even the ring of integers is Noetherian in thissense. In case A is discrete (meaning that the equality relation for A isdecidable), the appropriate constructive version of Noetherian seems to be thefollowing (as given in [29]).

    - DEFINITION. A sequence {a } of elements of A is almosteventually zero if for each sequence {n. } of positive integers there exists apositive integer k such that a =0 for k £ n £ k + 11, .DEFINITION. A basis operation r for A is a rule that to each finitesequence a , . . . ,a of elements of A assigns an element r(a_, . . . ,a ) ofIn InA of the form a + \,a. + • • • + X ,a ,, where each X. belongs to A.nil n-l n-i 1DEFINITION. A is Noetherian if it has a basis operation r such thatfor each sequence {a } of elements of A the associated sequence£r (a , . . . , a ) } is almost eventually zero.1 n

    - Tennenbaum proved the appropriateness of his version of Noetherian bychecking out the standard cases and proving the Hilbert basis theorem. Healso extended his definition and results to the case of a not-necessarilydiscrete ring A. The theory in that case is so complex that it cannot beconsidered satisfactory.

    - In spite of the pioneering efforts of Kronecker, and continued work bymany algebraists, resulting in many deep theorems, the systematic
      constructivization of algebra would seem hardly to have begun. The problemsare formidable. A very tentative suggestion is that we should restrict ourattentions to algebraic structures endowed with some sort of topology, withrespect to which all operations and maps are continuous. The work ofTennenbaum quoted above might provide some ideas of how to accomplish this.The task is complicated by the circumstance that no completely suitableconstructive framework for general topology has yet been found.

    - The constructivization of general topology is impeded by two obstacles.First, the classical notion of a topological space is not constructively viable.Second, even for metric spaces the classical notion of a continuous function isnot constructively viable; the reason is that there is no constructive proof thata (pointwise) continuous function from a compact (complete and totally bounded)metric space to R is uniformly continuous. Since uniform continuity forfunctions on a compact space is the useful concept, pointwise continuity (nolonger useful for proving uniform continuity) is left with no useful function toperform. Since uniform continuity cannot be formulated in the context of ageneral topological space, the latter concept also is left with no usefulfunction to perform.

    - In [l] I was able to get along by working mostly with metric spaces andusing various ad hoc definitions of continuity: one for compact spaces,another for locally compact spaces, and another for the duals of Banach spaces.The unpublished manuscript [4] was an attempt to develop constructive generaltopology systematically. The basic idea is that a topological space shouldconsist of a set X, endowed with both a family of metrics and a family of bound-edness notions, where a boundedness notion on X is a family S of subsetsof X (called bounded subsets), whose union is X, closed under finite unionsand the formation of subsets.

    - For example, let C be the set of all real valued functions f: R -* R ,bounded and (uniformly) continuous on finite intervals. Each finite intervalof R induces a metric on C (the uniform metric on that interval). Inaddition, there is a natural boundedness notion S. A subset E of C belongs toS if there exists r>0 such athat |f| ^ r for all f in E. A sequence {f }of elements of C converges to an element f of C if it converges withrespect to each of the metrics on C, and if it is bounded.

    - The notion of a continuous function from one such space to another, asgiven in [4] , is somewhat involved and will not be repeated here. It was
      possible to develop a theory that seems to accommodate the known examplesand to have certain pleasing functorial qualities, but the theory is somehow notconvincing -- for one thing, it is too involved. For another, there is a certainsort of space -- let us call it a ball space -- that does not fit well into thetheory.

    - DEFINITION. A ball space is a set X, together with a function that toeach r ^ 0 and point x of X associate a subset B(x, r) of X (to be thoughtof as the closed ball of radius r about x) satisfying the following axioms.(a) B(x,r) c B(x, s) if r £ s .(b) B(x,0) = {x}.(c) B(x.r) = 0 [B(x, s): s>r} .(d) If y € B(x,r), then x S B(y,r) .(e) If y € B(x,r) and z € B(y, s), then z € B(x, r+s).(f) U {B(x,r): r * 0} = X .

    - Duals of Banach spaces are particular instances of ball spaces, as arevarious other function spaces.

    - Algebraic topology, at least at the elementary level, should not be toodifficult to constructivize. There is a problem with defining singular co-homology constructively, as pointed out in [2], Richman [25] points out thatthe classical Vietoris homology theory is not satisfactory constructively, andhe gives a new version that constructively (and also classically) has certainfeatures that are more desirable.

* 總結 / conclude

*** 譯文

    * ><

*** 原文

    * I would like to conclude these lectures by discussing some of the tasksthat face constructive mathematics.

    * Of primary importance is the systematic constructive development ofenough of algebra for a pattern to begin to emerge. Of course, it may be thatmuch of the classical theory is inherently unconstructivizable, and thatconstructive algebra will go its own way. It is too early to tell.

    * Less critical, but also of interest, is the problem of a convincingconstructive foundation for general topology, to replace the ad hoc definitions incurrent use. It would also be good to see a constructivization of algebraictopology actually carried through, although I suspect this would not pose thecritical difficulties that seem to be arising in algebra.

    * To sum up, the first task is to constructivize as much of existingclassical mathematics as is suitable for constructivization. As this is being
      done, we should increasingly turn our attention to questions of the efficiency ofour algorithms, and bridge the gap between constructive mathematics on theone hand and numerical analysis and the theory of computation on the other.Since constructive mathematics is the study of what is theoreticallycomputable, it should afford a sound philosophical basis for the theory ofcomputation.

    * Our terminology and technical devices need constant re-examination asto whether they are the most appropriate tools for extracting the full meaningfrom our material. It seems to me that the meaning of implication, inparticular, should be thoroughly studied, and other possible candidatesinvestigated. Such statements as "(A -* B) -* C" have a rather tenuous meaning, andin many instances of proofs of such statements, something more is actuallybeing proved. Work of Godel [17] raises some interesting possibilities aboutpossible re-definitions of implication, which seem to be very difficult toimplement in usable generality, and which also seem to run counter to naturalmodes of thought. There seems to be no reason in principle that we shouldnot be able to develop a viable terminology that incorporates more than onemeaning for some or all of the quantifiers and connectives.

    * More important than any of these technical problems is the broaderproblem of involving ourselves more deeply with the meaning of mathematicsat all levels. This is the simplest and most general statement of the con-structivist program, and the technical developments are intended as a meansto that end.
