#+HTML_HEAD: <link rel="stylesheet" href="../asset/css/page.css" type="text/css" media="screen" />
#+TITLE: the group of mapping classes / 映射類羣

- 作者 Max Dehn
  譯者 謝宇恆

* 題解

  - Dehn 的原文爲德文
    基於 Dehn 1922 年在 Breslau 的演講
    發表於 1938 年

  - 原文由 John Stillwell 翻譯爲英文
    出版於 papers on group theory and topology, 1987
    本譯文轉譯自英文

  - 因爲是轉譯
    原作者的文風無論如何都難以保留了
    因此我有時使用意譯 以使得敘述變得更清晰

  - 文中插圖只給出標號
    我將在之後重新繪製的插圖 來補全文章

  - 記法方面
    1. 我用後綴表達式來表示函數作用與複合
    2. 並且用拉丁字母 而不用希臘字母
    3. 常常用 (...) 來標記表達式

  - 我的筆記用 [...] 標記
    成段落的筆記 用 [謝] 標記於段落開頭

  - 原文中的一些着重標記
    通過用 [...] 重複英文譯文來顯示

  - 翻譯中的疑點用 [?] 標記
    並在 [? ...] 中給出疑難的部分
    便於讀者指正

  - 省略部分用 [略] 或 [略 ...] 標出

* 引子

  - 在組合拓撲學中
    拓撲概念由算數概念表示

    - [謝]
      這裏的 組合拓撲學 [combinatorial topology]
      是 代數拓撲學 的舊稱
      因此 這裏所說的 '算數概念'
      可以理解爲 現在的 代數結構

    如此 原則上 所有組合拓撲問題
    都可以被劃歸爲 算數問題

    然而 這種劃歸對於解決大多數問題來說 都是無用的
    因爲 劃歸所得的算數問題 與 已知的結論與方法 少有聯繫

    當 問題中 同倫變換 被看作是非平凡的時候 尤其是如此
    - [謝] 之後 隨着文章展開
      我們就能知道 這裏的 '非平凡' 所對應的 '平凡'
      就是 用同倫等價來定義相等
    或者說
    當考慮 不同維度中 簡單聯通的多面體
    考慮它們 越發大量的 而且難以想象的構造 時
    情況尤其是如此

    在之前的工作中
    [Über kombinatorische Topologie, Acta math, 67 (1936), 123-168]
    對於 二維多面體 [多邊形]
    我嘗試以 容易理解的 算數的方式 來表達這些構造
    我展示了 同倫問題 所給出的 算數問題 已經出離了羣倫的廣泛領域
    它們關乎更一般的 難以研究的操作
    這些操作的全體我稱之爲 '遊戲'

  - 當人們研究那些忽略了同倫變換的問題時
    - [謝] 所謂 '忽略同倫變換' 就是用同倫等價來定義映射之相等
    情況就不同了

    這裏 人們常常可以很好地利用 羣論中的結果和方法

    對於流形 甚至是高維流形
    龐加萊的基本羣 開啓了解決這些問題的出路

    對於二維流形 最近尤其成功地發展了出了 映射理論 [theory of mappings]
    即 把所有只相差一個同倫變換的映射 收集成一類
    [見 (1)]

  - 這裏 我用 一個曲面的算數域[arithmetic field] 中的操作[operation]
    來表示 曲面的映射類

    這種域中的個體不能是曲面上的點
    因爲一個點可以被同倫變換到任意另一個點

    其實
    我們用 曲面上的 曲線系統[curve system] 的同倫類
    來捕捉 曲面的 映射類
    我們選擇 曲線系統 的算數表示
    來作爲 算數域 中的個體

    一個 曲線系統
    作爲 曲線系統 的同倫類 中的一個代表元
    被一列整數唯一確定

    這列整數的個數 可以被看成是 算數域 的維數[dimension]

    這一列整數就被看作是算數域中的個體
    它決定着一個曲線系統的同倫類

    一個映射類 誘導出 算數域上的一個變換
    這個變換是線性變換 [?]
    [? linear transformations related modular substitutions]

  - 這種算數表示 可以讓我們解決一系列簡單的映射問題
    這裏 我用這些解答 來初步把握更一般的問題
    因此 我只是初步使用了 算數域與其變換

    我能給出 任意一個曲面的 映射類羣 的有限生成子
    這些生成子 都是類型相似的 曲面到自身的映射
    即 沿着確定曲線的 扭動[twists]
    它們 與 高亏格[genus]曲面的通常表示方法
    有簡單的關係

  - 這裏給出了一個總結
    但是 算數域的變換理論 還很不完全
    這個方向的繼續發展 將是很重要的

    當然 有了變換的公式
    映射類羣 就有可由 線性變換 '表示'
    而且
    這種表示 可能將有助於從新的方面 解決
    映射類羣的 共軛問題[the conjugacy problem]
    這個問題是這個領域之前研究工作的主題

  - 由於 預見着這種種可能性
    目前的工作只能算是一些準備工作

    作爲準備工作
    我展示出簡單東西的細節
    我還推導出很多已知的結果
    它們有些是我們方法的必要基礎
    有些作爲有用的例子

* (1) 曲面的自我映射概論

*** (a) 映射羣 和 映射類羣

    - 曲面到自身的映射 f
      由曲面的兩個分割[decomposition]
      D1 與 D1 之間的一一對應給出
      點對應點 邊對應邊 面對應面
      並且要求
      相對應的點 落在相對應的邊的邊界上
      相對應的邊 落在相對應的面的邊界上

      - [謝]
        若 (c : D1)
        則 (c boundary f = c f boundary)
        或者記爲
        ((c : D1) -> (c boundary f = c f boundary))

      記作 (D1 f = D2)

      - [謝 關於形式化]
        我們也可以記錄類型 (f : (D1 -> D2))
        但是 其實這裏給出的信息不只是類型
        因爲 分割不被當成是空間的定義
        而是 分割本身就描述了映射的細節
        '分割' 與 '粘合' 同義
        在考慮 cell-complex 時
        用 '粘合' 來構造空間
        但是這裏所考慮的空間是曲面而已
        曲面的分類方式是衆所周知的
        只要說出 虧格 邊界 可定向性 一個曲面就確定了
        因此 '粘合' 被理解爲 '分割'
        不是用 '粘合' 來構造曲面
        而是用 '分割' 來揭示曲面的不同對稱性

      - [謝]
        下面的討論是爲了說明 如此定義的映射 如何可以做複合
        複合 將成爲 映射羣中的乘法

      當 f 映 D1 到 D2 時
      f 就也可以映射曲面的任意分割 D 到一個固定的分割 D'
      因爲 D 可以被 D1 加細
      這個更細的分割 就又可以被 f 映到 D2 的某個加細
      這樣我們就得到了 f 映 任意 D 到 D'
      比如 (D2 f = D3)
      因此 (D1 f f = D3)
      繼續複合 就得到 f 的冪[power]
      如果 g 是另外一個映射 它可以作用於任意分割 因此可以作用於 D2
      這樣我們就得到 (D1 f g = D2 g = D4)
      如從 我們就能 複合[compose] 曲面上的映射
      並且 曲面上的映射形成一個羣

      - [謝]
        Dehn 略去了 驗證羣公理的工作
        單位映射是顯然的
        既然映射被定義爲了具體的一一對應 其逆也是顯然的

      然而直接考慮這個羣是不切實際的
      因爲它不是由有限個元素生成的
      因此人們考慮它的商羣[quotient group]
      做商就把映射分成了類

      映射 f 屬於單位類[identity class]
      如果 (D1 f = D2) 得自 (D1 id = D1) 的一個同倫變換
      (也就是 形變[deformation])

      兩個映射屬於同一類
      如果 其中一個是是另一個與單位類中的變換的複合

      單位類中的映射構成映射羣的正規子羣[normal subgroup]
      因爲 如果 e 是單位類中的映射
      (f e f {-1}) 映 (D f) 到 D 也與單位映射同倫

      如此做商所得到的 映射類羣[mapping class group]
      就是我們研究的主題

*** (b) 不同類型的映射

    - 一個非單位映射[的冪]
      可能把某些分割映到自身
      此時 說這個分割 許可[admits] 一個非單位映射
      這個映射總是有限階的[of finite order]
      即 它的冪 不只是屬於單位類
      而且這個冪本身就是單位映射

      其他不屬於這類的映射是無限階的
      它們冪不屬於單位類

      最後還有可能有有限階的映射
      其 n 次冪 屬於單位類
      但是這個有限階映射的類中
      沒有映射的 n 次冪 等於單位映射
      即 (f {n} = e) 其中 e 是一個形變 [形變屬於單位類]
      但是 對於任意形變 e'
      ((e' f) {n}) 都不等於 單位映射

      在之後的章節中
      我們將給出 前兩類映射的例子

      第三類映射是否存在尚且存疑

      - [英譯者註]
        Nielsen 證明了第三類映射不存在
        見 Acta math. 75 (1942), 23-115.

*** (c) 固定邊界的同倫

    - 對於有邊界的曲面
      我們可以以不同的方式來選擇 單位類

      選取單位類爲與單位映射同倫的映射 而不在乎邊界
      或者 要求單位類中的映射同倫與單位映射的過程中 保持邊界不變

      者第二種 更小的 單位類
      也是映射羣的正規子羣
      當使用它來做商的時候
      我們必須限制與映射羣中保持邊界不變的映射

      與一邊的分類相比
      這些映射 被保持邊界不變的單位類 分得更細

    - 如果考慮 '打孔的' 曲面 ['punctured' surfaces]
      即 如果邊界可以收縮成一點
      ['打孔的' 曲面 是曲面去掉有限個點 因此 這樣得到的曲面是不是緊緻的]
      那麼 兩種單位類就重合了
      因爲 每個形變 都保持邊界不變 因爲 邊界只是一個點

      除了保持邊界不變的映射
      我們還可以提及 置換邊界 或者 孔 的特殊映射

*** (d) 指標[? indicatrix]

    - 一個映射 映有向曲線到另一個有確定定向的曲線

      一個映射 要麼顛倒 要麼保留 indicatrix

      保持 indicatrix 的映射類羣 是原映射類羣的正規子羣

      之後 除非有個別聲明
      映射都假設爲保持 indicatrix
      [indicatrix preserving] [orientation preserving]

* (2) 一 二 三洞球面的自我映射

  - 我們稱 帶有 n 個洞的球面
    爲 n 洞球面
    記爲 Ln

*** (a) 一洞球面

    - 考慮曲面上的算數域之前
      先考慮一些簡單的映射問題 是有用的

      一洞球面 即圓盤
      其映射類羣是單位羣

      不論固定邊界與否
      所有映射都屬於單位類

      其證明就是
      曲面的一個分割
      總是可以被相繼的同倫變換到另一個分割

*** (b) 二洞球面

    - 二洞球面 即圓柱
      其映射類羣 是二階羣
      其中的非單位映射就是交換邊界

      如果要求不能交換邊界
      但是邊界上的點不固定
      其映射類羣 是單位羣

      保持邊界不變
      其映射類羣 是無限階循環羣
      這是因爲
      有無限多不同的方式
      把一個邊界上的點 y1 鏈接到另一個邊界上的點 y2
      (見 圖1 中的 (y1 y y2) 和 (y1 z y2))

      [>< 圖1]

      圖1 展示了一個映射
      這個映射可以生成 上面所說的無限階循環羣
      映射由圓柱的兩個分割之間的如下一一對應定義
      分割 D1 爲多面體 (z1 r1 y1 y y2 r2 z2 z) 和 (z1 s1 y1 y y2 s2 z2 z)
      分割 D2 爲多面體 (z1 r1 y1 z y2 r2 z2 y) 和 (z1 s1 y1 z y2 s2 z2 y)
      如下的對應 保持邊界不變 只是交換了點 y 與 z
      (z1 r1 y1 y y2 r2 z2 z) 對 (z1 r1 y1 z y2 r2 z2 y)
      (z1 s1 y1 y y2 s2 z2 z) 對 (z1 s1 y1 z y2 s2 z2 y)

      我們稱這個映射爲 扭動[twist]
      當邊界固定的時候 這個扭動不是同倫形變

      如果不保持邊界不變 連接邊界的路 (y1 y y2)
      與任意 連接邊界的路 (y1' y' y2') 同倫

      如果保持邊界不變 (y1 y y2) 和 (y1 z y2) 就不同倫
      並且有無窮多不同倫的路
      確定了 正向 或 反向 繞邊界的次數
      就在同倫意義上 確定了這樣一個路
      [也就是說 這裏的算數域 就是整數的加法羣]

      [略 至本段末]

      - [謝]
        之後給出了 構造 映射類羣 中的兩個元素 之複合 的方式
        即 因爲 考慮的是 同倫等價類
        所以 我們可以用 辮子理論[braid theory] 來理解這個複合
        注意
        映射羣中的函數複合
        在映射類羣中 被處理成了 非常簡單的構造
        這就是同倫等價的力量

    - [略]
      這個映射類羣 誘導出 整數的加法羣 上的線性變換

    - 如上我給出了很多構造的細節
      因爲這裏我們有最簡單的 算數域確定曲線系統 的例子
      算數域上的變換 給出 映射類羣

*** (c) 三洞球面

    - 對於 三洞球面 L3

      [與 MAGNUS, Math. Ann. 109. 中的結果相一致]

* (3) 四洞球面上的特殊映射
* (4) self-mappings of the torus and the one-holed torus
*** (a) torus
*** (b) one-holed torus
* (5) the arithmetic field on the two- and three-holed spheres and the torus
*** (a) general
*** (b) two-holed sphere
*** (c) torus. orientation of curves
*** (d) transformations of the arithmetic field on the torus by mapping classes. generation and relations.
*** (e) three-holed sphere. arithmetic field. invariance under homotopic transformations
* (6) the arithmetic field or the curve systems on the one-holed torus
*** (a) introduction of the field
*** (b) transformation by mappings. examples.
*** (c) one-holed torus with fixed boundary. connection with the trefoil knot
* (7) arithmetic field on the four-holed sphere
*** (a) system of closed curves on the four-holed sphere
*** (b) mappings of the four-holed sphere and the action on the arithmetic field
*** (c) derivation of invariants of a curve system from the arithmetic presentation
*** (d) orientation. examples
*** (e) geometric presentation of the symbols. view of higher cases
*** (f) curve systems on the four-holed sphere with endpoints on a boundary
***** (1) normal form
***** (2) arithmetic field
*** (g) four-holed sphere with fixed boundaries
***** (1) derivation of a relation
***** (2) application to the two-holed torus with fixed boundaries
***** (3) twists along the boundary of singly-bounded surfaces
***** (4) twists along separating curves on closed or singly-bounded surfaces
* (8) five-holed sphere
*** (a) coordinate systems
*** (b) presentation of a system of closed curves
*** (c) reduction of symbols. generation of mappings
* (9) generation of the mapping classes for the sphere with n holes
*** (1) lemmas
*** (2) lemmas
*** (3) lemmas
*** (4) lemmas
*** (5) lemmas
*** (6) generation with the help of complete induction
*** (7) the five-holed sphere as an example
*** (8) direct exhibition of generators on the basis of a cyclic ordering of boundaries. the number of generators
* (10) generation of the mapping classes for every orientable surface
*** (1) lemmas
*** (2) lemmas
*** (3) generation with the help of complete induction
*** (4) double and triple torus as examples
*** (5) direct exhibition of generators on the basis of a normalrepresentation of the surfaces. the number of generators.
*** (6) arithmetic field in the general case.
