#+HTML_HEAD: <link rel="stylesheet" href="../asset/css/page.css" type="text/css" media="screen" />
#+TITLE: the group of mapping classes / 映射類羣

- 作者 Max Dehn
  譯者 謝宇恆

* 題解

  - Dehn 的原文爲德文
    基於 Dehn 1922 年在 Breslau 的演講
    發表於 1938 年

  - 原文由 John Stillwell 翻譯爲英文
    出版於 papers on group theory and topology, 1987
    本譯文轉譯自英文

  - 因爲是轉譯
    原作者的文風無論如何都難以保留了
    因此我有時使用意譯 以使得敘述變得更清晰

  - 文中插圖只給出標號
    我將在之後重新繪製的插圖 來補全文章

  - 記法方面
    1. 我用後綴表達式來表示函數作用與複合
    2. 並且用拉丁字母 而不用希臘字母
    3. 常常用 (...) 來標記表達式

  - 我的筆記用 [...] 標記
    成段落的筆記 用 [謝] 標記於段落開頭

  - 原文中的一些着重標記
    通過用 [...] 重複英文譯文來顯示

  - 翻譯中的疑點用 [?] 標記
    並在 [? ...] 中給出疑難的部分
    便於讀者指正

  - 省略部分用 [略] 或 [略 ...] 標出

* 引子

  - 在組合拓撲學中
    拓撲概念由算數概念表示

    - [謝]
      這裏的 組合拓撲學 [combinatorial topology]
      是 代數拓撲學 的舊稱
      因此 這裏所說的 '算數概念'
      可以理解爲 現在的 代數結構

    如此 原則上 所有組合拓撲問題
    都可以被劃歸爲 算數問題

    然而 這種劃歸對於解決大多數問題來說 都是無用的
    因爲 劃歸所得的算數問題 與 已知的結論與方法 少有聯繫

    當 問題中 同倫變換 被看作是非平凡的時候 尤其是如此
    - [謝] 之後 隨着文章展開
      我們就能知道 這裏的 '非平凡' 所對應的 '平凡'
      就是 用同倫等價來定義相等
    或者說
    當考慮 不同維度中 簡單聯通的多面體
    考慮它們 越發大量的 而且難以想象的構造 時
    情況尤其是如此

    在之前的工作中
    [Über kombinatorische Topologie, Acta math, 67 (1936), 123-168]
    對於 二維多面體 [多邊形]
    我嘗試以 容易理解的 算數的方式 來表達這些構造
    我展示了 同倫問題 所給出的 算數問題 已經出離了羣倫的廣泛領域
    它們關乎更一般的 難以研究的操作
    這些操作的全體我稱之爲 '遊戲'

  - 當人們研究那些忽略了同倫變換的問題時
    - [謝] 所謂 '忽略同倫變換' 就是用同倫等價來定義映射之相等
    情況就不同了

    這裏 人們常常可以很好地利用 羣論中的結果和方法

    對於流形 甚至是高維流形
    龐加萊的基本羣 開啓了解決這些問題的出路

    對於二維流形 最近尤其成功地發展了出了 映射理論 [theory of mappings]
    即 把所有只相差一個同倫變換的映射 收集成一類
    [見 (1)]

  - 這裏 我用 一個曲面的算數域[arithmetic field] 中的操作[operation]
    來表示 曲面的映射類

    這種域中的個體不能是曲面上的點
    因爲一個點可以被同倫形變到任意另一個點

    其實
    我們用 曲面上的 曲線系統[curve system] 的同倫類
    來捕捉 曲面的 映射類
    我們選擇 曲線系統 的算數表示
    來作爲 算數域 中的個體

    一個 曲線系統
    作爲 曲線系統 的同倫類 中的一個代表元
    被一列整數唯一確定

    這列整數的個數 可以被看成是 算數域 的維數[dimension]

    這一列整數就被看作是算數域中的個體
    它決定着一個曲線系統的同倫類

    一個映射類 誘導出 算數域上的一個變換
    這個變換是線性變換 [?]
    [? linear transformations related modular substitutions]

  - 這種算數表示 可以讓我們解決一系列簡單的映射問題
    這裏 我用這些解答 來初步把握更一般的問題
    因此 我只是初步使用了 算數域與其變換

    我能給出 任意一個曲面的 映射類羣 的有限生成子
    這些生成子 都是類型相似的 曲面到自身的映射
    即 沿着確定曲線的 扭動[twists]
    它們 與 高亏格[genus]曲面的通常表示方法
    有簡單的關係

  - 這裏給出了一個總結
    但是 算數域的變換理論 還很不完全
    這個方向的繼續發展 將是很重要的

    當然 有了變換的公式
    映射類羣 就有可由 線性變換 '表示'
    而且
    這種表示 可能將有助於從新的方面 解決
    映射類羣的 共軛問題[the conjugacy problem]
    這個問題是這個領域之前研究工作的主題

  - 由於 預見着這種種可能性
    目前的工作只能算是一些準備工作

    作爲準備工作
    我展示出簡單東西的細節
    我還推導出很多已知的結果
    它們有些是我們方法的必要基礎
    有些作爲有用的例子

* (1) 曲面的自我映射概論

*** (a) 映射羣 和 映射類羣

    - 曲面到自身的映射 f
      由曲面的兩個分割[decomposition]
      D1 與 D1 之間的一一對應給出
      點對應點 邊對應邊 面對應面
      並且要求
      相對應的點 落在相對應的邊的邊界上
      相對應的邊 落在相對應的面的邊界上

      - [謝]
        若 (c : D1)
        則 (c boundary f = c f boundary)
        或者記爲
        ((c : D1) -> (c boundary f = c f boundary))

      記作 (D1 f = D2)

      - [謝 關於形式化]
        我們也可以記錄類型 (f : (D1 -> D2))
        但是 其實這裏給出的信息不只是類型
        因爲 分割不被當成是空間的定義
        而是 分割本身就描述了映射的細節
        '分割' 與 '粘合' 同義
        在考慮 cell-complex 時
        用 '粘合' 來構造空間
        但是這裏所考慮的空間是曲面而已
        曲面的分類方式是衆所周知的
        只要說出 虧格 邊界 可定向性 一個曲面就確定了
        因此 '粘合' 被理解爲 '分割'
        不是用 '粘合' 來構造曲面
        而是用 '分割' 來揭示曲面的不同對稱性

      - [謝]
        下面的討論是爲了說明 如此定義的映射 如何可以做複合
        複合 將成爲 映射羣中的乘法

      當 f 映 D1 到 D2 時
      f 就也可以映射曲面的任意分割 D 到一個固定的分割 D'
      因爲 D 可以被 D1 加細
      這個更細的分割 就又可以被 f 映到 D2 的某個加細
      這樣我們就得到了 f 映 任意 D 到 D'
      比如 (D2 f = D3)
      因此 (D1 f f = D3)
      繼續複合 就得到 f 的冪[power]
      如果 g 是另外一個映射 它可以作用於任意分割 因此可以作用於 D2
      這樣我們就得到 (D1 f g = D2 g = D4)
      如從 我們就能 複合[compose] 曲面上的映射
      並且 曲面上的映射形成一個羣

      - [謝]
        Dehn 略去了 驗證羣公理的工作
        單位元是恆等映射 這是顯然的
        之後 恆等映射[identity map] 也稱爲單位映射
        既然映射被定義爲了具體的一一對應 其逆也是顯然的

      然而直接考慮這個羣是不切實際的
      因爲它不是由有限個元素生成的
      因此人們考慮它的商羣[quotient group]
      做商就把映射分成了類

      映射 f 屬於單位類[identity class]
      如果 (D1 f = D2) 得自 (D1 id = D1) 的一個同倫變換
      (也就是 形變[deformation])

      兩個映射屬於同一類
      如果 其中一個是是另一個與單位類中的變換的複合

      單位類中的映射構成映射羣的正規子羣[normal subgroup]
      因爲 如果 e 是單位類中的映射
      (f e f {-1}) 映 (D f) 到 D 也與單位映射同倫

      如此做商所得到的 映射類羣[mapping class group]
      就是我們研究的主題

*** (b) 不同類型的映射

    - 一個非單位映射[的冪]
      可能把某些分割映到自身
      此時 說這個分割 許可[admits] 一個非單位映射
      這個映射總是有限階的[of finite order]
      即 它的冪 不只是屬於單位類
      而且這個冪本身就是單位映射

      其他不屬於這類的映射是無限階的
      它們冪不屬於單位類

      最後還有可能有有限階的映射
      其 n 次冪 屬於單位類
      但是這個有限階映射的類中
      沒有映射的 n 次冪 等於單位映射
      即 (f {n} = e) 其中 e 是一個形變 [形變屬於單位類]
      但是 對於任意形變 e'
      ((e' f) {n}) 都不等於 單位映射

      在之後的章節中
      我們將給出 前兩類映射的例子

      第三類映射是否存在尚且存疑

      - [英譯者註]
        Nielsen 證明了第三類映射不存在
        見 Acta math. 75 (1942), 23-115.

*** (c) 固定邊界的同倫

    - 對於有邊界的曲面
      我們可以以不同的方式來選擇 單位類

      選取單位類爲與單位映射同倫的映射 而不在乎邊界
      或者 要求單位類中的映射同倫與單位映射的過程中 保持邊界不變

      者第二種 更小的 單位類
      也是映射羣的正規子羣
      當使用它來做商的時候
      我們必須限制與映射羣中保持邊界不變的映射

      與一邊的分類相比
      這些映射 被保持邊界不變的單位類 分得更細

    - 如果考慮 '打孔的' 曲面 ['punctured' surfaces]
      即 如果邊界可以收縮成一點
      ['打孔的' 曲面 是曲面去掉有限個點 因此 這樣得到的曲面是不是緊緻的]
      那麼 兩種單位類就重合了
      因爲 每個形變 都保持邊界不變 因爲 邊界只是一個點

      除了保持邊界不變的映射
      我們還可以提及 置換邊界 或者 孔 的特殊映射

*** (d) 指標[? indicatrix]

    - 一個映射 映有向曲線到另一個有確定定向的曲線

      一個映射 要麼顛倒 要麼保留 indicatrix

      保持 indicatrix 的映射類羣 是原映射類羣的正規子羣

      之後 除非有個別聲明
      映射都假設爲保持 indicatrix
      [indicatrix preserving] [orientation preserving]

* (2) 一 二 三洞球面的自我映射

  - 我們稱 帶有 n 個洞的球面
    爲 n 洞球面
    記爲 Ln

*** (a) 一洞球面

    - 考慮曲面上的算數域之前
      先考慮一些簡單的映射問題 是有用的

      一洞球面 即圓盤
      其映射類羣是單位羣

      不論固定邊界與否
      所有映射都屬於單位類

      其證明就是
      曲面的一個分割
      總是可以被相繼的同倫形變到另一個分割

*** (b) 二洞球面

    - 二洞球面 即圓柱
      其映射類羣 是二階羣
      其中的非單位映射就是交換邊界

      如果要求不能交換邊界
      但是邊界上的點不固定
      其映射類羣 是單位羣

      保持邊界不變
      其映射類羣 是無限階循環羣
      這是因爲
      有無限多不同的方式
      把一個邊界上的點 y1 連接到另一個邊界上的點 y2
      (見 圖1 中的 (y1 y y2) 和 (y1 z y2))

      - [謝]
        上面句話中的 '因爲'
        隱藏了 Dehn 劃歸問題的方法
        這個劃歸法就是
        利用嵌入在二洞球面上的線段
        來把二洞球面的映射問題 轉化爲 一洞球面的映射問題

        如果確定了 二洞球面 兩個邊界之間的一條路
        沿着這條路裁開 二洞球面 就成了 一洞球面

        因此
        二洞球面上 兩個邊界之間的路
        外加 一洞球面上的一個自我映射
        就給出了 二洞球面上的一個自我映射

        並且
        二洞球面上的所有自我映射
        都可以如此構造出來

        這個劃歸的方法 在這裏沒有明顯提及
        可能是因爲這裏的映射非常直觀
        但是在處理 三洞球面的時候 Dehn 明顯地指出了這個方法

      [>< 圖1]

      圖1 展示了一個映射
      這個映射可以生成 上面所說的無限階循環羣
      映射由圓柱的兩個分割之間的如下一一對應定義
      分割 D1 爲多面體 (z1 r1 y1 y y2 r2 z2 z) 和 (z1 s1 y1 y y2 s2 z2 z)
      分割 D2 爲多面體 (z1 r1 y1 z y2 r2 z2 y) 和 (z1 s1 y1 z y2 s2 z2 y)
      如下的對應 保持邊界不變 只是交換了點 y 與 z
      (z1 r1 y1 y y2 r2 z2 z) 對 (z1 r1 y1 z y2 r2 z2 y)
      (z1 s1 y1 y y2 s2 z2 z) 對 (z1 s1 y1 z y2 s2 z2 y)

      我們稱這個映射爲 扭動[twist]
      當邊界固定的時候 這個扭動不是同倫形變

      如果不保持邊界不變 連接邊界的路 (y1 y y2)
      與任意 連接邊界的路 (y1' y' y2') 同倫

      如果保持邊界不變 (y1 y y2) 和 (y1 z y2) 就不同倫
      並且有無窮多不同倫的路
      確定了 正向 或 反向 繞邊界的次數
      就在同倫意義上 確定了這樣一個路
      [也就是說 這裏的算數域 就是整數的加法羣]

      [略 至本段末]

      - [謝]
        之後給出了 構造 映射類羣 中的兩個元素 之複合 的方式
        即 因爲 考慮的是 同倫等價類
        所以 我們可以用 辮子理論[braid theory] 來理解這個複合
        注意
        映射羣中的函數複合
        在映射類羣中 被處理成了 非常簡單的構造
        這就是同倫等價的力量

    - [略]
      這個映射類羣 誘導出 整數的加法羣 上的線性變換

    - 如上我給出了很多構造的細節
      因爲這裏我們有最簡單的 算數域確定曲線系統 的例子
      算數域上的變換 給出 映射類羣

*** (c) 三洞球面

    - 三洞球面 L3
      其映射類羣 是三個邊界的對稱羣[symmetric group] [即 所有置換形成的羣]
      [這與 MAGNUS, Math. Ann. 109. 中的結果相一致]

    - 限制不能置換邊界的話
      映射類羣 就是單位羣
      [這是 DEHN, Autogr. Vortrag, Breslau 1922
       和 R. Baer, Journ. f. Math.,vols. 156, 160. 中
       關於曲面上的曲線系統工作的基礎]

      證明如下

      取兩個邊界
      再取兩條連接它們的路
      我們考慮這兩個路之間的同倫形變

      取三條路 (a b) (c d) (e f)
      它們把三洞球面分割成兩個圓盤
      [如 圖3]

      [>< 圖3]

      我們將證明 任意連接 a b 的路 v
      在 L3 中 與 (a b) 同倫

      沿着 v 考慮它與 (a b) (c d) (e f) 的相繼相交的點的序列

      我們可以假設 沒有相繼的兩個交點 落在 (a b) (c d) (e f) 中的同一條路上
      因爲 經過同倫形變 如此相繼的兩個交點 可以被消除

      同理 我們假設交點序列中的第一個 不落在 (a b) 上

      下面分情況討論

      假設第一個交點 x 落在 (c d) 上
      那麼下一個交點一定只落在 (a b) 上
      因爲 如果它落在 (f e) 上 它就不能回到 b 點了
      再下一個交點只能落在 (x c) 上
      再下一個交點只能落在 (a b) 上
      再下一個交點只能落在 (x c) 上
      等等
      如此循環 v 環繞 b c 所在的邊界很多圈 最終回到 b 點
      經過同倫形變 v 可以變得與 (a b) (c d) (e f) 皆不相交
      因而 v 與 (a b) 圈出 L3 中的一個圓盤
      因而 v 與 (a b) 同倫

      另外一種情況是
      交點序列中的第一個點 x 落在 (e f) 上 [見 圖4]
      [>< 圖4]
      若 下一個交點落在 (c d) 上
      那麼之後的 v 又只能環繞 c b 所在的邊界了
      把 v 的起點沿着外層的邊界移動
      就可以把 v 劃歸爲第一種情況
      若 下一個交點 z 落在 (a b) 上
      再下一個交點如果落在 (c d) 上
      就又可以被劃歸爲第一種情況
      所以考慮下一個交點 u 落在 (x e) 上
      對於之後的交點
      我們按照同樣的理由排除落其在 (c d) 上的可能
      這樣 之後的交點就相繼落在 (a b) 與 (f e) 上
      如此 v 就是環繞 a f 所在的邊界而回到 b 點
      因而 v 與 (a b) 同倫

      如此就完成了分情況的證明

    - 從上面的證明中我們還可以看出
      如果保持邊界固定
      v 的同倫類 由兩個整數確定
      這兩個整數分別記錄着
      v 相繼 環繞 a f 所在的邊界
      與 環繞 b c 所在的邊界
      的方向與次數

    - 注意
      我們的結論是 [當邊界不固定時]
      沿着任意一條連接兩個邊界的路 v
      裁開曲面 L3
      就如同沿着 (a b) 裁開
      從而得到 L2
      因爲 v 可以同倫形變到 (a b)

    - 任意一個 L3 的邊界可變的映射 f
      可能把 (a b) 映到 v

      L3 的一個同倫 h 可能也把 (a b) 形變到 v
      [這里說的 一個函數是空間的同倫
       就是指 這個函數與這個空間的單位映射的同倫]

      f 有別與 h 的部分 是二洞球面上的一個映射 g
      這個 L2 來源與沿着 (a b) 裁開 L3
      因此 g 保持 (a b) 所對應的兩條線段不變

      但是 二洞球面上的所有映射 只要一個邊界可變 就是同倫

      因此 g 是 L2 的同倫
      這個同倫保持 (a b) 所對應的兩條線段的不變

      因此 g 也是 L3 的同倫 [添加上 映 (a b) 到 v]

      因此 f 與 h 同倫 從而術語單位類

      如此我們完成對如下定理的證明
      限制不能置換邊界
      三洞球面的 映射類羣 是單位羣

      - [謝]
        我也可以給出 強調構造的 證明方式

        考慮 L3 的任何一個自我映射 f
        f 限制這個同倫在 (a b) 上
        就得到 (a b) 的嵌入

        沿 (a b) 裁開 L3 而得到 L2
        裁線 (a b) 就成了 所裁出的 L2 的一個邊界上的兩個線段
        f 限制在這個 L2 上
        就是一個保持這兩個線段不變的 L2 的自我映射

        任何 L3 的自我映射
        都可以用 一個嵌入 L3 的線段
        和一個 L2 的保持這兩個線段不變的 自我映射構造

        我們知道
        連接 (a b) 所連接的兩個邊界的 嵌入曲線
        只有一個同倫類
        即 (a b) 所代表的同倫類

        我們還知道
        只要 L2 的一個邊界不被固定
        其 映射類羣 就是單位羣

        因此 L3 的 映射類羣 也是單位羣

    - L3 的保持邊界不變的映射類羣
      是 有三個生成子的自由阿貝爾羣[free abelian group]
      三個生成子 是沿着三個邊界的扭動[twists]

      一個沿着邊界曲線的扭動 來自二洞球面上固定邊界的扭動
      在曲面上 扭動曲線[twist curve] 落在邊界和一條平行於邊界的曲線之間
      [扭動曲線 指用以確定扭動的嵌入曲線]
      我們取平行於邊界的曲線 使其互不相交

      證明如下

      L3 的映射 f 映 (a b) 到 v

      通過兩個 沿邊界的扭動 t1 與 t2
      (a b) 可以被映爲 與 v 同倫的曲線 v'

      當需要 n1 次扭動 t1 與 n2 次扭動 t2 時
      映射 (g := f h' t2 {-n2} t1 {-n1}) 保持 (a b) 不變
      其中 h' 是能夠映 v' 到 v 的同倫

      沿着 (a b) 裁開 L3 得 L2
      g 限制在 L2 上
      就成了 保持 L2 邊界不變的 L2 映射
      因此根據 (b) 節的結論
      g 與沿着第三個邊界的某個扭動 (t3 {n3}) 同倫
      (h'' t3 {n3} = f h' t2 {-n2} t1 {-n1})
      其中 h'' 是 L2 保持邊界的同倫

      因爲同倫構成是正規子羣
      [即 單位類構成是正規子羣]
      所以
      (f = h'' t3 {n3} t1 {n1} t2 {n2} h' {-1}
         = h t3 {n3} t1 {n1} t2 {n2})
      如此就證明了 三個沿着邊界的扭動生成 L3 的映射類羣

      三個扭動是相互交換的
      因爲假設了它們作用的部分不相交

      三個扭動之間沒有其他關係
      證明如下
      假設映射類羣中 (t1 {n1} t2 {n2} t3 {n3} = 1)
      取 v12 爲鏈接前兩個邊界的路
      選取第三個邊界上合適的扭動帶
      v12 就在 t3 的作用下不變
      t1 {n1} t2 {n2} 想要把 v12 變成同倫曲線
      只有 n1 n2 都爲零
      因爲映射想要屬於單位類
      它就必須把每個連線映爲同倫於連線自身的同倫曲線
      所以 n1 = n2 = 0
      類似地 可以證明 n1 = n3 = 0

      因此
      L3 的保持邊界不變的映射類羣
      是由 t1 t2 t3 生成的自由阿貝爾羣

* (3) 四洞球面上的特殊映射
* (4) 環面的自我映射 與 一洞環面
*** (a) 環面
*** (b) 一洞環面
* (5) 二 三洞球面 和 環面上的算數域
*** (a) 曲面上的算數域 得自 曲面上的曲線系統
*** (b) 二洞球面上的曲線系統
*** (c) torus. orientation of curves
*** (d) transformations of the arithmetic field on the torus by mapping classes. generation and relations.
*** (e) three-holed sphere. arithmetic field. invariance under homotopic transformations
* (6) the arithmetic field or the curve systems on the one-holed torus
*** (a) introduction of the field
*** (b) transformation by mappings. examples.
*** (c) one-holed torus with fixed boundary. connection with the trefoil knot
* (7) arithmetic field on the four-holed sphere
*** (a) system of closed curves on the four-holed sphere
*** (b) mappings of the four-holed sphere and the action on the arithmetic field
*** (c) derivation of invariants of a curve system from the arithmetic presentation
*** (d) orientation. examples
*** (e) geometric presentation of the symbols. view of higher cases
*** (f) curve systems on the four-holed sphere with endpoints on a boundary
***** (1) normal form
***** (2) arithmetic field
*** (g) four-holed sphere with fixed boundaries
***** (1) derivation of a relation
***** (2) application to the two-holed torus with fixed boundaries
***** (3) twists along the boundary of singly-bounded surfaces
***** (4) twists along separating curves on closed or singly-bounded surfaces
* (8) five-holed sphere
*** (a) coordinate systems
*** (b) presentation of a system of closed curves
*** (c) reduction of symbols. generation of mappings
* (9) generation of the mapping classes for the sphere with n holes
*** (1) lemmas
*** (2) lemmas
*** (3) lemmas
*** (4) lemmas
*** (5) lemmas
*** (6) generation with the help of complete induction
*** (7) the five-holed sphere as an example
*** (8) direct exhibition of generators on the basis of a cyclic ordering of boundaries. the number of generators
* (10) generation of the mapping classes for every orientable surface
*** (1) lemmas
*** (2) lemmas
*** (3) generation with the help of complete induction
*** (4) double and triple torus as examples
*** (5) direct exhibition of generators on the basis of a normalrepresentation of the surfaces. the number of generators.
*** (6) arithmetic field in the general case.
