#+title: max dehn

* [lectures on surface topology]

*** 1 閉曲面 / closed surfaces

*** 2 虧格爲 p 的曲面的基本羣 / fundamental group of the surface of genus p

    - x -
      說 surface 的 universal-covering-space
      解決了 surface 的 fundamental-group 的 word-problem
      如果想要把這種直觀的解法描述成一個算法的話
      可以想象給 universal-covering-space 中的點編碼
      然後 對於 group 中的一個元素
      固定 universal-covering-space 中的一個起點
      然後求出其終點的編碼
      求解編碼的過程[在最差的情況下]可以是逐次地
      即 羣中元素爲 某幾個生成子的乘積
      每次增加一個乘子的時候 就找一下所對應的點的編碼

      對於 torus 來說
      這種編碼是簡單的 (* Z Z)
      但是對於高虧格的曲面來說
      就有賴於雙曲空間中離散點集的編碼了

    - x -
      這裏 dehn 的敘述中最重要的想法是
      代數問題的拓撲[或者幾何]解釋

      - 等同問題 [identity-problem [word-problem]]
        "null reduction",
        i.e., to the question of whether a closed curve on the surface
        may be continuously contracted to a point.
        取定 定義 fundamental-group 時所用的 underlying-space 中的一點
        取定 universal-covering-space 中這以點所對應的一點作爲起點
        把 (A = B) 化爲 (A -B = 1)
        就能看出這個幾何解釋

      - 變換問題 [transformation-problem [conjugacy-problem]]
        to the deformability of closed curves on the surface into each other.
        利用前一節末尾的引理
        [注意對變換的分解的解釋]

      注意
      這裏對問題的解釋
      都是依賴於 surface 上的一個固定點的
      [當考慮二階代數時 應該如何呢?]

*** 3 變換問題的解法 / solution of the transformation problem

    - ><

*** 4 變換問題的第二個解法 / second method for the solution of the transformation problem

*** 5 單面曲面 / one-sided surfaces

*** 6 可分解羣 / decomposable groups

*** 7 解析的評論 / analytic remarks

* (1910) Uber die Topologie des dreidimensionalen Raumes [paper 3 : on the topology of three-dimensional space]

*** info

    - In this paper,
      Dehn had proved a purely topological result
      which is still known as "Dehn's Lemma"
      and which implies that the group of a knot is abelian
      and therefore cyclic if and only if the knot is isotopic in threespace with a circle.
      There was a mistake in the proof of the lemma
      which was pointed out in a letter dated April 22, 1929 from H. Kneser to Dehn.
      The lemma, however, is true and was proved by Papakyriakopoulos in 1957, five years after Dehn's death.

*** chapter i preliminaries

***** 1 Group theoretic aid (the group diagram)

      - ><

*** chapter ii knots and groups

*** chapter iii three dimensional manifolds

* (1912a) Über unendliche diskontinuierliche Gruppen [paper 4 : on infinite discontinuous groups]

*** introduction : the three fundamental problems for infinite discontinuous groups

    1. identity problem [word problem]
       An element of the group is given as a product of generators.
       One is required to give a method
       whereby it may be decided in a finite number of steps
       whether this element is the identity or not.

    2. transformation problem [conjugacy problem]
       any two elements S and Τ of the group are given.
       A method is sought for deciding the question
       whether S and Τ can be transformed into each other,
       i.e. whether there is an element U of the group satisfying the relation
       (S = U T U^-1)

    3. The ieomorphism problem
       Given two groups,
       one is to decide whether they are isomorphic or not
       and further, whether a given correspondence
       between the generators of one group
       and elements of the other group is an isomorphism or not.

    ------

    - These three problems have very different degrees of difficulty.

      Problem 1 is a special case of problem 2

      The first obviously concerns the character of one element of a group,
      the second the relation between two elements of one group,
      the third the relation between the elements of two groups.

    - 解決這三個問題
      就算是給了無限羣論一個系統的展示

      更重要的是 這些問題有其拓撲解釋
      考慮嵌入在三維空間中的結的補空間的基本羣

      1. 結是平凡的 = 羣是交換的
         這就引出了 等同問題

      2. 結的補空間中閉曲線的變換問題 = 羣中兩個元素的變換問題

      3. 兩個結的等價 = 兩個羣的同構問題

    - 對於有限羣來說
      這三個問題都是可解的

      如果考慮 n 維複空間的有解析表示的變換羣
      第一個問題通常也是很容易解決的

      第一個問題可以通過構造羣的圖[group-diagram [cayley-graph]]來解決

    - 如果羣是歐氏空間或非歐空間中某類運動所決定的離散羣
      那麼構造出基本域[fundamental domain] 就能解決第二個問題

      一般的有限生成羣的凱萊圖的自我映射
      有規範表示[canonical representation]
      找到這些規範表示也能解決第二個問題

    - 對於第三個問題
      解析表示並不重要
      從拓撲學的角度研究 羣的圖 纔是重要的

    - 對於每個生成子只在關係中出現兩次的有限生成羣
      我們在第二章 給出其三個問題的解法
      還有結羣的變換問題的解法

*** chapter i the fundamental groups of closed surfaces

***** intro

      - 就閉曲面的基本羣而言
        我們不是要用一般的羣論來研究拓撲學
        而是利用拓撲學所帶來的直覺來解決羣論的三個問題

***** 1 two-sided surfaces

      - ><

***** 2 one-sided surfaces

***** 3 analytic expression for surface curves

***** 4 amphidrome snrface curves

***** 5 introduction of the fundamental gronp

***** 6 topological properties of the gronp diagrams of fundamental gronps of closed surfaces

*** chapter ii gronps in which each generator appears at most twice in the defining relations

*** chapter iii higher groups

***** 1 general remarks

***** 2 knot groups

***** 3 groups with two generators

* (1912b) Transformation der Kurven auf zweiseitigen Flachen [paper 5 : transformation of curves on two-sided surfaces]

* (1914) Die beiden Kleeblattschlingen [paper 6 : the two trefoil knots]

* (1924) Uber die Gruppen [appendix to paper 6 : on the groups A^a B^b = 1]

* (1922) Uber Kurvensysteme auf zweiseitigen Flachenmit Anwendung auf das Abbildungsproblem [paper 7 : on curve systems on two-sided surfaces, with application to the mapping problem]

* (1938) Die Gruppe der Abbildungsklassen [paper 8 : the group of mapping classes]

*** 引子

    - 在組合拓撲學中
      拓撲概念由算數概念表示

      - [謝]
        這裏的 組合拓撲學 [combinatorial topology]
        是 代數拓撲學 的舊稱
        因此 這裏所說的 '算數概念'
        可以理解爲 現在的 代數結構

      如此 原則上 所有組合拓撲問題
      都可以被劃歸爲 算數問題

      然而 這種劃歸對於解決大多數問題來說 都是無用的
      因爲 劃歸所得的算數問題 與 已知的結論與方法 少有聯繫

      當 問題中 同倫變換 被看作是非平凡的時候 尤其是如此
      - [謝] 之後 隨着文章展開
        我們就能知道 這裏的 '非平凡' 所對應的 '平凡'
        就是 用同倫等價來定義相等
      或者說
      當考慮 不同維度中 簡單聯通的多面體
      考慮它們 越發大量的 而且難以想象的構造 時
      情況尤其是如此

      在之前的工作中
      [Über kombinatorische Topologie, Acta math, 67 (1936), 123-168]
      對於 二維多面體 [多邊形]
      我嘗試以 容易理解的 算數的方式 來表達這些構造
      我展示了 同倫問題 所給出的 算數問題 已經出離了羣倫的廣泛領域
      它們關乎更一般的 難以研究的操作
      這些操作的全體我稱之爲 '遊戲'

    - 當人們研究那些 忽略了同倫變換的問題時
      - [謝] 所謂 '忽略同倫變換' 就是用同倫等價來定義映射之相等
      情況就不同了

      這裏 人們常常可以很好地利用 羣論中的結果和方法

      對於流形 甚至是高維流形
      龐加萊的基本羣 開啓了解決這些問題的出路

      對於二維流形 最近尤其成功地發展了出了 映射理論 [theory of mappings]
      即 把所有只相差一個同倫變換的映射 收集成一類
      [見 (1)]

    - 這裏 我用 一個曲面的算數域[arithmetic field] 中的操作[operation]
      來表示 曲面的映射類

      這種域中的個體不能是曲面上的點
      因爲一個點可以被同倫形變到任意另一個點

      其實
      我們用 曲面上的 曲線系統[curve system] 的同倫類
      來捕捉 曲面的 映射類
      我們選擇 曲線系統 的算數表示
      來作爲 算數域 中的個體

      一個 曲線系統
      作爲 曲線系統 的同倫類 中的一個代表元
      被一列整數唯一確定

      這列整數的個數 可以被看成是 算數域 的維數[dimension]

      這一列整數就被看作是算數域中的個體
      它決定着一個曲線系統的同倫類

      一個映射類 誘導出 算數域上的一個變換
      這個變換是線性變換 [?]
      [? linear transformations related modular substitutions]

    - 這種算數表示 可以讓我們解決一系列簡單的映射問題
      這裏 我用這些解答 來初步把握更一般的問題
      因此 我只是初步使用了 算數域與其變換

      我能給出 任意一個曲面的 映射類羣 的有限生成子
      這些生成子 都是類型相似的 曲面到自身的映射
      即 沿着確定曲線的 扭轉[twists]
      它們 與 高亏格[genus]曲面的通常表示方法
      有簡單的關係

    - 這裏給出了一個總結
      但是 算數域的變換理論 還很不完全
      這個方向的繼續發展 將是很重要的

      當然 有了變換的公式
      映射類羣 就有可由 線性變換 '表示'
      而且
      這種表示 可能將有助於從新的方面 解決
      映射類羣的 共軛問題[the conjugacy problem]
      這個問題是這個領域之前研究工作的主題

    - 由於 預見着這種種可能性
      目前的工作只能算是一些準備工作

      作爲準備工作
      我展示出簡單東西的細節
      我還推導出很多已知的結果
      它們有些是我們方法的必要基礎
      有些作爲有用的例子

*** (1) 曲面的自我映射概論

***** (a) 映射羣 和 映射類羣

      - 曲面到自身的映射 f
        由 曲面的兩個分割[decomposition]
        D1 與 D2 之間的一一對應 給出
        記作 (D1 f = D2)
        點對應點 邊對應邊 面對應面
        並且要求
        相對應的點 落在相對應的邊的邊界上
        相對應的邊 落在相對應的面的邊界上

        - [謝]
          若 (c : D1)
          則 (c boundary f = c f boundary)
          或者記爲
          ((c : D1) -> (c boundary f = c f boundary))

        - [謝 關於形式化語言]
          我們也可以記錄類型 (f : (D1 -> D2))
          但是 其實這裏給出的信息不只是類型
          因爲 分割本身不是空間的定義 而是空間上附加的信息
          分割本身就用於描述映射的細節
          所以依照形式化語言中常用的記法
          可能應該記爲 (f = (D1 -> D2))

        - [謝 '分割' 與 '粘合' ]
          在考慮 cell-complex 時
          用 '粘合' 來構造空間
          但是這裏所考慮的空間是曲面而已
          曲面的分類方式是衆所周知的
          只要說出 虧格 邊界 可定向性 一個曲面就確定了
          因此 '粘合' 被理解爲 '分割'
          不是用 '粘合' 來構造曲面
          而是用 '分割' 來揭示曲面的不同對稱性

        - [謝]
          下面的討論是爲了說明 如此定義的映射 如何可以做複合
          複合 將成爲 映射羣中的乘法

        當 f 映 D1 到 D2 時
        f 就也可以映射曲面的任意分割 D 到一個固定的分割 D'
        因爲 D 可以被 D1 加細
        這個更細的分割 就又可以被 f 映到 D2 的某個加細
        這樣我們就得到了 f 映 任意 D 到 D'
        比如 (D2 f = D3)
        因此 (D1 f f = D3)
        繼續複合 就得到 f 的冪[power]
        如果 g 是另外一個映射 它可以作用於任意分割 因此可以作用於 D2
        這樣我們就得到 (D1 f g = D2 g = D4)
        如從 我們就能 複合[compose] 曲面上的映射
        並且 曲面上的映射形成一個羣

        - [謝]
          Dehn 略去了 驗證羣公理的工作
          單位元是恆等映射 這是顯然的
          之後 恆等映射[identity map] 也稱爲單位映射
          既然映射被定義爲了具體的一一對應 其逆也是顯然的

        然而直接考慮這個羣是不切實際的
        因爲它不是由有限個元素生成的
        因此人們考慮它的商羣[quotient group]
        做商就把映射分成了類

        映射 f 屬於單位類[identity class]
        如果 (D1 f = D2) 得自 (D1 id = D1) 的一個同倫變換
        (也就是 形變[deformation])

        兩個映射屬於同一類
        如果 其中一個是是另一個與單位類中的變換的複合

        單位類中的映射構成映射羣的正規子羣[normal subgroup]
        因爲 如果 e 是單位類中的映射
        (f e f {-1}) 映 (D f) 到 D 也與單位映射同倫

        如此做商所得到的 映射類羣[mapping class group]
        就是我們研究的主題

***** (b) 不同類型的映射

      - 一個非單位映射[的冪]
        可能把某些分割映到自身
        此時 說這個分割 許可[admits] 一個非單位映射
        這個映射總是有限階的[of finite order]
        即 它的冪 不只是屬於單位類
        而且這個冪本身就是單位映射

        其他不屬於這類的映射是無限階的
        它們冪不屬於單位類

        最後還有可能有有限階的映射
        其 n 次冪 屬於單位類
        但是這個有限階映射的類中
        沒有映射的 n 次冪 等於單位映射
        即 (f {n} = e) 其中 e 是一個形變 [形變屬於單位類]
        但是 對於任意形變 e'
        ((e' f) {n}) 都不等於 單位映射

        在之後的章節中
        我們將給出 前兩類映射的例子

        第三類映射是否存在尚且存疑

        - [英譯者註]
          Nielsen 證明了第三類映射不存在
          見 Acta math. 75 (1942), 23-115.

***** (c) 固定邊界的同倫

      - 對於有邊界的曲面
        我們可以以不同的方式來選擇 單位類

        選取單位類爲與單位映射同倫的映射 而不在乎邊界
        或者 要求單位類中的映射同倫於單位映射的過程中 保持邊界不變

        這第二種 更小的 單位類
        也是映射羣的正規子羣
        當使用它來做商的時候
        我們必須限制與映射羣中保持邊界不變的映射

        與一般的分類相比
        這些映射 被保持邊界不變的單位類 分得更細

      - 如果考慮 '打孔的' 曲面 ['punctured' surfaces]
        即 如果邊界可以收縮成一點
        ['打孔的' 曲面 是曲面去掉有限個點 因此 這樣得到的曲面是不是緊緻的]
        那麼 兩種單位類就重合了
        因爲 每個形變 都保持邊界不變 因爲 邊界只是一個點

        除了保持邊界不變的映射
        我們還可以提及 置換邊界 或者 孔 的特殊映射

***** (d) 指標[? indicatrix]

      - 一個映射 映有向曲線到另一個有確定定向的曲線

        一個映射 要麼顛倒 要麼保留 indicatrix

        保持 indicatrix 的映射類羣 是原映射類羣的正規子羣

        之後 除非有個別聲明
        映射都假設爲保持 indicatrix
        [indicatrix preserving] [orientation preserving]

*** (2) 一 二 三洞球面的自我映射

    - 我們稱 帶有 n 個洞的球面
      爲 n 洞球面
      記爲 Ln

***** (a) 一洞球面

      - 考慮曲面上的算數域之前
        先考慮一些簡單的映射問題 是有用的

        一洞球面 即圓盤
        其映射類羣是單位羣

        不論固定邊界與否
        所有映射都屬於單位類

        其證明就是
        曲面的一個分割
        總是可以被相繼的同倫形變到另一個分割

***** (b) 二洞球面

      - 二洞球面 即圓柱
        其映射類羣 是二階羣
        其中的非單位映射就是交換邊界

        如果要求不能交換邊界
        但是邊界上的點不固定
        其映射類羣 是單位羣

        保持邊界不變
        其映射類羣 是無限階循環羣
        這是因爲
        有無限多不同的方式
        把一個邊界上的點 y1 連接到另一個邊界上的點 y2
        (見 圖1 中的 (y1 y y2) 和 (y1 z y2))

        - [謝]
          上面句話中的 '因爲'
          隱藏了 Dehn 劃歸問題的方法
          這個劃歸法就是
          利用嵌入在二洞球面上的線段
          來把二洞球面的映射問題 轉化爲 一洞球面的映射問題

          如果確定了 二洞球面 兩個邊界之間的一條路
          沿着這條路裁開 二洞球面 就成了 一洞球面

          因此
          二洞球面上 兩個邊界之間的路
          外加 一洞球面上的一個自我映射
          就給出了 二洞球面上的一個自我映射

          並且
          二洞球面上的所有自我映射
          都可以如此構造出來

          這個劃歸的方法 在這裏沒有明顯提及
          可能是因爲這裏的映射非常直觀
          但是在處理 三洞球面的時候 Dehn 明顯地指出了這個方法

        [>< 圖1]

        圖1 展示了一個映射
        這個映射可以生成 上面所說的無限階循環羣
        映射由圓柱的兩個分割之間的如下一一對應定義
        分割 D1 爲多面體 (z1 r1 y1 y y2 r2 z2 z) 和 (z1 s1 y1 y y2 s2 z2 z)
        分割 D2 爲多面體 (z1 r1 y1 z y2 r2 z2 y) 和 (z1 s1 y1 z y2 s2 z2 y)
        如下的對應 保持邊界不變 只是交換了點 y 與 z
        (z1 r1 y1 y y2 r2 z2 z) 對 (z1 r1 y1 z y2 r2 z2 y)
        (z1 s1 y1 y y2 s2 z2 z) 對 (z1 s1 y1 z y2 s2 z2 y)

        我們稱這個映射爲 扭轉[twist]
        當邊界固定的時候 這個扭轉不是同倫形變

        如果不保持邊界不變 連接邊界的路 (y1 y y2)
        與任意 連接邊界的路 (y1' y' y2') 同倫

        如果保持邊界不變 (y1 y y2) 和 (y1 z y2) 就不同倫
        並且有無窮多不同倫的路
        確定了 正向 或 反向 繞邊界的次數
        就在同倫意義上 確定了這樣一個路
        [也就是說 這裏的算數域 就是整數的加法羣]

        [略 至本段末]

        - [謝]
          之後給出了 構造 映射類羣 中的兩個元素 之複合 的方式
          即 因爲 考慮的是 同倫等價類
          所以 我們可以用 辮子理論[braid theory] 來理解這個複合
          注意
          映射羣中的函數複合
          在映射類羣中 被處理成了 非常簡單的構造
          這就是同倫等價的力量

      - [略]
        這個映射類羣 誘導出 整數的加法羣 上的線性變換

      - 如上我給出了很多構造的細節
        因爲這裏我們有最簡單的 算數域確定曲線系統 的例子
        算數域上的變換 給出 映射類羣

***** (c) 三洞球面

      - 三洞球面 L3
        其映射類羣 是三個邊界的對稱羣[symmetric group] [即 所有置換形成的羣]
        [這與 MAGNUS, Math. Ann. 109. 中的結果相一致]

      - 限制不能置換邊界的話
        映射類羣 就是單位羣
        [這是 DEHN, Autogr. Vortrag, Breslau 1922
         和 R. Baer, Journ. f. Math.,vols. 156, 160. 中
         關於曲面上的曲線系統工作的基礎]

        證明如下

        取兩個邊界
        再取兩條連接它們的路
        我們考慮這兩個路之間的同倫形變

        取三條路 (a b) (c d) (e f)
        它們把三洞球面分割成兩個圓盤
        [如 圖3]

        [>< 圖3]

        我們將證明 任意連接 a b 的路 v
        在 L3 中 與 (a b) 同倫

        沿着 v 考慮它與 (a b) (c d) (e f) 的相繼相交的點的序列

        我們可以假設 沒有相繼的兩個交點 落在 (a b) (c d) (e f) 中的同一條路上
        因爲 經過同倫形變 如此相繼的兩個交點 可以被消除

        同理 我們假設交點序列中的第一個 不落在 (a b) 上

        下面分情況討論

        假設第一個交點 x 落在 (c d) 上
        那麼下一個交點一定只落在 (a b) 上
        因爲 如果它落在 (f e) 上 它就不能回到 b 點了
        再下一個交點只能落在 (x c) 上
        再下一個交點只能落在 (a b) 上
        再下一個交點只能落在 (x c) 上
        等等
        如此循環 v 環繞 b c 所在的邊界很多圈 最終回到 b 點
        經過同倫形變 v 可以變得與 (a b) (c d) (e f) 皆不相交
        因而 v 與 (a b) 圈出 L3 中的一個圓盤
        因而 v 與 (a b) 同倫

        另外一種情況是
        交點序列中的第一個點 x 落在 (e f) 上 [見 圖4]
        [>< 圖4]
        若 下一個交點落在 (c d) 上
        那麼之後的 v 又只能環繞 c b 所在的邊界了
        把 v 的起點沿着外層的邊界移動
        就可以把 v 劃歸爲第一種情況
        若 下一個交點 z 落在 (a b) 上
        再下一個交點如果落在 (c d) 上
        就又可以被劃歸爲第一種情況
        所以考慮下一個交點 u 落在 (x e) 上
        對於之後的交點
        我們按照同樣的理由排除落其在 (c d) 上的可能
        這樣 之後的交點就相繼落在 (a b) 與 (f e) 上
        如此 v 就是環繞 a f 所在的邊界而回到 b 點
        因而 v 與 (a b) 同倫

        如此就完成了分情況的證明

      - 從上面的證明中我們還可以看出
        如果保持邊界固定
        v 的同倫類 由兩個整數確定
        這兩個整數分別記錄着
        v 相繼 環繞 a f 所在的邊界
        與 環繞 b c 所在的邊界
        的方向與次數

      - 注意
        我們的結論是 [當邊界不固定時]
        沿着任意一條連接兩個邊界的路 v
        裁開曲面 L3
        就如同沿着 (a b) 裁開
        從而得到 L2
        因爲 v 可以同倫形變到 (a b)

      - 任意一個 L3 的邊界可變的映射 f
        可能把 (a b) 映到 v

        L3 的一個同倫 h 可能也把 (a b) 形變到 v
        [這里說的 一個函數是空間的同倫
         就是指 這個函數與這個空間的單位映射的同倫]

        f 有別與 h 的部分 是二洞球面上的一個映射 g
        這個 L2 來源與沿着 (a b) 裁開 L3
        因此 g 保持 (a b) 所對應的兩條線段不變

        但是 二洞球面上的所有映射 只要一個邊界可變 就是同倫

        因此 g 是 L2 的同倫
        這個同倫保持 (a b) 所對應的兩條線段的不變

        因此 g 也是 L3 的同倫 [添加上 映 (a b) 到 v]

        因此 f 與 h 同倫 從而術語單位類

        如此我們完成對如下定理的證明
        限制不能置換邊界
        三洞球面的 映射類羣 是單位羣

        - [謝]
          我也可以給出 強調構造的 證明方式

          考慮 L3 的任何一個自我映射 f
          f 限制這個同倫在 (a b) 上
          就得到 (a b) 的嵌入

          沿 (a b) 裁開 L3 而得到 L2
          裁線 (a b) 就成了 所裁出的 L2 的一個邊界上的兩個線段
          f 限制在這個 L2 上
          就是一個保持這兩個線段不變的 L2 的自我映射

          任何 L3 的自我映射
          都可以用 一個嵌入 L3 的線段
          和一個 L2 的保持這兩個線段不變的 自我映射構造

          我們知道
          連接 (a b) 所連接的兩個邊界的 嵌入曲線
          只有一個同倫類
          即 (a b) 所代表的同倫類

          我們還知道
          只要 L2 的一個邊界不被固定
          其 映射類羣 就是單位羣

          因此 L3 的 映射類羣 也是單位羣

      - L3 的保持邊界不變的映射類羣
        是 有三個生成子的自由阿貝爾羣[free abelian group]
        三個生成子 是沿着三個邊界的扭轉[twists]

        一個沿着邊界曲線的扭轉 來自二洞球面上固定邊界的扭轉
        在曲面上 扭轉曲線[twist curve] 落在邊界和一條平行於邊界的曲線之間
        [扭轉曲線 指用以確定扭轉的嵌入曲線]
        我們取平行於邊界的曲線 使其互不相交

        證明如下

        L3 的映射 f 映 (a b) 到 v

        通過兩個 沿邊界的扭轉 t1 與 t2
        (a b) 可以被映爲 與 v 同倫的曲線 v'

        當需要 n1 次扭轉 t1 與 n2 次扭轉 t2 時
        映射 (g := f h' t2 {-n2} t1 {-n1}) 保持 (a b) 不變
        其中 h' 是能夠映 v' 到 v 的同倫

        沿着 (a b) 裁開 L3 得 L2
        g 限制在 L2 上
        就成了 保持 L2 邊界不變的 L2 映射
        因此根據 (b) 節的結論
        g 與沿着第三個邊界的某個扭轉 (t3 {n3}) 同倫
        (h'' t3 {n3} = f h' t2 {-n2} t1 {-n1})
        其中 h'' 是 L2 保持邊界的同倫

        因爲同倫構成是正規子羣
        [即 單位類構成是正規子羣]
        所以
        (f = h'' t3 {n3} t1 {n1} t2 {n2} h' {-1}
           = h t3 {n3} t1 {n1} t2 {n2})
        如此就證明了 三個沿着邊界的扭轉生成 L3 的映射類羣

        三個扭轉是相互交換的
        因爲假設了它們作用的部分不相交

        三個扭轉之間沒有其他關係
        證明如下
        假設映射類羣中 (t1 {n1} t2 {n2} t3 {n3} = 1)
        取 v12 爲鏈接前兩個邊界的路
        選取第三個邊界上合適的扭轉帶
        v12 就在 t3 的作用下不變
        t1 {n1} t2 {n2} 想要把 v12 變成同倫曲線
        只有 n1 n2 都爲零
        因爲映射想要屬於單位類
        它就必須把每個連線映爲同倫於連線自身的同倫曲線
        所以 n1 = n2 = 0
        類似地 可以證明 n1 = n3 = 0

        因此
        L3 的保持邊界不變的映射類羣
        是由 t1 t2 t3 生成的自由阿貝爾羣

*** (3) 四洞球面上的特殊映射

    - 四洞球面 L4
      在 邊界不固定 但不置換邊界 時
      也擁有不在單位類中的映射

      記四個邊界爲 r1 r2 r3 r4 [見 圖5]
      [>< 圖5]
      考慮三條閉曲線 (y z) (s t) (u v)
      (y z) 分離 r1 r2 與 r3 r4
      (s t) 分離 r1 r4 與 r2 r3
      (u v) 分離 r2 r4 與 r1 r3

      我們現在考慮 沿着 (z y) (s t) (u v) 的扭轉
      就算是邊界可變時
      這些扭轉不屬於單位類
      因爲 比如說沿着 (z y)
      映 (s t) 爲 f = (s y1 z2 t y2 z1) [見 圖5]
      它與 (s t) 不同倫

      考慮 L4 的基本羣 我們就能明白這一點
      這個羣是 r1 r3 r4 生成的自由羣
      (s t) 對應與 (r1 r4) 的共軛
      f 對應與 (r1 r3 r4 r3 {-1}) 的共軛
      在自由羣中 這二者是不共軛的

      所以 f 與 (s t) 不同倫
      因此 把 (s t) 映到 f 的扭轉 也不是同倫

      人們可以讀出 f 在基本羣中的表示
      [? 如何看出]

      對於沿着 (s t) 與 (u v) 的扭轉也是如此
      之後 在 (7) 中 我們將看到
      L4 的映射類羣 是由沿着 (z y) 和 (s t) 的兩個扭轉生成的
      [? 解釋爲什麼只有連個生成子]

    - 在邊界不可移動情形下
      映射類羣就是上面的映射類羣外加沿着邊界的四個扭轉
      這四個扭轉相互可交換 並且也與任何保持邊界不變的映射可交換
      特別的 沿着 (y z) (s t) (u v) 的扭轉就是保持邊界不變的
      並且這前四個扭轉 與 後三個扭轉之間 有簡單的關係 [見 (7.g)]

*** (4) 環面的自我映射 與 一洞環面

***** (a) 環面

      - 環面 R [德語中環面以字幕 R 開頭]
        的映射類羣 在函數理論中已經久爲人知了
        然而我們會用我們的方法處理它 並把它練習到其他問題

        我們首先給出 R 上的兩個特殊映射
        即 沿着相交於一點的兩個閉曲線 a 與 b 的扭轉 [見 圖7]

        [>< 圖7] [>< 圖8]

        我們記錄 Da 與 Db
        Da 置 連線 (x y) 爲 (x z1 z2 y)
        Db 置 連線 (x q) 爲 (x s q)

        如果 S 是 R 的如 圖7 的分割
        由 a b 分開環面
        那麼相繼地作用 (S Da Db {-1} Da) 就得到 圖8
        [? 如何看出]
        這意味着
        這個變換將使得 用以粘得四面體 旋轉一個直角
        因此 (Da Db {-1} Da) 所屬於的映射類具有有限階 即 四階
        我們得到 ((Da Db {-1} Da) {4} = 1)
        同樣也有 ((Db Da {-1} Db) {4} = 1)

        之後我們將明白 Da 和 Db 可以生成 R 的映射類羣

      - Da 和 Db 也是 一洞環面 R1 的映射
        因爲 扭轉只影響 邊界 a b 的鄰域

      - R 的映射類羣因爲 a 與 b 的定向 而獲得定向
        如果 f 和 f' 把有向的 a 與 b 映到 a' 與 b'
        那麼 (f' {-1} f) 映 a 與 b 到自身 並保持其定向

        我們需要證明 (f' {-1} f) 在單位類中
        因爲 (f' {-1} f) 不變 a 與 b 並保持定向
        所以我們可以沿着 a 與 b 裁開環面 得到一個圓盤
        (f' {-1} f) 就成了這個圓盤的保持邊界的映射
        圓環的任何一個保持邊界的同倫 也是 R 的同倫
        因此 (f' {-1} f) 在單位類中

        可以發現 圓盤的不保持邊界的同倫
        不對應 R 的變換
        因爲 a 與 b 的交點所對應的四個點
        可能不被映射到它們自身

***** (b) 一洞環面

      - 類似地 一洞環面 R1 的 邊界可變的 映射類羣
        與環面 R 相同
        因爲通過如上的剪裁
        (f' {-1} f) 映 有一個邊界可變 一個邊界不可變的 二洞球面 到自身
        這個圖形的映射類羣是也單位羣
        [略 至本段末]

*** (5) 二 三洞球面 和 環面上的算數域

***** (a) 曲面上的算數域 得自 曲面上的曲線系統

      - 關於表示 我們的一般原則是
        使同倫的曲線 有相同的表示

        而且我們算數域中的元素
        不是單個開或閉的曲線
        而是很多這些曲線所形成的系統
        曲線之間沒有相交 曲線自己也不自交

        並且我們略去那些 可以收縮到一點的
        或可以收縮到某個邊界的曲線 不談
        明確這些條件 對於簡化表示來說 是必要的

        我們離題而回顧一下
        曲面上曲線作爲基本羣的元素的表示
        來看看它與我們將要給出的表示有何不同

        - 基本羣中的元素 對應一個可以有任意奇異點的閉曲線
        - 只有當給出曲面上一個固定的點 作爲初始點
          並且給以曲線以定向時
          這些曲線才有唯一的表示
        - 不取固定的點的話
          曲線所對應的元素 就是已有元素的共軛

        在我們的表示中
        曲線系統用長度固定的一列整數表示
        整數列的長度就對應算數域的維度

        然而 表示着曲線的 基本羣的元素
        可能由任意長的一列整數給出
        即 不同生成子的指數

        我們的表示更簡單
        曲面自我映射誘導出 算數域上的映射 更容易理解
        它們都是已知的算數變換

***** (b) 二洞球面上的曲線系統

      - 當邊界可以移動
        連接邊界的一個曲線系統 單單由其曲線的數量 n 決定
        因爲 當邊界可以移動 任意兩條連線都是同倫的
        因此 任意兩個有 n 個相互不交的連線的系統 總是同倫的
        [略 三句]

        當固定邊界在同倫下不變時
        在每個邊界上我們取 n 個固定的點
        再取一個 連接兩個邊界的 正規線 v [normal line]
        並且指出 v 的正面 [positive side]

        當沿着 n 條連線 從一個邊界跑到另一個邊界時
        我們記錄正向越過和反向越過 v 的次數的代數和
        記爲 d

        因爲假設 n 條連線是相互不交的
        所以在一個保持邊界不變的同倫變換下
        我們假設每條連線與 v 相交的方式都相同

        如果 d abs 小於 n
        那麼就有 d abs 條連線與 v 相交
        沿着邊界扭轉 不與 v 相交的連線 一次
        就得到它們 [見 圖9]
        [>< 圖9]
        因此 根據 (2.b)
        d 在保持邊界不變同倫下不變
        如果 (d = w + u * n)
        其中 w abs < n
        並且 w 與 u 的符號相同
        它來自於 對 w 條連接的一次扭轉
        跟着 對 n 條連接的 n 次扭轉
        根據 (2.b) 每條連接的纏繞數在保持邊界的同倫下不變
        因此 d 也在保持邊界不變同倫下不變

        數對 (* n d) 在忽略保持邊界的同倫的條件下
        決定了一個連線系統

        我們用 (* 0 d) 來記
        有 d abs 條與邊界平行的曲線系統
        d 的符號描述了它們與 正規線 v 相交的方向

        如此就完成了用 (* 0 d) 來表示曲線系統
        這種表示在忽略保持邊界的同倫變換的條件下
        是唯一的

      - 二洞球面上保持邊界的自我映射是 扭轉
        一個扭轉變 (* n d) 爲 (* n (d + k * n))
        其中 k 是非零的整數
        - 當 n 不等於 0 時
          這種變換所構成的羣 與 二洞球面的[保持邊界的]同倫類羣 同構
        - 當 n 等於 0 時
          扭轉把 (* 0 d) 變爲 (* 0 d) 本身
          所以變換羣是一個平凡羣
        這種表示下
        只有閉曲線的方向體現在了數對中

      - [謝]
        爲什麼嵌入曲面的曲線系統上的映射
        能夠用來捕捉曲面到自身的映射的性質呢?
        我想是因爲 n 可以選取得任意大
        使得曲線系密密麻麻地佈滿整個曲面
        如此一來 映射在曲線系統上的效果
        基本上能用來刻畫映射在曲面所有點上的效果了

        這種方法也算是一種劃歸
        把研究二維曲面的連續映射
        劃歸爲研究嵌入二維曲面中的曲線的連續映射
        二維就被化爲了一維

        我只是建議一些想像
        而並不是建議把 Dehn 的方法算數化
        [就像分析的算數化一樣]
        這種算數化只會推遲和延緩人們的想象
        從而抹殺人們的想像力

***** (c) 環面上的曲線系統 與 曲線的定向

      - 我們 用兩個不交的曲線 a1 與 a2
        分環面爲兩個 二洞球面 L2 與 L2' [見 圖10]
        [>< 圖10]
        除了與 a1 平行者之外
        環面上的任意曲線系統
        由 連接 a1 上的 n 個點 與 a2 上的 n 個點 的兩組曲線構成
        這兩組曲線分別落在 L2 與 L2' 上
        可以不考慮 連接 a1 或 a2 自身的曲線
        因爲它們可以被同倫消除

        考慮 L2 中可以移動邊界的同倫
        此時 任意連接 L2 兩個邊界的曲線系統
        都可以被同倫變到給定的一個曲線系統

        [? Even then, the association of the n fixed points
         and the n fixed connections to the n give n connections
         is determined only up to cyclic interchange.
         This cyclic interchange corresponds to a homotopy of the torus.]

        如果 曲線系統在 L2 上的部分被視爲是固定的
        那麼 L2' 上的同倫就是固定邊界的了
        根據 (b) 連接 L2' 的 n 條連線 就由數對 (* n d) 表示
        其中 d 是 沿着 L2' 中的曲線系統 從 a1 跑到 a2 時
        與 L2' 中的某條正規連線 之相正相交和反交次數的 代數和
        我們可以取 b1 在 L2' 中的部分爲這個正規曲線 [見 圖10]
        並且指出 b1 的正面
        利用同倫
        我們可以使得 L2' 中的連線系統中的每條連線 與 b1 只相交一次
        並且所有的相交都有相同的符號
        這樣 d abs 就代表相交的次數
        我們也取 b1 在 L2 中的部分
        使得它與 L2 中固定的連線系統平行
        這樣 L2 中固定的連線系統 也與 b1 相交 d abs 次

        利用同倫 我們還可以取一條與 b1 平行的 b2
        使得 L2 與 L2' 中的連線系統與 二者的相交情況類似

        沿着 b1 與 b2 裁開環面
        也得到兩個 二洞球面 L2'' 與 L2''' [見 圖10]
        同樣的曲線系統 也可以被看成是這兩個 二洞球面 的連線系統
        與之前的情況剛好相反 這時在邊界 b1 與 b2 上 我們有 d abs 個點

        最後
        我們用 (* 0 d) 來記
        有 d abs 條與 a1 和 a2 平行的曲線系統

        這樣就環面上的任意曲線系統
        我們就給出了數對 (* n d)
        其中 n 大於等於 0
        而 d 是任意的整數

      - [關於定向]
        除了與 a1 平行的曲線系統之外
        我們沒有給出曲線的定向
        這體現在我們的數對中 就是 n 只能是自然數

        [? This has the consequence that
         a mapping of the torus onto itself
         is first determined by the images of three curves,
         since e.g. a, and b.
         can be mapped onto themselves with reversed orientation.]

        對於高虧格的曲面
        這個問題還沒有被解決過
        因爲定向沒有得到算數的表示

        然而對於環面
        引入曲線的定向並無困難

        在環面上
        一個曲線系統中的所有曲線
        因爲是相互平行的
        所以是相互同倫的
        也就是說
        沿着一條曲線 c 裁開環面
        得到一個二洞球面
        而二洞球面上所有 不能收縮到一點的 簡單閉曲線
        都與邊界曲線 c 同倫

        我們給這個曲線系統一個定向
        此時從系統中的一個曲線同倫形變到另一個 就是保持定向的

        如果 在 L2' 中
        沿着個曲線系統中的一條曲線的定向
        我們從 a1 移動到了 a2
        那麼對於曲線系統中的任意一條曲線也是如此
        因爲我們已經假設
        在 L2 與 L2' 中
        連接 a1 自身 或 連接 a2 自身的曲線
        已經被同倫消除了
        既然曲線系統中的所有曲線都是如此
        此時我們就給 n 以正符號

        相反 如果
        沿着曲線系統在 L2' 中的部分
        從 a2 移動到了 a1
        那麼就給 n 以負符號

        d 的符號也依賴定向
        b1 與 b2 把環面分成兩部分
        假設我們取背面的部分
        如果曲線系統在這一部分是從 b1 到 b2
        就給 d 以正符號
        如此依賴 圖10 中的曲線所給出的數對就是 (* 1 1)
        如果把這個曲線的定向反過來就得到 (* -1 -1)
        一般來說 反轉定向會使得 (* n d) 變成 (* -n -d)

        最後 我們用 (* 0 d) 來記
        有 d abs 條與 a1 界平行的曲線系統
        d 的符號對應與其定向

***** >< (d) 環面上映射類羣所誘導出的算數域上的變換羣 生成與關係

      - ><

***** (e) three-holed sphere. arithmetic field. invariance under homotopic transformations

      - ><

*** (6) the arithmetic field or the curve systems on the one-holed torus
***** (a) introduction of the field
***** (b) transformation by mappings. examples.
***** (c) one-holed torus with fixed boundary. connection with the trefoil knot
*** (7) arithmetic field on the four-holed sphere
***** (a) system of closed curves on the four-holed sphere
***** (b) mappings of the four-holed sphere and the action on the arithmetic field
***** (c) derivation of invariants of a curve system from the arithmetic presentation
***** (d) orientation. examples
***** (e) geometric presentation of the symbols. view of higher cases
***** (f) curve systems on the four-holed sphere with endpoints on a boundary
******* (1) normal form
******* (2) arithmetic field
***** (g) four-holed sphere with fixed boundaries
******* (1) derivation of a relation
******* (2) application to the two-holed torus with fixed boundaries
******* (3) twists along the boundary of singly-bounded surfaces
******* (4) twists along separating curves on closed or singly-bounded surfaces
*** (8) five-holed sphere
***** (a) coordinate systems
***** (b) presentation of a system of closed curves
***** (c) reduction of symbols. generation of mappings
*** (9) generation of the mapping classes for the sphere with n holes
***** (1) lemmas
***** (2) lemmas
***** (3) lemmas
***** (4) lemmas
***** (5) lemmas
***** (6) generation with the help of complete induction
***** (7) the five-holed sphere as an example
***** (8) direct exhibition of generators on the basis of a cyclic ordering of boundaries. the number of generators
*** (10) generation of the mapping classes for every orientable surface
***** (1) lemmas
***** (2) lemmas
***** (3) generation with the help of complete induction
***** (4) double and triple torus as examples
***** (5) direct exhibition of generators on the basis of a normal representation of the surfaces. the number of generators.
***** (6) arithmetic field in the general case.

* appendix : the dehn-nielsen theorem
