#+title: Investigations into cell complex

- Author : Xie Yuheng
- Date : Started at 2019-03-22, WIP
- Keywords : CW complex, Cell complex, Algebraic Topology, Aristotle.

* Abstract

  - Just like Aristotle, I start by history reviews and critiques.

  - The axioms of topological space is motivated by
    the arithmetization of infinitesimal analysis {[[arith-analysis][1]]}.

    The axioms thus developed, capture the concept of nearness,
    the first impressive use of the axioms is the definition of continuity.

  - Based on cell complex, I show another list of axioms,
    to capture the concept of connectedness first,
    and firstly use it to give an alternative definition of continuity.

  - This approach can be traced back to Aristotle,
    in part six of his "Categories" {[[Categories][2]]}.

  - The aim of Algebraic topology is to develop functors
    to distinguish topological spaces.

    The functors developed often approach this aim
    by using algebraic structures to express connectedness.

    Thus my design is practical for algebraic topology.

* [todo]

* References

  - <<arith-analysis>>
    {1} Arithmetization of Analysis, on Wikipedia
    https://en.wikipedia.org/wiki/Arithmetization_of_analysis

    - The arithmetization of analysis
      was a research program in the foundations of mathematics
      carried out in the second half of the 19th century.

    - Kronecker originally introduced the term
      arithmetization of analysis, by which he meant
      its constructivization in the context of the natural numbers.

    - The meaning of the term later shifted to signify
      the set-theoretic construction of the real line.
      Its main proponent was Weierstrass, who argued
      the geometric foundations of calculus
      were not solid enough for rigorous work.

  - <<Categories>>
    {2} Categories, By Aristotle, Translated by E. M. Edghill

    - Quantity is either discrete or continuous. Moreover, some quantities
      are such that each part of the whole has a relative position to the
      other parts: others have within them no such relation of part to part.

    - Instances of discrete quantities are number and speech;
      of continuous, lines, surfaces, solids,
      and, besides these, time and place.

    - In the case of the parts of a number, there is no common boundary
      at which they join. For example: two fives make ten, but the two fives
      have no common boundary, but are separate; the parts three and seven
      also do not join at any boundary. Nor, to generalize, would it ever
      be possible in the case of number that there should be a common boundary
      among the parts; they are always separate. Number, therefore, is a
      discrete quantity.

    - The same is true of speech. That speech is a quantity is evident:
      for it is measured in long and short syllables. I mean here that speech
      which is vocal. Moreover, it is a discrete quantity for its parts
      have no common boundary. There is no common boundary at which the
      syllables join, but each is separate and distinct from the rest.

    - A line, on the other hand, is a continuous quantity, for it is possible
      to find a common boundary at which its parts join. In the case of
      the line, this common boundary is the point; in the case of the plane,
      it is the line: for the parts of the plane have also a common boundary.
      Similarly you can find a common boundary in the case of the parts
      of a solid, namely either a line or a plane.

    - Space and time also belong to this class of quantities. Time, past,
      present, and future, forms a continuous whole. Space, likewise, is
      a continuous quantity; for the parts of a solid occupy a certain space,
      and these have a common boundary; it follows that the parts of space
      also, which are occupied by the parts of the solid, have the same
      common boundary as the parts of the solid. Thus, not only time, but
      space also, is a continuous quantity, for its parts have a common
      boundary.
