#+title: a new kind of science

* 1 The Foundations for a New Kind of Science

** An Outline of Basic Ideas

- program: setup rules for change

- computation: change directed rules (behavior)

- nature (the dao):
  nature is a simple programs produce great complexity

- program written by human:

  and the reason that such complexity is not usually seen in human artifacts
  is just that in building these we tend in effect to use programs
  that are specially chosen to give only behavior simple enough for us
  to be able to see that it will achieve the purposes we want.

  when human direct change, we often want simple predictable result.

- perception:
  our own processes of perception and analysis can be thought of as computations.

* 2 The Crucial Experiment
* 3 The World of Simple Programs

- the "substitution systems" is generative grammar.

- 1-dim cellular automata v.s. phrase structure grammar

  - the rules of cellular automata can be describe by similar way we describe grammar,
    but the semantic of the rule is different.

    cellular automata simultaneous transform all cells in one step,
    while generative grammar transform one pattern in one step.

- the "tag systems" will occur in some implementation of breadth-first search (by a queue).

* 4 Systems Based on Numbers
* 5 Two Dimensions and Beyond
* 6 Starting from Randomness
* 7 Mechanisms in Programs and Nature
* 8 Implications for Everyday Systems
* 9 Fundamental Physics
* 10 Processes of Perception and Analysis
* 11 The Notion of Computation
* 12 The Principle of Computational Equivalence
