#+title: combinatorial group theory

* (1946 1967) (maurice frechet and kt fan) initiation combinatorial to topology

*** preface

    - x -
      開篇引用 poincare 對 topology theory 的定義
      以 Elementary Geometry, Projective Geometry, Topology 之間的對比爲例子
      強調 質 與 量 之間的對立

*** chapter one. topological generalities

***** 1 Qualitative Geometric Properties

      - x -
        追隨 poincare 的描述
        來強調 質 與 量 之間的對立

***** 2 Coloring Geographical Maps

      - x -
        染色問題在三維中是平凡的
        即 沒有染色數的上限
        因爲對三維空間的分割可能形成非常複雜的相鄰狀態
        或者說在三維空間中 有很靈活的方式來形成多種相鄰狀態

      - k -
        這種因爲維數增加 而使得理論不能類比的情形
        還真是令人擔心呢

      - x -
        這些都是事實
        我們只要描述它就行了

        這裏需要問的是
        這種複雜的相鄰情況
        是否會使得我們很難形成三階代數

      - k -
        knot 所帶來的複雜性 就有些類似

      - x -
        沒錯
        並且這裏還要注意染色問題是就流形而言的
        對於一階流形 只要兩個顏色就夠了
        當不限於流形的時候 染色問題也是平凡的

      - k -
        人們在考慮一階圖形的時候
        不把自己限制於流形 而是考慮有向圖
        但是在二階的時候 一般的 complex 就過於複雜了
        因而人們把自己限制於流形

      - x -
        我想限制與流形還有一個原因
        那就是要給 complex 以幾何
        但是其實不限制與流形可能也可以給其以幾何

        在之後討論 complex 到流形的限制時
        我們也應該從一階流形開始

***** 3 The Problem of Neighboring Regions

***** 4 Topology, India-Rubber Geometry

      - India-Rubber,
        which we are able to distort as we wish in a continuous fashion without tearing.

      - x -
        這種想法可以給拓撲不變量一個直觀的解釋

***** 5 Homeomorphism

      - x -
        可逆的連續雙射 homeomorphism
        可以用來捕捉之前的
        "to distort as we wish in a continuous fashion without tearing."
        這在於
        想要描述的空間 A 的所有性質
        都是利用連續映射建立的
        比如 (: f (-> X A)) 或者 (: g (-> A Y))
        因此當有 homeomorphism 的時候
        這些 描述已然有效
        並且 所描述的性質之間的關係已然被保持

      - k -
        可以發現
        我們是先發現了很多有趣的不變量
        之後在慢慢得到這個等價關係[同胚]的正確定義的
        但是在講述的時候
        我們會先定義等價關係
        然後再定義這些不變量
        其實對定價關係的定義正是爲了使得這些不變量成爲不變量

      - x -
        用德里達的話來說
        某個具體的 等價關係 並不是研究的中心
        不變量並不附屬於等價關係
        而是正相反
        等價關係起源於所發現的不變量

        當想要描述的不變量不適用於某種等價關係了
        就要修改這個等價關係的定義
        使得這些不變量重新變爲不變量
        [比如 homeomorphism 到 ambient-isotopy]

      ------

      - x -
        在定義連續映射的時候
        作者強調了這裏描述的映射是點到點的
        而不是寫 polar reciprocation 那種點到線的
        但是後者也可以是連續映射
        當把空間看作是線組成的時[而不是點組成的]
        topology 公理可能就是必要的了
        也就是說 topology 公理可能不能被理解爲分析算數化的產物
        而應該被理解爲有效的推廣

      - k -
        但是我們所使用的 uncurry 原則
        則是說
        所有的這種 level-up 映射都應該被 uncurry 爲 level-same 映射

      - x -
        很難想象這種處理方式能夠描述 polar reciprocation
        一種離散的 polar reciprocation ?

      - k -
        我想這是因爲 polar reciprocation 並非純粹的 topology 變換

      - x -
        什麼是純粹的 topology 變換 ?

      - k -
        首先
        當以組合的方式來描述空間時
        我們能夠定義很多空間之間的變換
        這樣
        我們就可以把純 '粹連 topology 變換'
        定義爲 與我們能夠定義的變換同倫的變換

      - x -
        何以見得 polar reciprocation 不能與這種變換同倫呢 ?

      - k -
        我們可以嘗試找 polar reciprocation 的同倫
        正如我們找 dehn twist 的同倫一樣
        映射可要被降階

      - x -
        我想我們需要先找到空間的合適劃分
        然後看看這個描述與點的變換限制於這些劃分的時候的樣子
        這個問題應該先放一放
        因爲我們對 polar reciprocation 與圓錐曲線的理解還不夠
        [注意 圓錐曲線可以被推廣到一般空間所形成的 cone]

        ><><><
        一般描述於點的連續變換的組合化
        以及 polar reciprocation 的組合化

      ------

      - x -
        這裏還指出了
        "to distort as we wish in a continuous fashion without tearing."
        必須用 ambient-isotopy 這個概念來捕捉
        而不能用 homeomorphism 來捕捉
        因爲 homeomorphism 還可以是 cut and re-glue

        同時這裏還指出了 一個線段和一個三角形之間可以有 homeomorphism
        但是這些都是集合論語言的問題
        當我們以組合的方式處理拓撲學時
        這些病態的現象並不會出現

***** 6 Topology, Continuous Geometry

      - It is important to note that
        a topological property of a set
        is not necessarily a topological invariant,

        in which case the property is said to be relative.
        In other words, two homeomorphic sets Ε and F
        can have certain different topological properties,
        as when it is a matter not of properties of Ε and F alone,
        but of properties concerning Ε and F and the spaces which contain them.

      - x -
        也就是說 relative topological properties 起源於拓撲不變量的細化
        而不是 直接起源與 空間與其子空間
        畢竟 子空間 與 空間 之間的關係
        並不直接涉及到 relative 這個詞

***** 7 Comparison of Elementary Geometry, Projective Geometry, and Topology

      - x -
        這裏跟隨開篇對 poincare 的引用

      - "projected from a center onto a figure."
        understood as "make a cone and make a section."

        from the point of view of projective geometry,
        one does not distinguish the three types of conies.

      - x -
        攝影變換下的等價
        可以利用 cone 來理解
        注意
        使用 cone 的時候
        就是增加了一個維度

        類似的
        uncurry 也是通過增加一個維度
        來理解變換之間的等價

      - k -
        但是
        當用變換之間的同倫
        來定義空間之間的同倫等價時
        情況就有些複雜了
        但是也許還是可以通過增加維度來理解

      - x -
        比如 mapping cylinder
        看來我們需要好好總結一下 mapping cylinder

        ><><><
        總結 mapping cylinder
        總結 空間之間同倫等價之判別的簡化

***** note about erlangen program

      - to form a geometry theory
        1. first, the fundamental element of the geometry (point, line,circle, etc.);
        2. next, the manifold or space of these elements
           plane of points, ordinary space of points,
           spherical surface of points, plane of lines,
           pencil of circles, etc.;
        3. and finally, the group of transformations
           to which the manifold of fundamental elements is to be subjected.

***** 8 Relative Topological Properties

      - x -
        這裏所說的是 ambient-isotopy
        所說的相對性是指 sub-space 相對於 ambient-space
        [而不是相對同倫羣中的相對性]

***** 9 Set Topology and Combinatorial Topology

      - Since the figures studied in set topology are extremely general sets,
        it is natural that the results obtained in this way
        are frequently far from intuitive
        and even sometimes in contradiction with intuition.

      - [bib]

        - [28]
          R. L. Wilder,
          "Point sets in three and higher dimensions
          and their investigation by means of a unified analysis situs,"
          Bull. Amer.Math. Soc, 38 (1932), 649-692.

      - Our book, as indicated by its title,
        is directed principally to combinatorial topology,
        accordingly, to the topology of complexes.

        Since complexes are generalizations of surfaces,
        we shall limit ourselves, in the other two chapters of this book,
        to the topology of surfaces.

        - In connection with the topology of surfaces,
          one can also consult: H.Seifert and W. Threlfall,
          "a textbook of topology",
          chapter six, surface topology.

***** 10 The Development of Topology

      - Poincare's combinatorial topology v.s. Cantor's set topology

*** chapter two. topological notions about surfaces

***** 11 Descartes'Theorem

      - A polyhedron is a system of a finite number of polygons
        which are situated in a mutual relationship
        such that the following four conditions are verified:

        1. each pair of polygons of the system
           have no common interior points.

        2. for each side of a polygon,
           there exist two and only two polygons having this side in common.

           the two polygons can be the same one,
           thus, two coinciding sides can belong to the same polygon.

        3. each pair of polygons of the system
           can be joined by a sequence of polygons of the system
           in the sense that each of these
           has a side in common with the following one.

           i.e.
           there exist joining sequence of faces, for every pair of two faces.
           thus connectivity is ensured in a non-degenerate way.

        4. the polygons about any vertex
           can be placed in a cyclic order
           so that each consecutive pair
           have a common side passing through the vertex.

           thus exclude some kind of singularity.

        According to this definition,
        when we speak of a polyhedron,
        we always mean the surface of the polyhedron.

      - A polyhedron is said to be simple
        if one can continuously deform it into the surface of a sphere.

***** 12 An Application of Descartes'Theorem

      - all regular polyhedra
        the tetra-hedron
        the octa-hedron
        the icosa-hedron
        the cube
        the dodeca-hedron

***** 13 Characteristic of a Surface

      - euler characteristic

***** 14 Unilateral Surfaces
***** 15 Orientability and Nonorientability

      - orientability can be defined by
        1. a oriented circle travelling on the surface.
        2. a subdivision of the surface
           and observing the orientation of the faces limited on the boundaries.

        the 2nd definition is easier to be applied,
        and we can check that heptahedron is nonorientable.

***** 16 Topological Polygons

***** note the thread

      1. define cell-complex
      2. as example, construct the normal form
      3. manifold-checker
      4. manifold-normalizer

***** 17 construction of closed orientable surfaces from polygons by identifying their sides

***** 18 construction of closed nonorientable surfaces from polygons by identifying their sides

      - mobius band = cross cap

        the curve of penetration on the cross cap
        corresponds to the mediancurve on the M6bius band.

      - 2 mobius band = klein bottle

      - thus
        2 cross cap = klein bottle

***** 19 topological definition of a closed surface

      - x -
        this chapter is golden,
        I will analysis of the heuristic of the author :

        In the last two sections,
        we have constructed some closed surfaces from polygons by identifying their sides.

        This shows us the possibility, by operating in the reverse order,
        of decomposing any one of these surfaces into one or more polygons
        satisfying certain conditions.

        - "decomposing any one of these surfaces"
          means that surfaces is going to be defined this way.

        These surfaces are so varied from the point of view of their metrical form
        that their very generality allows us in the following
        to limit the consideration of surfaces
        to those that can be cut up into polygons
        subjected to certain conditions that we are going to make precise.

        - refrain.

        It is quite natural to choose these conditions
        so as to generalize the conditions
        imposed on the polyhedra defined before.

        We have given a definition of the word polyhedron
        that gives us a more general interpretation
        than is meant by this word in elementary geometry.

        - not a generalization of the definition,
          but a generalization of the interpretation.

      - x -
        consider a surface defined in set topology theory,
        one can divide it in many different ways to different polyhedra.

        we replace "the surface to be divided"
        by an equivalent relation between polyhedra,
        to be pure combinatorial.

*** chapter three. topological classification of closed surfaces

***** 20 the principal problem in the topology of surfaces

      - the principal problem in the topology of closed surfaces
        is the search for the topological invariants of each closed surface
        so that we can tell if two arbitrarily given closed surfaces
        are or are not homeomorphic.

      - we shall see in this chapter that
        the characteristic and the property of being orientable or not
        are two topological invariants that suffice to characterize each class.
        In other words,
        two closed surfaces are homeomorphic
        if and only if they have the same characteristic
        and they are both orientable or both nonorientable.

***** 21 planar polygonal schema and symbolic representation of a polyhedron

      - x -
        這一章講 如何利用 polygon 構造 polyhedron
        polyhedron 的條件將被轉述於構造中

        polygon 被想象爲在某個 plane 上

        planar polygonal schema ->
        symbolic representation of a polyhedron

        same symbolic representation implies homeomorphic.
        but
        the same surface can give rise to different forms of polyhedra,
        the same polyhedron can give rise to different forms of symbolic representations.

***** note 'glue to each other' v.s. 'glue to a common skeleton'

      - x -
        "there are exactly two equivalent sides in the plane
        corresponding to each edge ofthe polyhedron."

        關於這個條件

        如果是在構造一個空間
        這個條件就體現爲檢查每個邊出現在面中的次數
        最多只能出現兩次

        如果是在一個已經構造好的 complex 中
        利用 (2 ...) 找 polyhedron
        這個條件就體現在 被使用於 glue 的邊
        在 glue 之後將被消除

      - x -
        作者的理解方式是 glue polygon
        而我們所採用的是類似 cell-complex 的逐階構造方式

        作者說 glue 的時候單單標出名稱是不夠的
        還要標出方向

        這一點在我們的構造方式中如何體現 ?
        在構造三階幾何體的時候又如何 ?

      - k -
        後一種想法的特點在於
        當想要描述 2-cell 的 glue 情況時
        已經有 1-cell 作爲骨架來幫助描述了
        爲了在構造中引入一個 2-cell
        只需要找一個 circle 到 1-cell 骨架的 immersion
        [immersion 即一個一般映射]

        這個 immersion 中非單值的地方 就包含着 glue 的信息
        [非單值的地方 就是邊界的部分名稱重複的地方]

        給 immersion 時所使用的 circle 以定向
        就能看出 兩種 glue 同一個邊的方式
        就對應與 兩種走過 1-cell 骨架中同一邊的方式

      - x -
        但是 sphere 到 2-skeleton 的 immersion 卻沒有類似的現象
        因爲 sphere 沒有像 circle 一樣的簡單定向

      - k -
        這正是我們之前說的
        (1 ...) 與 (2 ...) 這兩個語法的區別

      - x -
        我們需要更多的例子
        [用 lens-space]

***** ><><>< position in boundary

      - x -
        上面說到了 (1 ...) 與 (2 ...) 的語法差異
        (1 ...) 是微分語法
        (2 ...) 是積分語法
        前者 可以描述 穿過一個 loop 的兩種方式
        而後者如果只是利用邊界信息的話
        就沒法描述出 穿過 loop 的兩種方式

      - k -
        我們之前說過
        對於 (2 ...) 而言 積分語法與微分語法都要有
        而我們只有積分語法

        這兩種描述方式對於 (1 ...) 也同樣應該適用
        我們也應該給 (1 ...) 加上積分語法
        這樣各階元素之間的語法差異就消失了

***** ><><>< lens-space as example

      - ><

***** 22 elementary operations

      - Given two polyhedra
        [two symbolic representations of two polyhedra],
        what are the conditions that must be satisfied
        in order that the two closed surfaces determined by them be homeomorphic ?

      - solve this by a set of operations, on symbolic representation,
        that change a polyhedron to a polyhedron which is homeomorphic to it.

        [any function that establishes homotopic equivalence between spaces can do this.]

      - 4 elementary operations [on planar polygonal schema] :
        | 1-dim-subdivision | add point on edge                                  |
        | 1-dim-union       | to view two edges as one                           |
        | 2-dim-union       | to view two polygons as one                        |
        | 2-dim-subdivision | dividing one polygon in two by means of a diagonal |
        when "to view two as one",
        the two must not already been one.

      - the closed surfaces
        determined by two elementarily associated polyhedra
        are homeomorphic.

        to prove this condition of homeomorphic is sufficient is easy,
        we can also prove it is necessary in section 27.

***** 23 use of normal forms of polyhedra

      - By the preceding definition,
        polyhedra can be placed in pairwise disjoint classes
        in such a way that two polyhedra belong to the same class
        if and only if they are elementarily associated.

      - x -
        normal form 的作用就像我們把一個分數約分爲最簡一樣
        有了把一般元素化爲正規元素的算法
        並且兩個正規元素等價與否可以有簡單的判斷
        那麼我們就能判斷任意兩個元素是否等價了

      - k -
        但是與兩個分數之間相等的判斷又不同
        因爲當給出兩個分數的時候
        與其把二者都化爲正規形式 然後再比較
        我們顯然有更簡單的算法
        當給出 (a / b) (c / d) 的時候
        我們可以判斷 ((a * d) = (c * b))
        如果知道了 c > a 且 d > b
        我們也可以判斷 (c / a) 與 (d / b) 都是整數
        並且 ((c / a) = (d / b))

      - Among all the polyhedra of a class,
        we are going to try to choose the simplest one possible,
        and call it the normal form.

        It is clear that the normal form of a class
        will depend on the character of simplicity adopted.

        it is natural,
        from a certain point of view,
        to consider as the simplest
        those for which the numbers of faces, edges, and vertices
        are as small as possible.

***** 24 Reduction to Normal Form: I

      - We shall accomplish the reduction of a planar polygonal schema
        to its normal form in six stages,
        exclusively using a finite number of elementary operations in each stage.

        first three stages, reduce the number of faces, edges, and points.
        last three stages, make the schema as regular as possible.

        - [reference]
          In the reduction to normal form,
          we follow the method given by Seifert and Threlfall [22], pages 135-139.
          For another method of reduction, see J. W.Alexander [1].

          - [1]
            J. W. Alexander,
            "Normal forms for one- and two-sided surfaces,"
            Amah of Math., 76(1915), 158-161.

          - [22]
            H. Seifert and W. Threlfall,
            "Lehrbuch der Topologie." [textbook of topology]
            Leipzig:Teubner, 1934.

      - first stage :

        to use 2-dim-union,
        to get a schema that only have one polygon,
        which has even number of sides,
        which are pairwise equivalent.
        [for example, do this for tetrahedron]

        (a+ a-) and (a+ a+) are normal forms.

        in the following,
        we suppose the polygon has at least four sides.

      - second stage :

        (~~~~ a+ a- ~~~~) -> (~~~~ ~~~~)

        which is specified by the author as :
        2-dim-subdivision
        1-dim-union
        2-dim-union

        by repeating this procedure a finite number of times,
        we will finally arrive at one of the following two possible cases:
        either where we will have a polygon of two sides,
        or where we will have a polygon having at least four sides
        and not containing two adjacent sides of the form (a+ a-).
        In the first case, we have already arrived at the normal form (4) or (9).
        We have to pursue the reduction only for the second case.
        We will suppose, then, in the following,
        that the considered schema is composed of a single polygon
        having at least four sides and that this polygon
        does not have two adjacent sides of the form (a+ a-).

      - third stage :

        the aim is to reduce the number of vertices to one.

        - x -
          作者所描述的確實是一個遞歸算法的各個細節
          只是用的不是形式語言罷了
          可以發現
          這是一個遞減字典序的遞歸操作

          如果想要在我們的語言中執行這個操作
          看似就要執行 2-dim-subdivision 與 2-dim-union
          而這必須要引入新的點
          但是
          其實這些操作都可以被壓縮到邊界

***** 25 Reduction to Normal Form: II

      - x -
        此時 groupoid 已經被化爲了 group

      - fourth stage :

        non-adjacent equivalent sides with like signs ->
        adjacent equivalent sides with like signs

      - fifth stage :

        - x -
          這一步 在說
          (~~~~ c+ ~~~~ c- ~~~~) ->
          (~~~~ c+ ~~~~ d+ ~~~~ c- ~~~~ d- ~~~~)
          的時候 好像由漏洞

      - sixth stage :

        當有 cross-cap 的時候
        一個 handle 可以化爲 兩個 cross-cap

***** note bib about the proof

      - The proof,
        in Sections 24 and 25, of the classification theorem
        is based upon the proof given by H. R. Brahana,
        "Systemsof circuits on two-dimensional manifolds".

***** note 形式化的難點

      - x -
        我已經看到了一個形式化的難點了
        可能我們目前的語言的抽象能力並不夠強

        這在於
        在我們的語言中 一個空間是一個類型
        而這裏的算法要求我們能夠把一個空間當作一個數據來處理

      - k -
        我們可以想想看這整個算法的類型是什麼

      - x -
        首先輸入的是一個空間
        輸出的是一個被簡化了的空間
        同時還有一系列的證明
        證明這個簡化過程中所給出的一系列空間是相互等價的

        我知道利用 (type ...) 這個語法關鍵詞
        我們能夠構造匿名的類型
        利用 (lambda ...) 這個語法關鍵詞
        我們能夠構造匿名的證明

      - k -
        我想這裏我們可能要
        跨過 groupoid 與 cat 的邊界
        跨過可逆與不可逆的邊界
        跨過 intrinsic-type 與 extrinsic-type 的邊界

***** note 組合拓撲學的目的

      - x -
        我們要先確定學科的目的
        然後才能判斷我們所採用的方式的優劣

        組合拓撲學的目的是
        給空間分類

        類比別的 已經發展完備的 簡單數學理論 比如分數的理論

        (1)
        給出一種語言使得我們能夠描述拓撲空間
        ><><>< 語言其實是手段 其優劣應該由其目的判斷

        (2)
        ><><><

        引入代數
        引入各種構造新空間的方法也是手段 而不是目的

***** 26 Characteristic and Orientability

      - A polyhedron is said to be orientable
        if we can determine a cyclic sense of direction
        for the perimeter of each polygon of its planar polygonal schema
        so that, in the corresponding symbolic representation,
        each letter representing two equivalent sides
        appears twice with opposite signs.

        In particular,
        for a polyhedron having only one face to be orientable,
        it is necessary and sufficient that
        each letter representing two equivalent sides appear twice
        with opposite signs in every possible symbolic representation of this polyhedron.

      - x -
        利用 euler characteristic 與 可定向性 這兩個簡單的不變量
        可以證明上面所獲得的 normal form 是相互不等價的

      - In order that two polyhedra be elementarily associated,
        it is necessary and sufficient that
        they have the same characteristic
        and be simultaneously orientable or simultaneously nonorientable.

      - can it be, then, that two polyhedra obtained from the same closed surface
        have distinct characteristics
        or be such that one is orientable and the other not ?

        we accept this fact, that it can not be,
        without proving it.

***** 27 The Principal Theorem of the Topology of Closed Surfaces

***** 28 Application to the Geometric Theory of Functions

***** 29 Genus and Connection Number of Closed Orientable Surfaces

      - We shall call the maximum number of pairwise disjoint closed Jordan curves
        that can be drawn on a closed orientable surface
        without dividing the surface, the genus of the surface.

      - If we do not insist that the closed Jordan curves be disjoint,
        We call the maximum number of closed Jordan curves (disjoint or not)
        that can be drawn on a closed orientable surface
        without dividing the surface, the connection number of the surface.

      - Thus,
        for closed orientable surfaces,
        the genus is equal to exactly half the connection number.

* (1966 1976) (wilhelm magnus) combinatorial group theory

*** info

    - presentations of groups in terms of generators and relations

* (1977) (roger lyndon and paul schupp) combinatorial group theory

* (1980 1992) (john stillwell) classical topology and combinatorial group theory

*** info

    - topology is ostensibly the study of arbitrary continuous functions.
      in reality, however, we can comprehend and manipulate
      only functions which relate finite "chunks" of space
      in a simple combinatorial manner,
      and topology originally developed on this basis.

    - x -
      雖然作者在開頭這麼說了
      但是作者在之後的敘述中 還是遵循了拓撲空間那種 算數化的語言
      如下的用詞就是一些徵兆 :
      - neighbourhood
      - local compactness

*** 0 introduction and foundations

***** 0.1 The Fundamental Concepts and Problems ofTopology

******* 0.1.1 The Homeomorphism Problem

        - One may consider a geometric figure to be an arbitrary point set,
          and in fact the homeomorphism problem
          was first stated in this form, by Hurwitz 1897.
          However, this degree of generality
          makes the problem completely intractable,
          for reasons which belong more to set theory than geometry,
          namely the impossibility of describing or enumerating all point sets.

        - x -
          也就是說這種處理問題的方式不具有構造性
          沒法在計算機上用數據結構來實現這個模型
          更沒法用算法來實現就這個模型而敘述的函數

        - For the moment
          we wish to claim that all "natural" geometric figures
          are either simplicial complexes or homeomorphic to them,
          which is just as good for topological purposes.

        - knot complement in R3 is not finitely describable in terms of simplexes.

******* 0.1.2 Continuous Functions, Open and Closed Sets

******* 0.1.3 Examples of Continuous Maps

******* 0.1.4 Identification Spaces

        - x -
          again, glue is handled by quotient-space by the author.
          while in AT1, I handled it by common boundary.

******* 0.1.5 The H-ball and the ^-sphere

******* 0.1.6 Manifolds

        - x -
          這里給出了一個例子來說明
          #+begin_src scheme
          (type space
            (: base (-1 <>))
            (: p (0 base base))
            (: c (1 p p p)))
          #+end_src
          並非是 manifold
          也就是說 group 的 generators 與 relations
          所給出的 underlying-space 並非是 manifold

******* 0.1.7 Bounded Manifolds

        - x -
          既然可以把 manifold 推廣到 bounded manifold
          那麼也沒有什麼理由不把一般的 group 的 underlying-space
          包含到考慮範圍之內
          而所得到的 underlying-space 的差異
          都可以通過 group 的性質來描述

          之前問
          what are the underlying-space and covering-space
          of low order finite groups ?
          現在知道這些就是不是 manifold 的空間了

          之前關於有限生成羣的分類的問題
          二維曲面的分類很簡單 因爲這些曲面是 很特殊的羣的 underlying-space
          而一般的羣的分類很難 對應的 underlying-space 的分類也將很難

          而且之所以我們的討論要限制於
          那些 underlying-space 是 manifold 的羣
          可能就是因爲這種羣的 underlying-space 可以有簡單的嵌入
          從而讓人能夠直觀

          而對一般的羣的 underlying-space 的研究
          其實都是用代數方法來完成的

        - In dimension 2
          we can distinguish manifolds from bounded manifolds
          by the fundamental group (4.2.1 and 5.3.3).

******* 0.1.8 Embedding Problems

        - next to the homeomorphism problem,
          the most important type of topological problem is that of
          distinguishing different embeddings of one figure in another.

        - x -
          這裏的 homeomorphism problem 代數化之後就是空間之間的同倫等價
          即 (~~ A B)
          而後面的的 embedding 問題就是特殊的函數之間的等價
          即 (~ f g)
          其特殊性在於
          證明等價時所用的 (-> (* A I) B) 不能有自交

******* 0.1.9 Homotopy and Isotopy

        - The group properties depend crucially on the fact that
          the curve is not required to be simple at any stage,
          and in fact the deformation may create more singularities
          than were present at the beginning.

          Only then can one introduce a product of closed curves,
          and cancel a closed curve by its inverse.

        - x -
          同倫羣的定義依賴於各階球面的自交的映射

        - isotopy seems to be a more natural notion of deformation,
          but it is not algebraically tractable.
          In the case of simple curves on a 2-manifold
          the situation is saved by a theorem of Baer 1928 (6.2.5)
          which says that simple curves are isotopic
          if and only if they are homotopic.

        - note the difference between

          - isotopy
            the "knotted part" can be shrunk to nothing
            without acquiring asingularity at any stage.

          - ambient-isotopy
            knot theory

        - x -
          在 AT1 中
          應該如何定義上面兩個概念
          如果要求 證明等價時所用的 (-> (* A I) B) 不能有自交
          是否就有了 ambient-isotopy ?

          有可能不行
          因爲 ambient-isotopy 是用 (-> (* B I) B) 定義的

***** 0.2 Simplicial Complexes

******* 0.2.1 Definition and Basic Properties

        - simplicial complex as schema.
          It is a consequence of the triangulation and Hauptvermutung that
          all homeomorphism questions for 2- and 3-manifolds
          reduce to combinatorial questions about schemata.

******* 0.2.2 Orientation

        - in general,
          we interpret the ordered (n + 1)-tuple (P0, ..., Pn+1)
          as an orientation of the n-simplex.

          orientations are equivalent
          if they differ by an even permutation of the vertices,
          so there are in fact two possible orientations,
          - (+ (P0, ..., Pn+1)) which is just (P0, ..., Pn+1)
          - (— (P0, ..., Pn+1)) obtained by
            an odd number of exchanges of vertices.

        - an orientation of an n-complex
          is an assignment of orientations to its simplexes.
          The orientation is coherent
          if n-simplexes which share an (n-1)-dimensional face
          induce opposite orientations in that face.

******* 0.2.3 Realization in Euclidean Space

        - any n-complex can be embedded in R^(2n+1)

******* 0.2.4 Cell Complexes

        - in the last resort,
          one can always view cells and the dividing cells inside them
          as unions of simplexes in a simplicial decomposition.
          The point of considering cell complexes at all
          is to minimize the number of cells,
          which usually helps to shorten computations.

        - x -
          作者有使用 simplicial complex 的傾向

******* 0.2.5 Triangulation and Hauptvermutung

        - The Hauptvermutung (main conjecture) of Steinitz 1908
          states that homeomorphic manifolds are combinatorially homeomorphic.

***** 0.3 The Jordan Curve Theorem

******* 0.3.1 Connectedness and Separation

        - The statement, as a theorem,
          that every simple closed curve in R2
          separates it into two regions (Jordan 1887)
          was important in the history of topology
          as the first moment when an "obvious" fact
          was seen to require proof.

******* 0.3.2 The Polygonal Jordan Curve Theorem

******* 0.3.3 0-graphs

******* 0.3.4 Arcs Across a Polygon

******* 0.3.5 The Jordan Separation Theorem

******* 0.3.6 Arcs in a Polygon

******* 0.3.7 No Simple Arc Separates R2

******* 0.3.8 The Jordan Curve Theorem

******* 0.3.9 The Jordan-Schoenflies Theorem

        - there are topologically distinct embeddings of S2 in R3.

***** 0.4 Algorithms

******* 0.4.1 Algorithmic Problems

******* 0.4.2 Recursively Enumerable Sets

******* 0.4.3 The Diagonal Argument

***** 0.5 Combinatorial Group Theory

******* 0.5.1 The Fundamental Group

******* 0.5.2 Generators, Words, and Relations

******* 0.5.3 Group Presentations

******* 0.5.4 Coset Decomposition, Normal Subgroups

        - a set of elements v < G
          generates a normal subgroup N of G
          #+begin_src scheme
          (-> [(: :g G) (: :v V)]
              [(: [:g :v :g rev] N)
               (: [:g :v rev :g rev] N)])
          #+end_src

        - generating a subgroup by inverse and product,
          generating a normal subgroup also by conjugation.

        - x -
          how about the fact that
          the fundamental group of a covering space of (underlying-space G)
          is a subgroup of G ?

******* 0.5.5 Quotient Groups and Homomorphisms

        - we can get quotient group of a group representation
          by adding new relations.
          [where new relations generates a normal subgroup.]

        - isomorphism = (kernel = id)

******* 0.5.6 Dyck's Theorem (Dyck 1882)
******* 0.5.7 The Word Problem and Cayley Diagrams

        - solution of the word problem for G
          is equivalent to the construction of Cayley diagram of G.

        - x -
          如何等同呢 ?
          用有向圖實現這個 [有可能是無限的] cayley diagram 嗎 ?
          path 到 vertex 的 hash function 嗎 ?

******* 0.5.8 Tietze Transformations

        - Tietze's Theorem.
          Any two finite presentations of a group G
          are convertible into each other
          by a finite sequence of Tietze transformations.

******* 0.5.9 Coset Enumeration

        - x -
          這裏作者給出了不計算法複雜性的傻瓜算法

*** 1 complex analysis and surface topology

***** 1.1 Riemann Surfaces

******* 1.1.1 Introduction

        - A complex function is a map from sphere onto sphere.
          [a covering map.]

        - The general purpose of Riemann surfaces in function theory
          is to provide domains on which
          all algebraic functions become single-valued.

******* 1.1.2 Branched Coverings of the 2-sphere

        - torus can cover sphere.

******* 1.1.3 Connectivity and Genus

        - In general
          the connectivity of a surface
          can be measured
          by the maximu mnumber of disjoint closed curves
          which can be drawn on the surface without separating it.
          [This number is called the genus of the surface.]

        - mobius
          clifford
          klein

******* 1.1.4 Branched Coverings of Higher Dimension

        - for 3-dim covering-space

        - james w. alexander

***** 1.2 Nonorientable Surfaces

******* 1.2.1 The Mobius Band

        - Klein imagines a small oriented circle (the indicatrix)
          placed on the surface,
          then transported round an arbitrary closed curve.

******* 1.2.2 The Projective Plane

******* 1.2.3 The Klein Bottle

******* 1.2.4 Dyck's Classification of Nonorientable Surfaces

        - crosscap + handle = 3 crosscaps.

        - special underlying-space
          | group                   | underlying-space |
          |-------------------------+------------------|
          | general                 | cell-complex     |
          | orientable manifold     | ...              |
          | non-orientable manifold | ...              |
          | manifold with boundary  | ...              |

***** 1.3 The Classification Theorem for Surfaces

******* 1.3.1 Combinatorial Definition of a Surface

        - Dehn and Heegaard (1907)
          define a closed surface to be
          a finite 2-dimensional simplicial complex.

******* 1.3.2 Schemata

        - build surfaces from polygons instead of only using triangles.

******* 1.3.3 Reduction to a Single Polygon with a Single Vertex

        - amalgamate polygons to one polygon.
          reduce the number of vertices of the polygon.

******* 1.3.9 Bounded Surfaces

        - x -
          Dehn's paper about 1-holed sphere, 2-holed sphere, and so on,
          is based on the normalization of surface.

***** 1.4 Covering Surfaces

******* 1.4.1 The Universal Covering Surface

        - covering without branch points
          covering with branch points

******* 1.4.2 The Universal Cover of an Orientable Surface of Genus > 1

******* 1.4.3 Fuchsian Groups

******* 1.4.4 The 2-sheeted Cover of a Nonorientable Surface

*** 2 graphs and free groups

***** 2.1 Realization of Free Groups by Graphs

******* 2.1.1 intro

        - to vividly illustrate the dual view of
          a group as fundamental group of a space
          and automorphism group of a covering-space.

******* 2.1.2 Graphs, Paths, and Trees
******* 2.1.3 The Cay ley Diagram of a Free Group
******* 2.1.4 Solution of the Word Problem for Free Groups
******* 2.1.5 Spanning Trees
******* 2.1.7 Generators for the Fundamental Group
******* 2.1.8 Freeness of the Generators
******* 2.1.9 The Tree as the Universal Covering Graph of the Bouquet of Circles

***** 2.2 Realization of Subgroups

******* 2.2.1 Covering Graphs

        - covering-map can be adequately represented
          by labelling and orienting the edges in covering-space.

******* 2.2.2 The Subgroup Property

        - x -
          帶有類型的代數結構之間的同態
          誘導出去掉類型的代數結構之間的單同態

******* 2.2.3 Realization of an Arbitrary Subgroup of a Free Group

******* 2.2.4 The Nielsen-Schreier Theorem

        - Every subgroup of a free group is free.

******* 2.2.6 Schreier Transversals

******* 2.2.7 Normal Subgroups and Cayley Diagrams

        - (: covering (-> X (underlying-space G)))
          if (fundamental-group X) is normal subgroup of G,
          then (= X (cayley-graph (/ G (fundamental-group X))))

*** 3 foundations for the fundamental group

***** 3.1 The Fundamental Group

******* 3.1.1 introductionthe fundamental group

        - such a definition
          makes the computation of generators and relations routine,
          but it is open to the objection that
          the group is not obviously a topological invariant.

          since the topologists of the time
          pinned their hopes on the hauptvermutung,
          they could be satisfied with a proof that
          the fundamental group was invariant under combinatorial homeomorphisms,
          which was supplied by tietze 1908.

        - the only group which has to be derived from first principles
          is that of the circle;
          all the other fundamental groups we need
          are then obtained by combining the simple technique of
          deformation retraction
          with the seifert-van kampen theorem.

***** 3.2 The Fundamental Group of the Circle

******* 3.2.2 Tightening a Path

        - x -
          證明某些生成子能過生成整個函數空間
          要證明函數空間中的任意元素都能化爲生成子所生成的正規形式

        - k -
          但是這與我們理解基本羣的方式並不相同
          計算基本羣的方式也不同
          我們計算同倫羣的方式是
          把一個 groupoid 化爲 group

        - x -
          groupoid 化爲 group 的過程
          可以看作是收縮那些沒有自交的 path
          最終得到的全是 circle

          二維圖形也可以如此
          最終得到的卻不全是 sphere
          而是什麼 ?

        - k -
          我們必須找一些例子來觀察

        - x -
          在這個正規化的過程中
          我們也可以先處理點
          即 用一個支撐樹
          把所有的點收縮成一個點

        - k -
          這樣我們就會得到一個高階 group 了

******* 3.2.3 Brouwer Degree

******* 3.2.4 Invariance of the Brouwer Degree under Homotopy

***** 3.3 Deformation Retracts

***** 3.4 The Seifert-Van Kampen Theorem

***** 3.5 Direct Products

*** 4 fundamental groups of complexes

***** 4.1 Poincare's Method for Computing Presentations

***** 4.2 Examples

***** 4.3 Surface Complexes and Subgroup Theorems

*** 5 homology theory and abelianization

***** 5.1 Homology Theory

***** 5.2 The Structure Theorem for Finitely Generated Abelian Groups

***** 5.3 Abelianization

*** 6 curves on surfaces

***** 6.1 Dehn's Algorithm

******* 6.1.1 Introduction

        - The fundamental problem
          in the topological classification of curves on surfaces
          is to decide whether a given closed curve contracts to a point.
          We shall call this the contractibility problem.

        - The problem was solved,
          at least from a geometric point of view,
          with the introduction of the universal covering surface in the 1880s.

          If a curve p on the surface F
          is lifted to a curve p' in the universal covering surface F',
          then p contracts to a point on F if and only if p' is closed in F'.

          - x -
            note that,
            the covering-space of a closed surface
            can only be [hyperbolic] plane or sphere.
            plane and sphere both are simple-connected
            [with trivial fundamental-group].

          It is admittedly not very convenient
          because of the very dense packing of polygons required
          even for genus 2 (see Figure 111).

        - Dehn observed that
          the labelled net of polygons on the universal covering surface
          was in fact the Cayley diagram of the fundamental-group of F,
          and that the contractibility problem was therefore
          the same as the word problem for the fundamental-group of F.

          thus,
          Dehn's algorithm solves the problem.
          His first proof depended on the metric in the hyperbolic plane (Dehn 1912a),
          but he then saw how the algorithm could be justified
          by purely topological properties of the net (Dehn 1912b).

          - Dehn, M. (a):
            Uber unendliche diskontinuierliche Gruppen,
            Math. Ann. 71 (1912), 116-144.
            Dehn's algorithm for solution of the word problem for surface groups,
            proved using hyperbolic geometry.

          - Dehn, H. (b):
            Transformation der Kurven auf zweiseitigen Flachen,
            Math. Ann. 72 (1912), 413-421.
            Topological proof of Dehn's algorithm.

******* 6.1.2 Some Special Cases
******* note 二階元素指導 一階元素之間等價的證明

        - x -
          否則代入方式可能是不明確的

******* 6.1.3 The Subpath Property

        - Then if p is any closed path in the net,
          p contains
          1. either a spur
          2. or a subpath consisting
             of more than half the edges
             in the boundary of a polygon in succession.

******* 6.1.4 Dehn's Algorithm

***** 6.2 Simple Curves on Surfaces

***** 6.3 Simplification of Simple Curves by Homeomorphisms

******* 6.3.1 Introduction

******* 6.3.2 Twist Homeomorphisms

******* 6.3.3 Curves Which Meet at a Single Point and Cross

******* 6.3.4 Removal of Intersections

******* 6.3.5 Taking a Curve off the Handles

******* 6.3.6 Mapping onto a Canonical Curve

***** 6.4 The Mapping Class Group of the Torus

******* 6.4.1 Introduction

******* 6.4.2 Canonical Curve Pairs on the Torus

******* 6.4.3 Classification of Canonical Curve Pairs

******* 6.4.4 Generating Homeomorphisms for Transformations of Canonical Curves

******* 6.4.5 Homeomorphisms Are Determined up to Isotopy by the Transformation of the Canonical Curves

******* 6.4.6 The Mapping Class Group

******* 6.4.7 Automorphisms of H1(F) when F Is Orientable of Genus > 1

*** 7 knots and braids

***** 7.1 Dehn and Schreier's Analysis of the Torus Knot Groups

***** 7.2 Cyclic Coverings

***** 7.3 Braids

*** 8 three-dimensional manifolds

***** 8.1 Open Problems in Three-Dimensional Topology

******* 8.1.2 Methods of Constructing 3-manifolds

        - [simplicial decomposition]
          A 3-manifold is a union of solid tetrahedra
          with disjoint interiors,
          with at most two tetrahedra meeting at each face
          (exactly two for a closed manifold),
          and finitely many at each edge and vertex.

          Furthermore, the neighbourhood surface of each vertex
          must be a 2-sphere,
          so that each point in the complex
          has a neighbourhood homeomorphic to the 3-ball
          (see also 8.2).

          If the complex is finite,
          then all the above properties are decidable,
          so we have an algorithm for deciding
          whether a finite 3-complex is a manifold
          (and of course, for distinguishing
          between closed and bounded manifolds).

          As in dimension 2,
          we can amalgamate simplexes
          until we have a single polyhedron,
          homeomorphic to a ball,
          with faces identified in pairs.
          This cell decomposition method of constructing 3-manifolds
          is therefore completely general
          and could serve as an alternate definition
          provided we include the statement that
          the neighbourhood surface of each vertex is a sphere.

        - the remaining three methods of construction
          we shall mention yield only the orientable 3-manifolds.

        - [heegaard splitting]
          decomposes the manifold into two handlebodies.
          two handlebodies can produce infinitely many different manifolds
          via different homeomorphisms between their boundary surfaces.

          by starting with a simplicial decomposition.
          It is fairly easy to show that
          every finite orientable 3-manifold has a Heegaard splitting (8.3.1).

        - [dehn surgery]
          One removes some solid tori from an S3
          and sews them back differently.
          To obtain all orientable 3-manifolds
          the tori have to be knotted or linked in most cases.

          In 8.4 we shall follow Lickorish 1962 in
          deriving the surgery construction from a Heegaard splitting.

        - [branched coverings of S3]
          the 3-dimensional analogue of Riemann surfaces.
          Like surgery, it is generally based on knots or links,
          and can in fact be derived from the surgery construction
          (Lickorish 1973, see 8.5).

        - Each of the above methods
          yields a finite description of the 3-manifold
          which can be effectively translated into a simplicial decomposition.

          and different forms of description are intertranslatable.
          [which is often useful for showing that two manifolds are the same.]

          The problem is that
          the same manifold has infinitely many descriptions,
          so we cannot always be sure
          whether different descriptions
          actually represent different manifolds.

        - thus we have algorithm
          for effectively enumerating all finite 3-manifolds
          (with repetitions).

******* 8.1.3 The Homeomorphism Problem

        - Since we do not yet know how to recognize the simplest 3-manifold S3
          (see 8.1.4)
          it must be admitted that
          the homeomorphism problem is far frombeing solved.
          The principal obstacles seem to be
          1. absence of plausible normal forms,
          2. lack of bounds on the length of constructions
             which convert one desscription of a manifold to another.
             - to know when to stop looking for a description
               among the infinitely many descriptions equivalent to it.
               thus, bounding the length of the search.
               thus, we can solve the problem
               even when we do not have a normal form.

        - The homeomorphism problem has been solved
          for the subcase of lensspaces (Reidemeister 1935).
          We shall see in 8.3
          that the lens spaces are the 3-manifolds of Heegaard genus 1.

******* 8.1.4 Recognizing the 3-sphere

******* 8.1.5 An Unshellable Triangulation of the 3-ball

******* 8.1.6 The Poincare Conjecture

******* 8.1.7 The Word Problem for 3-manifold Groups

        - The Word Problem of fundamental group of 3-manifold,
          might be solvable,
          because many groups can not be fundamental group of 3-manifold.
          [for example, (Z x Z x Z x Z) (Stallings 1962)]

        - to solve the word problem in fundamental group of M,
          we only need to construct the universal covering space of M.
          The trouble is that we do not know
          what the potential covering spaces might be in general.

        - x -
          what is the relations between
          universal covering space
          and geometric of space.

******* 8.1.8 Above Dimension 3

        - It is not yet known whether all 4-manifolds can be triangulated.

        - any finitely presented group can be realized as fundamental group of a 4-manifold.

        - for dimensions >= 5,
          The Hauptvermutung is false (Milnor 1961).

***** 8.2 Polyhedral Schemata

******* 8.2.1 manifolds and pseudomanifolds

        - Poincare 1895 introduces the construction of 3-manifolds
          by identifying faces of simply-connected polyhedra :
          (1) a finite set of polyhedra (topological 3-balls) called cells, with disjoint interiors,
          (2) faces of cells identified in pairs, with vertices corresponding to vertices,
          (3) resulting in a connected complex.

        - However,
          Poincare observes that
          these conditions do not guarantee that
          the outcome will be a manifold.
          [thus, the concept of pseudomanifolds.]

          to get manifold,
          we need :
          (4) The neighbourhood surface of each vertex is a 2-sphere.

******* 8.2.2 The Euler Characteristic of a Pseudomanifold

        - 3-manifolds have Euler characteristic 0.
          [but pseudomanifold do not.]

******* 8.2.3 An Example

        - ><

******* 8.2.4 Remarks

        - Polyhedral schemata
          have never been used in a systematic way
          for the construction of 3-manifolds,
          even though some interesting manifolds
          originally arose in this way
          (for example lens spaces, cf. 4.2.8.
           See also Threlfall and Seifert 1930, 1932
           and Weber and Seifert 1933
           for manifolds obtainedfrom the Platonic solids).

          Apparently polyhedral schemata
          do not admit anything like the reductions applicable to polygon schemata,
          but it is not clear that anyone has worked very hard on the problem.

          Only recently, Thurston 1977 has found
          polyhedral forms of many 3-manifolds
          which can be used to tesselate hyperbolic 3-space,
          yielding a theory like the classical theory of 2-manifolds.

***** 8.3 Heegaard Splittings

******* 8.3.1 Existence

        - x -
          when getting heegaard-splitting from a polyhedral-schema,
          it seems more complex then polyhedral-schema.

          but we can also get heegaard-splitting from other picture of 3-manifold.

          we have :
          (polyhedral-schema -> heegaard-splitting)

******* 8.3.2 Heegaard Diagrams

        - A manifold which splits into handlebodies H1 H2
          is determined up to homeomorphism
          by the map (: h (-> [H1 boundary] [H2 boundary]))
          [which is determined by the images of the canonical meridians.]

          when a set of n disjoint simple closed curves
          on a handlebody of genus n is a Heegaard diagram ?

******* note

        - x -
          Heegaard Diagram 可以給 3-manifold 一個非常簡單的表示
          但是 我們缺很難判斷兩個 表示是否等價

          how about
          (heegaard-splitting -> polyhedral-schema) ?

******* 8.3.3 Reading a Presentation of the Fundamental Group

******* 8.3.4 Lens Spaces

        - x -
          do not use the simple algorithm of
          (polyhedral-schema -> heegaard-splitting)
          to get the heegaard-splitting,

          but to use the core dissection
          to get a heegaard-splitting of genus 1.
          (lens-space -> heegaard-splitting of genus 1)

          after add (0, 1) lens space,
          all heegaard-splitting of genus can be pictured as lens space.

******* 8.3.5 Alexander's Proof that the (5, 1) Lens Space and the(5, 2) Lens Space Are not Homeomorphic

******* 8.3.6 Heegaard Diagrams of Bounded 3-manifolds

******* 8.3.7 Fundamental Groups of Bounded 3-manifolds

******* 8.3.8 Heegaard Diagrams of Knot and Link Complements

***** 8.4 Surgery

***** 8.5 Branched Coverings

*** 9 unsolvable problems

***** 9.1 Computation

***** 9.2 HNN Extensions

***** 9.3 Unsolvable Problems in Group Theory

***** 9.4 The Homeomorphism Problem

* (1982) (bruce chandler and wilhelm magnus) the history of combinatorial group theory: a case study in the history of ideas

*** info

    - Nearly the entire body of research in the field
      is due to mathematicians who either are still alive
      or who were the teachers or senior colleagues of living mathematicians.
      This makes it possible to supplement the written tradition
      with oral information which is particularly valuable
      when dealing with questions of motivation
      for a particular investigation or of the transfer of ideas.

    - x -
      it seems the tradition of writing hides motivations,
      while the dialog reveals motivations.

      it might also be the authors who fail to convey their motivations
      are not good at their art.

*** Part I The Beginning of Combinatorial Group Theory

***** 1 Introduction to Part I

      - Part I of our book covers the period from 1882 to 1918,
        the end of the first World War.

***** 2 The Foundation: Dyck's Group-Theoretical Studies

      - in Dyck's paper :
        For the further development of the present group theoretical problems
        the analytic (combinatorial) formulation has to replace every geometric description.
        However, the primary geometric interpretation has produced certain viewpoints
        and it is the purpose of the present paper
        to develop both their geometric version and their analytic content.

      - "a geometric concretization (Versinnlichung) of the group G."
        like the theory of fuchsian groups.

        tessellation of the hyperbolic disk

      - Burnside's textbooks.

      - De Siguier used Cantor's set theory
        and coined the term 'semigroup'.

      - What we called Proposition 1
        [there exist free group for a set of generators]
        is then what Dehn called the solution of the word problem for free groups.

      - x -
        當 [像 Dehn 一樣]
        用 模型的實現 與 算法 來理解這些理論時
        某些堂皇的命題就是顯然的事實了

        作者區分了 The existence proof 與 The combinatorial proof
        後者是 構造主義 的

***** 3 The Origin: The Theory of Discontinuous Groups

      - poincare and klein

      - discontinuous action
        discontinuous group acting on space

      - the early theory of discontinuous groups did not stimulate
        the development of the theory of group presentations,
        because the discontinuous groups are not primarily given by presentations.
        They are defined either by a set of generating elements
        which describe circle-preserving conformal self-mappings of the complex plane [geometric]
        or as a set of 2x2 matrices, subject to arithmetic conditions [arithmetic].

***** 4 Motivation: The Fundamental Groups of Topological Spaces

      - poincare -> tietze -> dehn

      - [bib]

        - Birman, J. S.
          Poincare's conjecture and the homeotopy group of a closed, orientable 2-manifold
          1973

        - heinrich tietze
          on the topological invariants of multidimensional manifolds
          1908

      - Tietze's results are motivated by an observation of a specific difficulty
        arising when working with groups which are merely givenby a presentation.

      - Dehn recognized that the difficulties of combinatorial group theory
        start at a much lower level than that of the isomorphism problem as stated by Tietze.

      - [bib]

        - Greendlinger, M, 1960a,
          Dehn's algorithm for the word problem,
          Comm. Pure and Appl.Math.

        - Greendlinger, M., 1960b,
          Dehn's algorithm for the conjugacy and word problems, with applications,
          Comm. Pure and Appl. Math.

***** 5 The Graphical Representation of Groups

      - cayley diagram -> burnside [finite order] -> coxeter [finite order]

      - The point to be made here is that
        this is such an extremely simple definition
        when phrased in topological terms.
        Any possible translation into algebraic terms
        appears to be clumsy and opaque.
        Of course, one may say that
        all that matters about a definition is its precision.
        But this was certainly not Dehn's opinion.
        In a public talk for a nonmathematical academic audience,
        Dehn [1928] explained that the continued growth of mathematics
        requires the continued emergence of new ideas which reduce its complexity.
        He also expressed the hope that
        topology would renew its power through such an injection of new ideas.
        The reader should note the year when this was said.
        Within the following 10 years,
        there appeared monographs on topology by
        Alexandroff and Hopf,
        by Lefshetz, and by Seifert and Threlfall,
        documenting an upsurge in topological research which has not yet abated.

        - Dehn, M, 1928,
          Uber die geistige Eigenart des Mathematikers,
          Frankfurter Universitatsreden No. 27. 25 pp.,
          Universitatsdruckerei Wemer und Winter, Frankfurt am Main.
          Preface and I.5,

***** 6 Precursors of Later Developments

******* note

        - x -
          這章節值得仔細分析
          既然 羣論 可以用於描述諸多現象
          那麼 推廣而得到的 高階代數 是否也能描述這些現象的推廣呢 ?

        - k -
          如果可以的話
          就可以說 羣論 到 高階代數 的推廣是一個成功的推廣了

******* A. Arithmetically Defined Linear Groups in Higher Dimensions

        - siegel

******* B. Arithmetically Defined Linear Groups in Two Dimensions

        - magnus

******* C. Geometric Constructions. Fuchsian Groups

******* D. Braid Groups and Mapping Class Groups

        - hurwitz
          in a fiber space, the fundamental group of the base space
          acts as a group of self-mappings on the fiber.

******* E. Differential Equations, Linear Groups,and Lie Groups

******* F. Finite Groups

***** 7 Summary

      - Group theory started as the theory of groups of transformations,
        i.e., of one-to-one and onto self-mappings of a mathematical object.
        If the object is a finite set, the group appears as a permutation group.
        [Camille Jordan on "substitutions and algebraic equations"]

      - Infinite transformation groups
        became a topic of extensive research at about the same time.
        But this development was initiated not by a fundamental work but by a manifesto.
        [Felix Klein at Erlangen]
        [Sophus Lie]
        a program, according to which
        geometry should be considered from the point of view
        of transformation groups which act on certain spaces.

        for to get the generators of the group of Klein as in combinatorial group theory,
        the concept of generators has to be modified
        in the sense of Lie's "infinitesimal substitutions".

      - the tiling designs or tessellations
        of the euclidean or non-euclidean plane
        with a polygon as the basic tile,
        The generators and their inverses
        simply correspond to the edges of the basic polygonal tile,
        and the defining relations correspond to its vertices.

        this is the dual of the cayley-graph,
        so we have three graphs now,
        (1) underlying-space [classifying-space]
        (2) covering-space [cayley-graph]
        (3) acting-space [dual-cayley-graph]

      - finite group vs infinite group
        for finite group, we have :
        | finite group            | number            |
        | finite simple group     | prime number      |
        | direct product of group | product of number |
        but for infinite group, we do not have such.
x
      - The object on which a group of transformations acts
        has disappeared completely
        if we define a group through a presentation by generators and relations.

        while Poincare's fundamental group
        makes group generators and relations worth study.

      - the theory of representations of groups
        as linear transformations of finite-dimensional vector spaces

        [Frobenius Burnside, and L. E. Dickson]
        [linear groups over finite fields]

      - combinatorial group theory emphasis on algorithms.
        "to find a method of deciding in a finite number of steps"

      - combinatorial group theory
        geometric -> geometric interpretation
        algebraic -> classify and decomposition

***** 8 Modes of Communication. Growth and Distribution of Research in Group Theory

***** 9 Biographical Notes

***** 10 Notes on Terminology and Definitions

      - It is part of the purpose of every historical essay
        to make it easier to go back to the sources for those readers
        who may be interested in doing so.

***** 11 Sources

*** Part II The Emergence of Combinatorial Group Theory as an Independent Field

***** 1 Introduction to Part II

      - This part of our book deals mainly with the developments during the period
        from 1918 to 1945, that is, from the end of World War I
        to the end of World War II.

      - the mapping class group of a surface
        is the group of automorphisms
        of the fundamental group of the surface.

        - x -
          how about mapping-class-group with fixed boundary ?

***** 2 Free Groups and Their Automorphisms

      - Nielsen
        Hopf
        McCool

      - [bib]

        - McCool, J., 1974,
          A presentation of the automorphism group of a free group of finite rank

        - McCool, J. 1975a,
          On Nielsen's presentation of the automorphism group of a free group

        - McCool, J., 1975b,
          Some finitely presented subgroups of the automorphism group of a freegroup

***** 3 The Reidemeister-Schreier Method

***** 4 Free Products and Free Products with Amalgamations

***** 5 One-Relator Groups

***** 6 Metabelian Groups and Related Topics

***** 7 Commutator Calculus and the Lower Central Series

***** 8 Varieties of Groups

***** 9 Topological Properties of Groups and Group Extensions

      - this may be described as
        a method of associating a topological cell complex
        with the group and deriving results about the group from this association.

      - it was shown that
        the association of cell complexes and groups
        leads to a purely algebraicde finition of homology and cohomology groups
        belonging to any given group G which are invariants of G.

***** 10 Notes on Special Groups

***** 11 Postscript: The Impact of Mathematical Logic

***** 12 Modes of Communication

***** 13 Geographical Distribution of Research and Effects of Migration

***** 14 Organization of Knowledge

* (1989) (daniel cohen) combinatorial group theory: a topological approach

*** info

    - the author, daniel cohen, is influenced by
      ralph fox, hanna neumann and roger lyndon.

*** 1 combinatorial group theory

***** 1.1 free groups

***** 1.2 generators and relators

***** 1.3 free products

***** 1.4 pushouts and amalgamated free products

***** 1.5 hnn extensions

*** 2 spaces and their paths

***** 2.1 some point-set topology

***** 2.2 paths and homotopies

*** 3 groupoids

***** 3.1 groupoids

***** 3.2 direct limits

*** 4 the fundamental groupoid and the fundamental group

***** 4.1 the fundamental groupoid and the fundamental group

***** 4.2 van kampen's theorem

***** 4.3 covering spaces

***** 4.4 the circle and the complex plane

***** 4.5 joins and weak joins

*** 5 complexes

***** 5.1 graphs

***** 5.2 complexes and their fundamental groups

***** 5.3 free groups and their automorphisms

***** 5.4 coverings of complexes

***** 5.5 subdivisions

***** 5.6 geometric realisations

*** 6 coverings of spaces and complexes

*** 7 coverings and group theory

*** 8 bass-serre theory

***** 8.1 trees and free groups

***** 8.2 nielsen's method

***** 8.3 graphs of groups

***** 8.4 the structure theorems

***** 8.5 applications of the structure theorems

***** 8.6 construction of trees

*** 9 decision problems

***** 9.1 decision problems in general

***** 9.2 some easy decision problems in groups

***** 9.3 the word problem

***** 9.4 modular machines and unsolvable word problems

***** 9.5 some other unsolvable problems

***** 9.6 higman's embedding theorem

***** 9.7 groups with one relator

*** 10 further topics

***** 10.1 small cancellation theory

***** 10.2 other topics

* (1993) two-dimensional homotopy and combinatorial group theory

* (2008) (dmitry kozlov) combinatorial algebraic topology

* (2005) the geometry of the word problem for finitely generated groups

*** (Noel Brady) Dehn Functions and Non-Positive Curvature

*** (Tim Riley) Filling Functions

***** Introduction

      - Group action
      - word metric
      - Cayley graph
      - Cayley 2-complex
      - Asymptotic cones
      - Filling functions

***** 1 Filling Functions

******* 1.1 Van Kampen diagrams

        - (cayley-2-complex x) :=
          (universal-covering presentation-2-complex x)

        - van Kampen diagram of (= w identity)

******* 1.2 Filling functions via van Kampen diagrams

        - for a van Kampen diagram we can define :
          area
          intrinsic diameter
          extrinsic diameter
          gallery length
          filling length
          DGL

        - A shelling of ∆
          is a combinatorial null-homotopy of ∆
          down to its base vertex.
          [note about the concept of "combinatorial homotopy"]

******* 1.3 Example: combable groups

******* 1.4 Filling functions interpreted algebraically

******* 1.5 Filling functions interpreted computationally

******* 1.6 Filling functions for Riemannian manifolds

******* 1.7 Quasi-isometry invariance

***** 2 Relationships Between Filling Functions

******* 2.1 The Double Exponential Theorem

******* 2.2 Filling length and duality of spanning trees in planar graphs

******* 2.3 Extrinsic diameter versus intrinsic diameter

******* 2.4 Free filling length

***** 3 Example: Nilpotent Groups

******* 3.1 The Dehn and filling length functions

******* 3.2 Open questions

***** 4 Asymptotic Cones

******* 4.1 The definition

******* 4.2 Hyperbolic groups

******* 4.3 Groups with simply connected asymptotic cones

******* 4.4 Higher dimensions

*** (Hamish Short) Diagrams and Groups

* (1955) (robert c. james) combinatorial topology of surfaces

*** note

    - also about normal form.
