#+title: nietzsche

* 歷史的用途與濫用

  - 人利用歷史的方式有三種
    - 紀 :: 行動 榜樣
         有人爲了保持自己的行動 而在歷史中尋找榜樣
    - 懷 :: 虔敬 滿足
         有人滿足於自己所成長的環境 並要把這種環境傳給後人
    - 批 :: 痛苦 迫切
         有人不惜任何代價要拋棄包袱

  - 分析歷史中 '成功者' 的案例 而想要獲得 '有用' 的知識
    這是愚蠢的 這是濫用歷史
    因爲歷史中根本沒有這種知識

  [批評愚蠢的驕傲]
  因此我們就慣於不再嚴肅地看待任何真正的東西
  我們養成虛弱的個性
  真正和永久的東西 在這個個性上留不下任何印跡

  知識若並非在飢餓中
  而是在有違人的意願時 被過量吸收
  就會對改變外在的生活沒有任何影響
  而只是隱藏在現代人混亂的內在世界中

  - 知識應該與行動相協調
    行動使人飢餓
    知識應改變行動

  - 希臘人是 '非歷史感' 的
    是 '沒有受過教育的'

  他已經失去或破壞了他的本能
  當他的理解力讓他失望 他的道路穿過沙漠時
  他不再信任那 '神獸' 而信馬由繮
  他的個性動搖了 他對其不再有任何自信
  它沉入到自己的內心世界中去了
  這個內心世界只是它所學過東西的雜亂無章的狀態
  而且由於只是一些無法面向生活的教條
  這個內心世界總也沒有外在的自我表達

  因爲他們不是人
  而只是具有人形的綱要
  是被具體了的抽象

  只有強壯的人性才能承受歷史
  弱者會被它消滅
  當感情沒有強大到用自己來衡量過去時
  歷史就會讓它們感到不安
  一個不再敢於相信他自己的人
  違背自己的意願向歷史討教 '現在我應當感覺如何'
  他就會不知不覺因自己的怯懦而變成一個演員

  - 正義 正義的衝動 盲目的正義的衝動
    判決 判決的能力 清醒的判決的能力

  - 忘之於靈魂 如消化之於肉身
    不忘 則消化不良
    忘使意識寂靜 爲新的 治 預 謀 騰出地方

  - 記 如記他人之諾
    存之而取未來之利

  原來的音符個唱着 行動 需要 和 恐懼

  - 正義就是作出判斷的能力
    它使人能在抉擇中前進

  任何事物 如果它迫使一個人不再無條件地愛
  那它就切斷了這個人的力量之根
  他必會枯萎而蒙羞

  當人們將他們好奇的眼睛轉移到聲明和藝術的細枝末節處
  並在本該是學會生活而忘掉問題的地方尋覓知識時
  這就是人們對有生命力之物的殘害
  正如完全的解剖會使生命消失

  所有活的東西都需要一種氛圍
  一層神祕的薄霧圍繞在它們四周

  每個名族 甚至每個人 如果要變得成熟
  就需要這樣一層幻想的面紗 這樣一層保護雲

  不要用科學
  而要用本能和有力的幻想來指導生活

  有些鳥被人弄瞎了 這樣它們就會唱地更好聽
  今人並不比前人唱地好聽 但是他們早就被弄瞎了

  [諷刺歷史的車輪]
  而曾經學會了在歷史的力量面前點頭哈腰卑躬屈膝的人
  最終會像中國的木偶一樣
  對每一種力量都唯唯諾諾
  不管這種力量是 一個政府 一種公衆意見 還是一個大多數意見

  他按照他這個時代的時尚
  不加思考地稱自己的生活方爲
  '自己的個性徹底屈服於世界的進程'

  不錯 我們太清楚歷史將會得到何種優勢
  它會怎樣將他的 年輕 激情 勇氣 無私 和 熱愛 之強大本能完全根除
  怎樣冷卻他自己的正義感
  怎樣以相反的慾望來粉碎和壓抑 他要緩慢成熟的慾望
  這個相反的慾望即是想要盡快 生產 成熟 有用
  並且它對所有誠實和坦白的感情懷有病態的懷疑
  它甚至能騙取青年最美好的特權
  就是以充分的自信培植一個偉大思想
  並讓它成長成一個更偉大的思想的那種力量

  - 從生活中獲取知識 而不是從歷史中尋找觀點
    親自去體驗一些事情
    去感受一個緊密組織的 活生生的經驗體系 在自己的內心不斷成長
    用行動之力的深度 度量所學知識的強度

  它希望得到花朵 而不需要根和莖 因此它的希望落空了

  - 過量的歷史損害了生命的可塑力
    它再也不知道應該怎樣將過去作爲取得力量和營養的一種方式加以利用
    靈魂需要恢復那種洞察一切的天賦
    解藥是 '非歷史' 和 '超歷史'
    非歷史 以忘掉過去並在自己周圍劃出一個有限的視野
    超歷史 將目光從演變的進程轉向
    賦予存在以一種永恆與穩定的事物之上

  - 不要讓知識成爲寄生在生命上的蟲

  年輕人的力量與健康的最明顯的標記 就是這樣一個事實
  他們不用從今天文字與觀念的製造廠中找出什麼觀念
  和黨派

  我知道 這樣一些有希望的生命能夠從內心理解所有這些真理
  並通過自己的體驗 將它們變爲一套爲自己所用的學說

* 希臘悲劇時代的哲學

  希臘人想要立即經歷他們所學到的東西
  這樣他們的知慾就爲生活所限

  [關於異族的衝擊]
  不是去重新創造元素
  而是立刻致力於 充實 提高 揚棄 淨化 這些引進的元素

* beyond good and evil

  - we have developed a herd mentality, a culture of mediocrity in
    which the greatest and most creative human spirits cannot flourish.

  - free spirits, who will take delight in exploring new directions and
    subjecting the received tradition to ruthless criticism.
    They will do this, not in order to offer new truths,
    but in order to create their own personal languages
    and their own values in a spirit of creative play.
    Hence, they will be able to move “beyond good and evil.”

  - the nature of any kind of truth is fictional.
    christianity, science, democracy, pity.

  - the physiological demands for the preservation of a particular way of life,
    is the instinct leading philosophers thinking.

  - the fictional nature of the conditions of life,
    is to insist judgments must be true.
    we allow logical fictions to count.
    we measure reality against the purely invented world of the unconditional and self-identical.
    we constantly make falsification of the world through numbers.
    thus, it is clear to see,
    false judgments make demands on life, sustains life,
    maintains the species, perhaps even creates species.
